package org.apache.jsp.system.core.orgselect;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.tianee.webframe.util.servlet.TeeCookieUtils;
import java.util.*;
import com.tianee.oa.oaconst.TeeConst;
import com.tianee.oa.core.org.bean.TeePerson;
import com.tianee.webframe.util.str.TeeUtility;
import com.tianee.webframe.util.date.TeeDateUtil;
import com.tianee.webframe.util.global.TeeSysProps;
import com.tianee.webframe.util.str.TeeStringUtil;
import com.tianee.oa.core.org.service.TeePersonService;
import com.tianee.oa.oaconst.TeeModelIdConst;

public final class selectMultiDeptPost_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  static {
    _jspx_dependants = new java.util.ArrayList(2);
    _jspx_dependants.add("/header/header2.0.jsp");
    _jspx_dependants.add("/header/ztree.jsp");
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

String moduleId = request.getParameter("moduleId");
if (moduleId == null) {
  moduleId = "";
}
String privNoFlag = request.getParameter("privNoFlag");
if (privNoFlag == null || "".equals(privNoFlag)) {
  privNoFlag = "0";
}
String privOp = request.getParameter("privOp");
if (privOp == null) {
  privOp = "";
}

String objSelectType = request.getParameter("objSelectType");
if (objSelectType == null) {
	objSelectType = "";
}

String isSingle = request.getParameter("isSingle") == null  ? "" : request.getParameter("isSingle");

//回调函数
String callBackPara = request.getParameter("callBackPara") == null ? "" : request.getParameter("callBackPara")  ;
callBackPara = callBackPara.replace("\"", "\\\"");

      out.write("\r\n");
      out.write("<!-- <!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"> -->\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=Edge\"/>\r\n");
      out.write("<meta http-equiv=\"cache-control\" content=\"no-cache, must-revalidate\"/>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

String contextPath = request.getContextPath();
String basePath = request.getScheme() + "://"
		+ request.getServerName() + ":" + request.getServerPort()
		+ contextPath + "/";
//获取主题的索引号
int styleIndex = 1;
Integer styleInSession = (Integer) request.getSession().getAttribute("STYLE_TYPE_INDEX");
if (styleInSession != null) {
	styleIndex = styleInSession;
}
String stylePath = contextPath + "/common/styles";
String imgPath = stylePath + "/style" + styleIndex + "/img";
String cssPath = stylePath + "/style" + styleIndex + "/css";
String systemImagePath = contextPath+"/common/images";

//第二套风格
int STYLE_TYPE_INDEX_2 = TeeStringUtil.getInteger( request.getSession().getAttribute("STYLE_TYPE_INDEX_2"), 1);
String cssPathSecond = contextPath + "/system/frame/2/styles/style" + STYLE_TYPE_INDEX_2 + "/css";
String imgPathSecond = contextPath + "/system/frame/2/styles/style" + STYLE_TYPE_INDEX_2 + "/img";


String loginOutText = TeeSysProps.getString("LOGIN_OUT_TEXT");
String ieTitle = TeeSysProps.getString("IE_TITLE");
String secUserMem = TeeSysProps.getString("SEC_USER_MEM");

Cookie cookie = TeeCookieUtils.getCookie(request, "skin_new");
String skinNew = "1";
if(cookie!=null){
	skinNew = cookie.getValue();
}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- zt_webframe框架引入 jquery -->\r\n");
      out.write("<script src=\"");
      out.print(contextPath );
      out.write("/common/jquery-easyui-1.6.11/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- zt_webframe框架引入 核心库 -->\r\n");
      out.write("<script src=\"");
      out.print(contextPath );
      out.write("/common/zt_webframe/js/package.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(contextPath );
      out.write("/common/js/sys2.0.js?v=2\"></script>\r\n");
      out.write("<script src=\"");
      out.print(contextPath );
      out.write("/common/js/sysUtil.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(contextPath );
      out.write("/common/js/src/orgselect.js\"></script>\n");
      out.write("<!--\n");
      out.write("\n");
      out.write("//-->\r\n");
      out.write("<!-- zt_webframe框架引入 css样式 -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/common/zt_webframe/css/init");
      out.print(skinNew );
      out.write(".css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/common/zt_webframe/css/package");
      out.print(skinNew );
      out.write(".css\">\r\n");
      out.write("\r\n");
      out.write("<script src=\"");
      out.print(contextPath );
      out.write("/common/js/tools2.0.js?v=1\"></script>\r\n");
      out.write("<script src=\"");
      out.print(contextPath );
      out.write("/common/js/TeeMenu.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("/** 变量定义 **/\r\n");
      out.write("var contextPath = \"");
      out.print(contextPath );
      out.write("\";\r\n");
      out.write("var systemImagePath = contextPath+\"/common/images\";\r\n");
      out.write("var uploadFlashUrl = \"");
      out.print(contextPath );
      out.write("/common/swfupload/swfupload.swf\";\r\n");
      out.write("var commonUploadUrl = \"");
      out.print(contextPath );
      out.write("/attachmentController/commonUpload.action;jsessionid=");
      out.print(session.getId());
      out.write("\";\r\n");
      out.write("var xparent;\r\n");
      out.write("var stylePath = \"");
      out.print(stylePath);
      out.write("\";\r\n");
      out.write("if(window.dialogArguments){\r\n");
      out.write("\txparent = window.dialogArguments;\r\n");
      out.write("}else if(window.opener){\r\n");
      out.write("\txparent = opener;\r\n");
      out.write("}else{\r\n");
      out.write("\txparent = window;\r\n");
      out.write("}\r\n");
      out.write("window.UEDITOR_HOME_URL = \"");
      out.print(contextPath);
      out.write("/common/ueditor/\";\r\n");
      out.write("$.browser = {};\r\n");
      out.write("$.browser.mozilla = /firefox/.test(navigator.userAgent.toLowerCase());\r\n");
      out.write("$.browser.webkit = /webkit/.test(navigator.userAgent.toLowerCase());\r\n");
      out.write("$.browser.opera = /opera/.test(navigator.userAgent.toLowerCase());\r\n");
      out.write("$.browser.msie = /msie/.test(navigator.userAgent.toLowerCase());\r\n");
      out.write("</script>\r\n");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!-- zTree库 -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/common/jquery/ztree/css/zTreeStyle/zTreeStyle.css\" type=\"text/css\"/>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath() );
      out.write("/common/jquery/ztree/js/jquery.ztree.core-3.5.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath() );
      out.write("/common/jquery/ztree/js/jquery.ztree.excheck-3.5.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath() );
      out.write("/common/jquery/ztree/js/jquery.ztree.exedit-3.5.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath() );
      out.write("/common/js/ZTreeSync.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<title>选择部门</title>\r\n");
      out.write("<link rel=\"stylesheet\" href =\"");
      out.print(cssPath );
      out.write("/org_select.css\"/>\r\n");
      out.write("<link href=\"");
      out.print(cssPath);
      out.write("/selectControls.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(contextPath);
      out.write("/system/core/orgselect/orgselect.js?v=1\"></script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("/*** 定义全部添加和全部删除的样式  **/\r\n");
      out.write("li.list-group-item:hover{\r\n");
      out.write("\tbackground-color: #f5f5f5;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("li.list-group-item.active, li.list-group-item.active:hover, li.list-group-item.active:focus {\r\n");
      out.write("\tbackground-color: #fff;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("li.list-dept-item:hover{\r\n");
      out.write("\tbackground-color: #f5f5f5;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("li.list-dept-item.active, li.list-group-item.active:hover, li.list-group-item.active:focus {\r\n");
      out.write("\tbackground-color: #fff;\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\t/* html{\r\n");
      out.write("\t\toverflow-y: hidden;\r\n");
      out.write("\t} */\r\n");
      out.write("\ta:hover{\r\n");
      out.write("\t\tcolor:#fff;\r\n");
      out.write("\t\tbackground-color: #70beff;\r\n");
      out.write("\t}\r\n");
      out.write("\t.titlebar{\r\n");
      out.write("\t\toverflow:hidden;\r\n");
      out.write("\t}\r\n");
      out.write("\t.title1_img{\r\n");
      out.write("\t\twidth:40px;\r\n");
      out.write("\t\theight:40px;\r\n");
      out.write("\t\tdisplay: inline-block;\r\n");
      out.write("\t\tfloat: left;\r\n");
      out.write("\t}\r\n");
      out.write("\t.titleBlock{\r\n");
      out.write("\t\tfloat: left;\r\n");
      out.write("\t\tdisplay: inline-block;\r\n");
      out.write("\t}\r\n");
      out.write("\t.titleBlock .title{\r\n");
      out.write("\t\tmargin-left: 5px;\r\n");
      out.write("\t\tfont-weight: normal;\r\n");
      out.write("\t}\r\n");
      out.write("\t.tab{\r\n");
      out.write("\t\tmargin-left: 2px;\r\n");
      out.write("\t\toverflow:hidden;\r\n");
      out.write("\t}\r\n");
      out.write("\t.tab .tabMenu{\r\n");
      out.write("\t\tfloat: left;\r\n");
      out.write("\t\tmargin:0 3px;\r\n");
      out.write("\t\tpadding: 3px 0;\r\n");
      out.write("\t\tcursor: pointer;\r\n");
      out.write("\t}\r\n");
      out.write("\t.tabActive{\r\n");
      out.write("\t\tcolor:#379ff7;\r\n");
      out.write("\t\tborder-bottom:2px solid #379ff7;\r\n");
      out.write("\t}\r\n");
      out.write("\t.tabList .tabContent{\r\n");
      out.write("\t    height: 304px;\r\n");
      out.write("\t    width: 260px;\r\n");
      out.write("\t    border: 1px solid #dadada;\r\n");
      out.write("\t    overflow-x:hidden;\r\n");
      out.write("\t    overflow-y:auto;\r\n");
      out.write("\t    display: none;\r\n");
      out.write("\t}\r\n");
      out.write("\t.list-group-item{\r\n");
      out.write("\t\tdisplay:block;\r\n");
      out.write("\t\tline-height: 25px;\r\n");
      out.write("\t\t/* margin-left: 10px; */\r\n");
      out.write("\t}\r\n");
      out.write("\t.form-control{\r\n");
      out.write("\t\theight:26px;\r\n");
      out.write("\t\ttext-indent: 5px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.btn{\r\n");
      out.write("\t\tbackground-color: #0d93f6;\r\n");
      out.write("\t\tcolor:#fff;\r\n");
      out.write("\t\tborder:none;\r\n");
      out.write("\t\theight: 28px;\r\n");
      out.write("\t\twidth:53px;\r\n");
      out.write("\t}\r\n");
      out.write("\ta.list-group-item.active, a.list-group-item.active:hover, a.list-group-item.active:focus{\r\n");
      out.write("\t\tz-index: 2;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    background-color: #70beff;\r\n");
      out.write("    border-color: #428bca;\r\n");
      out.write("\t}\r\n");
      out.write("\t.tabList .list-group-item{\r\n");
      out.write("\t\twidth: 210px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.block-right{\r\n");
      out.write("\t\tborder: 1px solid #dadada;\r\n");
      out.write("\t\tmin-height: 305px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.block-right .list-group-item{\r\n");
      out.write("\t\t/* width: 183px; */\r\n");
      out.write("\t\tcursor: pointer;\r\n");
      out.write("\t}\r\n");
      out.write("\tdiv.right.single{\r\n");
      out.write("\t\tpadding-top:13px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.list-group-item-header{\r\n");
      out.write("\t\tborder:none;\r\n");
      out.write("\t\tborder-bottom: 1px solid #dadada;\r\n");
      out.write("\t}\r\n");
      out.write("\t.block-select .list-group-item{\r\n");
      out.write("\t\t/* width: 195px; */\r\n");
      out.write("\t}\r\n");
      out.write("\tdiv#select_item{\r\n");
      out.write("\t\theight: 380px;\r\n");
      out.write("\t\tmargin:8px;\r\n");
      out.write("\t\tpadding:0;\r\n");
      out.write("\t\tborder:1px solid #dadada;\r\n");
      out.write("\t}\r\n");
      out.write("\t.block-select{\r\n");
      out.write("\t\theight: 349px;\r\n");
      out.write("\t\toverflow-x: hidden;\r\n");
      out.write("\t\toverflow-y:auto;\r\n");
      out.write("\t}\r\n");
      out.write(" \t.selected_person{\r\n");
      out.write("\t\tdisplay:block;\r\n");
      out.write("\t\twidth:262px;\r\n");
      out.write("\t\theight:33px;\r\n");
      out.write("\t\ttext-align:left;\r\n");
      out.write("\t\ttext-indent:50px;\r\n");
      out.write("\t\tborder:1px solid #dadada;\r\n");
      out.write("\t\tline-height:33px;\r\n");
      out.write("\t\tmargin-top:5px;\r\n");
      out.write("\t\tcolor:#000;\r\n");
      out.write("\t\tbackground-image: url(unselected.png);\r\n");
      out.write("\t\tbackground-repeat:no-repeat;\r\n");
      out.write("\t\tbackground-position: 25px center;\r\n");
      out.write("\t}\r\n");
      out.write("\t.selected_person:hover{\r\n");
      out.write("\t\tbackground-color:#70beff;\r\n");
      out.write("\t\tcolor:#fff;\r\n");
      out.write("\t\tbackground-image: url(selected.png);\r\n");
      out.write("\t} \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("var selectedColor = \"rgb(0, 51, 255)\";\r\n");
      out.write("var deptId,deptName;\r\n");
      out.write("var moduleId = \"");
      out.print(moduleId);
      out.write("\";\r\n");
      out.write("var isSingle = \"");
      out.print(isSingle);
      out.write("\";//是否单个选择选择\r\n");
      out.write("objSelectType = '");
      out.print(objSelectType);
      out.write("';\r\n");
      out.write("\r\n");
      out.write("var callBackPara = \"");
      out.print(callBackPara);
      out.write("\";\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("var parentWindowObj = xparent;\r\n");
      out.write("var to_id_field ;\r\n");
      out.write("var to_name_field ;\r\n");
      out.write("\r\n");
      out.write("var single_select = false;\r\n");
      out.write("var ctroltime=null,key=\"\";\r\n");
      out.write("\r\n");
      out.write("function doInit(){\r\n");
      out.write("\t$(\"#collapseTwo\").addClass(\"panel-collapse collapse in\");\r\n");
      out.write("\tif(isSingle == '1'){\r\n");
      out.write("\t\tsingle_select = true;\r\n");
      out.write("\t}\r\n");
      out.write("\tvar deptRetNameArray = parentWindowObj[\"deptRetNameArray\"];\r\n");
      out.write("\tif (deptRetNameArray && (deptRetNameArray.length == 2 ||  deptRetNameArray.length == 3) ) {\r\n");
      out.write("\t    var roleCntrl = deptRetNameArray[0];\r\n");
      out.write("\t    var roleDescCntrl = deptRetNameArray[1];\r\n");
      out.write("\t    deptId = parentWindowObj.document.getElementById(roleCntrl);\r\n");
      out.write("\t    deptName = parentWindowObj.document.getElementById(roleDescCntrl);\r\n");
      out.write("\t  }else {\r\n");
      out.write("\t\tdeptId = parentWindowObj.document.getElementById(\"dept\");\r\n");
      out.write("\t    deptName = parentWindowObj.document.getElementById(\"deptDesc\");\r\n");
      out.write("\t  }\r\n");
      out.write("\tto_id_field = deptId;\r\n");
      out.write("\tto_name_field = deptName;\r\n");
      out.write("    getDeptTree();\r\n");
      out.write("//     if(isSingle == '1'){//单选模式\r\n");
      out.write("//     \tgetDeptStr('');\r\n");
      out.write("//     }\r\n");
      out.write("  \r\n");
      out.write("\tto_id_field_value = to_id_field.value;\r\n");
      out.write("\tto_name_field_value = to_name_field.value;\r\n");
      out.write("\tvar dataList = new Array();\r\n");
      out.write("\tvar dataNameList  = new Array();\r\n");
      out.write("\tif(to_id_field_value != \"\"){\r\n");
      out.write("\t\tdataList = to_id_field_value.split(\",\");\r\n");
      out.write("\t\tdataNameList = to_name_field_value.split(\",\");\r\n");
      out.write("\t}\r\n");
      out.write("\t//转数组对象\r\n");
      out.write("\tfor(var i =0 ; i <dataList.length ; i++){\r\n");
      out.write("\t\tif(dataList[i] && dataList[i] != \"\" ){\r\n");
      out.write("\t\t\tvar item = {id:dataList[i] , name:dataNameList[i]};\r\n");
      out.write("\t\t\tid_field_array.push(item);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("/**\r\n");
      out.write(" * 获取部门select字符串\r\n");
      out.write(" */\r\n");
      out.write("function getDeptStr(uuid){\r\n");
      out.write("\tvar url = contextPath +  \"/orgSelectManager/getSelectDept.action\";\r\n");
      out.write("\tvar para = {deptId:uuid , moduleId:moduleId};\r\n");
      out.write("\tvar jsonRs = tools.requestJsonRs(url,para);\r\n");
      out.write("\t\r\n");
      out.write("\tif(jsonRs.rtState){\r\n");
      out.write("\t\tvar dataList = jsonRs.rtData;\r\n");
      out.write("\t\t$(\"a\").remove(\".list-group-item\");\r\n");
      out.write("\t    for(var i = 0; i < dataList.length; i++){\r\n");
      out.write("\t\t\tvar roleId = dataList[i].uuid;\r\n");
      out.write("\t\t\tvar roleName = dataList[i].deptName;\r\n");
      out.write("\t\t\tvar deptNameStr = dataList[i].deptNameStr;//处理后部门名称\r\n");
      out.write("\t\t\tvar deptLevel = dataList[i].deptLevel;//级别\r\n");
      out.write("\t\t\tvar deptParentId = dataList[i].deptParentId;\r\n");
      out.write("\t\t\tvar roleIdObj = null;\r\n");
      out.write("\t\t\tif(deptParentId){\r\n");
      out.write("\t\t\t\t roleIdObj = document.getElementById(\"select_id_\" + deptParentId);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(roleIdObj){\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tvar deptLevelTemp =  $(roleIdObj).attr(\"deptLevel\");//获取级别\r\n");
      out.write("\t\t\t\t//获取上级部门  and 获取同辈之后的所有元素 and 级别是同一级别的\r\n");
      out.write("\t\t\t\tvar temp = $(roleIdObj).nextAll(\"[deptLevel='\"+ deptLevelTemp+\"']\").first();\r\n");
      out.write("\t\t\t\tif(temp){\r\n");
      out.write("\t\t\t\t\ttemp.before(\"<a class='list-group-item active'  style='text-align:left;;cursor:pointer' id='select_id_\" +roleId + \"' item_id='\"+roleId+ \"' item_name='\"+roleName+\"'  deptLevel='\"+deptLevel+ \"'><h6 class='list-group-item-heading'>\"+ deptNameStr+\"</h6></a>\");\r\n");
      out.write("\t\t\t\t}else{//如果没有则在上级后面添加\r\n");
      out.write("\t\t\t\t\t$(roleIdObj).after(\"<a class='list-group-item active'  style='text-align:left;;cursor:pointer' id='select_id_\" +roleId + \"' item_id='\"+roleId+ \"' item_name='\"+roleName+\"'><h6 class='list-group-item-heading'>\"+ deptNameStr+\"</h6></a>\");\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t} \r\n");
      out.write("\t\t\t\t \r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t    $(\"#dept_item_0\").append(\"<a class='list-group-item active'  style='text-align:left;;cursor:pointer' id='select_id_\" +roleId + \"' item_id='\"+roleId+ \"' item_name='\"+roleName+\"' deptLevel='\"+deptLevel+ \"'><h6 class='list-group-item-heading'>\"+ deptNameStr+\"</h6></a>\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t} \r\n");
      out.write("\t    \r\n");
      out.write("\t\tif(dataList.length < 0){\r\n");
      out.write("\t\t\t $(\"#dept_item_0\").append(\"<div align='center' class='emptyClass' style='padding-top:5px;'><h6>无相关部门！</h6></div>\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tload_init();  \r\n");
      out.write("\t\tload_init_item();  \r\n");
      out.write("\t    //默认加载角色选中状态\r\n");
      out.write("\t    init_item('dept');\r\n");
      out.write("\t\t$(\".list-group-item\").unbind( \"click\" ,remove_item);\r\n");
      out.write("\t\t$(\".list-group-item\").unbind( \"click\" ,add_item);\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\talert(jsonRs.rtMsg);\r\n");
      out.write("\t} \r\n");
      out.write("}\r\n");
      out.write("/**\r\n");
      out.write(" * 初始化加载\r\n");
      out.write(" */\r\n");
      out.write("function doInitDept(){\r\n");
      out.write("\t for(var i = 0; i < id_field_array.length; i++){\r\n");
      out.write("\t\tvar item = id_field_array[i];\r\n");
      out.write("\t\tvar uuid = item.id;\r\n");
      out.write("\t\tvar deptNameStr = item.name;\r\n");
      out.write("\t/* \tvar uuid = tempObj.id;\r\n");
      out.write("\t\tvar deptNameStr = tempObj.name; */\r\n");
      out.write("\t\t$(\"#dept_item_0\").append(\"<a class='list-group-item dept-item active'  style='text-align:center;;cursor:pointer' id='select_id_\" +uuid + \"' item_id='\"+uuid+ \"' item_name='\"+deptNameStr+\"' deptLevel=''><h6 class='list-group-item-heading'>\"+ deptNameStr+\"</h6></a>\");\r\n");
      out.write("\t\tadd_item(uuid, deptNameStr);\r\n");
      out.write("\t\tcheckOrNocheckNodesById(uuid ,true);\r\n");
      out.write("\t}\r\n");
      out.write("\tjQuery('#dept_item_0 .dept-item').on('click', function(){\r\n");
      out.write("\t\t checkOrNocheckNodesById(this.getAttribute(\"item_id\") ,false);\r\n");
      out.write("\t\t remove_item(this.getAttribute(\"item_id\"), this.getAttribute(\"item_name\"));\r\n");
      out.write("\t\t jQuery(this).remove();\r\n");
      out.write("\t\t \r\n");
      out.write("\t}); \r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/**\r\n");
      out.write(" * 初始化加载\r\n");
      out.write(" */\r\n");
      out.write("function doInitDept0(){\r\n");
      out.write("\t for(var i = 0; i < id_field_array.length; i++){\r\n");
      out.write("\t\tvar item = id_field_array[i];\r\n");
      out.write("\t\tvar uuid = item.id;\r\n");
      out.write("\t\tvar deptNameStr = item.name;\r\n");
      out.write("\t/* \tvar uuid = tempObj.id;\r\n");
      out.write("\t\tvar deptNameStr = tempObj.name; */\r\n");
      out.write("\t\tif(deptNameStr!=''){//去除无部门的时候第一个有padding值显示的一块  等于空则什么也不添加\r\n");
      out.write("\t\t\t$(\"#dept_item_0\").append(\"<a class='list-group-item dept-item active'  style='text-align:center;;cursor:pointer' id='select_id_\" +uuid + \"' item_id='\"+uuid+ \"' item_name='\"+deptNameStr+\"' deptLevel=''><h6 class='list-group-item-heading'>\"+ deptNameStr+\"</h6></a>\");\r\n");
      out.write("\t\t }\r\n");
      out.write("\t\tadd_item0(uuid, deptNameStr);\r\n");
      out.write("\t}\r\n");
      out.write("\tjQuery('#dept_item_0 .dept-item').on('click', function(){\r\n");
      out.write("\t\t checkOrNocheckNodesById(this.getAttribute(\"item_id\") ,false);\r\n");
      out.write("\t\t remove_item(this.getAttribute(\"item_id\"), this.getAttribute(\"item_name\"));\r\n");
      out.write("\t\t jQuery(this).remove();\r\n");
      out.write("\t\t \r\n");
      out.write("\t}); \r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/**\r\n");
      out.write(" * 选中项\r\n");
      out.write(" * @param item_id   Id\r\n");
      out.write(" * @param item_name  name\r\n");
      out.write(" * @param extend  扩展字段---比如人员在线状态\r\n");
      out.write(" */\r\n");
      out.write("function add_item0(item_id, item_name , extend)\r\n");
      out.write("{\r\n");
      out.write("\t//var toIdFiledName  = to_id_field.name;//文档框名称\r\n");
      out.write("\tvar callBackFunc =   \"ORG_SELECT_ADD_BACH_FUNC\";//回调函数\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t arguments.length = 5;\r\n");
      out.write("     var callBackParaObj ;\r\n");
      out.write("     if(callBackPara && callBackPara != ''){\r\n");
      out.write("    \t callBackParaObj = tools.string2JsonObj(callBackPara);\r\n");
      out.write("     }\r\n");
      out.write("\r\n");
      out.write("\tif(objSelectType &&objSelectType == '1'){//当为多选框时\r\n");
      out.write("\t\tgetMultiple();\r\n");
      out.write("\t\t/*to_id_field_value = item_id_multiple;\r\n");
      out.write("\t\tto_name_field_value = item_id_multiple_name;*/\r\n");
      out.write("\t}else if(objSelectType == '2'){//DIV\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t//var to_id_field_value = to_id_field.value;\r\n");
      out.write("   if(!item_id || !item_name)\r\n");
      out.write("      return;\r\n");
      out.write("   \r\n");
      out.write("   var item = {id:item_id , name:item_name};\r\n");
      out.write("   if(single_select)//单选\r\n");
      out.write("   {\r\n");
      out.write("\t  id_field_array.length = 0;//清空数组\r\n");
      out.write("\t\r\n");
      out.write("\t  id_field_array.push(item);//添加数组\r\n");
      out.write("      to_id_field.value = item_id;\r\n");
      out.write("      to_name_field.value = item_name;\r\n");
      out.write("\t  arguments[2] =  to_id_field.value;\r\n");
      out.write("\t  arguments[3] = to_name_field.value;\r\n");
      out.write("\t  arguments[4] = callBackParaObj;\r\n");
      out.write("      trigger_callback(callBackFunc, arguments  );\r\n");
      out.write("      return;\r\n");
      out.write("   }\r\n");
      out.write("\r\n");
      out.write("   //添加 数组 页面文本属性\r\n");
      out.write("   var isAddItem = true;\r\n");
      out.write("   for(var i =0 ; i<id_field_array.length ; i++){//循环所选项\r\n");
      out.write("\t   var itemTemp = id_field_array[i];\r\n");
      out.write("\t   if(itemTemp.id == item_id){//如果相等\r\n");
      out.write("\t\t   isAddItem = false;\r\n");
      out.write("\t\t   break;\r\n");
      out.write("\t   }\r\n");
      out.write("   }\r\n");
      out.write("   if(isAddItem){\r\n");
      out.write("\t   id_field_array.push(item);//添加对象\r\n");
      out.write("\t   \r\n");
      out.write("\t   if(to_id_field.value == \"\"){// 等于空，直接赋值\r\n");
      out.write("\t\t   to_id_field_value = item_id;\r\n");
      out.write("\t\t   to_name_field_value = item_name;\r\n");
      out.write("\t   }else{\r\n");
      out.write("\t\t   if(to_id_field.value.substring(to_id_field.value.length - 1 , to_id_field.value.length) == ','){\r\n");
      out.write("\t\t\t   to_id_field_value = to_id_field.value + item_id ;\r\n");
      out.write("\t\t\t   to_name_field_value = to_name_field.value + item_name;\r\n");
      out.write("\t\t   }else{\r\n");
      out.write("\t\t\t   to_id_field_value = to_id_field.value + \",\" + item_id ;\r\n");
      out.write("\t\t\t   to_name_field_value = to_name_field.value + \",\" + item_name;\r\n");
      out.write("\t\t   }\r\n");
      out.write("\t   }\r\n");
      out.write("   }\r\n");
      out.write("  \r\n");
      out.write("   to_id_field.value = to_id_field_value;\r\n");
      out.write("   to_name_field.value = to_name_field_value;\r\n");
      out.write("\r\n");
      out.write("   /**\r\n");
      out.write("    * 判断是否存在此方法，转为多选人员，第三栏处理\r\n");
      out.write("    */\r\n");
      out.write("   if( window.dataSelectLoadInit ){  \r\n");
      out.write("\t    dataSelectLoadInit(id_field_array);  \r\n");
      out.write("\t }   \r\n");
      out.write("   \r\n");
      out.write("  // arguments.push(to_id_field.value );\r\n");
      out.write("  // arguments.push(to_name_field.value );\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   arguments[2] =  to_id_field.value;\r\n");
      out.write("   arguments[3] = to_name_field.value;\r\n");
      out.write("   arguments[4] = callBackParaObj;\r\n");
      out.write("   trigger_callback(callBackFunc, arguments );\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function getDeptTree(){\r\n");
      out.write("\tvar url = \"");
      out.print(contextPath );
      out.write("/orgSelectManager/getSelectDeptTreePost.action?moduleId=\"+moduleId;\r\n");
      out.write("\tvar config = {};\r\n");
      out.write("\tif(isSingle == '1'){\r\n");
      out.write("\t\t config = {//单选\r\n");
      out.write("\t\t\t\t\tzTreeId:\"selectDeptZtree\",\r\n");
      out.write("\t\t\t\t\trequestURL:url,\r\n");
      out.write("\t\t\t\t\tparam:{\"moduleId\":moduleId,isSingle:isSingle},\r\n");
      out.write("\t\t           \tonClickFunc:deptOnClick,\r\n");
      out.write("\t\t\t\t\tasync:false,\r\n");
      out.write("\t\t\t\t\tonAsyncSuccess:doInitDept0\r\n");
      out.write("\t\t\t\t};\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\t config = {//多选\r\n");
      out.write("\t\t\t\tzTreeId:\"selectDeptZtree\",\r\n");
      out.write("\t\t\t\trequestURL:url,\r\n");
      out.write("\t\t\t\tparam:{\"moduleId\":moduleId,isSingle:isSingle},\r\n");
      out.write("\t\t\t\tcheckController:{\r\n");
      out.write("\t\t\t\t\tenable : true,\r\n");
      out.write("\t\t\t\t\tchkboxType: { \"Y\": \"\", \"N\": \"\"}\r\n");
      out.write("\t               },\r\n");
      out.write("\t            onClickFunc:deptOnClick0,\r\n");
      out.write("\t           \tonCheckFunc:deptOnCheckFunc,\r\n");
      out.write("\t\t\t\tasync:false,\r\n");
      out.write("\t\t\t\tonAsyncSuccess:doInitDept,\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t};\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tzTreeObj = ZTreeTool.config(config);\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("function deptOnClick(event, treeId, treeNode) {\r\n");
      out.write("\t var uuid = treeNode.id;\r\n");
      out.write("\tif(uuid.split(\";\").length == 1){\r\n");
      out.write("\t\tadd_item(treeNode.id,treeNode.name);\r\n");
      out.write("\t} \r\n");
      out.write("}\r\n");
      out.write("function deptOnClick0(event, treeId, treeNode) {\r\n");
      out.write("\tif(treeNode.nocheck){\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\tif(treeNode.checked){\r\n");
      out.write("\t\tsetCheckStatue(false,treeNode);\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\tsetCheckStatue(true,treeNode);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("/**\r\n");
      out.write(" * 勾选\r\n");
      out.write(" */\r\n");
      out.write("function deptOnCheckFunc(event, treeId, treeNode) {\r\n");
      out.write("\tvar uuid = treeNode.id;\r\n");
      out.write("\t//console.log(treeNode);\r\n");
      out.write("\tvar isChecked = treeNode.checked;\r\n");
      out.write("\tvar deptNameStr = treeNode.name;\r\n");
      out.write("\tvar zTreeObj = $.fn.zTree.getZTreeObj(treeId);\r\n");
      out.write("\t// = $.fn.zTree.getZTreeObj(\"selectDeptZtree\");\r\n");
      out.write("\t$(\".search_result\").slideUp(200);\r\n");
      out.write("\tif(uuid.split(\";\")[1] == 'org'){//点击单位\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar allChildNote = zTreeObj.getNodesByParamFuzzy(\"name\", \"\", treeNode);\r\n");
      out.write("\t\tfor(var i= 0  ;i <allChildNote.length ; i ++){\r\n");
      out.write("\t\t\tvar tempNote = allChildNote[i];\r\n");
      out.write("\t\t\tif(tempNote.nocheck){\r\n");
      out.write("\t\t\t\tcontinue;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tsetCheckStatue(isChecked ,tempNote);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\tsetCheckStatue(isChecked ,treeNode);\r\n");
      out.write("\t\tvar allChildNote = zTreeObj.getNodesByParamFuzzy(\"name\", \"\", treeNode);\r\n");
      out.write("\t\tfor(var i= 0  ;i <allChildNote.length ; i ++){\r\n");
      out.write("\t\t\tvar tempNote = allChildNote[i];\r\n");
      out.write("\t\t\tsetCheckStatue(isChecked ,tempNote);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("// \tgetDeptStr(uuid,window.isCheckedState,deptName);\r\n");
      out.write("\t\r\n");
      out.write("\t//添加不嫩\r\n");
      out.write("\t// $(\"#dept_item_0\").append(\"<a class='list-group-item' href='javascript:void(0);' style='text-align:center'  item_id='\"+uuid+ \"' item_name='\"+deptName+\"'><h6 class='list-group-item-heading' >\"+ deptName+\"<i class='glyphicon glyphicon-remove' style='text-align:right;'></i></h6></a>\");\r\n");
      out.write("\t\r\n");
      out.write("\t\t \r\n");
      out.write("}\r\n");
      out.write("/**\r\n");
      out.write(" * 点击或者或者不选择状态\r\n");
      out.write(" */\r\n");
      out.write("function setCheckStatue(isChecked , treeNode){\r\n");
      out.write("\tvar uuid = treeNode.id;\r\n");
      out.write("\tvar deptNameStr = treeNode.name;\r\n");
      out.write("\t\r\n");
      out.write("\tif(isChecked){\r\n");
      out.write("\t\tif(!existsId(uuid)){\r\n");
      out.write("\t\t\t$(\"#dept_item_0\").append(\"<a class='list-group-item dept-item active'  style='text-align:center;;cursor:pointer' id='select_id_\" +uuid + \"' item_id='\"+uuid+ \"' item_name='\"+deptNameStr+\"' deptLevel=''><h6 class='list-group-item-heading'>\"+ deptNameStr+\"</h6></a>\");\r\n");
      out.write("\t\t\tadd_item(uuid, deptNameStr);\r\n");
      out.write("\t\t\tjQuery('#dept_item_0 .dept-item').on('click', function(){\r\n");
      out.write("\t\t\t\t checkOrNocheckNodesById(this.getAttribute(\"item_id\") ,false);\r\n");
      out.write("\t\t\t\t remove_item(this.getAttribute(\"item_id\"), this.getAttribute(\"item_name\"));\r\n");
      out.write("\t\t\t\t jQuery(this).remove();\r\n");
      out.write("\t\t\t\t \r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\t//if(existsId(uuid)){\r\n");
      out.write("\t\t\t remove_item($(\"#select_id_\" +uuid).attr(\"item_id\"),$(\"#select_id_\" +uuid).attr(\"item_name\"));\r\n");
      out.write("\t\t\t $(\"#select_id_\" +uuid).remove();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t//}\r\n");
      out.write("\t}\r\n");
      out.write("\tcheckOrNocheckNodesById(uuid , isChecked);\r\n");
      out.write("}\r\n");
      out.write("/**\r\n");
      out.write(" * 判断是否存在此部门id\r\n");
      out.write(" */\r\n");
      out.write("function existsId( id ){\r\n");
      out.write("\tvar existsObj = false;\r\n");
      out.write("\tvar obj = $(\"#select_id_\" +id)[0];\r\n");
      out.write("\tif(obj){\r\n");
      out.write("\t\texistsObj = true;\r\n");
      out.write("\t}\r\n");
      out.write("\treturn existsObj;\r\n");
      out.write("}\r\n");
      out.write("/**\r\n");
      out.write(" * 批量删除\r\n");
      out.write(" */\r\n");
      out.write("function removeDeptAll(){\r\n");
      out.write("\tvar zTreeObj = $.fn.zTree.getZTreeObj(\"selectDeptZtree\");\r\n");
      out.write("\tjQuery('#dept_item_0 .dept-item').each(function(){\r\n");
      out.write("\t\tremove_item(this.getAttribute(\"item_id\"), this.getAttribute(\"item_name\"));\r\n");
      out.write("\t\t jQuery(this).remove();\r\n");
      out.write("\t});\r\n");
      out.write("\tzTreeObj.checkAllNodes(false);//取消所有节点\r\n");
      out.write("}\r\n");
      out.write("/**\r\n");
      out.write(" * 取消部门树打勾状态\r\n");
      out.write("  id:ID\r\n");
      out.write("  check：取消选中\r\n");
      out.write(" */\r\n");
      out.write("function checkOrNocheckNodesById(id , check){\r\n");
      out.write("\tvar zTreeObj = $.fn.zTree.getZTreeObj(\"selectDeptZtree\");\r\n");
      out.write("\tvar node = zTreeObj.getNodeByParam(\"id\",id,null);\r\n");
      out.write("\tif(node){\r\n");
      out.write("\t\tif(check){\r\n");
      out.write("\t\t\tzTreeObj.checkNode(node, true,true); \r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\tzTreeObj.checkNode(node, false,true); \r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("/**\r\n");
      out.write(" * 按条件查询部门\r\n");
      out.write(" */\r\n");
      out.write("function CheckSend1(){\r\n");
      out.write("\tvar kword = document.getElementById(\"kword\");\r\n");
      out.write("\tvar search_icon = document.getElementById(\"search_icon1\");\r\n");
      out.write("\t  if(kword.value==\"按部门名称搜索...\")\r\n");
      out.write("\t     kword.value=\"\";\r\n");
      out.write("\t  if(kword.value==\"\" && search_icon.innerHTML ==\"查询\"){\r\n");
      out.write("\t\t  search_icon.innerHTML ==\"查询\";\r\n");
      out.write("\t  }\r\n");
      out.write("\t  if(key!=kword.value && kword.value!=\"\"){\r\n");
      out.write("\t     key=kword.value;\r\n");
      out.write("\t     doSearch(key);\r\n");
      out.write("\t     \r\n");
      out.write("\t     if(search_icon.innerHTML ==\"查询\"){   \r\n");
      out.write("\t    \t search_icon.innerHTML =\"清除\";\r\n");
      out.write("\t    \t search_icon.title=\"清除关键字\";\r\n");
      out.write("\t    \t search_icon.onclick=function(){\r\n");
      out.write("\t    \t\t $(\".search_result\").slideUp(200);\r\n");
      out.write("\t    \t\t kword.value='按部门名称搜索...';\r\n");
      out.write("\t    \t\t search_icon.innerHTML =\"查询\";\r\n");
      out.write("\t    \t\t search_icon.title=\"\";\r\n");
      out.write("\t    \t\t search_icon.onclick=null;\r\n");
      out.write("\t    \t\t };\r\n");
      out.write("\t     }\r\n");
      out.write("\t  }\r\n");
      out.write("\t  \r\n");
      out.write("\t  ctroltime=setTimeout(CheckSend1,100);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/***\r\n");
      out.write(" * 按部门名称模糊查询\r\n");
      out.write(" */\r\n");
      out.write("function doSearch(name){\r\n");
      out.write("\tvar url = contextPath +  \"/orgSelectManager/selectPostDeptByDeptName.action\";\r\n");
      out.write("\tvar para = {dept:name};\r\n");
      out.write("\tvar jsonRs = tools.requestJsonRs(url,para);\r\n");
      out.write("\tif(jsonRs.rtState){\r\n");
      out.write("\t\tvar dataList = jsonRs.rtData;\r\n");
      out.write("\t\tdataLoad1(dataList,\"部门查询\");\r\n");
      out.write("\t\t//dataLoad(dataList,jsonRs.rtMsg);\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\talert(jsonRs.rtMsg);\r\n");
      out.write("\t} \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/***\r\n");
      out.write(" * 加载数据 \r\n");
      out.write(" * datList: 人员列表\r\n");
      out.write(" * type ：判断是否需要初始化右侧项目 1-不需要 其他-需要\r\n");
      out.write(" */\r\n");
      out.write("function dataLoad1(dataList,name, type){\r\n");
      out.write("\t $(\"a\").remove(\".right .list-group-item\");\r\n");
      out.write("\t $(\"a\").remove(\".list-group-item-header\");\r\n");
      out.write("\t $(\"div\").remove(\".block-right-item,.emptyClass\");\r\n");
      out.write("\t if(dataList.length > 0){\r\n");
      out.write("\t\t if(isSingle == '1'){//单选\r\n");
      out.write("\t\t\t\tsingle_select = true;\r\n");
      out.write("\t\t\t $(\"#dept_item_0\").append(\"<a  class='list-group-item-header' style='padding:8px 15px;cursor:pointer'>\" + name + \"</a>\");\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t for(var i = 0; i < dataList.length; i++){\r\n");
      out.write("\t\t\t\t\tvar roleId = dataList[i].uuid;\r\n");
      out.write("\t\t\t\t\tvar item = dataList[i];\r\n");
      out.write("\t\t\t\t\tvar itemId = item.id;\r\n");
      out.write("\t\t\t\t\tvar name = dataList[i].deptName;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t if(roleId != ''){\r\n");
      out.write("\t\t\t\t\t\t $(\"#dept_item_0\").append(\"<a class='list-group-item' style='text-align:center;cursor:pointer'  item_id='\"+roleId+ \"' item_name='\"+name+\"'><h6 class='list-group-item-heading'>\"+ name +\"</h6></a>\");\r\n");
      out.write("\t\t\t\t\t }  \r\n");
      out.write("\t\t\t\t }\r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t }else{\r\n");
      out.write("\t\t\tvar arr = [];\r\n");
      out.write("\t\t\tfor(var i = 0,l=dataList.length;i<l;i++){\r\n");
      out.write("\t\t\t\tarr.push(\"<li uuid=\"+dataList[i].uuid+\" deptName=\"+dataList[i].deptName+\" class='search_result_li' style='list-style:none;text-indent:20px;color:#000;'><a class='' uuid=\"+dataList[i].uuid+\">\"+dataList[i].deptName+\"</a></li>\");\r\n");
      out.write("\t\t\t};\r\n");
      out.write("\t\t\t$(\".search_result\").empty();\r\n");
      out.write("\t\t\t$(\".search_result\").append(arr.join(\"\"));\r\n");
      out.write("\t\t\t$(\".search_result\").slideDown(200);\r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t\t $(\"li\").remove(\".list-group-item\");\r\n");
      out.write("\t\t     $(\"#dept_item_0\").append(\"<a  class='list-group-item-header' style='padding:8px 15px;cursor:pointer'>\" + '已选部门'+ \"</a>\");\r\n");
      out.write("\t\t     $(\"#dept_item_0\").append(\"<li  id='removeDeptAll' onclick='removeDeptAll();'  class='list-group-item' style='text-align:center;;cursor:pointer'>全部删除</li>\");\r\n");
      out.write("\t\t     doInitDept();\r\n");
      out.write("\t\t };\r\n");
      out.write(" \r\n");
      out.write("\t }else{\r\n");
      out.write("\t\t /* if(!name){\r\n");
      out.write("\t\t\tname = \"已选部门\";\r\n");
      out.write("\t\t}  */\r\n");
      out.write("\t\t//$(\"li\").remove(\".list-group-item\");\r\n");
      out.write("\t\t if(isSingle == '1'){\r\n");
      out.write("\t\t\t\tsingle_select = true;\r\n");
      out.write("\t\t\t\t$(\"li\").remove(\".list-group-item\");\r\n");
      out.write("\t\t\t\t $(\"#dept_item_0\").append(\"<a   class='list-group-item-header'  style='padding:8px 15px;;cursor:pointer'>\" + name + \"</a>\"\r\n");
      out.write("\t\t\t\t\t\t\t+\"<div align='center' class='emptyClass' style='padding-top:5px;'><h6>无相关部门！</h6></div>\");\r\n");
      out.write("\t\t }else{\r\n");
      out.write("\t\t\t \r\n");
      out.write("\t\t$(\".search_result\").empty();\r\n");
      out.write("\t\t$(\".search_result\").append(\"<a   class='list-group-item-header'  style='padding:8px 15px;;cursor:pointer'>\" + name + \"</a>\"\r\n");
      out.write("\t\t\t\t+\"<div align='center' class='emptyClass' style='padding-top:5px;'><h6>无相关部门！</h6></div>\");\r\n");
      out.write("\t\t$(\".search_result\").slideDown(200);\r\n");
      out.write("\t\t$(\"li\").remove(\".list-group-item\");\r\n");
      out.write("\t\t$(\"#dept_item_0\").append(\"<a  class='list-group-item-header' style='padding:8px 15px;cursor:pointer'><input type='checkbox' id='isCheckAll' onclick='checkAll(this)'/>\" + '已选部门'+ \"</a>\");\r\n");
      out.write("\t\t$(\"#dept_item_0\").append(\"<li  id='removeDeptAll' onclick='removeDeptAll();'  class='list-group-item' style='text-align:center;;cursor:pointer'>全部删除</li>\");\r\n");
      out.write("\t\tdoInitDept();\r\n");
      out.write("\t\t }\r\n");
      out.write("\t\t/* $(\"#dept_item_0\").append(\"<a   class='list-group-item-header'  style='padding:8px 15px;;cursor:pointer'>\" + name + \"</a>\"\r\n");
      out.write("\t\t\t+\"<div align='center' class='emptyClass' style='padding-top:5px;'><h6>无相关人员！</h6></div>\"); */\r\n");
      out.write("\t\t\r\n");
      out.write("\t }\r\n");
      out.write("/* \t //处理多选人员。点击删除\r\n");
      out.write("     if(type && type == '1'){\r\n");
      out.write("    \t alert(type);\r\n");
      out.write("    \t dataSelectLoadInit(dataList); \r\n");
      out.write("     } */\r\n");
      out.write("\t\r\n");
      out.write(" \tload_init();  \r\n");
      out.write("\tload_init_item();  \r\n");
      out.write("    //默认加载角色选中状态\r\n");
      out.write("   init_item('dept'); \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(".search_result li:hover{\r\n");
      out.write("\tbackground-color:#aaa;\r\n");
      out.write("\ttext-indent:20px;\r\n");
      out.write("\tcolor:#fff;\r\n");
      out.write("}\r\n");
      out.write(".search_result li a{\r\n");
      out.write("\tdisplay:inline-block;\r\n");
      out.write("\twidth:100%;\r\n");
      out.write("\theight:100%;\r\n");
      out.write("\tpadding:10px 5px;\r\n");
      out.write("}\r\n");
      out.write(".search_result li a:hover{\r\n");
      out.write("\tbackground-color:#aaa;\r\n");
      out.write("\ttext-indent:20px;\r\n");
      out.write("\tcolor:#fff;\r\n");
      out.write("\ttext-decoration:none;\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body onload=\"doInit()\" >\r\n");
      out.write("<div style=\"margin-top:5px;margin-left:5px;\">\r\n");
      out.write("\t<div class=\"titlebar\">\r\n");
      out.write("\t\t<img src=\"");
      out.print(contextPath );
      out.write("/system/core/orgselect/icon_dept.png\" alt=\"\" class='title1_img'/>\r\n");
      out.write("\t\t<div class=\"titleBlock\">\r\n");
      out.write("\t\t\t<p class=\"title\">选择部门</p>\r\n");
      out.write("\t\t\t<ul class=\"tab\">\r\n");
      out.write("\t\t\t\t<li class='tabMenu tabActive'>按部门选择</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class='panel-group'>\r\n");
      out.write("\t\t<ul class='tabList' id=\"accordion\" >\r\n");
      out.write("\t\t\t<li class=\"tabContent\" style=\"display:block;\">\r\n");
      out.write("\t\t\t\t<ul id=\"selectDeptZtree\" class=\"ztree\">\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t</div>\r\n");
      out.write(" <div class=\"main-block\" id=\"block_dept\" style=\"display:block;top:0px;\">\r\n");
      out.write("    <div class=\"right single\" id=\"dept_item\">\r\n");
      out.write("    \t<div style=\"padding-bottom: 5px;\">\r\n");
      out.write("\t\t<table >\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t    \t <div class=\"input-group clearfix\" style='position:relative;'>\r\n");
      out.write("          \t\t    <input class=\"form-control\" style=\"float:left;;width:190px;\" type=\"text\" id=\"kword\" name=\"kword\" value=\"按部门名称搜索...\" onfocus=\"ctroltime=setTimeout(CheckSend1,100);\" onblur=\"clearTimeout(ctroltime);if(this.value=='')this.value='按部门名称搜索...';\" >\r\n");
      out.write("            \t    <div class=\"input-group-btn\" style=\"float:left;\">          \t\r\n");
      out.write("\t            \t  <button tabindex=\"-1\" class=\"btn btn-default\" type=\"button\"  value=\"\"  id=\"search_icon1\">查询</button>\r\n");
      out.write("                   </div>\r\n");
      out.write("                   \r\n");
      out.write("               \t\t<ul class=\"search_result\" style='position:absolute;z-index:999;overflow-y:auto;overflow-x:hidden;margin-left:-2px;border:1px solid #e2e2e2;border-top:none;padding-left:0px;top:100%;left:0;width:248px;height:313px;background-color:#fff;display:none;'>\r\n");
      out.write("               \t\t\r\n");
      out.write("               \t\t</ul>\r\n");
      out.write("                   \r\n");
      out.write("                 </div>\r\n");
      out.write("\t\t    </td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</div>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("\t\t<div class=\"block-right\" id=\"dept_item_0\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<a  class='list-group-item-header'  style=\"padding:8px 15px;;cursor:pointer\">已选部门</a>\r\n");
      out.write("\t\t\t\t ");
if(!isSingle.equals("1")){ 
      out.write("\r\n");
      out.write("\t\t\t   <!--  <li href='javascript:void(0);' id=\"addDeptAll\" class=\"list-group-item \" style=\"text-align:center;\">全部添加</li> -->\r\n");
      out.write("\t\t\t\t<li  id=\"removeDeptAll\" onclick=\"removeDeptAll();\" class=\"list-group-item\" style=\"text-align:center;;cursor:pointer\">全部删除</li>\r\n");
      out.write("\t\t\t   ");
} 
      out.write(" \r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t<!-- <div class=\"block-right\" id=\"dept_item_0\">\r\n");
      out.write("\t    </div>  -->\r\n");
      out.write("\t\t<div id=\"\" align=\"center\" style=\"margin-top:10px;height:40px;\">\r\n");
      out.write("\t\t   <input type=\"button\" class=\"btn btn-primary\" value=\"确定\" onclick=\"close_window();\">&nbsp;&nbsp;\r\n");
      out.write("\t\t</div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("$(\"body\").on(\"click\",\".search_result_li\",function(){\r\n");
      out.write("\tdeptId= $(this).attr('uuid');\r\n");
      out.write("\tdeptName= $(this).attr('deptName');\r\n");
      out.write("\t$(\".search_result\").empty();\r\n");
      out.write("\t$(\".search_result\").hide();\r\n");
      out.write("\t$(\".form-control\").val(\"按部门名称搜索...\");\r\n");
      out.write("\t//$(\"#dept_item_0\").append(\"<a class='list-group-item dept-item active' style='text-align:center;cursor:pointer;display:none;'  item_id='\"+''+ \"' item_name='\"+''+\"'><h6 class='list-group-item-heading'>\"+ '' +\"</h6></a>\");\r\n");
      out.write("\t//$(\"#dept_item_0\").append(\"<a class='list-group-item dept-item active'  style='text-align:center;;cursor:pointer' id='select_id_\" +deltId + \"' item_id='\"+deptId+ \"' item_name='\"+deptName+\"' deptLevel=''><h6 class='list-group-item-heading'>\"+ deptName+\"<i class='glyphicon glyphicon-remove' style='text-align:right;'></i></h6></a>\");\r\n");
      out.write("\tvar oUl = $(\".block-right\").find(\".dept-item\");\r\n");
      out.write("\tif(oUl.length==0){\r\n");
      out.write("\t\t$(\"#dept_item_0\").append(\"<a class='list-group-item dept-item active' style='text-align:center;cursor:pointer' id='select_id_\"+deptId+\"' item_id='\"+deptId+ \"' item_name='\"+deptName+\"'><h6 class='list-group-item-heading'>\"+ deptName +\"</h6></a>\");\r\n");
      out.write("\t\tadd_item(deptId, deptName);\r\n");
      out.write("\t\tcheckOrNocheckNodesById(deptId, true);\r\n");
      out.write("\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\tvar check1 = false;\r\n");
      out.write("\t\tfor(var i=0,l=oUl.length;i<l;i++){\r\n");
      out.write("\t\t\tif($(oUl[i]).attr(\"item_id\")==deptId){\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t} else{\r\n");
      out.write("\t\t\t\tcheck1 = true;\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}; \r\n");
      out.write("\t\t};\r\n");
      out.write("\t\tif(check1){\r\n");
      out.write("\t\t\t$(\"#dept_item_0\").append(\"<a class='list-group-item dept-item active' style='text-align:center;cursor:pointer' id='select_id_\"+deptId+\"' item_id='\"+deptId+ \"' item_name='\"+deptName+\"'><h6 class='list-group-item-heading'>\"+ deptName +\"</h6></a>\");\r\n");
      out.write("\t\t\tadd_item(deptId, deptName);\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\t\tcheckOrNocheckNodesById(deptId, true);\r\n");
      out.write("\t};\r\n");
      out.write("\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("var check1 = 0;//判断是否为空  空收回面板  显示已选择数据\r\n");
      out.write("$(\".form-control\").keyup(function(){\r\n");
      out.write("\tif($(this).val()==\"\"){\r\n");
      out.write("\t\t$(\".search_result\").slideUp(200);\r\n");
      out.write("\t\t//$(\".search_result\").empty();\r\n");
      out.write("\t\tcheck1++;\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("$(\".tabMenu\").click(function(){\r\n");
      out.write("\tvar index = $(this).index();\r\n");
      out.write("\t$(\".tabMenu\").removeClass('tabActive');\r\n");
      out.write("\t$(this).addClass(\"tabActive\");\r\n");
      out.write("\t$(\".tabContent\").hide();\r\n");
      out.write("\t$(\".tabContent\").eq(index).show();\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else log(t.getMessage(), t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
