package org.apache.jsp.xzfy.jsp.homePage;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.text.SimpleDateFormat;
import com.tianee.webframe.util.servlet.TeeCookieUtils;
import java.util.*;
import com.tianee.oa.oaconst.TeeConst;
import com.tianee.oa.core.org.bean.TeePerson;
import com.tianee.webframe.util.str.TeeUtility;
import com.tianee.webframe.util.date.TeeDateUtil;
import com.tianee.webframe.util.global.TeeSysProps;
import com.tianee.webframe.util.str.TeeStringUtil;
import com.tianee.oa.core.org.service.TeePersonService;
import com.tianee.oa.oaconst.TeeModelIdConst;
import com.tianee.webframe.util.servlet.TeeCookieUtils;
import com.tianee.webframe.util.str.TeeStringUtil;
import com.tianee.webframe.util.global.TeeSysProps;

public final class homePage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  static {
    _jspx_dependants = new java.util.ArrayList(3);
    _jspx_dependants.add("/header/header2.0.jsp");
    _jspx_dependants.add("/header/easyui2.0.jsp");
    _jspx_dependants.add("/header/upload.jsp");
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=Edge\">\r\n");

String contextPath = request.getContextPath();
String basePath = request.getScheme() + "://"
		+ request.getServerName() + ":" + request.getServerPort()
		+ contextPath + "/";
//获取主题的索引号
int styleIndex = 1;
Integer styleInSession = (Integer) request.getSession().getAttribute("STYLE_TYPE_INDEX");
if (styleInSession != null) {
	styleIndex = styleInSession;
}
String stylePath = contextPath + "/common/styles";
String imgPath = stylePath + "/style" + styleIndex + "/img";
String cssPath = stylePath + "/style" + styleIndex + "/css";
String systemImagePath = contextPath+"/common/images";

//第二套风格
int STYLE_TYPE_INDEX_2 = TeeStringUtil.getInteger( request.getSession().getAttribute("STYLE_TYPE_INDEX_2"), 1);
String cssPathSecond = contextPath + "/system/frame/2/styles/style" + STYLE_TYPE_INDEX_2 + "/css";
String imgPathSecond = contextPath + "/system/frame/2/styles/style" + STYLE_TYPE_INDEX_2 + "/img";


String loginOutText = TeeSysProps.getString("LOGIN_OUT_TEXT");
String ieTitle = TeeSysProps.getString("IE_TITLE");
String secUserMem = TeeSysProps.getString("SEC_USER_MEM");

Cookie cookie = TeeCookieUtils.getCookie(request, "skin_new");
String skinNew = "1";
if(cookie!=null){
	skinNew = cookie.getValue();
}

      out.write("<!-- zt_webframe框架引入 jquery -->\r\n");
      out.write("<script src=\"");
      out.print(contextPath );
      out.write("/common/jquery-easyui-1.6.11/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- zt_webframe框架引入 核心库 -->\r\n");
      out.write("<script src=\"");
      out.print(contextPath );
      out.write("/common/zt_webframe/js/package.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(contextPath );
      out.write("/common/js/sys2.0.js?v=2\"></script>\r\n");
      out.write("<script src=\"");
      out.print(contextPath );
      out.write("/common/js/sysUtil.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(contextPath );
      out.write("/common/js/src/orgselect.js\"></script>\r\n");
      out.write("<!--\r\n");
      out.write("\r\n");
      out.write("//-->\r\n");
      out.write("<!-- zt_webframe框架引入 css样式 -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/common/zt_webframe/css/init");
      out.print(skinNew );
      out.write(".css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/common/zt_webframe/css/package");
      out.print(skinNew );
      out.write(".css\">\r\n");
      out.write("\r\n");
      out.write("<script src=\"");
      out.print(contextPath );
      out.write("/common/js/tools2.0.js?v=1\"></script>\r\n");
      out.write("<script src=\"");
      out.print(contextPath );
      out.write("/common/js/TeeMenu.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("/** 变量定义 **/\r\n");
      out.write("var contextPath = \"");
      out.print(contextPath );
      out.write("\";\r\n");
      out.write("var systemImagePath = contextPath+\"/common/images\";\r\n");
      out.write("var uploadFlashUrl = \"");
      out.print(contextPath );
      out.write("/common/swfupload/swfupload.swf\";\r\n");
      out.write("var commonUploadUrl = \"");
      out.print(contextPath );
      out.write("/attachmentController/commonUpload.action;jsessionid=");
      out.print(session.getId());
      out.write("\";\r\n");
      out.write("var xparent;\r\n");
      out.write("var stylePath = \"");
      out.print(stylePath);
      out.write("\";\r\n");
      out.write("if(window.dialogArguments){\r\n");
      out.write("\txparent = window.dialogArguments;\r\n");
      out.write("}else if(window.opener){\r\n");
      out.write("\txparent = opener;\r\n");
      out.write("}else{\r\n");
      out.write("\txparent = window;\r\n");
      out.write("}\r\n");
      out.write("window.UEDITOR_HOME_URL = \"");
      out.print(contextPath);
      out.write("/common/ueditor/\";\r\n");
      out.write("$.browser = {};\r\n");
      out.write("$.browser.mozilla = /firefox/.test(navigator.userAgent.toLowerCase());\r\n");
      out.write("$.browser.webkit = /webkit/.test(navigator.userAgent.toLowerCase());\r\n");
      out.write("$.browser.opera = /opera/.test(navigator.userAgent.toLowerCase());\r\n");
      out.write("$.browser.msie = /msie/.test(navigator.userAgent.toLowerCase());\r\n");
      out.write("</script>\r\n");
      out.write("<!-- zt_webframe框架引入 核心库 -->\r\n");
      out.write("<script type=\"text/javascript\" src = '");
      out.print(request.getContextPath() );
      out.write("/common/jquery-easyui-1.6.11/jquery.easyui.min.js'></script>\r\n");
      out.write("<script type=\"text/javascript\" src = '");
      out.print(request.getContextPath() );
      out.write("/common/zt_webframe/js/jquery.datagrid.extend.js'></script>\r\n");
      out.write("<script type=\"text/javascript\" src = '");
      out.print(request.getContextPath() );
      out.write("/common/jquery-easyui-1.6.11/locale/easyui-lang-zh_CN.js'></script>\r\n");
      out.write("\r\n");

Cookie __cookie = TeeCookieUtils.getCookie(request, "skin_new");
String __skinNew = "1";
if(__cookie!=null){
	__skinNew = __cookie.getValue();
}

      out.write("<!-- zt_webframe框架引入 css样式 -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/common/jquery-easyui-1.6.11/themes/metro/easyui.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/common/swfupload/css/default.css\" />\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/common/js/jquery.form.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/common/swfupload/swfupload.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/common/swfupload/swfupload.queue.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/common/swfupload/fileprogress.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/common/swfupload/handlers.js?v=1\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/common/js/upload.js?v=4\"></script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("var UPLOAD_ATTACH_LIMIT_GLOBAL = \"");
      out.print(TeeSysProps.getString("UPLOAD_ATTACH_LIMIT"));
      out.write("\";\r\n");
      out.write("var GLOBAL_ATTACH_TYPE=\"");
      out.print(TeeStringUtil.getString(TeeSysProps.getString("GLOBAL_ATTACH_TYPE")) );
      out.write("\";\r\n");
      out.write("</script>");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(contextPath);
      out.write("/supervise/adminCoercion/js/coercion_direct_input.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(contextPath);
      out.write("/supervise/common/js/common.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(contextPath);
      out.write("/common/js/juicer-min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(contextPath);
      out.write("/system/frame/default/js/echarts.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(contextPath);
      out.write("/system/frame/default/js/mainForSimple.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/xzfy/css/init1.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/xzfy/css/common.css\">\r\n");
      out.write("    \r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/common/font-awesome/css/font-awesome.min.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/supervise/testFrontPage/iconfont/iconfont.css\" />\r\n");
      out.write("\r\n");
      out.write("<title>行政强制案件填报</title>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("<style>\r\n");
      out.write("        /*整体布局样式*/\r\n");
      out.write("        \r\n");
      out.write("        .main {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .main-up {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 38%;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .main-down {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 59%;\r\n");
      out.write("            margin-top: 1%;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .moheader {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            height: 35px;\r\n");
      out.write("            line-height: 35px;\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            text-align: left;\r\n");
      out.write("            text-indent: 10px;\r\n");
      out.write("            border-bottom: 1px solid #e8e8e8;\r\n");
      out.write("            background: #fbfbfb;\r\n");
      out.write("            color: #2d4c98;\r\n");
      out.write("            border-top-left-radius: 5px;\r\n");
      out.write("            border-top-right-radius: 5px;\r\n");
      out.write("            font-size: 13px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .downleft {\r\n");
      out.write("            width: 74%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            vertical-align: top;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .downright {\r\n");
      out.write("            width: 25%;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            vertical-align: top;\r\n");
      out.write("            border: 1px solid #d1d1d1;\r\n");
      out.write("            float: right;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("        }\r\n");
      out.write("        /*待办事项*/\r\n");
      out.write("        \r\n");
      out.write("        .info {\r\n");
      out.write("            width: 30%;\r\n");
      out.write("            float: left;\r\n");
      out.write("            border: 1px solid #d1d1d1;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            margin-bottom: 10px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .infoheader {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            text-indent: 0;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .infocontent li {\r\n");
      out.write("            height: 22px;\r\n");
      out.write("            margin: 0 5px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .infocontent li :first-child {\r\n");
      out.write("            padding-left: 20px;\r\n");
      out.write("            line-height: 22px;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("            float: left;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .infocontent li :last-child {\r\n");
      out.write("            padding-right: 20px;\r\n");
      out.write("            line-height: 22px;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("            float: right;\r\n");
      out.write("            color: #6989FF;\r\n");
      out.write("        }\r\n");
      out.write("        /*通知公告*/\r\n");
      out.write("        \r\n");
      out.write("        .notice {\r\n");
      out.write("            width: 40%;\r\n");
      out.write("            margin: 0 10px;\r\n");
      out.write("            border: 1px solid #d1d1d1;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            float: left;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            margin-bottom: 10px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .noticeUl li {\r\n");
      out.write("            list-style-type: square;\r\n");
      out.write("            margin-left: 27px;\r\n");
      out.write("            height: 25px;\r\n");
      out.write("            text-indent: -5px;\r\n");
      out.write("            line-height: 25px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .noticeDate {\r\n");
      out.write("            width: 25%;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            float: right;\r\n");
      out.write("        }\r\n");
      out.write("        /*受理情况统计*/\r\n");
      out.write("        \r\n");
      out.write("        .pie {\r\n");
      out.write("            width: 28%;\r\n");
      out.write("            border: 1px solid #d1d1d1;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            float: right;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            margin-bottom: 10px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        #pieDiv {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            height: calc(100% - 35px);\r\n");
      out.write("        }\r\n");
      out.write("        /*常用功能*/\r\n");
      out.write("        \r\n");
      out.write("        .enter {\r\n");
      out.write("            height: 25%;\r\n");
      out.write("            position: relative;\r\n");
      out.write("            border: 1px solid #d1d1d1;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            margin-bottom: 10px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .enterhead {\r\n");
      out.write("width: 60px;\r\n");
      out.write("    height: 60px;\r\n");
      out.write("    line-height: 30px;\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("    color: #2d4c98;\r\n");
      out.write("    margin: 0 auto;\r\n");
      out.write("    padding-right: 20px;\r\n");
      out.write("    border-right: 1px solid #DADADA;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .enter ul {\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            margin-left: 15px;\r\n");
      out.write("            display: table;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .enter ul li {\r\n");
      out.write("            margin-right: 10px;\r\n");
      out.write("            display: table-cell;\r\n");
      out.write("            width: 80px;\r\n");
      out.write("            height: 70%;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            vertical-align: middle;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .enter ul li span {\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            margin-top: 5px;\r\n");
      out.write("        }\r\n");
      out.write("        /*常用功能*/\r\n");
      out.write("        \r\n");
      out.write("        .list {\r\n");
      out.write("            height: 72%;\r\n");
      out.write("            border: 1px solid #d1d1d1;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .data {\r\n");
      out.write("            border-bottom: 1px solid #e8e8e8;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        #pieDiv {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            height: calc(100% - 35px);\r\n");
      out.write("        }\r\n");
      out.write("        /*结案情况统计*/\r\n");
      out.write("        \r\n");
      out.write("        #dataDiv {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            height: calc(100% - 35px);\r\n");
      out.write("        }\r\n");
      out.write("        /*待办tab切换*/\r\n");
      out.write("        \r\n");
      out.write("        #tableNav {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            border-bottom: 1px solid #ececed;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .tabactive {\r\n");
      out.write("            border-bottom: 3px solid #4374e8;\r\n");
      out.write("            color: #4374e8;\r\n");
      out.write("            font-size: 15px!important;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        .tabnav-button input {\r\n");
      out.write("            margin-top: 3px;\r\n");
      out.write("            margin-left: 10px;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("            font-size: 14px;\r\n");
      out.write("            width: 80px;\r\n");
      out.write("            height: 26px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        #tab {\r\n");
      out.write("            /* font-size: 0; */\r\n");
      out.write("            height: 37px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("        #tab li {\r\n");
      out.write("            /* border-right: 1px solid #ececed; */\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            padding: 0 20px;\r\n");
      out.write("            /* margin: 0 20px; */\r\n");
      out.write("            line-height: 38px;\r\n");
      out.write("            height: 38px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            font-size: 13px;\r\n");
      out.write("            /* vertical-align: middle; */\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .noticemore {\r\n");
      out.write("            float: right;\r\n");
      out.write("            margin-right: 20px;\r\n");
      out.write("            color: #5B5B5B;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\" overflow: hidden; padding: 10px;\">\r\n");
      out.write("    <div class=\"main\">\r\n");
      out.write("        <div class=\"main-up\">\r\n");
      out.write("            <!-- 待办提醒 -->\r\n");
      out.write("            <div class=\"info\">\r\n");
      out.write("                <p class=\"moheader infoheader\">您好，xxx！您所在复议机关：xxx</p>\r\n");
      out.write("                <table id=\"dg\" class=\"easyui-datagrid\"\r\n");
      out.write("\t\t                       url=\"/xzfy/homepage/caseSummary/listByStatus.action\"\r\n");
      out.write("\t\t                       toolbar=\"#toolbar\"\r\n");
      out.write("\t\t                       rownumbers=\"true\" fitColumns=\"true\" singleSelect=\"true\"\r\n");
      out.write("\t\t                       class=\"infocontent\">\r\n");
      out.write("\t                 <thead>\r\n");
      out.write("\t\t                 <tr>\r\n");
      out.write("\t\t\t             <th field=\"caseStatus\" width=\"50\">任务类型</th>\r\n");
      out.write("\t\t\t             <th field=\"total\" width=\"50\">总数</th>\r\n");
      out.write("\t\t                 </tr>\r\n");
      out.write("\t                </thead>\r\n");
      out.write("                </table>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- 通知公告 -->\r\n");
      out.write("            <div class=\"notice\">\r\n");
      out.write("                <p class=\"moheader noticeheader\">通知公告<span class=\"noticemore\">更多 ></span></p>\r\n");
      out.write("                <ul class=\"noticeUl\">\r\n");
      out.write("                    <li><a>【置顶】抓住规范行为的牛鼻子123123541345</a><span class=\"noticeDate\">2019-02-10</span></li>\r\n");
      out.write("                    <li><a>【置顶】抓住规范行为的牛鼻子123123541345</a><span class=\"noticeDate\">2019-02-10</span></li>\r\n");
      out.write("                    <li><a>【置顶】抓住规范行为的牛鼻子123123541345</a><span class=\"noticeDate\">2019-02-10</span></li>\r\n");
      out.write("                    <li><a>【置顶】抓住规范行为的牛鼻子123123541345</a><span class=\"noticeDate\">2019-02-10</span></li>\r\n");
      out.write("                    <li><a>【置顶】抓住规范行为的牛鼻子123123541345</a><span class=\"noticeDate\">2019-02-10</span></li>\r\n");
      out.write("                    <li><a>【置顶】抓住规范行为的牛鼻子123123541345</a><span class=\"noticeDate\">2019-02-10</span></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- 受理情况统计 -->\r\n");
      out.write("            <div class=\"pie\">\r\n");
      out.write("                <p class=\"moheader\">受理情况统计</p>\r\n");
      out.write("                <div id=\"pieDiv\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"main-down\">\r\n");
      out.write("            <div class=\"downleft\">\r\n");
      out.write("                <!-- 常用功能 -->\r\n");
      out.write("                <div class=\"enter\">\r\n");
      out.write("                    <ul>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <p class=\"enterhead\">常用功能</p>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><img src=\"./img/home_red.png\" alt=\"\">\r\n");
      out.write("                            <span>案件登记</span>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><img src=\"./img/home_yellow.png\" alt=\"\">\r\n");
      out.write("                            <span>案件填报</span>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><img src=\"./img/home_blue.png\" alt=\"\">\r\n");
      out.write("                            <span>案件提取</span>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><img src=\"./img/home_green.png\" alt=\"\">\r\n");
      out.write("                            <span>案件提取</span>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><img src=\"./img/home_plus.png\" alt=\"\"></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- 待办事项/办件 -->\r\n");
      out.write("                <div class=\"list\">\r\n");
      out.write("                    <div id=\"tableNav\">\r\n");
      out.write("                        <ul id='tab' class='tab maintab'>\r\n");
      out.write("                            <li id=\"option1\" class='tabactive'>待办事项</li>\r\n");
      out.write("                            <li id=\"option2\">我的办件</li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <table width=\"100%\" id=\"datagrid\" fit=\"true\"></table>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- 结案情况统计 -->\r\n");
      out.write("            <div class=\"downright\">\r\n");
      out.write("                <p class=\"moheader\">结案情况统计</p>\r\n");
      out.write("                <div id=\"dataDiv\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("        //受理情况统计 饼图\r\n");
      out.write("        var myChart1 = echarts.init(document.getElementById('pieDiv'));\r\n");
      out.write("        var option1 = {\r\n");
      out.write("            // title: {\r\n");
      out.write("            //     text: '某站点用户访问来源',\r\n");
      out.write("            //     subtext: '纯属虚构',\r\n");
      out.write("            //     x: 'center'\r\n");
      out.write("            // },\r\n");
      out.write("            color: [\r\n");
      out.write("                '#7D83FF',\r\n");
      out.write("                '#79CCEA',\r\n");
      out.write("                '#EF7D65',\r\n");
      out.write("                '#FED176',\r\n");
      out.write("                '#87D8C9',\r\n");
      out.write("                '#4DA5FE'\r\n");
      out.write("            ],\r\n");
      out.write("            tooltip: {\r\n");
      out.write("                trigger: 'item',\r\n");
      out.write("                formatter: \"{a} <br/>{b} : {c} ({d}%)\"\r\n");
      out.write("            },\r\n");
      out.write("            // legend: {\r\n");
      out.write("            //     orient: 'vertical',\r\n");
      out.write("            //     left: 'left',\r\n");
      out.write("            //     data: ['直接访问', '邮件营销', '联盟广告', '视频广告', '搜索引擎']\r\n");
      out.write("            // },\r\n");
      out.write("            series: [{\r\n");
      out.write("                name: '',\r\n");
      out.write("                type: 'pie',\r\n");
      out.write("                radius: '70%',\r\n");
      out.write("                center: ['50%', '50%'],\r\n");
      out.write("                data: [{\r\n");
      out.write("                    value: 122,\r\n");
      out.write("                    name: '行政许可'\r\n");
      out.write("                }, {\r\n");
      out.write("                    value: 326,\r\n");
      out.write("                    name: '行政强制'\r\n");
      out.write("                }, {\r\n");
      out.write("                    value: 480,\r\n");
      out.write("                    name: '行政处罚'\r\n");
      out.write("                }, {\r\n");
      out.write("                    value: 406,\r\n");
      out.write("                    name: '信息公开'\r\n");
      out.write("                }, {\r\n");
      out.write("                    value: 152,\r\n");
      out.write("                    name: '行政特权'\r\n");
      out.write("                }, {\r\n");
      out.write("                    value: 142,\r\n");
      out.write("                    name: '行政确认'\r\n");
      out.write("                }],\r\n");
      out.write("                itemStyle: {\r\n");
      out.write("                    emphasis: {\r\n");
      out.write("                        shadowBlur: 10,\r\n");
      out.write("                        shadowOffsetX: 0,\r\n");
      out.write("                        shadowColor: 'rgba(0, 0, 0, 0.5)'\r\n");
      out.write("                    }\r\n");
      out.write("                }\r\n");
      out.write("            }]\r\n");
      out.write("        };\r\n");
      out.write("        if (option1 && typeof option1 === \"object\") {\r\n");
      out.write("            myChart1.setOption(option1, true);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        //结案情况统计 横向柱状图\r\n");
      out.write("        var myChart2 = echarts.init(document.getElementById('dataDiv'));\r\n");
      out.write("        var option2 = {\r\n");
      out.write("            // title: {\r\n");
      out.write("            //     text: '世界人口总量',\r\n");
      out.write("            //     subtext: '数据来自网络'\r\n");
      out.write("            // },\r\n");
      out.write("            tooltip: {\r\n");
      out.write("                show: false,\r\n");
      out.write("                formatter: '{c}%'　,\r\n");
      out.write("                trigger: 'item',\r\n");
      out.write("            },\r\n");
      out.write("            // legend: {\r\n");
      out.write("            //     data: ['2011年', '2012年']\r\n");
      out.write("            // },\r\n");
      out.write("            grid: {\r\n");
      out.write("                top: '2%',\r\n");
      out.write("                left: '2%',\r\n");
      out.write("                right: '2%',\r\n");
      out.write("                bottom: '2%',\r\n");
      out.write("                containLabel: true\r\n");
      out.write("            },\r\n");
      out.write("            xAxis: {\r\n");
      out.write("                type: 'value',\r\n");
      out.write("                boundaryGap: [0, 0.01],\r\n");
      out.write("                show: false,\r\n");
      out.write("                axisLine: {\r\n");
      out.write("                    show: false\r\n");
      out.write("                }, // 控制y轴线是否显示\r\n");
      out.write("                splitLine: {\r\n");
      out.write("                    show: false\r\n");
      out.write("                }, // 控制网格线是否显示\r\n");
      out.write("                axisTick: {\r\n");
      out.write("                    show: false\r\n");
      out.write("                } // 去除y轴上的刻度线\r\n");
      out.write("            },\r\n");
      out.write("            yAxis: {\r\n");
      out.write("                type: 'category',\r\n");
      out.write("                data: ['撤销', '缺人违法', '变更', '责令履行', '终止，其他', '终止、调解', '维持', '驳回', '其他'],\r\n");
      out.write("                axisLine: {\r\n");
      out.write("                    show: false\r\n");
      out.write("                }, // 控制y轴线是否显示\r\n");
      out.write("                splitLine: {\r\n");
      out.write("                    show: false\r\n");
      out.write("                }, // 控制网格线是否显示\r\n");
      out.write("                axisTick: {\r\n");
      out.write("                    show: false\r\n");
      out.write("                } // 去除y轴上的刻度线\r\n");
      out.write("            },\r\n");
      out.write("            series: [{\r\n");
      out.write("                type: 'bar',\r\n");
      out.write("                data: [3, 3, 10, 48, 171, 359, 359, 127, 89],\r\n");
      out.write("                barWidth: '15px',\r\n");
      out.write("                itemStyle: {\r\n");
      out.write("                    normal: {\r\n");
      out.write("                        barBorderRadius: [20, 20, 20, 20],\r\n");
      out.write("                        color: new echarts.graphic.LinearGradient(1, 0, 0, 0, [{\r\n");
      out.write("                            offset: 0,\r\n");
      out.write("                            color: \"#5FD7FC\" // 0% 处的颜色\r\n");
      out.write("                        }, {\r\n");
      out.write("                            offset: 0.6,\r\n");
      out.write("                            color: \"#649CFD\" // 60% 处的颜色\r\n");
      out.write("                        }, {\r\n");
      out.write("                            offset: 1,\r\n");
      out.write("                            color: \"#6B66F5\" // 100% 处的颜色\r\n");
      out.write("                        }], false),\r\n");
      out.write("                        label: {\r\n");
      out.write("                            show: true,\r\n");
      out.write("                            position: 'right',\r\n");
      out.write("                            formatter: '{c}'\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("                },\r\n");
      out.write("            }]\r\n");
      out.write("        };\r\n");
      out.write("        if (option2 && typeof option2 === \"object\") {\r\n");
      out.write("            myChart2.setOption(option2, true);\r\n");
      out.write("        }\r\n");
      out.write("        //图表自适应\r\n");
      out.write("        window.onresize = function() {\r\n");
      out.write("            myChart1.resize();\r\n");
      out.write("            myChart2.resize();\r\n");
      out.write("        };\r\n");
      out.write("\r\n");
      out.write("        //待办事项/办件切换\r\n");
      out.write("        $(\"#tab li\").click(function() {\r\n");
      out.write("            $('#tab li').removeClass('tabactive');\r\n");
      out.write("            $(this).addClass('tabactive');\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else log(t.getMessage(), t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
