package org.apache.jsp.xzfy.jsp.organ;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.tianee.webframe.util.str.TeeUtility;
import com.tianee.webframe.util.servlet.TeeCookieUtils;
import java.util.*;
import com.tianee.oa.oaconst.TeeConst;
import com.tianee.oa.core.org.bean.TeePerson;
import com.tianee.webframe.util.str.TeeUtility;
import com.tianee.webframe.util.date.TeeDateUtil;
import com.tianee.webframe.util.global.TeeSysProps;
import com.tianee.webframe.util.str.TeeStringUtil;
import com.tianee.oa.core.org.service.TeePersonService;
import com.tianee.oa.oaconst.TeeModelIdConst;

public final class a_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  static {
    _jspx_dependants = new java.util.ArrayList(3);
    _jspx_dependants.add("/header/header2.0.jsp");
    _jspx_dependants.add("/header/easyui.jsp");
    _jspx_dependants.add("/header/ztree.jsp");
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");

	String puuid = request.getParameter("puuid") == null ? "" : request.getParameter("puuid");
	String uuid = request.getParameter("uuid") == null ? "" : request.getParameter("uuid");
	String type = request.getParameter("type") == null ? "" : request.getParameter("type");
	String deptParent = request.getParameter("deptParent") == null? "" : request.getParameter("deptParent");

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=Edge\"/>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"/>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

String contextPath = request.getContextPath();
String basePath = request.getScheme() + "://"
		+ request.getServerName() + ":" + request.getServerPort()
		+ contextPath + "/";
//获取主题的索引号
int styleIndex = 1;
Integer styleInSession = (Integer) request.getSession().getAttribute("STYLE_TYPE_INDEX");
if (styleInSession != null) {
	styleIndex = styleInSession;
}
String stylePath = contextPath + "/common/styles";
String imgPath = stylePath + "/style" + styleIndex + "/img";
String cssPath = stylePath + "/style" + styleIndex + "/css";
String systemImagePath = contextPath+"/common/images";

//第二套风格
int STYLE_TYPE_INDEX_2 = TeeStringUtil.getInteger( request.getSession().getAttribute("STYLE_TYPE_INDEX_2"), 1);
String cssPathSecond = contextPath + "/system/frame/2/styles/style" + STYLE_TYPE_INDEX_2 + "/css";
String imgPathSecond = contextPath + "/system/frame/2/styles/style" + STYLE_TYPE_INDEX_2 + "/img";


String loginOutText = TeeSysProps.getString("LOGIN_OUT_TEXT");
String ieTitle = TeeSysProps.getString("IE_TITLE");
String secUserMem = TeeSysProps.getString("SEC_USER_MEM");

Cookie cookie = TeeCookieUtils.getCookie(request, "skin_new");
String skinNew = "1";
if(cookie!=null){
	skinNew = cookie.getValue();
}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- zt_webframe框架引入 jquery -->\r\n");
      out.write("<script src=\"");
      out.print(contextPath );
      out.write("/common/jquery-easyui-1.6.11/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- zt_webframe框架引入 核心库 -->\r\n");
      out.write("<script src=\"");
      out.print(contextPath );
      out.write("/common/zt_webframe/js/package.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(contextPath );
      out.write("/common/js/sys2.0.js?v=2\"></script>\r\n");
      out.write("<script src=\"");
      out.print(contextPath );
      out.write("/common/js/sysUtil.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(contextPath );
      out.write("/common/js/src/orgselect.js\"></script>\n");
      out.write("<!--\n");
      out.write("\n");
      out.write("//-->\r\n");
      out.write("<!-- zt_webframe框架引入 css样式 -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/common/zt_webframe/css/init");
      out.print(skinNew );
      out.write(".css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/common/zt_webframe/css/package");
      out.print(skinNew );
      out.write(".css\">\r\n");
      out.write("\r\n");
      out.write("<script src=\"");
      out.print(contextPath );
      out.write("/common/js/tools2.0.js?v=1\"></script>\r\n");
      out.write("<script src=\"");
      out.print(contextPath );
      out.write("/common/js/TeeMenu.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("/** 变量定义 **/\r\n");
      out.write("var contextPath = \"");
      out.print(contextPath );
      out.write("\";\r\n");
      out.write("var systemImagePath = contextPath+\"/common/images\";\r\n");
      out.write("var uploadFlashUrl = \"");
      out.print(contextPath );
      out.write("/common/swfupload/swfupload.swf\";\r\n");
      out.write("var commonUploadUrl = \"");
      out.print(contextPath );
      out.write("/attachmentController/commonUpload.action;jsessionid=");
      out.print(session.getId());
      out.write("\";\r\n");
      out.write("var xparent;\r\n");
      out.write("var stylePath = \"");
      out.print(stylePath);
      out.write("\";\r\n");
      out.write("if(window.dialogArguments){\r\n");
      out.write("\txparent = window.dialogArguments;\r\n");
      out.write("}else if(window.opener){\r\n");
      out.write("\txparent = opener;\r\n");
      out.write("}else{\r\n");
      out.write("\txparent = window;\r\n");
      out.write("}\r\n");
      out.write("window.UEDITOR_HOME_URL = \"");
      out.print(contextPath);
      out.write("/common/ueditor/\";\r\n");
      out.write("$.browser = {};\r\n");
      out.write("$.browser.mozilla = /firefox/.test(navigator.userAgent.toLowerCase());\r\n");
      out.write("$.browser.webkit = /webkit/.test(navigator.userAgent.toLowerCase());\r\n");
      out.write("$.browser.opera = /opera/.test(navigator.userAgent.toLowerCase());\r\n");
      out.write("$.browser.msie = /msie/.test(navigator.userAgent.toLowerCase());\r\n");
      out.write("</script>\r\n");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/common/easyui/jquery.easyui.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/common/easyui/locale/easyui-lang-zh_CN.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath() );
      out.write("/common/js/src/teeValidagteBox.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/common/easyui/datagrid-groupview.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/common/easyui/themes/gray/easyui.css\">");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!-- zTree库 -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/common/jquery/ztree/css/zTreeStyle/zTreeStyle.css\" type=\"text/css\"/>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath() );
      out.write("/common/jquery/ztree/js/jquery.ztree.core-3.5.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath() );
      out.write("/common/jquery/ztree/js/jquery.ztree.excheck-3.5.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath() );
      out.write("/common/jquery/ztree/js/jquery.ztree.exedit-3.5.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath() );
      out.write("/common/js/ZTreeSync.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<title>部门管理</title>\r\n");
      out.write("<link href=\"");
      out.print(cssPath);
      out.write("/style.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("<link href=\"");
      out.print(contextPath);
      out.write("/common/jquery/ztree/css/demo.css\" type=\"text/css\" rel=\"stylesheet\"/>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("var deptParent = '");
      out.print(deptParent);
      out.write("';\r\n");
      out.write("var puuid = '");
      out.print(puuid);
      out.write("';\r\n");
      out.write("var uuid = '");
      out.print(uuid);
      out.write("';\r\n");
      out.write("var type = '");
      out.print(type);
      out.write("';\r\n");
      out.write("//alert(\"deptParent:\"+deptParent+\",\"+\"uuid:\"+uuid+\",\"+\"puuid:\"+puuid+\",\"+\"type:\"+type);\r\n");
      out.write("function doInit(){\r\n");
      out.write("\t//初始化所属单位列表\r\n");
      out.write("\tinitUnitsList();\r\n");
      out.write("\t\r\n");
      out.write("\t//添加例子一\r\n");
      out.write("\tif(uuid != \"\"){//编辑\r\n");
      out.write("\t\tvar url = \"");
      out.print(contextPath);
      out.write("/deptManager/getDeptById.action?isSelectAllColumn=1\";\r\n");
      out.write("\t\tvar para = {uuid:uuid};\r\n");
      out.write("\t\tvar jsonObj = tools.requestJsonRs(url,para);\r\n");
      out.write("\t\t//alert(jsonObj.rtState);\r\n");
      out.write("\t\tif(jsonObj.rtState){\r\n");
      out.write("\t\t\tvar json = jsonObj.rtData;\r\n");
      out.write("\t\t\t//alert(json.pid);\r\n");
      out.write("\t\t\tif(json.uuid){\t\r\n");
      out.write("\t\t\t\tbindJsonObj2Cntrl(json);\r\n");
      out.write("\t\t\t\t$(\"#deptParent\").val(json.pId);\r\n");
      out.write("\t\t\t\t$(\"#deptParentName\").val(json.pName);\r\n");
      out.write("\t\t\t\t//判读当前登陆人对该部门有没有管理权限\r\n");
      out.write("\t\t\t\t//获取当前登录人员的管理范围\r\n");
      out.write("\t\t        var json = tools.requestJsonRs(contextPath+\"/personManager/getPostDeptIds.action\");\r\n");
      out.write("\t\t        var postIds = \",\"+json.rtData+\",\";\r\n");
      out.write("\t\t        if(postIds==\",0,\" || postIds.indexOf(uuid)!=-1){//有管理权限\r\n");
      out.write("\t\t        \t$(\"#deleteDeptSpan\").show();\r\n");
      out.write("\t\t        \t$(\"#saveBtn\").show();\r\n");
      out.write("\t\t        }\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\t//alert(jsonObj.rtMsrg);\r\n");
      out.write("\t\t\t$.MsgBox.Alert_auto(jsonObj.rtMsrg);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}else{//新增\r\n");
      out.write("\t\t$(\"#saveBtn\").show();\r\n");
      out.write("\t}\r\n");
      out.write("\t//getDeptParent(uuid);\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function addDept(){\r\n");
      out.write("\tvar parent = window.parent.contentFrame;\r\n");
      out.write("\tvar deptParent = uuid;\r\n");
      out.write("\tvar url = \"");
      out.print(contextPath);
      out.write("/system/core/dept/addupdate.jsp?puuid=\" + uuid +\"&type=\"+type\r\n");
      out.write("\r\n");
      out.write("+\"&deptParent=\"+deptParent;\r\n");
      out.write("\twindow.parent.changePage(url);\t\t \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/**\r\n");
      out.write(" * 保存\r\n");
      out.write(" */\r\n");
      out.write("function doSave(){\r\n");
      out.write("\tif (check()){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//验证部门名称是不是空字符串\r\n");
      out.write("\t\tvar deptName=$(\"#deptName\").val();\r\n");
      out.write("\t\tvar reg=/(^\\s*)|(\\s*$)/g; //去掉字符串左右的空格\r\n");
      out.write("\t\tdeptName=deptName.replace(reg,'');\r\n");
      out.write("\t\tif(deptName==null||deptName==\"\"){\r\n");
      out.write("\t\t\t//alert(\"您输入的部门名称为空字符串，请重新输入\");\r\n");
      out.write("\t\t\t$.MsgBox.Alert_auto(\"您输入的部门名称为空字符串，请重新输入\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar url = \"");
      out.print(contextPath);
      out.write("/deptManager/addOrUpdateDept.action\";\r\n");
      out.write("\t\tvar para =  tools.formToJson($(\"#form1\")) ;\r\n");
      out.write("\t\t//处理信息上报人员id\r\n");
      out.write("\t\tif($(\"#infoReportUserId\").val()==\"\"){\r\n");
      out.write("\t\t\tpara['infoReportUserId']=0;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tvar jsonRs = tools.requestJsonRs(url,para);\r\n");
      out.write("\t\tif(jsonRs.rtState){\r\n");
      out.write("\t\t\tvar data = jsonRs.rtData;\r\n");
      out.write("\t\t    //alert(\"保存成功！\");\r\n");
      out.write("\t\t\t//top.$.jBox.tip('保存成功','info',{timeout:2000});\r\n");
      out.write("\r\n");
      out.write("\t\t\t$.MsgBox.Alert_auto('保存成功');\r\n");
      out.write("\t\t\tvar parent = window.parent;\t\r\n");
      out.write("\t\t\tparent.location.reload();\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t//window.location.reload();\t\t\t\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\t$.MsgBox.Alert_auto(jsonRs.rtMsg);\r\n");
      out.write("\t\t} \r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function check() {\r\n");
      out.write("\treturn $(\"#form1\").form('validate'); \r\n");
      out.write("}\r\n");
      out.write("/**\r\n");
      out.write(" * 获取部门作为上级部门\r\n");
      out.write(" */\r\n");
      out.write("function getDeptParent(uuid){\r\n");
      out.write("\tvar url =  \"");
      out.print(contextPath );
      out.write("/deptManager/getDeptTree.action\";\r\n");
      out.write("\t\tvar config = {\r\n");
      out.write("\t\t\t\tzTreeId:\"deptParentZTree\",\r\n");
      out.write("\t\t\t\trequestURL:url,\r\n");
      out.write("\t\t\t\tparam:{uuid:uuid},\r\n");
      out.write("\t           \tonClickFunc:onclickDept,\r\n");
      out.write("\t\t\t\t\tasync:false,\r\n");
      out.write("\t\t\t\t\tonAsyncSuccess:setDeptParentSelct\r\n");
      out.write("\t\t\t};\r\n");
      out.write("\t\tzTreeObj = ZTreeTool.config(config);\r\n");
      out.write("\t\r\n");
      out.write("\t\t//showMenu();\r\n");
      out.write("\t\t\r\n");
      out.write("\t//\t$(\"#deptParentName\").bind(\"click\", showParentTree);\r\n");
      out.write("\t\t//$(\"#deptParentNameSpan\").bind(\"click\", showParentTree);\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t//\r\n");
      out.write("} \r\n");
      out.write("/**\r\n");
      out.write(" * 初始化后选中节点,上级部门\r\n");
      out.write(" */\r\n");
      out.write("function setDeptParentSelct(){\r\n");
      out.write("\tvar deptName = \"\";\r\n");
      out.write("\tZTreeObj = $.fn.zTree.getZTreeObj(ZTreeTool.zTreeId);\r\n");
      out.write("    if(ZTreeObj == null){\r\n");
      out.write("    \t//setTimeout('setDeptParentSelct()',500);\r\n");
      out.write("    \tsetDeptParentSelct();\r\n");
      out.write("    }else{\r\n");
      out.write("    \t///ZTreeObj.expandAll(true);全部展开\r\n");
      out.write("    \t var node = ZTreeObj.getNodeByParam(\"id\",$(\"#deptParent\").val(),null);\r\n");
      out.write("    \t    if(node){\r\n");
      out.write("    \t    \tZTreeObj.selectNode(node);\r\n");
      out.write("    \t    \tdeptName = node.name;\r\n");
      out.write("    \t  }\r\n");
      out.write("    }  \r\n");
      out.write("    ZTreeTool.inputBindZtree(ZTreeTool.zTreeId,'deptParent',deptName);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//点击树执行事件\r\n");
      out.write("function onclickDept (event, treeId, treeNode) {\r\n");
      out.write("\t$(\"#deptParentName\").val(treeNode.name);\r\n");
      out.write("\t$(\"#deptParent\").val(treeNode.id);\r\n");
      out.write("\tZTreeTool.hideZtreeMenu();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/**\r\n");
      out.write(" * 删除部门一级下级部门\r\n");
      out.write(" */\r\n");
      out.write("function deleteDeptAndSubDept(){\r\n");
      out.write("\tif($(\"#uuid\").val() <= 0){\r\n");
      out.write("\t\t$.MsgBox.Alert_auto(\"没有选择部门\");\r\n");
      out.write("\t\t//alert(\"没有选择部门\");\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t $.MsgBox.Confirm (\"提示\", \"确定要删除当前部门,这样删除会删除下级所有部门,删除后将不可恢复！\", function(){\r\n");
      out.write("\t\t var url = \"");
      out.print(contextPath);
      out.write("/deptManager/deleteDeptAndSubDept.action\";\r\n");
      out.write("\t\t\tvar para =  {id: $(\"#uuid\").val() } ;\r\n");
      out.write("\t\t\tvar jsonRs = tools.requestJsonRs(url,para);\r\n");
      out.write("\t\t\tif(jsonRs.rtState){\r\n");
      out.write("\t\t\t\t//var data = jsonRs.rtData;\r\n");
      out.write("\t\t\t\t//alert(\"删除成功！\");\r\n");
      out.write("\t\t\t\t$.MsgBox.Alert_auto(\"删除成功！\",function(){\r\n");
      out.write("\t\t\t\t\tvar parent = window.parent;\r\n");
      out.write("\t\t\t\t\tparent.location.reload();\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t   \t   //window.location.href = \"");
      out.print(contextPath);
      out.write("/system/core/dept/addupdate.jsp\";\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\t//alert(jsonRs.rtMsg);\r\n");
      out.write("\t\t\t\t$.MsgBox.Alert_auto(jsonRs.rtMsg);\r\n");
      out.write("\t\t\t}  \r\n");
      out.write("\t  });\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("// 初始化所属单位列表\r\n");
      out.write("function initUnitsList() {\r\n");
      out.write("    var url=\"");
      out.print(contextPath);
      out.write("/sysCode/getSysCodeByParentCodeNo.action\";\r\n");
      out.write("    var jsonObj = tools.requestJsonRs(url, {codeNo : \"UNIT_LIST\"});\r\n");
      out.write("    var str = \"<option value=''></option>\";\r\n");
      out.write("    if (jsonObj.rtState) {\r\n");
      out.write("        $(\"#subordinateUnitsCode\").find('option').remove();\r\n");
      out.write("        for (var i = 0; i < jsonObj.rtData.length; i++) {\r\n");
      out.write("            str += \"<option value='\"+jsonObj.rtData[i].codeNo+\"'>\" + jsonObj.rtData[i].codeName + \"</option>\";\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("    $(\"#subordinateUnitsCode\").append(str);\r\n");
      out.write("    \r\n");
      out.write("    $(\"#subordinateUnitsCode\").change(function(){\r\n");
      out.write("    \tvar checkText = $(\"#subordinateUnitsCode\").find(\"option:selected\").text(); \r\n");
      out.write("        $(\"#subordinateUnits\").val(checkText);\r\n");
      out.write("    }); \r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body onload=\"doInit()\" style=\"font-family: MicroSoft YaHei;font-size: 12px;\">\r\n");
      out.write("\t<form method=\"post\" name=\"form1\" id=\"form1\" class=\"tableForm\" style=\"padding-bottom:5px;\">\r\n");
      out.write("\t\t<table class=\"TableBlock_page\" width=\"100%\" align=\"center\">\r\n");
      out.write("            <tr>\r\n");
      out.write("               <td colspan=\"2\" style='vertical-align: middle;font-family: MicroSoft YaHei;font-size: 14px;line-height: 30px;'><img src=\"");
      out.print(contextPath );
      out.write("/common/zt_webframe/imgs/common_img/icon_yhcx.png\" align=\"absMiddle\">&nbsp;&nbsp; \r\n");
      out.write("                  ");

					if (TeeUtility.isNullorEmpty(uuid)) {
				  
      out.write(" <span> 新增部门</span> ");

 	             } else {
                 
      out.write("<span> 编辑部门</span> ");

 	             }
                
      out.write("\r\n");
      out.write("               </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td nowrap class=\"TableData\" style=\"text-indent: 10px\">部门排序号：</td>\r\n");
      out.write("\t\t\t\t<td nowrap class=\"TableData\"><input type=\"text\" name=\"deptNo\"\r\n");
      out.write("\t\t\t\t\tid=\"deptNo\" class=\"easyui-validatebox BigInput\" required=\"true\" size=\"10\"\r\n");
      out.write("\t\t\t\t\tmaxlength=\"3\" validType=\"integeBetweenLength[1,999]\">&nbsp;整数类型，用于同一级次部门排序\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td nowrap class=\"TableData\" style=\"text-indent: 10px\">部门名称：</td>\r\n");
      out.write("\t\t\t\t<td nowrap class=\"TableData\"><input type=\"text\" name=\"deptName\"\r\n");
      out.write("\t\t\t\t\tid=\"deptName\" class=\"easyui-validatebox BigInput\" required=\"true\" size=\"25\"\r\n");
      out.write("\t\t\t\t\tmaxlength=\"25\">&nbsp;</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td nowrap class=\"TableData\" style=\"text-indent: 10px\">部门类型：</td>\r\n");
      out.write("\t\t\t\t<td nowrap class=\"TableData\">\r\n");
      out.write("\t\t\t\t\t<select class=\"BigSelect\" name=\"deptType\" id=\"deptType\" >\r\n");
      out.write("\t\t\t\t\t\t<option value=\"2\">单位</option>\r\n");
      out.write("\t\t\t\t\t\t<option value=\"1\">部门</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("                <td nowrap class=\"TableData\" style=\"text-indent: 10px\">所属单位：</td>\r\n");
      out.write("                <td nowrap class=\"TableData\">\r\n");
      out.write("                \t<input type=\"text\" name=\"UnitName\" id=\"unitName\" class=\"BigInput\" readonly=\"readonly\">\r\n");
      out.write("                \t<!-- \r\n");
      out.write("                    <input type=\"hidden\" name=\"subordinateUnits\" id=\"subordinateUnits\" value=\"\" />\r\n");
      out.write("                    <select class=\"BigSelect\" name=\"subordinateUnitsCode\" id=\"subordinateUnitsCode\" >\r\n");
      out.write("                    </select>\r\n");
      out.write("                     -->\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td nowrap class=\"TableData\" style=\"text-indent: 10px\">电话：</td>\r\n");
      out.write("\t\t\t\t<td nowrap class=\"TableData\">\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"telNo\" id=\"telNo\" class=\"easyui-validatebox BigInput\" size=\"25\" maxlength=\"25\">&nbsp;\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td nowrap class=\"TableData\" style=\"text-indent: 10px\">传真：</td>\r\n");
      out.write("\t\t\t\t<td nowrap class=\"TableData\"><input type=\"text\" name=\"faxNo\"\r\n");
      out.write("\t\t\t\t\tid=\"faxNo\" class=\"BigInput\" size=\"25\" maxlength=\"25\" >&nbsp;\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td nowrap class=\"TableData\" style=\"text-indent: 10px\">部门地址：</td>\r\n");
      out.write("\t\t\t\t<td nowrap class=\"TableData\"><input type=\"text\"\r\n");
      out.write("\t\t\t\t\tname=\"address\" class=\"BigInput\" size=\"40\" maxlength=\"40\">&nbsp;\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td nowrap class=\"TableData\" style=\"text-indent: 10px\">上级部门：</td>\r\n");
      out.write("\t\t\t\t<td class=\"TableData\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<input type=\"text\" name=\"deptParentName\" readonly  id=\"deptParentName\">&nbsp;\r\n");
      out.write("\t\t        <input type=\"hidden\" name=\"deptParent\" id=\"deptParent\"  />\r\n");
      out.write("\t\t       \r\n");
      out.write("\t\t        <span class='addSpan'>\r\n");
      out.write("\t\t         \t<img src=\"");
      out.print(contextPath );
      out.write("/common/zt_webframe/imgs/xtgl/zzjggl/yhgl/add.png\" onclick=\"selectSingleDept(['deptParent','deptParentName'],'0')\" value=\"选择\"/>\r\n");
      out.write("\t\t\t        <img src=\"");
      out.print(contextPath );
      out.write("/common/zt_webframe/imgs/xtgl/zzjggl/yhgl/clear.png\"  onclick=\"clearData('deptParent','deptParentName')\" value=\"清空\"/>\r\n");
      out.write("\t\t        </span>\r\n");
      out.write("\t\r\n");
      out.write("               </td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("\t\t\t\t<td nowrap class=\"TableData\" style=\"text-indent: 10px\">部门信息上报员：</td>\r\n");
      out.write("\t\t\t\t<td class=\"TableData\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<input type=\"text\" name=\"infoReportUserName\" readonly  id=\"infoReportUserName\">&nbsp;\r\n");
      out.write("\t\t        <input type=\"hidden\" name=\"infoReportUserId\" id=\"infoReportUserId\"/>\r\n");
      out.write("\t\t       \r\n");
      out.write("\t\t        <span class='addSpan'>\r\n");
      out.write("\t\t         \t<img src=\"");
      out.print(contextPath );
      out.write("/common/zt_webframe/imgs/xtgl/zzjggl/yhgl/add.png\" onclick=\"selectSingleUser(['infoReportUserId','infoReportUserName'],'0')\" value=\"选择\"/>\r\n");
      out.write("\t\t\t        <img src=\"");
      out.print(contextPath );
      out.write("/common/zt_webframe/imgs/xtgl/zzjggl/yhgl/clear.png\"  onclick=\"clearData('infoReportUserId','infoReportUserName')\" value=\"清空\"/>\r\n");
      out.write("\t\t        </span>\r\n");
      out.write("\t\r\n");
      out.write("               </td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td nowrap class=\"TableData\" style=\"text-indent: 10px\">部门主管领导(选填)：</td>\r\n");
      out.write("\t\t\t\t<td nowrap class=\"TableData\">\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"manager\" id=\"manager\" value=\"\"> \r\n");
      out.write("\t\t\t\t\t <textarea cols=\"45\"\r\n");
      out.write("\t\t\t\t\t\tname=\"managerName\" id=\"managerName\" rows=\"2\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"overflow-y: auto;\" class=\"SmallStatic BigTextarea\" wrap=\"yes\" readonly  ></textarea>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<span class='addSpan'>\r\n");
      out.write("\t\t\t\t\t   <img src=\"");
      out.print(contextPath );
      out.write("/common/zt_webframe/imgs/grbg/gryj/icon_select.png\" onClick=\"selectUser(['manager', 'managerName'] )\" value=\"选择\"/>\r\n");
      out.write("\t\t\t\t\t   &nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t   <img src=\"");
      out.print(contextPath );
      out.write("/common/zt_webframe/imgs/grbg/gryj/icon_cancel.png\" onClick=\"clearData('manager', 'managerName')\" value=\"清空\"/>\r\n");
      out.write("\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t\t\t<td nowrap class=\"TableData\"  style=\"text-indent: 10px\">部门分管领导(选填)：</td>\r\n");
      out.write("\t\t\t\t<td nowrap class=\"TableData\">\r\n");
      out.write("\t\t\t\t     \r\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"manager2\" id=\"manager2\" value=\"\"> \r\n");
      out.write("\t\t\t\t\t <textarea cols=\"45\"\r\n");
      out.write("\t\t\t\t\t\tname=\"managerName2\" id=\"manager2Name\" rows=\"2\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"overflow-y: auto;\" class=\"SmallStatic BigTextarea\" wrap=\"yes\" readonly  ></textarea>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<span class='addSpan'>\r\n");
      out.write("\t\t\t\t\t   <img src=\"");
      out.print(contextPath );
      out.write("/common/zt_webframe/imgs/grbg/gryj/icon_select.png\" onClick=\"selectUser(['manager2', 'manager2Name'] )\" value=\"选择\"/>\r\n");
      out.write("\t\t\t\t\t   &nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t   <img src=\"");
      out.print(contextPath );
      out.write("/common/zt_webframe/imgs/grbg/gryj/icon_cancel.png\" onClick=\"clearData('manager2', 'manager2Name')\" value=\"清空\"/>\r\n");
      out.write("\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<tr style=\"display:none\">\r\n");
      out.write("\t\t\t\t<td nowrap class=\"TableData\" style=\"text-indent: 10px\">上级主管领导(选填)：</td>\r\n");
      out.write("\t\t\t\t<td nowrap class=\"TableData\"><input type=\"hidden\"\r\n");
      out.write("\t\t\t\t\tname=\"leader1\" id=\"leader1\" value=\"\"> <textarea cols=\"45\"\r\n");
      out.write("\t\t\t\t\t\tname=\"leader1Name\" id=\"leader1Name\" rows=\"2\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"overflow-y: auto;\" class=\"SmallStatic BigTextarea\" wrap=\"yes\" readonly></textarea>\r\n");
      out.write("\t\t\t\t\t<a href=\"javascript:void(0);\" class=\"orgAdd\"\r\n");
      out.write("\t\t\t\t\tonClick=\"selectUser(['leader1', 'leader1Name'])\">添加</a> <a\r\n");
      out.write("\t\t\t\t\thref=\"javascript:void(0);\" class=\"orgClear\"\r\n");
      out.write("\t\t\t\t\tonClick=\"clearData('leader1', 'leader1Name')\">清空</a></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr style=\"display:none\">\r\n");
      out.write("\t\t\t\t<td nowrap class=\"TableData\" style=\"text-indent: 10px\">上级分管领导(选填)：</td>\r\n");
      out.write("\t\t\t\t<td nowrap class=\"TableData\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t <input id=\"leader2\" type=\"hidden\" name=\"leader2\" style=\"width:100%\"/>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t <textarea cols=\"45\"\r\n");
      out.write("\t\t\t\t\t\tname=\"leader2Name\" id=\"leader2Name\" rows=\"2\"\r\n");
      out.write("\t\t\t\t\t\tstyle=\"overflow-y: auto;\" class=\"SmallStatic BigTextarea\" wrap=\"yes\" readonly></textarea>\r\n");
      out.write("\t\t\t<a href=\"javascript:void(0);\" class=\"orgAdd\"\r\n");
      out.write("\t\t\t\t\tonClick=\"selectUser(['leader2', 'leader2Name'])\">添加</a> <a\r\n");
      out.write("\t\t\t\t\thref=\"javascript:void(0);\" class=\"orgClear\"\r\n");
      out.write("\t\t\t\t\tonClick=\"clearData('leader2', 'leader2Name')\">清空</a></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td nowrap class=\"TableData\" style=\"text-indent: 10px\">部门职能：</td>\r\n");
      out.write("\t\t\t\t<td nowrap class=\"TableData\"><textarea name=\"deptFunc\"\r\n");
      out.write("\t\t\t\t\t\tid=\"deptFunc\" class=\"BigTextarea\" cols=\"60\" rows=\"5\"></textarea></td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<td colspan=\"2\">\r\n");
      out.write("\t\t\t\t <div  align=\"center\">\r\n");
      out.write("\t\t\t\t\t<input id=\"saveBtn\" style=\"display: none;\" type=\"button\" value=\"保存\" class=\"btn-win-white\" onclick=\"doSave();\">&nbsp;&nbsp;  \r\n");
      out.write("\t\t\t\t\t<input type=\"text\" id=\"uuid\" name=\"uuid\" value=\"0\" style=\"display: none;\" />\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t<span id=\"deleteDeptSpan\" style=\"display:none;\"> <input type=\"button\" value=\"删除当前部门/下级部门\" class=\"btn-win-white\" onclick=\"deleteDeptAndSubDept();\">&nbsp;&nbsp;  </span>\r\n");
      out.write("\t\t\t\t  </div>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t</form>\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("/**\r\n");
      out.write(" * 选择部门\r\n");
      out.write(" * @return\r\n");
      out.write(" */\r\n");
      out.write("function selectDept(retArray , moduleId,privNoFlag , noAllDept,callBackFunc) {\r\n");
      out.write("  deptRetNameArray = retArray;\r\n");
      out.write("  objSelectType  = retArray[2] || \"\";\r\n");
      out.write("  var url = contextPath + \"/system/core/orgselect/selectMultiDeptPost.jsp?objSelectType=\" + objSelectType;\r\n");
      out.write("  var has = false;\r\n");
      out.write("  if (moduleId) {\r\n");
      out.write("    url += \"&moduleId=\" + moduleId ;\r\n");
      out.write("  }\r\n");
      out.write("  if (privNoFlag) {\r\n");
      out.write("    url += \"&privNoFlag=\" + privNoFlag ;\r\n");
      out.write("  }\r\n");
      out.write("  if (noAllDept) {\r\n");
      out.write("    url += \"&noAllDept=\" + noAllDept ;\r\n");
      out.write("  }\r\n");
      out.write("  if(callBackFunc){\r\n");
      out.write("\t  url += \"&callBackPara=\" + callBackFunc ;\r\n");
      out.write("  }\r\n");
      out.write("  var IM_OA;\r\n");
      out.write("try{\r\n");
      out.write("    IM_OA = window.external.IM_OA;\r\n");
      out.write("}catch(e){}\r\n");
      out.write("\r\n");
      out.write("if(window.showModelDialog || IM_OA){\r\n");
      out.write("\t  dialogChangesize(url, 560, 400);\r\n");
      out.write("  }else{\r\n");
      out.write("\t  openWindow(url,\"选择人员\", 560, 400);\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/**\r\n");
      out.write(" * 选择单个部门\r\n");
      out.write(" * @return\r\n");
      out.write(" */\r\n");
      out.write("function selectSingleDept(retArray , moduleId,privNoFlag , noAllDept) {\r\n");
      out.write("  deptRetNameArray = retArray;\r\n");
      out.write("  objSelectType  = retArray[2] || \"\";\r\n");
      out.write("  var url = contextPath + \"/system/core/orgselect/selectMultiDeptPost.jsp?objSelectType=\" + objSelectType + \"&isSingle=1\";\r\n");
      out.write("  var has = false;\r\n");
      out.write("  if (moduleId) {\r\n");
      out.write("    url += \"&moduleId=\" + moduleId ;\r\n");
      out.write("  }\r\n");
      out.write("  if (privNoFlag) {\r\n");
      out.write("    url += \"&privNoFlag=\" + privNoFlag ;\r\n");
      out.write("  }\r\n");
      out.write("  if (noAllDept) {\r\n");
      out.write("    url += \"&noAllDept=\" + noAllDept ;\r\n");
      out.write("  }\r\n");
      out.write("  var IM_OA;\r\n");
      out.write("try{\r\n");
      out.write("    IM_OA = window.external.IM_OA;\r\n");
      out.write("}catch(e){}\r\n");
      out.write("\r\n");
      out.write("if(window.showModelDialog || IM_OA){\r\n");
      out.write("\t  dialogChangesize(url, 560, 400);\r\n");
      out.write("  }else{\r\n");
      out.write("\t  openWindow(url,\"选择人员\", 560, 400);\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else log(t.getMessage(), t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
