package org.apache.jsp.system.frame.html.templates.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.tianee.webframe.util.servlet.TeeCookieUtils;
import java.util.*;
import com.tianee.oa.oaconst.TeeConst;
import com.tianee.oa.core.org.bean.TeePerson;
import com.tianee.webframe.util.str.TeeUtility;
import com.tianee.webframe.util.date.TeeDateUtil;
import com.tianee.webframe.util.global.TeeSysProps;
import com.tianee.webframe.util.str.TeeStringUtil;
import com.tianee.oa.core.org.service.TeePersonService;
import com.tianee.oa.oaconst.TeeModelIdConst;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  static {
    _jspx_dependants = new java.util.ArrayList(1);
    _jspx_dependants.add("/header/header2.0.jsp");
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');


  //获取当前登陆人的信息
  TeePerson loginUser=(TeePerson)request.getSession().getAttribute(TeeConst.LOGIN_USER);
  String loginUserName=loginUser.getUserName();
  String deptName=loginUser.getDept().getDeptName();
  
  //获取当前日期
  String currentDateStr=TeeDateUtil.format(new Date(), "yyyy-MM-dd");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/one.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/pagetu.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/reset.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

String contextPath = request.getContextPath();
String basePath = request.getScheme() + "://"
		+ request.getServerName() + ":" + request.getServerPort()
		+ contextPath + "/";
//获取主题的索引号
int styleIndex = 1;
Integer styleInSession = (Integer) request.getSession().getAttribute("STYLE_TYPE_INDEX");
if (styleInSession != null) {
	styleIndex = styleInSession;
}
String stylePath = contextPath + "/common/styles";
String imgPath = stylePath + "/style" + styleIndex + "/img";
String cssPath = stylePath + "/style" + styleIndex + "/css";
String systemImagePath = contextPath+"/common/images";

//第二套风格
int STYLE_TYPE_INDEX_2 = TeeStringUtil.getInteger( request.getSession().getAttribute("STYLE_TYPE_INDEX_2"), 1);
String cssPathSecond = contextPath + "/system/frame/2/styles/style" + STYLE_TYPE_INDEX_2 + "/css";
String imgPathSecond = contextPath + "/system/frame/2/styles/style" + STYLE_TYPE_INDEX_2 + "/img";


String loginOutText = TeeSysProps.getString("LOGIN_OUT_TEXT");
String ieTitle = TeeSysProps.getString("IE_TITLE");
String secUserMem = TeeSysProps.getString("SEC_USER_MEM");

Cookie cookie = TeeCookieUtils.getCookie(request, "skin_new");
String skinNew = "1";
if(cookie!=null){
	skinNew = cookie.getValue();
}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- zt_webframe框架引入 jquery -->\r\n");
      out.write("<script src=\"");
      out.print(contextPath );
      out.write("/common/jquery-easyui-1.6.11/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- zt_webframe框架引入 核心库 -->\r\n");
      out.write("<script src=\"");
      out.print(contextPath );
      out.write("/common/zt_webframe/js/package.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(contextPath );
      out.write("/common/js/sys2.0.js?v=2\"></script>\r\n");
      out.write("<script src=\"");
      out.print(contextPath );
      out.write("/common/js/sysUtil.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(contextPath );
      out.write("/common/js/src/orgselect.js\"></script>\r\n");
      out.write("<!--\r\n");
      out.write("\r\n");
      out.write("//-->\r\n");
      out.write("<!-- zt_webframe框架引入 css样式 -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/common/zt_webframe/css/init");
      out.print(skinNew );
      out.write(".css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/common/zt_webframe/css/package");
      out.print(skinNew );
      out.write(".css\">\r\n");
      out.write("\r\n");
      out.write("<script src=\"");
      out.print(contextPath );
      out.write("/common/js/tools2.0.js?v=1\"></script>\r\n");
      out.write("<script src=\"");
      out.print(contextPath );
      out.write("/common/js/TeeMenu.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("/** 变量定义 **/\r\n");
      out.write("var contextPath = \"");
      out.print(contextPath );
      out.write("\";\r\n");
      out.write("var systemImagePath = contextPath+\"/common/images\";\r\n");
      out.write("var uploadFlashUrl = \"");
      out.print(contextPath );
      out.write("/common/swfupload/swfupload.swf\";\r\n");
      out.write("var commonUploadUrl = \"");
      out.print(contextPath );
      out.write("/attachmentController/commonUpload.action;jsessionid=");
      out.print(session.getId());
      out.write("\";\r\n");
      out.write("var xparent;\r\n");
      out.write("var stylePath = \"");
      out.print(stylePath);
      out.write("\";\r\n");
      out.write("if(window.dialogArguments){\r\n");
      out.write("\txparent = window.dialogArguments;\r\n");
      out.write("}else if(window.opener){\r\n");
      out.write("\txparent = opener;\r\n");
      out.write("}else{\r\n");
      out.write("\txparent = window;\r\n");
      out.write("}\r\n");
      out.write("window.UEDITOR_HOME_URL = \"");
      out.print(contextPath);
      out.write("/common/ueditor/\";\r\n");
      out.write("$.browser = {};\r\n");
      out.write("$.browser.mozilla = /firefox/.test(navigator.userAgent.toLowerCase());\r\n");
      out.write("$.browser.webkit = /webkit/.test(navigator.userAgent.toLowerCase());\r\n");
      out.write("$.browser.opera = /opera/.test(navigator.userAgent.toLowerCase());\r\n");
      out.write("$.browser.msie = /msie/.test(navigator.userAgent.toLowerCase());\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(contextPath);
      out.write("/common/KinSlideshow/jquery.KinSlideshow-1.2.1.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(contextPath);
      out.write("/system/frame/6/js/jquery.datePicker-min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(contextPath );
      out.write("/system/frame/6/css/datepicker.css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(contextPath);
      out.write("/system/frame/2/js/sms.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(contextPath);
      out.write("/common/js/lazyloader.js\"></script>\r\n");
      out.write("<title>深圳法治政府信息平台</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".smsbox{\r\n");
      out.write("position:fixed;\r\n");
      out.write("height:330px;\r\n");
      out.write("width:470px;\r\n");
      out.write("background:#f0f0f0;\r\n");
      out.write("top:50%;\r\n");
      out.write("left:50%;\r\n");
      out.write("margin-top:-150px;\r\n");
      out.write("margin-left:-235px;\r\n");
      out.write("z-index:10000;\r\n");
      out.write("}\r\n");
      out.write(".smsbox .title{\r\n");
      out.write("padding:10px;\r\n");
      out.write("font-size:14px;\r\n");
      out.write("background:rgb(67, 129, 230);\r\n");
      out.write("color:white;\r\n");
      out.write("}\r\n");
      out.write(".smsbox .content{\r\n");
      out.write("height:288px;\r\n");
      out.write("overflow:auto;\r\n");
      out.write("background-color: #fff;\r\n");
      out.write("overflow-x:hidden;\r\n");
      out.write("}\r\n");
      out.write(".smsbox .content .item{\r\n");
      out.write("padding:5px;\r\n");
      out.write("border-bottom:1px solid #dbdbdb;\r\n");
      out.write("cursor:pointer;\r\n");
      out.write("overflow:hidden;\r\n");
      out.write("line-height:20px;\r\n");
      out.write("}\r\n");
      out.write(".smsbox .content .item:hover{\r\n");
      out.write("background:#e2e2e2;\r\n");
      out.write("}\r\n");
      out.write(".smsbox_loadmore{\r\n");
      out.write("text-align:center;\r\n");
      out.write("padding:5px;\r\n");
      out.write("cursor:pointer;\r\n");
      out.write("color: #007eff;\r\n");
      out.write("background:#ebebeb;\r\n");
      out.write("}\r\n");
      out.write(".smsbox_loadmore:hover{\r\n");
      out.write("background:#e2e2e2;\r\n");
      out.write("}\r\n");
      out.write(".smsbox .content .item .left0{\r\n");
      out.write("float:left;\r\n");
      out.write("font-weight:bold;\r\n");
      out.write("color:black;\r\n");
      out.write("}\r\n");
      out.write(".smsbox .content .item .right0{\r\n");
      out.write("float:right;\r\n");
      out.write("font-weight:bold;\r\n");
      out.write("color:orange;\r\n");
      out.write("}\r\n");
      out.write(".smsbox_icon1{\r\n");
      out.write("background-image:url('cancel.png');\r\n");
      out.write("background-repeat:no-repeat;\r\n");
      out.write("padding-left:20px;\r\n");
      out.write("font-weight:normal;\r\n");
      out.write("font-size:12px;\r\n");
      out.write("margin-right:10px;\r\n");
      out.write("}\r\n");
      out.write(".smsbox_icon2{\r\n");
      out.write("background-image:url('read.png');\r\n");
      out.write("background-repeat:no-repeat;\r\n");
      out.write("padding-left:20px;\r\n");
      out.write("font-weight:normal;\r\n");
      out.write("font-size:12px;\r\n");
      out.write("margin-right:10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#calendarDataList{\r\n");
      out.write("\t\twidth:100%;\r\n");
      out.write("\t}\r\n");
      out.write("\t#calendarDataList li{\r\n");
      out.write("\t\tmargin-top:5px;\r\n");
      out.write("\t\tmargin-bottom:5px;\r\n");
      out.write("\t\toverflow:hidden;\r\n");
      out.write("\t\tcolor:gray;\r\n");
      out.write("\t\tfont-size:12px;\r\n");
      out.write("\t}\r\n");
      out.write("\t#calendarDataList li .l{\r\n");
      out.write("\t\tfloat:left;\r\n");
      out.write("\t\twidth:60%;\r\n");
      out.write("\t}\r\n");
      out.write("\t#calendarDataList li .r{\r\n");
      out.write("\t\tfloat:right;\r\n");
      out.write("\t\twidth:30%;\r\n");
      out.write("\t\ttext-align:right;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write(".brandbox:hover{\r\n");
      out.write("    background: rgb(35,152,241);\r\n");
      out.write("   }\r\n");
      out.write("   .brandbox:hover{\r\n");
      out.write("   color: #fff;\r\n");
      out.write("   }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body onload=\"doInit()\" >\r\n");
      out.write("<div class=\"body1\" style=\"height: 100%\">\r\n");
      out.write("    <div class=\"nav\" style=\"overflow: hidden\">\r\n");
      out.write("        <div class=\"logo\">\r\n");
      out.write("            <img src=\"image/1.png\" alt=\"\" style=\"width: 100% ;height: 100%\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"nav1-right\" style=\"float: right\">\r\n");
      out.write("            <div class=\"tu-b\" style=\"position: absolute; right: 10px; top: 38px;\">\r\n");
      out.write("                <ul>\r\n");
      out.write("\t                <li>\r\n");
      out.write("\t                \t<div style=\"color: white;letter-spacing: 1px;font-size: 14px;width:80px;\"><span id=\"userName\"></span></div>\r\n");
      out.write("\t                </li>\r\n");
      out.write("                    <!-- 组织架构-->\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"javascript:void(0)\"><img src=\"image/7.png\" alt=\"\" class=\"img group fl\"></a>\r\n");
      out.write("\t\t\t\t\t\t<div id='groupContent' style='width:240px;position:fixed;right:-240px;top:77px;bottom:3px;z-index:99999;box-shadow:0 0 15px #a2a2a2;'>\r\n");
      out.write("\t\t\t\t\t\t\t<iframe style='width:100%;height:100%;' id='right' src=\"/system/frame/3/right.jsp\" frameborder=\"0\"></iframe>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("                \t<!-- 消息提醒 -->\r\n");
      out.write("                     <li>\r\n");
      out.write("                     \t<a href=\"javascript:void(0)\" ><img id=\"tip_alert\" src=\"image/8.png\" alt=\"\" class=\"img\"></a><div class=\"sign_in_tid\" style=\"display:none\">新的消息！</div>\r\n");
      out.write("                    </li>\r\n");
      out.write("\t\t\t\t\t<!-- 注销 -->\r\n");
      out.write("                     <li>\r\n");
      out.write("                     \t<a href=\"javascript:void(0)\" ><img src=\"image/6.png\" alt=\"\" class=\"img\" onclick=\"doLogout();\"></a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div><!--顶部-->\r\n");
      out.write("    <div class=\"mag\">\r\n");
      out.write("        <div class=\"mag-left\">\r\n");
      out.write("            <div class=\"x-t\" style=\"height:20px\"></div>\r\n");
      out.write("            <div class=\"x-t-1\">\r\n");
      out.write("                <ul class=\"ul1\">\r\n");
      out.write("\t\t\t\t\t<li style=\"opacity:0.5;\" id=\"zflf\"  ><a  href=\"javaScript:void(0);\" class=\"minghu_ui_li_0\"><p>政府立法</p></a></li>\r\n");
      out.write("\t\t\t\t\t<li style=\"opacity:0.5;\" id=\"xzzf\"  ><a  href=\"javaScript:void(0);\" class=\"minghu_ui_li_1\"><p>行政执法</p></a></li>\r\n");
      out.write("\t\t\t\t\t<li style=\"opacity:0.5;\" id=\"zfjd\"  ><a  href=\"javaScript:void(0);\" class=\"minghu_ui_li_2\"><p>执法监督</p></a></li>\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<li style=\"opacity:0.5;\" id=\"gfxwj\"  ><a  href=\"javaScript:void(0);\" class=\"minghu_ui_li_3\"><p>规范性文件</p></a></li>\r\n");
      out.write("\t\t\t\t\t<li style=\"opacity:0.5;\" id=\"fyys\"  ><a  href=\"javaScript:void(0);\" class=\"minghu_ui_li_9\"><p>复议应诉</p></a></li>\t\r\n");
      out.write("\t\t\t\t\t<li style=\"opacity:0.5;\" id=\"fzzfkh\"  ><a  href=\"javaScript:void(0);\" class=\"minghu_ui_li_5\"><p>法治政府考核</p></a></li>\r\n");
      out.write("\t\t\t\t\t<li style=\"opacity:0.5;\" id=\"flgw\"  ><a  href=\"javaScript:void(0);\" class=\"minghu_ui_li_6\"><p>法律顾问</p></a></li>\r\n");
      out.write("\t\t\t\t\t<li style=\"opacity:0.5;\" id=\"xtgl\"  ><a  href=\"javaScript:void(0);\" class=\"minghu_ui_li_7\"><p>系统管理</p></a></li>\r\n");
      out.write("\t\t\t\t\t<li style=\"opacity:0.5;\" id=\"fzzsk\"  ><a  href=\"javaScript:void(0);\" class=\"minghu_ui_li_8\"><p>法治知识库</p></a></li>\r\n");
      out.write("                    <li style=\"opacity:0.5;\" id=\"znsc\"  ><a  href=\"javaScript:void(0);\" class=\"minghu_ui_li_4\"><p>智能审查</p></a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"mag-right\">\r\n");
      out.write("           <div style=\"height: 282px \"class=\"zong\">\r\n");
      out.write("\t\t\t\t<div id=\"datepicker\" style=\"margin-top:0px;width:100%;height: 100%\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("        \t<div id=\"dataDiv\" style=\"margin-top:5px;width:94%;height:173px;background:#fff;overflow-y: auto;padding: 10px\">\r\n");
      out.write("\t\t\t\t<ul id=\"calendarDataList\">\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("   <div class=\"b-d\" style=\"text-align: center;vertical-align: middle\">技术支持：北京北大软件工程股份有限公司</div>\r\n");
      out.write("</div>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    $(document).ready(function () {\r\n");
      out.write("    \t\r\n");
      out.write("        brandPicTurn();\r\n");
      out.write("    });\r\n");
      out.write("    function brandPicTurn() {\r\n");
      out.write("        $(\".brand_detail\").hide();\r\n");
      out.write("      \r\n");
      out.write("        $(\".brand_item\").hover(\r\n");
      out.write("                function () {\r\n");
      out.write("                    $(this).children(\".brand_name\").hide();\r\n");
      out.write("                    $(this).children(\".brand_detail\").show();\r\n");
      out.write("                }\r\n");
      out.write("                , function () {\r\n");
      out.write("                    $(this).children(\".brand_detail\").hide();\r\n");
      out.write("                    $(this).children(\".brand_name\").show();\r\n");
      out.write("                }\r\n");
      out.write("        );\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    var loginUserName=\"");
      out.print(loginUserName );
      out.write("\";\r\n");
      out.write("    var currentDateStr=\"");
      out.print(currentDateStr );
      out.write("\";\r\n");
      out.write("    var deptName=\"");
      out.print(deptName );
      out.write("\";\r\n");
      out.write("        jQuery(document).ready(function () {\r\n");
      out.write("        \t//渲染当天的日程安排列表\r\n");
      out.write("             renderData(currentDateStr);\r\n");
      out.write("        \t\r\n");
      out.write("        \t//渲染日历\r\n");
      out.write("        \t$(\"#datepicker\").datePicker({\r\n");
      out.write("        \t\tinline:true,\r\n");
      out.write("        \t\tselectMultiple:false,\r\n");
      out.write("        \t\tonSelect:function(date){\r\n");
      out.write("        \t\t\tfor(var i=0;i<window.dpCalendarDates.length;i++){\r\n");
      out.write("        \t\t\t\tif(window.dpCalendarDates[i]==date.getDate()){\r\n");
      out.write("        \t\t\t\t\trenderData(getFormatDateStr(date.getTime(),\"yyyy-MM-dd\"));\r\n");
      out.write("        \t\t\t\t\tbreak;\r\n");
      out.write("        \t\t\t\t}\r\n");
      out.write("        \t\t\t}\r\n");
      out.write("        \t\t},\r\n");
      out.write("        \t\tonChangeDate:function(month,year){\r\n");
      out.write("        \t\t\twindow.dpCalendarDates = tools.requestJsonRs(contextPath+\"/calendarManage/desktopPortletData4GetMonthData.action?year=\"+year+\"&month=\"+month).rtData;\r\n");
      out.write("        \t\t},\r\n");
      out.write("        \t\trenderCallback:function(y, m, B, p){\r\n");
      out.write("        \t\t\tfor(var i=0;i<window.dpCalendarDates.length;i++){\r\n");
      out.write("        \t\t\t\tif(window.dpCalendarDates[i]==m.getDate()){\r\n");
      out.write("        \t\t\t\t\ty.addClass(\"event\");\r\n");
      out.write("        \t\t\t\t\tbreak;\r\n");
      out.write("        \t\t\t\t}\r\n");
      out.write("        \t\t\t}\r\n");
      out.write("        \t\t}\r\n");
      out.write("        \t});\r\n");
      out.write("        \t//消息提醒\r\n");
      out.write("    \t\tvar tip_zhezhao = \"<div class='tip_zhezhao' style='width:100%;height:100%;z-index: 9999;position: fixed;filter:Alpha(opacity=60);background-color: #000;top: 0;left: 0;opacity: 0.6;'></div>\";\r\n");
      out.write("    \t\t$(\"#tip_alert\").on(\"click\",function(){\r\n");
      out.write("    \t\t\t$(\"body\").append(tip_zhezhao);\r\n");
      out.write("    \t\t\t$(\".smsbox\").fadeIn(200);\r\n");
      out.write("    \t\t\tsmsAlert();\r\n");
      out.write("    \t\t});\r\n");
      out.write("    \t\t$(\"body\").on(\"click\",\".sms_close_win,.sms_list,.all_check\",function(){\r\n");
      out.write("    \t\t\t$(\".tip_zhezhao\").remove();\r\n");
      out.write("    \t\t});\r\n");
      out.write("        \t//组织架构显示\r\n");
      out.write("    \t\t$(\"body\").on(\"click\",\".group\",function(){\r\n");
      out.write("    \t\t\tif($(\"#groupContent\").css(\"right\")==\"0px\"){\r\n");
      out.write("    \t\t\t\t$(\"#groupContent\").animate({right:\"-240px\"},300);\r\n");
      out.write("    \t\t\t}else{\r\n");
      out.write("    \t\t\t\t$(\"#groupContent\").animate({right:\"0px\"},300);\r\n");
      out.write("    \t\t\t}\r\n");
      out.write("\r\n");
      out.write("    \t\t});\r\n");
      out.write("        });\r\n");
      out.write("     \r\n");
      out.write("     //渲染当天的日程\r\n");
      out.write("     function renderData(dateStr){\r\n");
      out.write("    \t   //先清空div\r\n");
      out.write("    \t   $(\"#dataDiv\").html(\"\");\r\n");
      out.write("    \t    var json = tools.requestJsonRs(contextPath+\"/calendarManage/desktopPortletDataRequest.action?date=\"+dateStr);\r\n");
      out.write("    \t\tvar render = [];\r\n");
      out.write("    \t\tif(json.rtData!=null&&json.rtData.length>0){\r\n");
      out.write("    \t\t\trender.push(\"<ul id=\\\"calendarDataList\\\">\");\r\n");
      out.write("    \t\t\tfor(var j=0;j<json.rtData.length;j++){\r\n");
      out.write("    \t\t\t\trender.push(\"<li style=\\\"cursor:pointer;\\\"  onclick=\\\"top.bsWindow('/system/core/base/calendar/detail.jsp?id=\"+json.rtData[j].sid+\"','日程详情',{width:'400',height:'200',buttons:[]})\\\"><span class=\\\"l\\\">\"+(j+1)+\".\"+json.rtData[j].content+\"</span><span class=\\\"r\\\">\"+getFormatDateStr(json.rtData[j].startTime,\"HH:mm\")+\"</span></li>\");\r\n");
      out.write("    \t\t\t}\r\n");
      out.write("    \t\t\trender.push(\"</ul>\");\r\n");
      out.write("    \t\t}else{\r\n");
      out.write("    \t\t\trender.push(\"<img src=\\\"nodata.png\\\" style=\\\"width:100%;height:100%\\\"/>\");\r\n");
      out.write("    \t\t}\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t\t$(\"#dataDiv\").html(render.join(\"\"));\r\n");
      out.write("     }\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("     //初始化方法\r\n");
      out.write("      function doInit(){\r\n");
      out.write("    \t //退出登录操作渲染\r\n");
      out.write("    \t  $(\".dian\").click(function(){\r\n");
      out.write("    \t\t\t$(\".bao\").toggle(100);\r\n");
      out.write("    \t  });\r\n");
      out.write("    \t //渲染当前登陆人的信息\r\n");
      out.write("    \t  renderLoginUserInfo();\r\n");
      out.write("    \t //获取当前登陆人的系统权限\r\n");
      out.write("    \t  getLoginUserPriv();\r\n");
      out.write("     }   \r\n");
      out.write("     //初始化的时候   判断当前登陆人有哪些系统权限\r\n");
      out.write("     function getLoginUserPriv(){\r\n");
      out.write("    \t var  url=contextPath+\"/ApplicationSystemMaintainController/getPrivListByLoginUser.action\";\r\n");
      out.write("    \t var json=tools.requestJsonRs(url);\r\n");
      out.write("    \t if(json.rtState){\r\n");
      out.write("    \t\t var data=json.rtData;\r\n");
      out.write("    \t\t if(data!=null&&data.length>0){\r\n");
      out.write("    \t\t\t for(var i=0;i<data.length;i++){\r\n");
      out.write("    \t\t\t\t if(data[i].sid==5002){//政府立法\r\n");
      out.write("    \t\t\t\t\t $(\"#zflf\").css(\"opacity\",\"1\");\r\n");
      out.write("    \t\t\t\t     $(\"#zflf\").bind(\"click\",function(){\r\n");
      out.write("    \t\t\t\t    \t goPage(5002);\r\n");
      out.write("    \t\t\t\t     });\r\n");
      out.write("    \t\t\t\t }\r\n");
      out.write("    \t\t\t\t if(data[i].sid==1){//行政执法\r\n");
      out.write("    \t\t\t\t\t $(\"#xzzf\").css(\"opacity\",\"1\");\r\n");
      out.write("    \t\t\t\t     $(\"#xzzf\").bind(\"click\",function(){\r\n");
      out.write("    \t\t\t\t    \t goPage(1);\r\n");
      out.write("    \t\t\t\t     });\r\n");
      out.write("    \t\t\t\t }\r\n");
      out.write("    \t\t\t\t if(data[i].sid==5001){//执法监督\r\n");
      out.write("    \t\t\t\t\t $(\"#zfjd\").css(\"opacity\",\"1\");\r\n");
      out.write("    \t\t\t\t     $(\"#zfjd\").bind(\"click\",function(){\r\n");
      out.write("    \t\t\t\t    \t goPage(5001);\r\n");
      out.write("    \t\t\t\t     }); \r\n");
      out.write("    \t\t\t\t }\r\n");
      out.write("    \t\t\t\t if(data[i].sid==5004){//规范性文件\r\n");
      out.write("    \t\t\t\t\t $(\"#gfxwj\").css(\"opacity\",\"1\");\r\n");
      out.write("    \t\t\t\t     $(\"#gfxwj\").bind(\"click\",function(){\r\n");
      out.write("    \t\t\t\t    \t goPage(5004);\r\n");
      out.write("    \t\t\t\t     });\r\n");
      out.write("    \t\t\t\t }\r\n");
      out.write("    \t\t\t\t if(data[i].sid==5021){//复议应诉\r\n");
      out.write("    \t\t\t\t\t $(\"#fyys\").css(\"opacity\",\"1\");\r\n");
      out.write("    \t\t\t\t     $(\"#fyys\").bind(\"click\",function(){\r\n");
      out.write("    \t\t\t\t    \t goPage(5021);\r\n");
      out.write("    \t\t\t\t     }); \r\n");
      out.write("    \t\t\t\t }\r\n");
      out.write("    \t\t\t\t if(data[i].sid==5006){//法治政府考核\r\n");
      out.write("    \t\t\t\t\t $(\"#fzzfkh\").css(\"opacity\",\"1\");\r\n");
      out.write("    \t\t\t\t     $(\"#fzzfkh\").bind(\"click\",function(){\r\n");
      out.write("    \t\t\t\t    \t goPage(5006);\r\n");
      out.write("    \t\t\t\t     });\r\n");
      out.write("    \t\t\t\t }\r\n");
      out.write("    \t\t\t\t if(data[i].sid==5007){//法律顾问\r\n");
      out.write("    \t\t\t\t\t $(\"#flgw\").css(\"opacity\",\"1\");\r\n");
      out.write("    \t\t\t\t     $(\"#flgw\").bind(\"click\",function(){\r\n");
      out.write("    \t\t\t\t    \t goPage(5007);\r\n");
      out.write("    \t\t\t\t     });\r\n");
      out.write("    \t\t\t\t }\r\n");
      out.write("    \t\t\t\t /* if(data[i].sid==5008){//协同办公\r\n");
      out.write("    \t\t\t\t\t $(\"#xtbg\").css(\"opacity\",\"1\");\r\n");
      out.write("    \t\t\t\t     $(\"#xtbg\").bind(\"click\",function(){\r\n");
      out.write("    \t\t\t\t    \t goPage(5008);\r\n");
      out.write("    \t\t\t\t     });\r\n");
      out.write("    \t\t\t\t } */\r\n");
      out.write("    \t\t\t\t if(data[i].sid==11){//系统管理\r\n");
      out.write("    \t\t\t\t\t $(\"#xtgl\").css(\"opacity\",\"1\");\r\n");
      out.write("    \t\t\t\t     $(\"#xtgl\").bind(\"click\",function(){\r\n");
      out.write("    \t\t\t\t    \t goPage(11);\r\n");
      out.write("    \t\t\t\t     });\r\n");
      out.write("    \t\t\t\t }\r\n");
      out.write("    \t\t\t\t if(data[i].sid==5009){//法治知识库\r\n");
      out.write("    \t\t\t\t\t $(\"#fzzsk\").css(\"opacity\",\"1\");\r\n");
      out.write("    \t\t\t\t     $(\"#fzzsk\").bind(\"click\",function(){\r\n");
      out.write("    \t\t\t\t    \t goPage(5009);\r\n");
      out.write("    \t\t\t\t     });\r\n");
      out.write("    \t\t\t\t }\r\n");
      out.write("    \t\t\t\t if(data[i].sid==5010){//智能审查\r\n");
      out.write("    \t\t\t\t\t $(\"#znsc\").css(\"opacity\",\"1\");\r\n");
      out.write("    \t\t\t\t     $(\"#znsc\").bind(\"click\",function(){\r\n");
      out.write("    \t\t\t\t    \t goPage(5010);\r\n");
      out.write("    \t\t\t\t     });\r\n");
      out.write("    \t\t\t\t }\r\n");
      out.write("    \t\t\t }\r\n");
      out.write("    \t\t }\r\n");
      out.write("    \t }\r\n");
      out.write("     }\r\n");
      out.write("        \r\n");
      out.write("     //跳转页面\r\n");
      out.write("     function goPage(sysId){\r\n");
      out.write("    \t var url=contextPath+\"/ApplicationSystemMaintainController/getInfoBySid.action\";\r\n");
      out.write("    \t var json=tools.requestJsonRs(url,{sid:sysId});\r\n");
      out.write("    \t if(json.rtState){\r\n");
      out.write("    \t\t var  data=json.rtData;\r\n");
      out.write("    \t\t if(data.url){\r\n");
      out.write("    \t\t\t window.location=data.url+\"?&sysId=\"+data.sid;\r\n");
      out.write("    \t\t }else{\r\n");
      out.write("    \t\t\t alert(\"该应用系统暂无跳转页面！\"); \r\n");
      out.write("    \t\t }\r\n");
      out.write("    \t }else{\r\n");
      out.write("    \t\t     alert(\"该应用系统不存在！\");\r\n");
      out.write("    \t }\r\n");
      out.write("     }\r\n");
      out.write("     \r\n");
      out.write("    //注销\r\n");
      out.write("     function doLogout(){\r\n");
      out.write("    \t\tvar msg = \"感谢您使用，再见！\\n确定要注销吗?\";\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t\t var mymessage=confirm(msg);\r\n");
      out.write("    \t\t    if(mymessage==true){   \r\n");
      out.write("    \t\t    \tvar url = contextPath + \"/systemAction/doLoginout.action\";\r\n");
      out.write("    \t\t\t\tvar para = {};\r\n");
      out.write("    \t\t\t\tvar jsonObj = tools.requestJsonRs(url,para);\r\n");
      out.write("    \t\t\t\tif(jsonObj){\r\n");
      out.write("    \t\t\t\t\tvar json = jsonObj.rtData;\r\n");
      out.write("    \t\t\t\t}else{\r\n");
      out.write("    \t\t\t\t\talert(jsonObj.rtMsg);\r\n");
      out.write("    \t\t\t\t}\r\n");
      out.write("    \t\t\t\twindow.location.href =contextPath+\"/login.jsp\";\r\n");
      out.write("    \t\t    }\r\n");
      out.write("    }\r\n");
      out.write("    //退出登陆\r\n");
      out.write("    function closeLogin(){\r\n");
      out.write("    \twindow.close();\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    //消息提醒\r\n");
      out.write("    function getSms(){\r\n");
      out.write("    \tif($(\".tip_zhezhao\").length==0){\r\n");
      out.write("    \t\tvar tip_zhezhao = \"<div class='tip_zhezhao' style='width:100%;height:100%;z-index: 9999;position: fixed;filter:Alpha(opacity=60);background-color: #000;top: 0;left: 0;opacity: 0.6;'></div>\";\r\n");
      out.write("    \t\t$(\"body\").append(tip_zhezhao);\r\n");
      out.write("    \t}else{\r\n");
      out.write("    \t\t$(\".tip_zhezhao\").show();\r\n");
      out.write("    \t}\r\n");
      out.write("    \t$(\".smsbox\").fadeIn(200);\r\n");
      out.write("    \tsmsAlert();\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    //获取当前登陆人基本信息\r\n");
      out.write("    function renderLoginUserInfo(){\r\n");
      out.write("       var url=contextPath+\"/personManager/getLoginUserInfo.action\";\r\n");
      out.write("       var json=tools.requestJsonRs(url);\r\n");
      out.write("       if(json.rtState){\r\n");
      out.write("    \t   var data=json.rtData;\r\n");
      out.write("    \t   $(\"#userName\").text(data.userName);\r\n");
      out.write("    \t   $(\"#deptName\").text(data.deptName);\r\n");
      out.write("    \t   if(data.tx!=0){\r\n");
      out.write("    \t\t    //height: 50px;width: 50px;position: fixed;right: 136px;top: 14px;background:url('/system/frame/classic/image/images/02.png') round ;border-radius: 50%;\r\n");
      out.write("    \t\t   \t$(\"#txDiv\").attr(\"style\",\"height: 50px;width: 50px;position: fixed;right: 136px;top: 14px;background:url('/attachmentController/downFile.action?id=\"+data.tx+\"') round ;border-radius: 50%;\");\r\n");
      out.write("\t\t\t\t//$(\"#txDiv\").css({borderRadius:\"50% !important\",background:\"url('/attachmentController/downFile.action?id=\"+data.tx+\"') round\"});\r\n");
      out.write("    \t   }\r\n");
      out.write("       }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    function smsDetails(){\r\n");
      out.write("    \topenFullWindow(contextPath+'/system/core/sms/index.jsp');\r\n");
      out.write("    \t$(\"#smsbox,.tip_zhezhao\").hide();\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function smsViewAlls(){\r\n");
      out.write("    \tvar url = contextPath+\"/sms/viewAll.action\";\r\n");
      out.write("        tools.requestJsonRs(url,{},true);\r\n");
      out.write("        $(\"#smsbox,.tip_zhezhao\").hide();\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<!-- 短消息面板 -->\r\n");
      out.write("<div class=\"smsbox\" id=\"smsbox\" style=\"display: none;\">\r\n");
      out.write("\t<div class=\"title\">\r\n");
      out.write("\t<span style=\"float:left;\">消息提醒</span>\r\n");
      out.write("\t<span class='sms_close_win' style=\"float:right;font-size:16px;cursor:pointer\" onclick=\"$('#smsbox,.tip_zhezhao').hide()\">×</span>\r\n");
      out.write("\t<span style=\"float:right;cursor:pointer;margin-top:3px;background-image:url(imgs/index/read.png);\" class=\"sms_list smsbox_icon2\" onclick=\"smsDetails()\">消息列表</span>\r\n");
      out.write("\t<span style=\"float:right;cursor:pointer;margin-top:3px;background-image:url(imgs/index/cancel.png);\" class=\"all_check smsbox_icon1\" onclick=\"smsViewAlls()\">全部已阅</span>\r\n");
      out.write("\t<div style=\"clear:both\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"content\" id=\"smsBoxContent\">\r\n");
      out.write("\t\t<div class=\"smsbox_loadmore\" id=\"loadMore\">\r\n");
      out.write("\t\t\t查看更多\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else log(t.getMessage(), t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
