package org.apache.jsp.xzfy.jsp.caseQuery;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.tianee.webframe.util.servlet.TeeCookieUtils;
import java.util.*;
import com.tianee.oa.oaconst.TeeConst;
import com.tianee.oa.core.org.bean.TeePerson;
import com.tianee.webframe.util.str.TeeUtility;
import com.tianee.webframe.util.date.TeeDateUtil;
import com.tianee.webframe.util.global.TeeSysProps;
import com.tianee.webframe.util.str.TeeStringUtil;
import com.tianee.oa.core.org.service.TeePersonService;
import com.tianee.oa.oaconst.TeeModelIdConst;
import com.tianee.webframe.util.servlet.TeeCookieUtils;

public final class caseStat_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  static {
    _jspx_dependants = new java.util.ArrayList(2);
    _jspx_dependants.add("/header/header2.0.jsp");
    _jspx_dependants.add("/header/easyui2.0.jsp");
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

String contextPath = request.getContextPath();
String basePath = request.getScheme() + "://"
		+ request.getServerName() + ":" + request.getServerPort()
		+ contextPath + "/";
//获取主题的索引号
int styleIndex = 1;
Integer styleInSession = (Integer) request.getSession().getAttribute("STYLE_TYPE_INDEX");
if (styleInSession != null) {
	styleIndex = styleInSession;
}
String stylePath = contextPath + "/common/styles";
String imgPath = stylePath + "/style" + styleIndex + "/img";
String cssPath = stylePath + "/style" + styleIndex + "/css";
String systemImagePath = contextPath+"/common/images";

//第二套风格
int STYLE_TYPE_INDEX_2 = TeeStringUtil.getInteger( request.getSession().getAttribute("STYLE_TYPE_INDEX_2"), 1);
String cssPathSecond = contextPath + "/system/frame/2/styles/style" + STYLE_TYPE_INDEX_2 + "/css";
String imgPathSecond = contextPath + "/system/frame/2/styles/style" + STYLE_TYPE_INDEX_2 + "/img";


String loginOutText = TeeSysProps.getString("LOGIN_OUT_TEXT");
String ieTitle = TeeSysProps.getString("IE_TITLE");
String secUserMem = TeeSysProps.getString("SEC_USER_MEM");

Cookie cookie = TeeCookieUtils.getCookie(request, "skin_new");
String skinNew = "1";
if(cookie!=null){
	skinNew = cookie.getValue();
}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- zt_webframe框架引入 jquery -->\r\n");
      out.write("<script src=\"");
      out.print(contextPath );
      out.write("/common/jquery-easyui-1.6.11/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- zt_webframe框架引入 核心库 -->\r\n");
      out.write("<script src=\"");
      out.print(contextPath );
      out.write("/common/zt_webframe/js/package.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(contextPath );
      out.write("/common/js/sys2.0.js?v=2\"></script>\r\n");
      out.write("<script src=\"");
      out.print(contextPath );
      out.write("/common/js/sysUtil.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(contextPath );
      out.write("/common/js/src/orgselect.js\"></script>\r\n");
      out.write("<!--\r\n");
      out.write("\r\n");
      out.write("//-->\r\n");
      out.write("<!-- zt_webframe框架引入 css样式 -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/common/zt_webframe/css/init");
      out.print(skinNew );
      out.write(".css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/common/zt_webframe/css/package");
      out.print(skinNew );
      out.write(".css\">\r\n");
      out.write("\r\n");
      out.write("<script src=\"");
      out.print(contextPath );
      out.write("/common/js/tools2.0.js?v=1\"></script>\r\n");
      out.write("<script src=\"");
      out.print(contextPath );
      out.write("/common/js/TeeMenu.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("/** 变量定义 **/\r\n");
      out.write("var contextPath = \"");
      out.print(contextPath );
      out.write("\";\r\n");
      out.write("var systemImagePath = contextPath+\"/common/images\";\r\n");
      out.write("var uploadFlashUrl = \"");
      out.print(contextPath );
      out.write("/common/swfupload/swfupload.swf\";\r\n");
      out.write("var commonUploadUrl = \"");
      out.print(contextPath );
      out.write("/attachmentController/commonUpload.action;jsessionid=");
      out.print(session.getId());
      out.write("\";\r\n");
      out.write("var xparent;\r\n");
      out.write("var stylePath = \"");
      out.print(stylePath);
      out.write("\";\r\n");
      out.write("if(window.dialogArguments){\r\n");
      out.write("\txparent = window.dialogArguments;\r\n");
      out.write("}else if(window.opener){\r\n");
      out.write("\txparent = opener;\r\n");
      out.write("}else{\r\n");
      out.write("\txparent = window;\r\n");
      out.write("}\r\n");
      out.write("window.UEDITOR_HOME_URL = \"");
      out.print(contextPath);
      out.write("/common/ueditor/\";\r\n");
      out.write("$.browser = {};\r\n");
      out.write("$.browser.mozilla = /firefox/.test(navigator.userAgent.toLowerCase());\r\n");
      out.write("$.browser.webkit = /webkit/.test(navigator.userAgent.toLowerCase());\r\n");
      out.write("$.browser.opera = /opera/.test(navigator.userAgent.toLowerCase());\r\n");
      out.write("$.browser.msie = /msie/.test(navigator.userAgent.toLowerCase());\r\n");
      out.write("</script>\r\n");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- zt_webframe框架引入 核心库 -->\r\n");
      out.write("<script type=\"text/javascript\" src = '");
      out.print(request.getContextPath() );
      out.write("/common/jquery-easyui-1.6.11/jquery.easyui.min.js'></script>\r\n");
      out.write("<script type=\"text/javascript\" src = '");
      out.print(request.getContextPath() );
      out.write("/common/zt_webframe/js/jquery.datagrid.extend.js'></script>\r\n");
      out.write("<script type=\"text/javascript\" src = '");
      out.print(request.getContextPath() );
      out.write("/common/jquery-easyui-1.6.11/locale/easyui-lang-zh_CN.js'></script>\r\n");
      out.write("\r\n");

Cookie __cookie = TeeCookieUtils.getCookie(request, "skin_new");
String __skinNew = "1";
if(__cookie!=null){
	__skinNew = __cookie.getValue();
}

      out.write("\r\n");
      out.write("<!-- zt_webframe框架引入 css样式 -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/common/jquery-easyui-1.6.11/themes/metro/easyui.css\">\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\t<title>统计分析</title>\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"/xzfy/css/caseQuery.css\" />\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/xzfy/js/common/common.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"/common/My97DatePicker/WdatePicker.js\"></script>\r\n");
      out.write("\t<style> \r\n");
      out.write("\t\t.firstTh{ text-align:center} \r\n");
      out.write("\t\t.firstColTh{vertical-align:center;text-align:center}\r\n");
      out.write("\t\t.shuli{ margin:0 auto;width:20px;line-height:24px;border:1px solid #333;text-align:center} \r\n");
      out.write("\t</style> \r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body style=\"padding-left: 10px;padding-right: 10px\" onload=\"doInit();\">\r\n");
      out.write("\r\n");
      out.write("   <div id=\"toolbar\" class = \" clearfix\" style=\"margin-top: 5px\">\r\n");
      out.write("\t    <div class=\"fl\" style=\"position:static\">\r\n");
      out.write("\t\t    <img id=\"img1\" class = 'title_img' src=\"");
      out.print(contextPath );
      out.write("/common/zt_webframe/imgs/jhrw/icon_任务中心.png\">\r\n");
      out.write("\t\t    <span class=\"title\" id=\"title\">案件统计表</span>\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t    <span class=\"basic_border_grey\" style=\"margin-top: 10px\"></span>\r\n");
      out.write("\t    \r\n");
      out.write("\t    <div class=\"setHeight\">\r\n");
      out.write("\t        <form id=\"form1\" style=\"\">\r\n");
      out.write("\t            <input type=\"hidden\" id=\"orgId\" value=\"\" >\r\n");
      out.write("\t            <table class=\"none_table\" width=\"100%\" height=\"65\">\r\n");
      out.write("\t           \r\n");
      out.write("\t \t\t\t\t<tr id=\"accsearchTr1\">\r\n");
      out.write("\t \t\t\t\t\r\n");
      out.write("\t \t\t\t\t\t<td class=\"TableData TableBG\">复议机关：\r\n");
      out.write("\t \t\t\t\t\t    <select name=\"moreselAge\" id=\"addNew\">   \r\n");
      out.write("\t\t\t\t\t\t        <option value=\"1\" selected>默认机关名称</option>   \r\n");
      out.write("\t\t\t\t\t\t        <option value=\"2\">下级机关名称</option>    \r\n");
      out.write("\t\t\t\t\t\t      </select>   \r\n");
      out.write("\t \t\t\t\t\t    <input type=\"checkbox\" name=\"\" value=\"\" />本级及下级\r\n");
      out.write("\t \t\t\t\t\t</td>\r\n");
      out.write("\t \t\t\t\t\r\n");
      out.write("\t \t\t\t\t\t<td class=\"TableData TableBG\">开始时间：\r\n");
      out.write("\t \t\t\t\t\t\r\n");
      out.write("\t \t\t\t\t\t \t<input type=\"text\" name=\"beginTime\" id=\"beginTime\" readonly onclick=\"WdatePicker({dateFmt:'yyyy-MM-dd'})\" \r\n");
      out.write("\t \t\t\t\t\t \t\tclass=\"Wdate BigInput\" style=\"width:172px;height: 20px\"/>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<td class=\"TableData TableBG\">结束时间：\r\n");
      out.write("\r\n");
      out.write("\t \t\t\t\t\t\t<input type=\"text\" name=\"endTime\" id=\"endTime\" readonly onclick=\"WdatePicker({minDate:'#F{$dp.$D(\\'beginTime\\',{d:0});}',dateFmt:'yyyy-MM-dd'})\" \r\n");
      out.write("\t\t\t\t\t\t\t    class=\"Wdate BigInput\" style=\"width:172px;height: 20px\"/>\r\n");
      out.write("\t \t\t\t\t\t</td>\r\n");
      out.write("\t \t\t\t\t\t\r\n");
      out.write("\t \t\t\t\t\t<td class=\"TableData TableBG\"></td>\r\n");
      out.write("\t \t\t\t\t\t\r\n");
      out.write(" \t\t\t\t\t\t<td class=\"TableData\"><button class=\"btn-win-white\" type=\"button\" onclick=\"search()\">生成统计图</button></td>\r\n");
      out.write("\t \t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</form>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<span class=\"basic_border\"></span>\r\n");
      out.write("\t\t\r\n");
      out.write("   \t</div>\r\n");
      out.write("   \t<br>\r\n");
      out.write("   \t<div align=\"center\" >\r\n");
      out.write("   \t<span class=\"title\">行政复议案件统计表<br></span>\r\n");
      out.write("   \t<span id=\"dateTxt\"></span>\r\n");
      out.write("   \t</div>\r\n");
      out.write("   \t<div id=\"tablediv\" align=\"center\" >\r\n");
      out.write("     <table border=\"1\" cellspacing=\"0\" cellpadding=\"0\" id=\"table\">\r\n");
      out.write("     \t<thead>\r\n");
      out.write("        \t<tr>\r\n");
      out.write("        \t\t<th rowspan=\"3\" class=\"firstColTh\">行政管理类型</th>\r\n");
      out.write("        \t\t<th rowspan=\"3\" class=\"shuli\">上期结转</th>\r\n");
      out.write("        \t\t<th rowspan=\"3\" class=\"shuli\">本期新收</th>\r\n");
      out.write("        \t\t<th rowspan=\"3\" class=\"shuli\">受理</th>\r\n");
      out.write("        \t\t<th rowspan=\"3\" class=\"shuli\">申请人总数</th>\r\n");
      out.write("        \t\t<th colspan=\"9\" class=\"firstTh\">被申请人</th>\r\n");
      out.write("        \t\t<th colspan=\"8\" class=\"firstTh\">复议机关</th>\r\n");
      out.write("        \t\t<th colspan=\"10\" class=\"firstTh\">申请复议事项</th>\r\n");
      out.write("        \t\t<th colspan=\"10\" class=\"firstTh\">已审结</th>\r\n");
      out.write("        \t\t<th rowspan=\"3\" class=\"shuli\">未审结</th>\r\n");
      out.write("        \t\t<th rowspan=\"3\" class=\"shuli\">对规范性文件附带审查</th>\r\n");
      out.write("        \t\t<th colspan=\"2\" class=\"firstTh\">行政<br>赔偿</th>\r\n");
      out.write("        \t\t<th colspan=\"2\" class=\"firstTh\">行政复议意见书</th>\r\n");
      out.write("        \t</tr>\r\n");
      out.write("        \t<tr>\r\n");
      out.write("        \t\t<th rowspan=\"2\" class=\"shuli\">乡镇政府</th>\r\n");
      out.write("        \t\t<th rowspan=\"2\" class=\"shuli\">县级政府的部门</th>\r\n");
      out.write("        \t\t<th rowspan=\"2\" class=\"shuli\">县级政府</th>\r\n");
      out.write("        \t\t<th rowspan=\"2\" class=\"shuli\">市<br>（<br>地<br>）<br>级<br>政<br>府<br>的<br>部<br>门</th>\r\n");
      out.write("        \t\t<th rowspan=\"2\" class=\"shuli\">市<br>（<br>地<br>）<br>级<br>政<br>府</th>\r\n");
      out.write("        \t\t<th rowspan=\"2\" class=\"shuli\">省级政府的部门</th>\r\n");
      out.write("        \t\t<th rowspan=\"2\" class=\"shuli\">省级政府</th>\r\n");
      out.write("        \t\t<th rowspan=\"2\" class=\"shuli\">国务院部门</th>\r\n");
      out.write("        \t\t<th rowspan=\"2\" class=\"shuli\">其他</th>\r\n");
      out.write("        \t\t<th rowspan=\"2\" class=\"shuli\">县级政府的部门</th>\r\n");
      out.write("        \t\t<th rowspan=\"2\" class=\"shuli\">县级政府</th>\r\n");
      out.write("        \t\t<th rowspan=\"2\" class=\"shuli\">市<br>（<br>地<br>）<br>级<br>政<br>府<br>的<br>部<br>门</th>\r\n");
      out.write("        \t\t<th rowspan=\"2\" class=\"shuli\">市<br>（<br>地<br>）<br>级<br>政<br>府</th>\r\n");
      out.write("        \t\t<th rowspan=\"2\" class=\"shuli\">省级政府的部门</th>\r\n");
      out.write("        \t\t<th rowspan=\"2\" class=\"shuli\">省级政府</th>\r\n");
      out.write("        \t\t<th rowspan=\"2\" class=\"shuli\">国务院部门</th>\r\n");
      out.write("        \t\t<th rowspan=\"2\" class=\"shuli\">国务院</th>\r\n");
      out.write("        \t\t<th rowspan=\"2\" class=\"shuli\">行政处罚</th>\r\n");
      out.write("        \t\t<th rowspan=\"2\" class=\"shuli\">行政强制</th>\r\n");
      out.write("        \t\t<th rowspan=\"2\" class=\"shuli\">行政征收</th>\r\n");
      out.write("        \t\t<th rowspan=\"2\" class=\"shuli\">行政许可</th>\r\n");
      out.write("        \t\t<th rowspan=\"2\" class=\"shuli\">行政确权</th>\r\n");
      out.write("        \t\t<th rowspan=\"2\" class=\"shuli\">行政确认</th>\r\n");
      out.write("        \t\t<th rowspan=\"2\" class=\"shuli\">信息公开</th>\r\n");
      out.write("        \t\t<th rowspan=\"2\" class=\"shuli\">举报投诉处理</th>\r\n");
      out.write("        \t\t<th rowspan=\"2\" class=\"shuli\">行政不作为</th>\r\n");
      out.write("        \t\t<th rowspan=\"2\" class=\"shuli\">其他</th>\r\n");
      out.write("        \t\t<th rowspan=\"2\" class=\"shuli\">总计</th>\r\n");
      out.write("        \t\t<th rowspan=\"2\" class=\"shuli\">驳回</th>\r\n");
      out.write("        \t\t<th rowspan=\"2\" class=\"shuli\">维持</th>\r\n");
      out.write("        \t\t<th rowspan=\"2\" class=\"shuli\">确认违法</th>\r\n");
      out.write("        \t\t<th rowspan=\"2\" class=\"shuli\">撤销</th>\r\n");
      out.write("        \t\t<th rowspan=\"2\" class=\"shuli\">变更</th>\r\n");
      out.write("        \t\t<th rowspan=\"2\" class=\"shuli\">责令履行</th>\r\n");
      out.write("        \t\t<th colspan=\"2\">终止</th>\r\n");
      out.write("        \t\t<th rowspan=\"2\" rowspan=\"2\" class=\"shuli\">其他</th>\r\n");
      out.write("        \t\t<th rowspan=\"2\" class=\"shuli\">件数</th>\r\n");
      out.write("        \t\t<th rowspan=\"2\">赔<br/>偿<br/>数<br/>额<br/>（<br/>元<br/>）</th>\r\n");
      out.write("        \t\t<th rowspan=\"2\">制发数</th>\r\n");
      out.write("        \t\t<th rowspan=\"2\">落实数</th>\r\n");
      out.write("        \t</tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("            \t<th class=\"shuli\">调<br>解<br>（<br>和<br>解<br>）</th>\r\n");
      out.write("        \t\t<th class=\"shuli\">其他</th>\r\n");
      out.write("            </tr>\r\n");
      out.write("     \t</thead>\r\n");
      out.write("        <tbody id=\"tbody\">\r\n");
      out.write("           <!--  <tr>\r\n");
      out.write("                <th class=\"firstColTh\">公安</th>\r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td>\r\n");
      out.write("                <td> </td>\r\n");
      out.write("                <td> </td>\r\n");
      out.write("                <td>2</td>\r\n");
      out.write("                <td> </td>\r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> 9</td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> 6</td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> 3</td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td>    \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td>  \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td>\r\n");
      out.write("                <td> </td>\r\n");
      out.write("                <td> </td>\r\n");
      out.write("                <td> </td>          \r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <th class=\"firstColTh\">国家安全</th>\r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td>\r\n");
      out.write("                <td> </td>\r\n");
      out.write("                <td> </td>\r\n");
      out.write("                <td>2</td>\r\n");
      out.write("                <td> </td>\r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> 9</td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> 6</td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> 3</td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td>    \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td>  \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td>\r\n");
      out.write("                <td> </td>\r\n");
      out.write("                <td> </td>\r\n");
      out.write("                <td> </td>          \r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <th class=\"firstColTh\">劳动和社会保障</th>\r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td>\r\n");
      out.write("                <td> </td>\r\n");
      out.write("                <td> </td>\r\n");
      out.write("                <td>2</td>\r\n");
      out.write("                <td> </td>\r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> 9</td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> 6</td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> 3</td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td>    \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td>  \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td>\r\n");
      out.write("                <td> </td>\r\n");
      out.write("                <td> </td>\r\n");
      out.write("                <td> </td>          \r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <th class=\"firstColTh\">水利</th>\r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td>\r\n");
      out.write("                <td> </td>\r\n");
      out.write("                <td> </td>\r\n");
      out.write("                <td>2</td>\r\n");
      out.write("                <td> </td>\r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> 9</td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> 6</td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td>    \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> 4</td> \r\n");
      out.write("                <td> </td>  \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td>\r\n");
      out.write("                <td> </td>\r\n");
      out.write("                <td> </td>\r\n");
      out.write("                <td> </td>          \r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <th class=\"firstColTh\">城乡规划</th>\r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td>\r\n");
      out.write("                <td> </td>\r\n");
      out.write("                <td> </td>\r\n");
      out.write("                <td>2</td>\r\n");
      out.write("                <td> </td>\r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> 9</td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> 6</td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td>    \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> 4</td> \r\n");
      out.write("                <td> </td>  \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td>\r\n");
      out.write("                <td> </td>\r\n");
      out.write("                <td> </td>\r\n");
      out.write("                <td> </td>          \r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <th class=\"firstColTh\">工商</th>\r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td>\r\n");
      out.write("                <td> </td>\r\n");
      out.write("                <td> </td>\r\n");
      out.write("                <td>2</td>\r\n");
      out.write("                <td> </td>\r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> 9</td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> 6</td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td>    \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> 4</td> \r\n");
      out.write("                <td> </td>  \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td>\r\n");
      out.write("                <td> </td>\r\n");
      out.write("                <td> </td>\r\n");
      out.write("                <td> </td>          \r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <th class=\"firstColTh\">安监</th>\r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td>\r\n");
      out.write("                <td> </td>\r\n");
      out.write("                <td> </td>\r\n");
      out.write("                <td>2</td>\r\n");
      out.write("                <td> </td>\r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> 9</td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> 6</td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td>    \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> 4</td> \r\n");
      out.write("                <td> </td>  \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td>\r\n");
      out.write("                <td> </td>\r\n");
      out.write("                <td> </td>\r\n");
      out.write("                <td> </td>          \r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <th class=\"firstColTh\">商务</th>\r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td>\r\n");
      out.write("                <td> </td>\r\n");
      out.write("                <td> </td>\r\n");
      out.write("                <td>2</td>\r\n");
      out.write("                <td> </td>\r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> 9</td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> 6</td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td>    \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> 4</td> \r\n");
      out.write("                <td> </td>  \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td>\r\n");
      out.write("                <td> </td>\r\n");
      out.write("                <td> </td>\r\n");
      out.write("                <td> </td>          \r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <th class=\"firstColTh\">物价</th>\r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td>\r\n");
      out.write("                <td> </td>\r\n");
      out.write("                <td> </td>\r\n");
      out.write("                <td>2</td>\r\n");
      out.write("                <td> </td>\r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> 9</td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> 6</td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td>    \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> 4</td> \r\n");
      out.write("                <td> </td>  \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td>\r\n");
      out.write("                <td> </td>\r\n");
      out.write("                <td> </td>\r\n");
      out.write("                <td> </td>          \r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <th class=\"firstColTh\">能源</th>\r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td>\r\n");
      out.write("                <td> </td>\r\n");
      out.write("                <td> </td>\r\n");
      out.write("                <td>2</td>\r\n");
      out.write("                <td> </td>\r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> 9</td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> 6</td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td>    \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> 4</td> \r\n");
      out.write("                <td> </td>  \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td>\r\n");
      out.write("                <td> </td>\r\n");
      out.write("                <td> </td>\r\n");
      out.write("                <td> </td>          \r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <th class=\"firstColTh\">交通运输</th>\r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td>\r\n");
      out.write("                <td> </td>\r\n");
      out.write("                <td> </td>\r\n");
      out.write("                <td></td>\r\n");
      out.write("                <td> </td>\r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> 9</td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> 6</td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td>    \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> 4</td> \r\n");
      out.write("                <td> </td>  \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td> \r\n");
      out.write("                <td> </td>\r\n");
      out.write("                <td> </td>\r\n");
      out.write("                <td> </td>\r\n");
      out.write("                <td> </td>          \r\n");
      out.write("            </tr> -->\r\n");
      out.write("            \r\n");
      out.write("        </tbody>\r\n");
      out.write("        <tfoot id=\"tfoot\">\r\n");
      out.write("        \t<tr  id=\"count\">\r\n");
      out.write("                      \r\n");
      out.write("            </tr>\r\n");
      out.write("        </tfoot>\r\n");
      out.write("    </table>\r\n");
      out.write("    </div>\r\n");
      out.write("   \r\n");
      out.write("    <script type=\"text/javascript\" src=\"/xzfy/js/base/juicer-min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"/xzfy/js/caseList/stat.js\"></script>\r\n");
      out.write("  \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else log(t.getMessage(), t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
