package org.apache.jsp.gzpt.admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import com.tianee.oa.oaconst.TeeConst;
import com.tianee.oa.core.org.bean.TeePerson;
import com.tianee.webframe.util.global.TeeSysProps;
import com.tianee.webframe.util.date.TeeLunarCalendarUtils;
import com.tianee.webframe.util.str.TeeStringUtil;
import com.tianee.webframe.util.auth.TeeAuthUtil;
import com.tianee.webframe.util.global.TeeSysCustomerProps;
import com.tianee.oa.core.org.bean.TeeUserRole;
import com.tianee.oa.core.org.bean.TeeDepartment;
import com.tianee.oa.oaconst.TeeConst;
import com.tianee.webframe.util.date.TeeDateUtil;
import com.tianee.oa.core.org.bean.TeePerson;
import com.tianee.oa.core.org.service.TeePersonService;
import java.util.Date;
import com.tianee.webframe.util.date.TeeDateUtil;
import com.tianee.webframe.util.str.TeeUtility;
import com.tianee.webframe.util.str.TeeStringUtil;
import com.tianee.oa.oaconst.TeeConst;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  static {
    _jspx_dependants = new java.util.ArrayList(1);
    _jspx_dependants.add("/header/userheader.jsp");
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");


	String contextPath = request.getContextPath();
	String basePath = request.getScheme() + "://"
			+ request.getServerName() + ":" + request.getServerPort()
			+ contextPath + "/";
	//获取主题的索引号
	int styleIndex = 1;
	Integer styleInSession = (Integer) request.getSession().getAttribute("STYLE_TYPE_INDEX");
	if (styleInSession != null) {
		styleIndex = styleInSession;
	}
	String stylePath = contextPath + "/common/styles";
	String imgPath = stylePath + "/style" + styleIndex + "/img";
	String cssPath = stylePath + "/style" + styleIndex + "/css";
	String systemImagePath = contextPath+"/common/images";
	
	//第二套风格
	int STYLE_TYPE_INDEX_2 = TeeStringUtil.getInteger( request.getSession().getAttribute("STYLE_TYPE_INDEX_2"), 1);
	String cssPathSecond = contextPath + "/system/frame/2/styles/style" + STYLE_TYPE_INDEX_2 + "/css";
	String imgPathSecond = contextPath + "/system/frame/2/styles/style" + STYLE_TYPE_INDEX_2 + "/img";
	
	
	String loginOutText = TeeSysProps.getString("LOGIN_OUT_TEXT");
	String ieTitle = TeeSysProps.getString("IE_TITLE");
	String secUserMem = (String) request.getSession().getAttribute("SEC_USER_MEM") == null ? "" : (String) request.getSession().getAttribute("SEC_USER_MEM");//是否记忆用户名
    
	//单点跳转参数
	String tzcs=(String) request.getSession().getAttribute("cuo");
	String outUrl=TeeSysCustomerProps.getString("MHLJ");
	


      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=Edge\">\r\n");
      out.write("<title>");
      out.print(ieTitle );
      out.write("</title>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	TeePerson person = (TeePerson)request.getSession().getAttribute(TeeConst.LOGIN_USER);
	boolean isAdminPriv = TeePersonService.checkIsAdminPriv(person);
	boolean isSuperAdmin = TeePersonService.checkIsSuperAdmin(person,"");
	String isAdmin = person.getIsAdmin();

	Date date = person.getLastPassTime();
	String lastPassTime = "";
	if(date != null){
		lastPassTime = TeeDateUtil.getDateTimeStr(date);
	}
	int loginPersonId = person.getUuid();
	
	
	
	
	String SEC_INIT_PASS = (String) request.getSession().getAttribute("SEC_INIT_PASS") == null ? "0" : (String) request.getSession().getAttribute("SEC_INIT_PASS");//初始密码
	String SEC_PASS_FLAG = TeeStringUtil.getString( (String) request.getSession().getAttribute("SEC_PASS_FLAG"), "0");//是否过期
	String SEC_PASS_TIME = TeeStringUtil.getString((String) request.getSession().getAttribute("SEC_PASS_TIME"), "0");//过期时间
	String SEC_SHOW_IP = TeeStringUtil.getString((String) request.getSession().getAttribute("SEC_SHOW_IP"), "0");//是否显示IP
	String SEC_ON_STATUS = TeeStringUtil.getString((String) request.getSession().getAttribute("SEC_ON_STATUS"), "0");//记录在线状态
	
	int AVATAR_UPLOAD = TeeStringUtil.getInteger(request.getSession().getAttribute("AVATAR_UPLOAD"), 0 );//是否允许上传图象
	int AVATAR_WIDTH =  TeeStringUtil.getInteger(request.getSession().getAttribute("AVATAR_WIDTH"), 0 );//图象宽度
	int  AVATAR_HEIGHT = TeeStringUtil.getInteger(request.getSession().getAttribute("AVATAR_HEIGHT"),0);//图象高度
  
	String userName = person.getUserName();
	String userId = person.getUserId();
	int userSid = person.getUuid();
	TeeDepartment dept = person.getDept();
	String currUserDeptName  = "";
	String currUserRoleName = "";
	TeeUserRole role = person.getUserRole();
	if(dept != null){
		currUserDeptName = dept.getDeptName();
	}
	if(role != null){
		currUserRoleName = role.getRoleName();
	}
	String avatar = person.getAvatar();
	//用于判断用户性别
	String avatar_default = "";
	if(("0".equals(person.getSex())) && TeeUtility.isNullorEmpty(person.getAvatar())){
		avatar_default = "0";  //0代表男
	}else if(("1".equals(person.getSex())) && TeeUtility.isNullorEmpty(person.getAvatar())){
		avatar_default = "1";  //1代表女
	}

      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("/** 变量定义 **/\r\n");
      out.write("var isAdminPriv = '");
      out.print(isAdminPriv);
      out.write("';\r\n");
      out.write("var isSuperAdmin = '");
      out.print(isSuperAdmin);
      out.write("';\r\n");
      out.write("var loginPersonId = ");
      out.print(loginPersonId);
      out.write(";\r\n");
      out.write("var lastPassTime = '");
      out.print(lastPassTime);
      out.write("';\r\n");
      out.write("\r\n");
      out.write("var SEC_SHOW_IP =  '");
      out.print(SEC_SHOW_IP);
      out.write("';\r\n");
      out.write("var SEC_ON_STATUS =  '");
      out.print(SEC_ON_STATUS);
      out.write("';\r\n");
      out.write("var AVATAR_UPLOAD =  '");
      out.print(AVATAR_UPLOAD);
      out.write("';\r\n");
      out.write("var AVATAR_WIDTH =  '");
      out.print(AVATAR_WIDTH);
      out.write("';\r\n");
      out.write("var AVATAR_HEIGHT =  '");
      out.print(AVATAR_HEIGHT);
      out.write("';\r\n");
      out.write("var userId = \"");
      out.print(userId);
      out.write("\";\r\n");
      out.write("var userName = \"");
      out.print(userName);
      out.write("\";\r\n");
      out.write("var avatar = \"");
      out.print(avatar);
      out.write("\";\r\n");
      out.write("var avatar_default = \"");
      out.print(avatar_default);
      out.write("\";\r\n");
      out.write("</script>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- jQuery库 -->\r\n");
      out.write("<script src=\"");
      out.print(contextPath );
      out.write("/common/zt_webframe/js/jquery-1.11.1.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" >\r\n");
      out.write("window.UEDITOR_HOME_URL = \"");
      out.print(contextPath);
      out.write("/common/ueditor/\";\r\n");
      out.write("$.browser = {};\r\n");
      out.write("$.browser.mozilla = /firefox/.test(navigator.userAgent.toLowerCase());\r\n");
      out.write("$.browser.webkit = /webkit/.test(navigator.userAgent.toLowerCase());\r\n");
      out.write("$.browser.opera = /opera/.test(navigator.userAgent.toLowerCase());\r\n");
      out.write("$.browser.msie = /msie/.test(navigator.userAgent.toLowerCase());\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<!-- 其他工具库类 -->\r\n");
      out.write("<script src=\"");
      out.print(contextPath );
      out.write("/common/js/tools.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(contextPath );
      out.write("/common/js/sys2.0.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(contextPath );
      out.write("/common/js/sysUtil.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(contextPath );
      out.write("/common/js/src/orgselect.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(contextPath);
      out.write("/common/js/easyuiTools.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(contextPath );
      out.write("/common/zt_webframe/js/package.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- 图片预览器 -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(contextPath);
      out.write("/common/js/lazyloader.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("/** 常量定义 **/\r\n");
      out.write("var TDJSCONST = {\r\n");
      out.write("  YES: 1,\r\n");
      out.write("  NO: 0\r\n");
      out.write("};\r\n");
      out.write("/** 变量定义 **/\r\n");
      out.write("var contextPath = \"");
      out.print(contextPath );
      out.write("\";\r\n");
      out.write("var imgPath = \"");
      out.print(imgPath );
      out.write("\";\r\n");
      out.write("var cssPath = \"");
      out.print(cssPath);
      out.write("\";\r\n");
      out.write("var stylePath = \"");
      out.print(stylePath);
      out.write("\";\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("var cssPathSecond = \"");
      out.print(cssPathSecond);
      out.write("\";\r\n");
      out.write("var imgPathSecond = \"");
      out.print(imgPathSecond);
      out.write("\";\r\n");
      out.write("var loginOutText = \"");
      out.print(loginOutText);
      out.write("\";\r\n");
      out.write("var uploadFlashUrl = \"");
      out.print(contextPath );
      out.write("/common/swfupload/swfupload.swf\";\r\n");
      out.write("var commonUploadUrl = \"");
      out.print(contextPath );
      out.write("/attachmentController/commonUpload.action\";\r\n");
      out.write("var systemImagePath = \"");
      out.print(systemImagePath);
      out.write("\";\r\n");
      out.write("var xparent;\r\n");
      out.write("var tzcs=\"");
      out.print(tzcs);
      out.write("\";\r\n");
      out.write("var outUrl=\"");
      out.print(outUrl);
      out.write("\";\r\n");
      out.write("if(window.dialogArguments){\r\n");
      out.write("\txparent = window.dialogArguments;\r\n");
      out.write("}else if(window.opener){\r\n");
      out.write("\txparent = opener;\r\n");
      out.write("}else{\r\n");
      out.write("\txparent = window;\r\n");
      out.write("}\r\n");
      out.write("function parseNumber(value, defValue) {\r\n");
      out.write("  if (isNaN(value)) {\r\n");
      out.write("    return defValue;\r\n");
      out.write("  }\r\n");
      out.write("  return value * 1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/common/zt_webframe/css/init1.css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/common/zt_webframe/css/package1.css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(contextPath);
      out.write("/system/frame/3/js/jquery.SuperSlide.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(contextPath);
      out.write("/system/frame/4/js/index2.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(contextPath);
      out.write("/system/frame/2/js/index.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(contextPath);
      out.write("/system/frame/2/js/sms.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(contextPath);
      out.write("/common/jbox-v2.3/jBox/jquery.jBox-2.3.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(contextPath);
      out.write("/common/jbox-v2.3/jBox/i18n/jquery.jBox-zh-CN.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/index.css?v=1\">\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("function doInit(){\r\n");
      out.write("\t queryOnlineUserCount();\r\n");
      out.write("\t //获取皮肤\r\n");
      out.write("\t getSkinFunc();\r\n");
      out.write("\t //初始化桌面\r\n");
      out.write("\t //doInitDeskTop();\r\n");
      out.write("}\r\n");
      out.write("//获取cookie中的皮肤\r\n");
      out.write("function getSkinFunc(){\r\n");
      out.write("\t$(\".header\").css(\"background-color\",\"#0099cb\");\r\n");
      out.write("\t$(\".section .secLeft .avatar\").css(\"background-color\",\"#014876\");\r\n");
      out.write("\t$(\".section .secLeft\").css(\"background-color\",\"#192f47\");\r\n");
      out.write("\t$(\".section .default\").css(\"background-color\",\"#192f47\");\r\n");
      out.write("\t$(\".currentIdentity\").css(\"background-color\",\"#496290\");\r\n");
      out.write("\t$(\".footer_info\").css(\"background-color\",\"#2285c6\");\r\n");
      out.write("\t$(\".menu_active_red\").css(\"background-color\",\"#496290\");\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/**\r\n");
      out.write("*\r\n");
      out.write("*注销\r\n");
      out.write("*/\r\n");
      out.write("function doLogout(){\r\n");
      out.write("\tvar msg = loginOutText + \"\\n确定要注销吗?\";\r\n");
      out.write("\t$.MsgBox.Confirm(\"提示\",msg,function(){\r\n");
      out.write("\t\tvar url = contextPath + \"/systemAction/doLoginout.action\";\r\n");
      out.write("\t\tvar para = {};\r\n");
      out.write("\t\tvar jsonObj = tools.requestJsonRs(url,para);\r\n");
      out.write("\t\tif(jsonObj){\r\n");
      out.write("\t\t\tvar json = jsonObj.rtData;\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\t$.MsgBox.Alert(\"提示\", jsonObj.rtMsg);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\twindow.location.href = \"/\"+contextPath;\r\n");
      out.write("});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function toDesktop(){\r\n");
      out.write("\t//$(\"#mainIframe\")[0].src = \"");
      out.print(contextPath);
      out.write("/system/frame/default/mainForSimple.jsp\";\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");

String todayLunarStr = TeeLunarCalendarUtils.today();
String TOP_BANNER_TEXT = TeeSysProps.getString("TOP_BANNER_TEXT");
String BOTTOM_STATUS_TEXT = TeeSysProps.getString("BOTTOM_STATUS_TEXT");
String TOP_ATTACHMENT_ID = TeeSysProps.getString("TOP_ATTACHMENT_ID");

      out.write("\r\n");
      out.write("<body onload=\"doInit()\">\r\n");
      out.write("<!--------------- 系统头部 -------------->\r\n");
      out.write("\t<div class=\"header\">\r\n");
      out.write("\t<!---------- logo ---------->\r\n");
      out.write("\t\t<div class=\"logo fl\">\r\n");
      out.write("\t\t\t<img src=\"imgs/index/logo.png\"/>\r\n");
      out.write("\t\t\t系统管理员后台\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"fl clearfix firstMenuContent\">\r\n");
      out.write("\t\t\t<ul id = 'firstMenuList' class = 'clearfix fl'>\r\n");
      out.write("\t\t\t\t<!-- \r\n");
      out.write("\t\t\t    <img class = 'home' style=\"cursor:pointer\" src=\"imgs/index/home.png\" onclick=\"toDesktop()\" title=\"桌面\"> -->\r\n");
      out.write("\t\t\t\t<!-- 这里是第一级列表 -->\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class = 'fl menuListRight'>\r\n");
      out.write("\t\t\t\t\t<span class = 'moreApp fl'>更多应用\r\n");
      out.write("\t\t\t\t\t\t<img src=\"imgs/index/xialasanjiao.png\">\r\n");
      out.write("\t\t\t\t\t\t<ul class='moreAppcContent'></ul>\r\n");
      out.write("\t\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t\t<span class=\"search \"><img src=\"imgs/index/search.png\"></span>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" class='search_input fl' >\r\n");
      out.write("\t\t\t\t\t<ul class = ' clearfix fl'>\r\n");
      out.write("\t\t\t\t\t\t<li onclick=\"openFullWindow('/system/core/base/weibo/index.jsp')\" title=\"企业社区\"><img src=\"imgs/index/weibo.png\"></li>\r\n");
      out.write("\t\t\t\t\t\t<li><img class='sms' id='tip_alert' src=\"imgs/index/alert.png\">\r\n");
      out.write("\t\t\t\t\t\t  <!--  <p class=\"top_fot\" title=\"消息事务\">消息事务</p> -->\r\n");
      out.write("                           <div class=\"sign_in_tid\" style=\"display:none\">新的消息！</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li><img class=\"sign_img\" src=\"imgs/index/sign.png\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"signin_out\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<p id=\"signInTime\" class='sign_time' style=\"font-weight: bold;font-size: 16px;\"></p>\r\n");
      out.write("\t\t\t\t\t\t\t\t<p><button id=\"signInButton\" class='sign_btn' onclick=\"signInFunc();\" style='color:#fff;'>登记</button></p>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t<li onclick=\"doLogout()\"><img src=\"imgs/index/switch.png\"></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t<img class = 'group fl' src=\"imgs/index/group.png\">\r\n");
      out.write("\t\t\t\t\t<div id='groupContent' style='width:240px;position:fixed;right:-240px;top:60px;bottom:32px;z-index:99999;box-shadow:0 0 15px #a2a2a2;'>\r\n");
      out.write("\t\t\t\t\t\t<iframe style='width:100%;height:100%;' id='right' src=\"/system/frame/3/right.jsp\" frameborder=\"0\"></iframe>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t</div><!-- header结束 -->\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"section\">\r\n");
      out.write("\t\t<div class=\"secLeft\">\r\n");
      out.write("\t\t\t<div class=\"avatar\">\r\n");
      out.write("\t\t\t\t<span class='radius'>\r\n");
      out.write("\t\t\t\t\t<img class = 'avatarIcon' src=\"");
      out.print(contextPath );
      out.write("/attachmentController/downFile.action?id=");
      out.print(avatar );
      out.write("\" width=\"40\" height=\"40\" onerror=\"this.src = '");
      out.print(request.getContextPath() );
      out.write("/common/images/default_avatar.gif'\">\r\n");
      out.write("\t\t\t\t</span>\r\n");
      out.write("\t\t\t\t<span>\r\n");
      out.write("\t\t\t\t");

            		if(userName.length()>4){
            			out.print("<span style='font-size:12px'>"+userName+"</span>");
            		}else{
            			out.print(userName);
            		}
            	
      out.write("\r\n");
      out.write("                </span>\r\n");
      out.write("\t\t\t\t<img hidden class ='shareIcon' src=\"imgs/index/share.png\">\r\n");
      out.write("\t\t\t\t<ul hidden class='positionBlock'>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<span class='current_pos'><img src=\"imgs/index/current_pos.png\" alt=\"\"></span>\r\n");
      out.write("\t\t\t\t\t\t<span class='position'>总经理</span>\r\n");
      out.write("\t\t\t\t\t\t<span class='note'>(集团总经办)</span>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<span class='current_pos'><img src=\"imgs/index/current_pos.png\" alt=\"\"></span>\r\n");
      out.write("\t\t\t\t\t\t<span class='position'>总经理</span>\r\n");
      out.write("\t\t\t\t\t\t<span class='note'>(集团总经办)</span>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"secMenuListContent\"><!-- 左侧的二级菜单 -->\r\n");
      out.write("\t\t\t\t<ul id = 'secMenuList' class=\"\">\r\n");
      out.write("\t\t\t\t\t<div class=\"default\">\r\n");
      out.write("\t\t\t\t\t\t<p style=\"cursor:pointer;\" class='home'><img src=\"imgs/index/xialasanjiao.png\">桌面</p>\r\n");
      out.write("\t\t\t\t\t\t<ul class = 'defaultContent' id=\"desktopDiv\">\r\n");
      out.write("\t\t\t\t\t\t\t<!-- <li onclick=\"changePage(12)\"><img src=\"imgs/index/page.png\">个人门户</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><img src=\"imgs/index/page.png\">公司门户</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><img src=\"imgs/index/page.png\">管理门户</li> -->\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"settingContent\">\r\n");
      out.write("\t\t\t\t\t\t<p style=\"cursor:pointer;\" class='setHead'><img src=\"imgs/index/xialasanjiao.png\">设置中心</p>\r\n");
      out.write("\t\t\t\t\t\t<ul class = 'defaultContent'>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"imgs/index/page.png\">界面设置<img class=\"menu_hide_show\" src=\"imgs/index/hide.png\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class='setContent_ul'>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li onclick=\"changePage(1)\">界面主题</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li onclick=\"changePage(2)\">收藏夹</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li onclick=\"changePage(3)\">桌面空间</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"imgs/index/page.png\">个人信息<img class=\"menu_hide_show\" src=\"imgs/index/hide.png\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class='setContent_ul'>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li onclick=\"changePage(4)\">个人资料</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li onclick=\"changePage(5)\">昵称与头像</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li onclick=\"changePage(6)\">自定义用户组</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li onclick=\"changePage(7)\">电子签章管理</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li onclick=\"changePage(13)\">图片签章管理</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li onclick=\"changePage(8)\">常用语维护</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"#\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<img src=\"imgs/index/page.png\">账户安全<img class=\"menu_hide_show\" src=\"imgs/index/hide.png\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t<ul class='setContent_ul'>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li onclick=\"changePage(9)\">我的账户</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li onclick=\"changePage(10)\">修改密码</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<li onclick=\"changePage(11)\">安全日志</li>\r\n");
      out.write("\t\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"mainContent\">\r\n");
      out.write("\t\t\t<iframe id='mainIframe'  frameborder=\"0\" style=\"box-sizing: border-box;\" src=\"\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t</iframe>\r\n");
      out.write("\t\t</div><!-- section结束 -->\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"footer\">\r\n");
      out.write("\t\t<div class=\"setting\">\r\n");
      out.write("\t\t\t<p class='currentIdentity'>\r\n");
      out.write("\t\t\t\t<img class='setIcon' src=\"imgs/index/set.png\">\r\n");
      out.write("\t\t\t\t<span>\r\n");
      out.write("\t\t\t\t\t<img class = 'themeIcon' src=\"imgs/index/pageStyle.png\">\r\n");
      out.write("\t\t\t\t\t<ul class='themeList'>\r\n");
      out.write("\t\t\t\t\t\t<li><span class='theme_red' value=\"red\"></span></li>\r\n");
      out.write("\t\t\t\t\t\t<!-- <li><span class='theme_black' value=\"black\"></span></li> -->\r\n");
      out.write("\t\t\t\t\t\t<li><span class='theme_blue' value=\"blue\"></span></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</span>\r\n");
      out.write("<!-- \t\t\t\t<img class='setIcon12' src=\"imgs/index/set.png\"> -->\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div id=\"scrollDiv_keleyi_com\" class=\"scrollDiv\" style=\"overflow:hidden\"> \r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t\t<li><span class='footer_info' id=\"onlineUserCount\"></span>\r\n");
      out.write("                        </li>\r\n");
      out.write("\t\t\t\t\t\t");

			if(!TeeAuthUtil.getInfoString().equals("")){
				
      out.write("\r\n");
      out.write("\t\t\t\t<li><span class='footer_info'>");
      out.print(TeeAuthUtil.getInfoString() );
      out.write("</span>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t");

			}else{
				
      out.write("\r\n");
      out.write("\t\t\t\t");

					String sp [] = BOTTOM_STATUS_TEXT.split("\n");
					for(int i=0;i<sp.length;i++){
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<li><span class='footer_info'>");
      out.print(sp[i] );
      out.write("</span></li>\r\n");
      out.write("\t\t\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\t\t\t\t\t");

					}
				
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</ul> \r\n");
      out.write("\t\t</div> \r\n");
      out.write("\t\t\t\t<script type=\"text/javascript\"> \r\n");
      out.write("\t\t\t\tfunction AutoScroll(obj){ \r\n");
      out.write("\t\t\t\t$(obj).find(\"ul:first\").animate({ \r\n");
      out.write("\t\t\t\tmarginTop:\"-32px\",background:\"none\"\r\n");
      out.write("\t\t\t\t},500,function(){ \r\n");
      out.write("\t\t\t\t$(this).css({marginTop:\"0px\",background:\"none\"}).find(\"li:first\").appendTo(this); \r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t} \r\n");
      out.write("\t\t\t\t$(document).ready(function(){ \r\n");
      out.write("\t\t\t\tsetInterval('AutoScroll(\"#scrollDiv_keleyi_com\")',5000);\r\n");
      out.write("\t\t\t\t}); \r\n");
      out.write("\t\t\t\t</script> \r\n");
      out.write("\t\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 短消息面板 -->\r\n");
      out.write("\t\t<div class=\"smsbox\" id=\"smsbox\" style=\"display:none\">\r\n");
      out.write("\t\t\t<div class=\"title\">\r\n");
      out.write("\t\t\t<span style=\"float:left;\">消息提醒</span>\r\n");
      out.write("\t\t\t<span class='sms_close_win' style=\"float:right;font-size:16px;cursor:pointer\" onclick=\"$('#smsbox').hide()\">×</span>\r\n");
      out.write("\t\t\t<span style=\"float:right;cursor:pointer;margin-top:3px;background-image:url(imgs/index/read.png);\" class=\"sms_list smsbox_icon2\" onclick=\"smsDetails()\">消息列表</span>\r\n");
      out.write("\t\t\t<span style=\"float:right;cursor:pointer;margin-top:3px;background-image:url(imgs/index/cancel.png);\" class=\"all_check smsbox_icon1\" onclick=\"smsViewAlls()\">全部已阅</span>\r\n");
      out.write("\t\t\t<div style=\"clear:both\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"content\" id=\"smsBoxContent\">\r\n");
      out.write("\t\t\t\t<div class=\"smsbox_loadmore\" id=\"loadMore\">\r\n");
      out.write("\t\t\t\t\t查看更多\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div style=\"right: 5px; bottom: 30px; width: 200px; max-height:500px;overflow-y:auto;overflow-x:hidden; position: absolute;\" id=\"smsInfo\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- 搜索框面板 -->\r\n");
      out.write("\t\t<div class=\"quick_search_div\" style=\"overflow:hidden;\">\r\n");
      out.write("\t\t\t<div class=\"closeBtn\">\r\n");
      out.write("\t\t\t\t<span class=\"searchTitle\">搜索</span>\r\n");
      out.write("\t\t\t\t<span onclick=\"$('.quick_search_div').hide()\">×</span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<iframe src=\"/system/core/base/quicksearch/search_result_1.jsp\" frameborder=\"0\" style=\"height:98%;width:99%\"></iframe>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\ttype:'post',\r\n");
      out.write("\t\turl:\"/bdadmin/getAdminMenu.action\",\r\n");
      out.write("\t\tbeforeSend: function(XMLHttpRequest){\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\tsuccess: function(data, textStatus){\r\n");
      out.write("\t\t\tvar json = JSON.parse(data);\r\n");
      out.write("\t\t\trenderFirstMenu(json);\r\n");
      out.write("\t\t\trenderSecondMenu(json);\r\n");
      out.write("\t\t\tother();\r\n");
      out.write("\t\t\tsetMoreAPP();\r\n");
      out.write("\t\t\t$(\".default\").show();\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\tcomplete: function(XMLHttpRequest, textStatus){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\terror: function(){\r\n");
      out.write("\t\t\t$.MSg.Alert(\"提示\",'获取文件失败！');\r\n");
      out.write("\t\t}\r\n");
      out.write("\t})\r\n");
      out.write("\r\n");
      out.write("\tvar windowWidth = $(window).width();\r\n");
      out.write("\tfunction renderFirstMenu(data){\r\n");
      out.write("\t\tvar str = '';\r\n");
      out.write("\t\tfor(var i =0;i<data.rtData.length;i++){\r\n");
      out.write("\t\tif(data.rtData[i].menuId.length == 3){\r\n");
      out.write("\t\tstr = '<li id=\"menu-lv1-' +data.rtData[i].menuId + '\" class=\"firstMenu fl menu-lv1-' + data.rtData[i].menuId +'\" menuCode=\\\"'+ data.rtData[i].menuCode +'\\\" title=\"'+ data.rtData[i].menuName +'\">' +\r\n");
      out.write("\t\t'<img src=\"imgs/icon/2/' + data.rtData[i].icon + '\">'+\r\n");
      out.write("\t\tdata.rtData[i].menuName +\r\n");
      out.write("\t\t'</li>';\r\n");
      out.write("\t\t$(\"#firstMenuList\").append(str);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t};\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\tfunction renderSecondMenu(data){//具有折叠功能二级菜单\r\n");
      out.write("\t\tvar str2 = '';\r\n");
      out.write("\t\t$(\".default\").hide();\r\n");
      out.write("\t\tfor(var i = 0,l=data.rtData.length;i<l;i++){\r\n");
      out.write("\t\t\tif(data.rtData[i].menuId.length == 6){\r\n");
      out.write("\t\t\t\tvar parentId = data.rtData[i].menuId.substring(0,6);\r\n");
      out.write("\t\t\t\tstr2 = '<li style=\"display:none;\" id=\"menu_2_' + data.rtData[i].menuId +'\" class=\"\" title=\"' + data.rtData[i].menuName + '\">' +\r\n");
      out.write("\t\t\t\t\t\t\t'<a id=\"' + data.rtData[i].menuId + '\" menuCode=\"' + data.rtData[i].menuCode + '\"> ' + '<img class=\"menu_img\" src=\"imgs/icon/2/' + data.rtData[i].icon + '\">' + data.rtData[i].menuName +\r\n");
      out.write("\t\t\t\t\t\t\t'</a>' +\r\n");
      out.write(" \t\t\t\t\t\t\t\t'<ul class=\"thirdMenuList\"' + 'class=\"\" style=\"display:none;\">' +\r\n");
      out.write("\t\t\t\t\t\t\t\t\t'<div class=\"\"' + 'menuCode=\"' + data.rtData[i].menuCode + '\"id = \"thirdMenu' + parentId + '\">'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t'</div>' +\r\n");
      out.write("\t\t\t\t\t\t\t\t'</ul>'+\r\n");
      out.write("\t\t\t\t\t\t'</li>';\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t$(\"#secMenuList\").append(str2);\r\n");
      out.write("\t\t\t}else if(data.rtData[i].menuId.length == 9){\r\n");
      out.write("\t\t\t\tvar parentId = data.rtData[i].menuId.substring(0,6);\r\n");
      out.write("\t\t\t\tvar str3 = \"<p id='menu_3_\" + data.rtData[i].menuId + \"' menuCode='\" + data.rtData[i].menuCode + \"' title='\" + data.rtData[i].menuName + \"'>\" + data.rtData[i].menuName + '</p>';\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t$(\"#thirdMenu\"+parentId).append(str3);\r\n");
      out.write("\t\t\t\tvar $a = $(\"#thirdMenu\"+parentId).parent().siblings(\"a\");\r\n");
      out.write("\t\t\t\tif(!$a.hasClass(\"hasImg\")){\r\n");
      out.write("\t\t\t\t\t$a.append(\"<img class='menu_hide_show' src='imgs/index/hide.png'>\").addClass(\"hasImg\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\tvar menuHead = '<div class=\"menuHead\"><p style=\"cursor:pointer;\" class=\"setHead\"><img src=\"imgs/index/xialasanjiao.png\"><span></span></p></div>'\r\n");
      out.write("\t\t$(\"#secMenuList .settingContent\").after(menuHead);\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t\tfunction other(){\r\n");
      out.write("\r\n");
      out.write("\t\t\t//一级菜单的点击绑定\r\n");
      out.write("\t\t\t$(\"#firstMenuList li\").on(\"click\",function(){\r\n");
      out.write("\t\t\t\t$(\".default\").hide();\r\n");
      out.write("\t\t\t\t$(\".settingContent\").hide();\r\n");
      out.write("\t\t\t\tvar menuCode = $(this).attr(\"menuCode\");\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tif(menuCode!='' && menuCode!=\"undefined\" && menuCode!=undefined){\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t$(\"#mainIframe\").attr(\"src\",menuCode);\r\n");
      out.write("\t\t\t\t\t$(\".menuHead p span\").text($(this).text());\r\n");
      out.write("\t\t\t\t\t$(\"#secMenuList>li\").hide();\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\tvar first_id = $(this).attr(\"id\").substring(9,12);\r\n");
      out.write("\t\t\t\t\tfor(var i=0,l=$(\"#secMenuList>li\").length;i<l;i++){\r\n");
      out.write("\t\t\t\t\tvar second_id = $($(\"#secMenuList>li\")[i]).attr(\"id\").substring(7,10);\r\n");
      out.write("\t\t\t\t\tif(first_id==second_id){\r\n");
      out.write("\t\t\t\t\t$(\".menuHead\").show();\r\n");
      out.write("\t\t\t\t\t$(\".menuHead p span\").text($(this).text());\r\n");
      out.write("\t\t\t\t\t$($(\"#secMenuList>li\")[i]).show();\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t$($(\"#secMenuList>li\")[i]).hide();\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t//点击主页\r\n");
      out.write("\t\t\t$(\".home\").on(\"click\",function(){\r\n");
      out.write("\t\t\t\t$(\".default\").show();\r\n");
      out.write("\t\t\t\t$(\".menuHead\").hide();\r\n");
      out.write("\t\t\t\t$(\".settingContent\").hide();\r\n");
      out.write("\t\t\t\t$(\"#secMenuList>li\").hide();\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t//点击设置\r\n");
      out.write("\t\t\t$(\".setIcon\").on(\"click\",function(){\r\n");
      out.write("\t\t\t\t$(\".default\").hide();\r\n");
      out.write("\t\t\t\t$(\".menuHead\").hide();\r\n");
      out.write("\t\t\t\t$(\"#secMenuList>li\").hide();\r\n");
      out.write("\t\t\t\t$(\".settingContent\").show();\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t//设置页面的折叠功能\r\n");
      out.write("\t\t\t$(\".defaultContent>li\").on(\"click\",function(){\r\n");
      out.write("\t\t\t\t$(this).find(\".setContent_ul\").slideToggle(100);\r\n");
      out.write("\t\t\t\tif(!$(this).hasClass(\"slideDown\")){\r\n");
      out.write("\t\t\t\t\t\t$(this).find(\".menu_hide_show\").attr(\"src\",\"imgs/index/show.png\");\r\n");
      out.write("\t\t\t\t\t\t$(this).addClass(\"slideDown\");\r\n");
      out.write("\t\t\t\t\t\t$(\".settingContent .defaultContent .slideDown\").css(\"padding-left\",\"0px!important\")\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t$(this).find(\".menu_hide_show\").attr(\"src\",\"imgs/index/hide.png\");\r\n");
      out.write("\t\t\t\t\t\t$(this).removeClass(\"slideDown\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t$(\".setContent_ul\").on(\"click\",function(e){\r\n");
      out.write("\t\t\t\te.stopPropagation();\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t//二级菜单的点击折叠\r\n");
      out.write("\t\t\t$('#secMenuList>li').on('click',function(){\r\n");
      out.write("\t\t\t\tif($(this).find(\".menu_hide_show\").length!=0){\r\n");
      out.write("\t\t\t\t\t$(this).find('.thirdMenuList').slideToggle(100);\r\n");
      out.write("\t\t\t\t\tif(!$(this).hasClass(\"slideDown\")){\r\n");
      out.write("\t\t\t\t\t\t$(this).find(\".menu_hide_show\").attr(\"src\",\"imgs/index/show.png\");\r\n");
      out.write("\t\t\t\t\t\t$(this).addClass(\"slideDown\");\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t$(this).find(\".menu_hide_show\").attr(\"src\",\"imgs/index/hide.png\");\r\n");
      out.write("\t\t\t\t\t\t$(this).removeClass(\"slideDown\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t//阻止下拉菜单中的点击冒泡\r\n");
      out.write("\t\t\t$(\".thirdMenuList,.setContent_ul\").on(\"click\",function(e){\r\n");
      out.write("\t\t\t\te.stopPropagation();\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t//桌面互换点击事件\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"body\").on(\"click\",\"#desktopDiv li\",function(){\r\n");
      out.write("\t\t\t\tvar skin = getCookie(\"skinChange\");\r\n");
      out.write("\t\t\t\tif(skin == \"blue\"||skin==\"\"||skin==null){\r\n");
      out.write("\t\t\t\t\t$(\".thirdMenuList p\").removeClass(\"menu_active_blue\");\r\n");
      out.write("\t\t\t\t\t$(\"#secMenuList li\").removeClass(\"menu_active_blue\");\r\n");
      out.write("\t\t\t\t\t$(this).addClass(\"menu_active_blue\");\r\n");
      out.write("\t\t\t\t}else if(skin == \"red\"){\r\n");
      out.write("\t\t\t\t\t$(\".thirdMenuList p\").removeClass(\"menu_active_red\");\r\n");
      out.write("\t\t\t\t\t$(\"#secMenuList li\").removeClass(\"menu_active_red\");\r\n");
      out.write("\t\t\t\t\t$(this).addClass(\"menu_active_red\");\r\n");
      out.write("\t\t\t\t};\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t//二级三级菜单绑定事件切换iframe\r\n");
      out.write("\t\t\t$(\"#secMenuList li\").on(\"click\",function(){\r\n");
      out.write("\t\t\t\tif($(this).find(\"a\").attr(\"menucode\")!=\"\" && $(this).find(\"a\").attr(\"menucode\")!=\"undefined\" && $(this).find(\"a\").attr(\"menucode\")!=undefined){\r\n");
      out.write("\t\t\t\t\tvar src = $(this).find(\"a\").attr(\"menuCode\");\r\n");
      out.write("\t\t\t\t\t$(\"#mainIframe\").attr(\"src\",src);\r\n");
      out.write("\t\t\t\t\tvar skin = getCookie(\"skinChange\");\r\n");
      out.write("\t\t\t\t\tif(skin == \"blue\"||skin==\"\"||skin==null){\r\n");
      out.write("\t\t\t\t\t\t$(\".thirdMenuList p\").removeClass(\"menu_active_blue\");\r\n");
      out.write("\t\t\t\t\t\t$(\"#secMenuList li\").removeClass(\"menu_active_blue\");\r\n");
      out.write("\t\t\t\t\t}else if(skin == \"red\"){\r\n");
      out.write("\t\t\t\t\t\t$(\".thirdMenuList p\").removeClass(\"menu_active_red\");\r\n");
      out.write("\t\t\t\t\t\t$(\"#secMenuList li\").removeClass(\"menu_active_red\");\r\n");
      out.write("\t\t\t\t\t};\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tif($(this).find(\".menu_hide_show\").length==0){\r\n");
      out.write("\t\t\t\t\t\t//$(this).addClass(\"menu_active\");\r\n");
      out.write("\t\t\t\t\t\tif(skin == \"blue\"||skin==\"\"||skin==null){\r\n");
      out.write("\t\t\t\t\t\t\t$(this).addClass(\"menu_active_blue\");\r\n");
      out.write("\t\t\t\t\t\t\t$(this).addClass(\"menu_active_blue\");\r\n");
      out.write("\t\t\t\t\t\t}else if(skin == \"red\"){\r\n");
      out.write("\t\t\t\t\t\t\t$(this).addClass(\"menu_active_red\");\r\n");
      out.write("\t\t\t\t\t\t\t$(this).addClass(\"menu_active_red\");\r\n");
      out.write("\t\t\t\t\t\t};\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t\t$(\".thirdMenuList p\").on(\"click\",function(){\r\n");
      out.write("\t\t\t\tvar skin = getCookie(\"skinChange\");\r\n");
      out.write("\t\t\t\tif($(this).attr(\"menucode\")!=\"\"){\r\n");
      out.write("\t\t\t\t\tvar src = $(this).attr(\"menuCode\");\r\n");
      out.write("\t\t\t\t\t$(\"#mainIframe\").attr(\"src\",src);\r\n");
      out.write("\t\t\t\t\tif(skin == \"blue\"||skin==\"\"||skin==null){\r\n");
      out.write("\t\t\t\t\t\t$(\"#secMenuList li\").removeClass(\"menu_active_blue\");\r\n");
      out.write("\t\t\t\t\t\t$(\".thirdMenuList p\").removeClass(\"menu_active_blue\");\r\n");
      out.write("\t\t\t\t\t}else if(skin == \"red\"){\r\n");
      out.write("\t\t\t\t\t\t$(\"#secMenuList li\").removeClass(\"menu_active_red\");\r\n");
      out.write("\t\t\t\t\t\t$(\".thirdMenuList p\").removeClass(\"menu_active_red\");\r\n");
      out.write("\t\t\t\t\t};\r\n");
      out.write("\t\t\t\t\tif(skin == \"blue\"||skin==\"\"||skin==null){\r\n");
      out.write("\t\t\t\t\t\t$(this).addClass(\"menu_active_blue\");\r\n");
      out.write("\t\t\t\t\t}else if(skin == \"red\"){\r\n");
      out.write("\t\t\t\t\t\t$(this).addClass(\"menu_active_red\");\r\n");
      out.write("\t\t\t\t\t};\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t//$(\".thirdMenuList p\").removeClass(\"menu_active\");\r\n");
      out.write("\t\t\t\t\t//$(\"#secMenuList li\").removeClass(\"menu_active\");\r\n");
      out.write("\t\t\t\t\t//$(this).addClass(\"menu_active\");\r\n");
      out.write("\t\t\t\t};\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\t//设置一级菜单自适应显示\r\n");
      out.write("\t\tvar win_width = $(window).width();\r\n");
      out.write("\t\t$(\".firstMenuContent\").width(win_width-650);\r\n");
      out.write("\t\t$(window).resize(function(){\r\n");
      out.write("\t\t\tvar win_width = $(window).width();\r\n");
      out.write("\t\t\t$(\".firstMenuContent\").width(win_width-650);\r\n");
      out.write("\t\t\tsetMoreAPP();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t//更多按钮\r\n");
      out.write("\t\tfunction setMoreAPP(){\r\n");
      out.write("\t\t\t$(\".moreAppcContent\").html(\"\");\r\n");
      out.write("\t\t\tvar f_li = $(\"#firstMenuList li\")\r\n");
      out.write("\t\t\tvar le = f_li.length;\r\n");
      out.write("\t\t\tfor(var i=0;i<le;i++){\r\n");
      out.write("\t\t\t\tvar offset_top = $(f_li[i]).offset().top;\r\n");
      out.write("\t\t\t\tif(offset_top != 0){\r\n");
      out.write("\t\t\t\t\tvar li_copy = $(f_li[i]).clone();\r\n");
      out.write("\t\t\t\t\t// console.log(li_copy);\r\n");
      out.write("\t\t\t\t\tvar img_src = $(li_copy).find(\"img\").attr(\"src\");\r\n");
      out.write("\t\t\t\t\tvar img_name = img_src.substring(12);\r\n");
      out.write("\t\t\t\t\tvar newName = \"imgs/icon/1/\" + img_name;\r\n");
      out.write("\t\t\t\t\t// img_src.replace(\"2\",\"1\");\r\n");
      out.write("\t\t\t\t\t$(li_copy).find(\"img\").attr(\"src\",newName);\r\n");
      out.write("\t\t\t\t\tif(li_copy.length!=0){\r\n");
      out.write("\t\t\t\t\t\t$(li_copy).remove();\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t$(\".moreAppcContent\").append(li_copy);\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\tvar className = $(f_li[i]).attr(\"class\");\r\n");
      out.write("\t\t\t\t\tvar arr = className.split(\" \");\r\n");
      out.write("\t\t\t\t\tfor(var j=0,l=arr.length;j<l;j++){\r\n");
      out.write("\t\t\t\t\t\tvar s_0_8 = arr[j].substring(0,8);\r\n");
      out.write("\t\t\t\t\t\tif(s_0_8 == \"menu-lv1\"){\r\n");
      out.write("\t\t\t\t\t\t\tclassName = arr[j];\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t$(\".moreAppcContent .\"+className).remove();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t$(\".moreApp\").on(\"click\",function(event){\r\n");
      out.write("\t\t\tevent.stopPropagation();\r\n");
      out.write("\t\t\t$(\".moreAppcContent\").slideToggle(100);\r\n");
      out.write("\t\t\tsetMoreAPP();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(\".header\").on(\"click\",function(){\r\n");
      out.write("\t\t\t$(\".moreAppcContent\").slideUp(100);\r\n");
      out.write("\t\t\t$(\"#groupContent\").animate({right:\"-240px\"},300);\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(\".secLeft\").on(\"click\",function(){\r\n");
      out.write("\t\t\t$(\".moreAppcContent\").slideUp(100);\r\n");
      out.write("\t\t\t$(\"#groupContent\").animate({right:\"-240px\"},300);\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(\".moreApp\").on(\"click\",\".moreAppcContent li\",function(){\r\n");
      out.write("\t\t\t$(\".default\").hide();\r\n");
      out.write("\t\t\t$(\".settingContent\").hide();\r\n");
      out.write("\t\t\tvar menuCode = $(this).attr(\"menuCode\");\r\n");
      out.write("\t\t\t/*检查一级目录是否有menuCode*/\r\n");
      out.write("\t\t\tif(menuCode!='' && menuCode!=undefined && menuCode!='undefined'){\r\n");
      out.write("\t\t\t\t$(\"#mainIframe\").attr(\"src\",menuCode);\r\n");
      out.write("\t\t\t\t$(\".menuHead p span\").text($(this).text());\r\n");
      out.write("\t\t\t\t$(\".section .menuHead\").show();\r\n");
      out.write("\t\t\t\t$(\"#secMenuList>li\").hide();\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\tvar first_id = $(this).attr(\"id\").substring(9,12);\r\n");
      out.write("\t\t\t\tfor(var i=0,l=$(\"#secMenuList>li\").length;i<l;i++){\r\n");
      out.write("\t\t\t\tvar second_id = $($(\"#secMenuList>li\")[i]).attr(\"id\").substring(7,10);\r\n");
      out.write("\t\t\t\tif(first_id==second_id){\r\n");
      out.write("\t\t\t\t$(\".menuHead\").show();\r\n");
      out.write("\t\t\t\t$(\".menuHead p span\").text($(this).text());\r\n");
      out.write("\t\t\t\t$($(\"#secMenuList>li\")[i]).show();\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t$($(\"#secMenuList>li\")[i]).hide();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t//抖动功能\r\n");
      out.write("\t\tfunction shake(id){\r\n");
      out.write("\t\t    var $panel = $(\"#\"+id);\r\n");
      out.write("\t\t    $panel.css({'position':'relative'});\r\n");
      out.write("\t\t    for(var i=1; i<=4; i++){\r\n");
      out.write("\t\t        $panel.animate({left:5},30);\r\n");
      out.write("\t\t        $panel.animate({right:5},30);\r\n");
      out.write("\t\t        $panel.animate({left:0},30);\r\n");
      out.write("\t\t    }\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\t//登记登出\r\n");
      out.write("\t\t$(\".sign_img\").on(\"click\",function(){\r\n");
      out.write("\t\t\t$(\".signin_out\").slideToggle(50);\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(\".signin_out\").on(\"mouseleave\",function(){\r\n");
      out.write("\t\t\t$(\".signin_out\").slideToggle(50);\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t//消息提醒\r\n");
      out.write("\t\tvar tip_zhezhao = \"<div class='tip_zhezhao' style='width:100%;height:100%;z-index: 9999;position: fixed;filter:Alpha(opacity=60);background-color: #000;top: 0;left: 0;opacity: 0.6;'></div>\";\r\n");
      out.write("\t\t$(\"#tip_alert\").on(\"click\",function(){\r\n");
      out.write("\t\t\t$(\"body\").append(tip_zhezhao);\r\n");
      out.write("\t\t\t$(\".smsbox\").fadeIn(200);\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(\"body\").on(\"click\",\".sms_close_win,.sms_list,.all_check\",function(){\r\n");
      out.write("\t\t\t$(\".tip_zhezhao\").remove();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t//皮肤切换\r\n");
      out.write("\t\t$(\".themeIcon\").click(function(){\r\n");
      out.write("\t\t\t$(\".themeList\").slideToggle(100);\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(\".themeList\").mouseleave(function(){\r\n");
      out.write("\t\t\t$(this).hide();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(\".themeList li\").click(function(){\r\n");
      out.write("\t\t\tvar skinColor = $(this).find(\"span\").attr(\"value\");\r\n");
      out.write("\t\t\tswitch(skinColor){\r\n");
      out.write("\t\t\t\tcase \"red\":\r\n");
      out.write("\t\t\t\t\t$(\".header\").css(\"background-color\",\"#e87676\");\r\n");
      out.write("\t\t\t\t\t$(\".section .secLeft .avatar\").css(\"background-color\",\"#a33b3c\");\r\n");
      out.write("\t\t\t\t\t$(\".section .secLeft\").css(\"background-color\",\"#713e3d\");\r\n");
      out.write("\t\t\t\t\t$(\".section .default\").css(\"background-color\",\"#713e3d\");\r\n");
      out.write("\t\t\t\t\t$(\".currentIdentity\").css(\"background-color\",\"#be6464\");\r\n");
      out.write("\t\t\t\t\t$(\".footer_info\").css(\"background-color\",\"#eb4849\");\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t$(\".menu_active_blue\").addClass(\"menu_active_red\");\r\n");
      out.write("\t\t\t\t\t$(\".thirdMenuList p\").removeClass(\"menu_active_blue\");\r\n");
      out.write("\t\t\t\t\t$(\"#secMenuList li\").removeClass(\"menu_active_blue\");\r\n");
      out.write("\t\t\t\t\tsetCookie(\"skinChange\" , \"red\" , 365);\r\n");
      out.write("\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\tcase \"blue\":\r\n");
      out.write("\t\t\t\t\t$(\".header\").css(\"background-color\",\"#0099cb\");\r\n");
      out.write("\t\t\t\t\t$(\".section .secLeft .avatar\").css(\"background-color\",\"#014876\");\r\n");
      out.write("\t\t\t\t\t$(\".section .secLeft\").css(\"background-color\",\"#192f47\");\r\n");
      out.write("\t\t\t\t\t$(\".section .default\").css(\"background-color\",\"#192f47\");\r\n");
      out.write("\t\t\t\t\t$(\".currentIdentity\").css(\"background-color\",\"#496290\");\r\n");
      out.write("\t\t\t\t\t$(\".footer_info\").css(\"background-color\",\"#2285c6\");\r\n");
      out.write("\t\t\t\t\t$(\".menu_active_red\").addClass(\"menu_active_blue\");\r\n");
      out.write("\t\t\t\t\t$(\".thirdMenuList p\").removeClass(\"menu_active_red\");\r\n");
      out.write("\t\t\t\t\t$(\"#secMenuList li\").removeClass(\"menu_active_red\");\r\n");
      out.write("\t\t\t\t\tsetCookie(\"skinChange\" , \"blue\" , 365);\r\n");
      out.write("\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//菜单鼠标移入上滑\r\n");
      out.write("\t\t$(\"body\").on(\"mouseover\",\"#firstMenuList li\",function(){\r\n");
      out.write("\t\t\tvar top = $(\".firstMenu\").offset().top;\r\n");
      out.write("\t\t\t//console.log(top);\r\n");
      out.write("\t\t\t$(this).css(\"position\",\"relative\");\r\n");
      out.write("\t\t\t$(this).stop().animate({top:\"-3px\"},100);\r\n");
      out.write("\t\t\t//console.log(top);\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(\"body\").on(\"mouseleave\",\"#firstMenuList li\",function(){\r\n");
      out.write("\t\t\t$(this).css(\"position\",\"relative\");\r\n");
      out.write("\t\t\tvar top = $(this).offset().top;\r\n");
      out.write("\t\t\t$(this).stop().animate({top:\"0px\"},100);\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//组织架构显示\r\n");
      out.write("\t\t$(\"body\").on(\"click\",\".group\",function(){\r\n");
      out.write("\t\t\tif($(\"#groupContent\").css(\"right\")==\"0px\"){\r\n");
      out.write("\t\t\t\t$(\"#groupContent\").animate({right:\"-240px\"},300);\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\t$(\"#groupContent\").animate({right:\"0px\"},300);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t});\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("        //控制面板界面跳转\r\n");
      out.write("\t\tfunction changePage(sel){\r\n");
      out.write("\t\t\tif(sel==1){\r\n");
      out.write("\t\t\t\t$(\"#mainIframe\").attr(\"src\",contextPath+\"/system/core/person/setdescktop/desktop.jsp\");//界面主题\r\n");
      out.write("\t\t\t}else if(sel==2){\r\n");
      out.write("\t\t\t\t$(\"#mainIframe\").attr(\"src\",contextPath+\"/system/core/fav/manage.jsp\");//收藏夹\r\n");
      out.write("\t\t\t}else if(sel==3){\r\n");
      out.write("\t\t\t\t$(\"#mainIframe\").attr(\"src\",contextPath+\"/system/core/person/setdescktop/desktopSetting.jsp\");//桌面空间\r\n");
      out.write("\t\t\t}else if(sel==4){\r\n");
      out.write("\t\t\t\t$(\"#mainIframe\").attr(\"src\",contextPath+\"/system/core/person/setdescktop/info.jsp\");//个人资料\r\n");
      out.write("\t\t\t}else if(sel==5){\r\n");
      out.write("\t\t\t\t$(\"#mainIframe\").attr(\"src\",contextPath+\"/system/core/person/setdescktop/avatar.jsp\");//昵称与头像\r\n");
      out.write("\t\t\t}else if(sel==6){\r\n");
      out.write("\t\t\t\t$(\"#mainIframe\").attr(\"src\",contextPath+\"/system/core/dept/usergroup/personalgroup.jsp\");//自定义用户组\r\n");
      out.write("\t\t\t}else if(sel==7){\r\n");
      out.write("\t\t\t\t$(\"#mainIframe\").attr(\"src\",contextPath+\"/system/core/person/setdescktop/updateSealPwd.jsp\");//印章密码修改\r\n");
      out.write("\t\t\t}else if(sel==8){\r\n");
      out.write("\t\t\t\t$(\"#mainIframe\").attr(\"src\",contextPath+\"/system/core/person/commonword/list.jsp\");//常用语维护\r\n");
      out.write("\t\t\t}else if(sel==9){\r\n");
      out.write("\t\t\t\t$(\"#mainIframe\").attr(\"src\",contextPath+\"/system/core/person/setdescktop/mypriv.jsp\");//我的账户\r\n");
      out.write("\t\t\t}else if(sel==10){\r\n");
      out.write("\t\t\t\t$(\"#mainIframe\").attr(\"src\",contextPath+\"/system/core/person/setdescktop/password.jsp\");//修改密码\r\n");
      out.write("\t\t\t}else if(sel==11){\r\n");
      out.write("\t\t\t\t$(\"#mainIframe\").attr(\"src\",contextPath+\"/system/core/person/setdescktop/securitylog.jsp\");//安全日志\r\n");
      out.write("\t\t\t}else if(sel==12){\r\n");
      out.write("\t\t\t\t$(\"#mainIframe\").attr(\"src\",contextPath+\"/system/frame/default/mainForSimple.jsp\");//首页--个人门户\r\n");
      out.write("\t\t\t}else if(sel==13){\r\n");
      out.write("\t\t\t\t$(\"#mainIframe\").attr(\"src\",contextPath+\"/system/core/person/setdescktop/updatePicSealPwd.jsp\");//签章密码修改\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\tsetCookie(\"skinChange\" , \"blue\" , 365);\r\n");
      out.write("\t\tsetCookie(\"skin_new\" , \"1\" , 365);\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else log(t.getMessage(), t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
