package org.apache.jsp.system.frame.classic;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import com.tianee.oa.oaconst.TeeConst;
import com.tianee.oa.core.org.bean.TeePerson;
import com.tianee.webframe.util.global.TeeSysProps;
import com.tianee.webframe.util.date.TeeLunarCalendarUtils;
import com.tianee.webframe.util.str.TeeStringUtil;
import com.tianee.webframe.util.global.TeeSysCustomerProps;
import com.tianee.oa.core.org.bean.TeeUserRole;
import com.tianee.oa.core.org.bean.TeeDepartment;
import com.tianee.oa.oaconst.TeeConst;
import com.tianee.webframe.util.date.TeeDateUtil;
import com.tianee.oa.core.org.bean.TeePerson;
import com.tianee.oa.core.org.service.TeePersonService;
import java.util.Date;
import com.tianee.webframe.util.date.TeeDateUtil;
import com.tianee.webframe.util.str.TeeUtility;
import com.tianee.webframe.util.str.TeeStringUtil;
import com.tianee.oa.oaconst.TeeConst;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  static {
    _jspx_dependants = new java.util.ArrayList(1);
    _jspx_dependants.add("/header/userheader.jsp");
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    String contextPath = request.getContextPath();
    String basePath = request.getScheme() + "://" + request.getServerName() + ":" + request.getServerPort()
            + contextPath + "/";
    //获取主题的索引号
    int styleIndex = 1;
    Integer styleInSession = (Integer) request.getSession().getAttribute("STYLE_TYPE_INDEX");
    if (styleInSession != null) {
        styleIndex = styleInSession;
    }
    String stylePath = contextPath + "/common/styles";
    String imgPath = stylePath + "/style" + styleIndex + "/img";
    String cssPath = stylePath + "/style" + styleIndex + "/css";
    String systemImagePath = contextPath+"/common/images";
    
    //第二套风格
    int STYLE_TYPE_INDEX_2 = TeeStringUtil.getInteger( request.getSession().getAttribute("STYLE_TYPE_INDEX_2"), 1);
    String cssPathSecond = contextPath + "/system/frame/2/styles/style" + STYLE_TYPE_INDEX_2 + "/css";
    String imgPathSecond = contextPath + "/system/frame/2/styles/style" + STYLE_TYPE_INDEX_2 + "/img";
    
    
    String loginOutText = TeeSysProps.getString("LOGIN_OUT_TEXT");
    String ieTitle = TeeSysProps.getString("IE_TITLE");
    String secUserMem = (String) request.getSession().getAttribute("SEC_USER_MEM") == null ? "" : (String) request.getSession().getAttribute("SEC_USER_MEM");//是否记忆用户名
    
    //单点跳转参数
    String tzcs=(String) request.getSession().getAttribute("cuo");
    String outUrl=TeeSysCustomerProps.getString("MHLJ");
    
    
    //菜单权限   所属的应用系统
    int sysId=TeeStringUtil.getInteger(request.getParameter("sysId"),0);    

      out.write("\r\n");
      out.write("<!DOCTYPE html >\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=Edge\">\r\n");
      out.write("<title>行政复议工作平台</title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	TeePerson person = (TeePerson)request.getSession().getAttribute(TeeConst.LOGIN_USER);
	boolean isAdminPriv = TeePersonService.checkIsAdminPriv(person);
	boolean isSuperAdmin = TeePersonService.checkIsSuperAdmin(person,"");
	String isAdmin = person.getIsAdmin();
    
	Date date = person.getLastPassTime();
	String lastPassTime = "";
	if(date != null){
		lastPassTime = TeeDateUtil.getDateTimeStr(date);
	}
	int loginPersonId = person.getUuid();
	
	
	
	
	String SEC_INIT_PASS = (String) request.getSession().getAttribute("SEC_INIT_PASS") == null ? "0" : (String) request.getSession().getAttribute("SEC_INIT_PASS");//初始密码
	String SEC_PASS_FLAG = TeeStringUtil.getString( (String) request.getSession().getAttribute("SEC_PASS_FLAG"), "0");//是否过期
	String SEC_PASS_TIME = TeeStringUtil.getString((String) request.getSession().getAttribute("SEC_PASS_TIME"), "0");//过期时间
	String SEC_SHOW_IP = TeeStringUtil.getString((String) request.getSession().getAttribute("SEC_SHOW_IP"), "0");//是否显示IP
	String SEC_ON_STATUS = TeeStringUtil.getString((String) request.getSession().getAttribute("SEC_ON_STATUS"), "0");//记录在线状态
	
	int AVATAR_UPLOAD = TeeStringUtil.getInteger(request.getSession().getAttribute("AVATAR_UPLOAD"), 0 );//是否允许上传图象
	int AVATAR_WIDTH =  TeeStringUtil.getInteger(request.getSession().getAttribute("AVATAR_WIDTH"), 0 );//图象宽度
	int  AVATAR_HEIGHT = TeeStringUtil.getInteger(request.getSession().getAttribute("AVATAR_HEIGHT"),0);//图象高度
  
	String userName = person.getUserName();
	String userId = person.getUserId();
	int userSid = person.getUuid();
	TeeDepartment dept = person.getDept();
	String currUserDeptName  = "";
	String currUserRoleName = "";
	TeeUserRole role = person.getUserRole();
	if(dept != null){
		currUserDeptName = dept.getDeptName();
	}
	if(role != null){
		currUserRoleName = role.getRoleName();
	}
	String avatar = person.getAvatar();
	//用于判断用户性别
	String avatar_default = "";
	if(("0".equals(person.getSex())) && TeeUtility.isNullorEmpty(person.getAvatar())){
		avatar_default = "0";  //0代表男
	}else if(("1".equals(person.getSex())) && TeeUtility.isNullorEmpty(person.getAvatar())){
		avatar_default = "1";  //1代表女
	}

      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("/** 变量定义 **/\r\n");
      out.write("var isAdminPriv = '");
      out.print(isAdminPriv);
      out.write("';\r\n");
      out.write("var isSuperAdmin = '");
      out.print(isSuperAdmin);
      out.write("';\r\n");
      out.write("var loginPersonId = ");
      out.print(loginPersonId);
      out.write(";\r\n");
      out.write("var lastPassTime = '");
      out.print(lastPassTime);
      out.write("';\r\n");
      out.write("\r\n");
      out.write("var SEC_SHOW_IP =  '");
      out.print(SEC_SHOW_IP);
      out.write("';\r\n");
      out.write("var SEC_ON_STATUS =  '");
      out.print(SEC_ON_STATUS);
      out.write("';\r\n");
      out.write("var AVATAR_UPLOAD =  '");
      out.print(AVATAR_UPLOAD);
      out.write("';\r\n");
      out.write("var AVATAR_WIDTH =  '");
      out.print(AVATAR_WIDTH);
      out.write("';\r\n");
      out.write("var AVATAR_HEIGHT =  '");
      out.print(AVATAR_HEIGHT);
      out.write("';\r\n");
      out.write("var userId = \"");
      out.print(userId);
      out.write("\";\r\n");
      out.write("var userName = \"");
      out.print(userName);
      out.write("\";\r\n");
      out.write("var avatar = \"");
      out.print(avatar);
      out.write("\";\r\n");
      out.write("var avatar_default = \"");
      out.print(avatar_default);
      out.write("\";\r\n");
      out.write("</script>");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/one.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/reset.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- 其他工具库类 -->\r\n");
      out.write("<script src=\"");
      out.print(contextPath );
      out.write("/common/zt_webframe/js/jquery-1.11.1.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(contextPath );
      out.write("/common/js/tools.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(contextPath );
      out.write("/common/js/sys2.0.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(contextPath );
      out.write("/common/js/sysUtil.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(contextPath );
      out.write("/common/js/src/orgselect.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(contextPath);
      out.write("/common/js/easyuiTools.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(contextPath );
      out.write("/common/zt_webframe/js/package.js\"></script>\r\n");
      out.write("<script src=\"js/divscroll.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" >\r\n");
      out.write("window.UEDITOR_HOME_URL = \"");
      out.print(contextPath);
      out.write("/common/ueditor/\";\r\n");
      out.write("$.browser = {};\r\n");
      out.write("$.browser.mozilla = /firefox/.test(navigator.userAgent.toLowerCase());\r\n");
      out.write("$.browser.webkit = /webkit/.test(navigator.userAgent.toLowerCase());\r\n");
      out.write("$.browser.opera = /opera/.test(navigator.userAgent.toLowerCase());\r\n");
      out.write("$.browser.msie = /msie/.test(navigator.userAgent.toLowerCase());\r\n");
      out.write("//var params;\r\n");
      out.write("</script>\r\n");
      out.write("<!-- 图片预览器 -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(contextPath);
      out.write("/common/js/lazyloader.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/index.css?v=1\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/common/zt_webframe/css/package1.css\">\r\n");
      out.write(" <script type=\"text/javascript\" src=\"");
      out.print(contextPath);
      out.write("/system/frame/3/js/jquery.SuperSlide.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(contextPath);
      out.write("/system/frame/4/js/index2.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(contextPath);
      out.write("/system/frame/2/js/index.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(contextPath);
      out.write("/system/frame/2/js/sms.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(contextPath);
      out.write("/common/jbox-v2.3/jBox/jquery.jBox-2.3.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(contextPath);
      out.write("/common/jbox-v2.3/jBox/i18n/jquery.jBox-zh-CN.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(contextPath);
      out.write("/system/frame/3/js/tabs.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/common/font-awesome/css/font-awesome.min.css\" />\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("var loginUserRoleId=0;\r\n");
      out.write("var  sysId=");
      out.print(sysId );
      out.write(";\r\n");
      out.write("/** 常量定义 **/\r\n");
      out.write("var TDJSCONST = {\r\n");
      out.write("  YES: 1,\r\n");
      out.write("  NO: 0\r\n");
      out.write("};\r\n");
      out.write("/** 变量定义 **/\r\n");
      out.write("var contextPath = \"");
      out.print(contextPath );
      out.write("\";\r\n");
      out.write("var imgPath = \"");
      out.print(imgPath );
      out.write("\";\r\n");
      out.write("var cssPath = \"");
      out.print(cssPath);
      out.write("\";\r\n");
      out.write("var stylePath = \"");
      out.print(stylePath);
      out.write("\";\r\n");
      out.write("var cssPathSecond = \"");
      out.print(cssPathSecond);
      out.write("\";\r\n");
      out.write("var imgPathSecond = \"");
      out.print(imgPathSecond);
      out.write("\";\r\n");
      out.write("var loginOutText = \"");
      out.print(loginOutText);
      out.write("\";\r\n");
      out.write("var uploadFlashUrl = \"");
      out.print(contextPath );
      out.write("/common/swfupload/swfupload.swf\";\r\n");
      out.write("var commonUploadUrl = \"");
      out.print(contextPath );
      out.write("/attachmentController/commonUpload.action\";\r\n");
      out.write("var systemImagePath = \"");
      out.print(systemImagePath);
      out.write("\";\r\n");
      out.write("var xparent;\r\n");
      out.write("var tzcs=\"");
      out.print(tzcs);
      out.write("\";\r\n");
      out.write("var outUrl=\"");
      out.print(outUrl);
      out.write("\";\r\n");
      out.write("var defultSysId = 5021;\r\n");
      out.write("if(window.dialogArguments){\r\n");
      out.write("    xparent = window.dialogArguments;\r\n");
      out.write("}else if(window.opener){\r\n");
      out.write("    xparent = opener;\r\n");
      out.write("}else{\r\n");
      out.write("    xparent = window;\r\n");
      out.write("}\r\n");
      out.write("function parseNumber(value, defValue) {\r\n");
      out.write("  if (isNaN(value)) {\r\n");
      out.write("    return defValue;\r\n");
      out.write("  }\r\n");
      out.write("  return value * 1;\r\n");
      out.write("}\r\n");
      out.write("/**\r\n");
      out.write("*\r\n");
      out.write("*注销\r\n");
      out.write("*/\r\n");
      out.write("function doLogout(){\r\n");
      out.write("    var msg = loginOutText + \"\\n确定要注销吗?\";\r\n");
      out.write("    $.MsgBox.Confirm(\"提示\",msg,function(){\r\n");
      out.write("        var url = contextPath + \"/systemAction/doLoginout.action\";\r\n");
      out.write("        var para = {};\r\n");
      out.write("        var jsonObj = tools.requestJsonRs(url,para);\r\n");
      out.write("        if(jsonObj){\r\n");
      out.write("            var json = jsonObj.rtData;\r\n");
      out.write("        }else{\r\n");
      out.write("            $.MsgBox.Alert(\"提示\", jsonObj.rtMsg);\r\n");
      out.write("        }\r\n");
      out.write("        window.location.href =contextPath+\"/login.jsp\";\r\n");
      out.write("});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function closeLogin(){\r\n");
      out.write("    var msg = loginOutText + \"\\n确定要退出吗?\";\r\n");
      out.write("    $.MsgBox.Confirm(\"提示\",msg,function(){\r\n");
      out.write("        var url = contextPath + \"/systemAction/doLoginout.action\";\r\n");
      out.write("        var para = {};\r\n");
      out.write("        var jsonObj = tools.requestJsonRs(url,para);\r\n");
      out.write("        if(jsonObj){\r\n");
      out.write("            var json = jsonObj.rtData;\r\n");
      out.write("        }else{\r\n");
      out.write("            $.MsgBox.Alert(\"提示\", jsonObj.rtMsg);\r\n");
      out.write("        }\r\n");
      out.write("        window.location.href =contextPath+\"/login.jsp\";\r\n");
      out.write("});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function remindCheck(){\r\n");
      out.write("    tools.requestJsonRs(contextPath+\"/sms/remindCheck.action\",{},true,function(json){\r\n");
      out.write("        if(json.rtState){\r\n");
      out.write("            if(json.rtData.smsFlag!=0){//弹出短消息\r\n");
      out.write("                msgFrame.playSound(2);\r\n");
      out.write("                if(autoPopSms==\"0\"){\r\n");
      out.write("                    shake();\r\n");
      out.write("                    $('.sign_in_tid').show();\r\n");
      out.write("                }else{\r\n");
      out.write("                    smsAlert();\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("            if(json.rtData.msgFlag!=0){//弹出通讯消息\r\n");
      out.write("                msgFrame.playSound(1);\r\n");
      out.write("                var offlineMsgJson = tools.requestJsonRs(contextPath+\"/messageManage/getOfflineMessages.action\");\r\n");
      out.write("                for(var i=0;i<offlineMsgJson.rtData.length;i++){\r\n");
      out.write("                    socketHandler(offlineMsgJson.rtData[i]);\r\n");
      out.write("                }\r\n");
      out.write("                offlineMsgJson = null;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        setTimeout(\"remindCheck()\",10*1000);//10秒\r\n");
      out.write("    });\r\n");
      out.write("}\r\n");
      out.write("function smsDetails(){\r\n");
      out.write("    openFullWindow(contextPath+'/system/core/sms/index.jsp',\"消息事务\");\r\n");
      out.write("    $(\"#smsbox\").hide();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function openFullWindow(actionUrl, title) {\r\n");
      out.write("      var winParam = \"menubar=0,toolbar=0,status=0\";\r\n");
      out.write("      winParam += \",scrollbars=1,resizable=1\";\r\n");
      out.write("      var left = 0;\r\n");
      out.write("      var top = 0;\r\n");
      out.write("      var width = window.screen.availWidth;\r\n");
      out.write("      var height = window.screen.availHeight;\r\n");
      out.write("//    if($.browser.webkit){\r\n");
      out.write("//        height = parseInt(height)-60;\r\n");
      out.write("//    }\r\n");
      out.write("      height = parseInt(height)-80;\r\n");
      out.write("      winParam += \",width=\" + width;\r\n");
      out.write("      winParam += \",height=\" + height;\r\n");
      out.write("      winParam += \",top=\" + top;\r\n");
      out.write("      winParam += \",left=\" + left;\r\n");
      out.write("      winParam += \",location=no\";\r\n");
      out.write("      \r\n");
      out.write("      try{\r\n");
      out.write("          if(window.external && window.external.IM_OA){\r\n");
      out.write("            window.external.IM_OpenNavigation(title,actionUrl.replace(contextPath,\"\"),0,0);\r\n");
      out.write("            return;\r\n");
      out.write("          }\r\n");
      out.write("      }catch(e){\r\n");
      out.write("          \r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      return window.open(actionUrl, new Date().getTime()+\"\", winParam);\r\n");
      out.write("    }\r\n");
      out.write("    function souSuo(){\r\n");
      out.write("        var souSouContent=$(\"#souSouContent\").val();\r\n");
      out.write("        openFullWindow(\"");
      out.print(contextPath );
      out.write("/system/core/base/quicksearch/search_result_new.jsp?souSouContent=\"+souSouContent,\"搜索\");\r\n");
      out.write("    }\r\n");
      out.write("    function doinit(){\r\n");
      out.write("        $.addTab(\"tabs\",\"tabs-content\",{title:\"\",url:contextPath + \"/xzfy/jsp/homePage/homePage.jsp\",active:true,cache:false});\r\n");
      out.write("        $(\"#nav_width\").children('div:first').css({\"background\":\"url(../classic/image/images/gzt.png) no-repeat 8px 6px\"});\r\n");
      out.write("        getSysMenu();\r\n");
      out.write("        renderLoginUserInfo();\r\n");
      out.write("    /*      $(\"body\").on(\"click\",\".inactive\",function(){\r\n");
      out.write("                    if ($(this).siblings('ul:first').css('display') == 'none') {\r\n");
      out.write("                        //$(this).parent('li').siblings('li').removeClass('inactives');\r\n");
      out.write("                        $(this).addClass('inactives');\r\n");
      out.write("                        $(this).siblings('ul:first').slideDown(100);\r\n");
      out.write("                        //if ($(this).parents('li').siblings('li').children('ul').css('display') == 'block') {\r\n");
      out.write("                        //    $(this).parents('li').siblings('li').children('ul').parent('li').children('h1').removeClass('inactives');\r\n");
      out.write("                        //    $(this).parents('li').siblings('li').children('ul').slideUp(100);\r\n");
      out.write("                        //}\r\n");
      out.write("\r\n");
      out.write("                        if($(this).hasClass(\"cole\")){\r\n");
      out.write("                            $(this).siblings('ul:first').addClass(\"ac\");\r\n");
      out.write("                        }\r\n");
      out.write("                    } else {\r\n");
      out.write("                        //控制自身变成+号\r\n");
      out.write("                        $(this).removeClass('inactives');\r\n");
      out.write("                        //控制自身菜单下子菜单隐藏\r\n");
      out.write("                        $(this).siblings('ul:first').slideUp(100);\r\n");
      out.write("                        //控制自身子菜单变成+号\r\n");
      out.write("                        $(this).siblings('ul:first').children('li').children('ul').parent('li').children('h1').addClass('inactives');\r\n");
      out.write("                        //控制自身菜单下子菜单隐藏\r\n");
      out.write("                        $(this).siblings('ul:first').children('li').children('ul').slideUp(100);\r\n");
      out.write("\r\n");
      out.write("                        //控制同级菜单只保持一个是展开的（-号显示）\r\n");
      out.write("                        $(this).siblings('ul:first').children('li').children('h1').removeClass('inactives');\r\n");
      out.write("\r\n");
      out.write("                        if($(this).hasClass(\"cole\")){\r\n");
      out.write("                            $(this).siblings('ul:first').removeClass(\"ac\");\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("         }); */\r\n");
      out.write("         //菜单点击效果\r\n");
      out.write("         $(\"body\").on(\"click\", \".one-active\", function () {\r\n");
      out.write("        \t $(this).parents('li').siblings('li').children('h1').removeClass('one-actives');\r\n");
      out.write("        \t $(this).addClass('one-actives');\r\n");
      out.write("        \t \r\n");
      out.write("         });\r\n");
      out.write("         $(\"body\").on(\"click\", \".inactive\", function () {\r\n");
      out.write("             if ($(this).siblings('ul:first').css('display') == 'none') {\r\n");
      out.write("                 $(this).addClass('inactives');\r\n");
      out.write("                 $(this).siblings('ul:first').slideDown(100);\r\n");
      out.write("                 if ($(this).siblings('ul:first').css('display') == 'block') {\r\n");
      out.write("                     $(this).parents('li').siblings('li').children('ul').slideUp(100);\r\n");
      out.write("                     $(this).parents('li').siblings('li').children('h1').removeClass('inactives');\r\n");
      out.write("                     $(this).addClass('inactive');\r\n");
      out.write("                 }\r\n");
      out.write("                 if ($(this).parents('li').siblings('li').children('ul').css('display') == 'block') {\r\n");
      out.write("                     $(this).parents('li').siblings('li').children('ul').parent('li').children('h1').removeClass('inactives');\r\n");
      out.write("                     $(this).parents('li').siblings('li').children('ul').slideUp(100);\r\n");
      out.write("                     $(this).addClass('inactive');\r\n");
      out.write("                 }\r\n");
      out.write("\r\n");
      out.write("             } else {\r\n");
      out.write("                 //控制自身变成+号\r\n");
      out.write("                 $(this).removeClass('inactives');\r\n");
      out.write("                 //控制自身菜单下子菜单隐藏\r\n");
      out.write("                 $(this).siblings('ul:first').slideUp(100);\r\n");
      out.write("                 //控制自身子菜单变成+号\r\n");
      out.write("                 $(this).siblings('ul:first').children('li').children('ul').parent('li').children('h1').addClass('inactives');\r\n");
      out.write("                 //控制自身菜单下子菜单隐藏\r\n");
      out.write("                 $(this).siblings('ul:first').children('li').children('ul').slideUp(100);\r\n");
      out.write("\r\n");
      out.write("                 //控制同级菜单只保持一个是展开的（-号显示）\r\n");
      out.write("                 $(this).siblings('ul:first').children('li').children('h1').removeClass('inactives');\r\n");
      out.write("             }\r\n");
      out.write("         });\r\n");
      out.write("         \r\n");
      out.write("         $('.ul1').perfectScrollbar();\r\n");
      out.write("         //setTimeout(\"sms()\",5*1000);//5秒\r\n");
      out.write("    }\r\n");
      out.write("    function NewPageINfo(title,url){\r\n");
      out.write("        $.addTab(\"tabs\",\"tabs-content\",{title:title,url:contextPath + url,active:true,cache:true,closable:true});\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    //获取当前登陆人基本信息\r\n");
      out.write("    function renderLoginUserInfo(){\r\n");
      out.write("       var url=contextPath+\"/personManager/getLoginUserInfo.action\";\r\n");
      out.write("       var json=tools.requestJsonRs(url);\r\n");
      out.write("       if(json.rtState){\r\n");
      out.write("           var data=json.rtData;\r\n");
      out.write("           loginUserRoleId=data.roleId;\r\n");
      out.write("           $(\"#userName\").text(data.userName);\r\n");
      out.write("           $(\"#deptName\").text(data.deptName);\r\n");
      out.write("           if(data.tx!=0){\r\n");
      out.write("               //height: 50px;width: 50px;position: fixed;right: 136px;top: 14px;background:url('/system/frame/classic/image/images/02.png') round ;border-radius: 50%;\r\n");
      out.write("               $(\"#txDiv\").attr(\"style\",\"height: 50px;width: 50px;position: fixed;right: 136px;top: 14px;background:url('/attachmentController/downFile.action?id=\"+data.tx+\"') round ;border-radius: 50%;\");\r\n");
      out.write("           }\r\n");
      out.write("       }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    //返回\r\n");
      out.write("    function goBack(){\r\n");
      out.write("        window.location.href = \"");
      out.print(contextPath);
      out.write("/system/frame/classic/index.jsp\";\r\n");
      out.write("    }\r\n");
      out.write("    function sms(){\r\n");
      out.write("    \tvar url = \"");
      out.print(contextPath );
      out.write("/sms/getSmsBoxDatas.action\";\r\n");
      out.write("    \tvar jsonRs = tools.requestJsonRs(url,null);\r\n");
      out.write("    \t//var json = eval(\"(\"+jsonRs+\")\");\r\n");
      out.write("    \t//var json=tools.jsonObj2String(jsonRs);\r\n");
      out.write("    \t/* alert(jsonRs.total); */\r\n");
      out.write("        $(\"#ss\").html(jsonRs.total);\r\n");
      out.write("    \tif(jsonRs.total>0){\r\n");
      out.write("    \t\t$(\"#ss\").show();\r\n");
      out.write("    \t}else{\r\n");
      out.write("    \t\t$(\"#ss\").hide();\r\n");
      out.write("    \t}\r\n");
      out.write("    }\r\n");
      out.write("    </script>\r\n");
      out.write("<style>\r\n");
      out.write(".active{\r\n");
      out.write("text-color:#000;\r\n");
      out.write("color:#000;\r\n");
      out.write("}\r\n");
      out.write(".tee_tab_pointer_right{ width:18px; height:40px;  background:url(/system/frame/3/style/images/header/nav_left01.png) no-repeat; text-indent:-9999px; cursor:pointer;}\r\n");
      out.write(".tee_tab_pointer_left{ width:18px; height:40px;  background:url(/system/frame/3/style/images/header/nav_right01.png) no-repeat;text-indent:-9999px; cursor:pointer;}\r\n");
      out.write(".tee_tab{    \r\n");
      out.write(" /*margin: auto 8px;*/\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    position: relative;\r\n");
      out.write("    margin-top: -2px;\r\n");
      out.write("    float: left;\r\n");
      out.write("    height: 30px;\r\n");
      out.write("    line-height: 30px;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    color: #000;\r\n");
      out.write("    padding: 0 20px 0 15px;\r\n");
      out.write("    font-size: 14px;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("#tabs-content{\r\n");
      out.write("position: absolute;\r\n");
      out.write("left:0px;\r\n");
      out.write("top:36px;\r\n");
      out.write("bottom:10px;\r\n");
      out.write("right:10px;\r\n");
      out.write("border:1px solid #cdcdcd;\r\n");
      out.write("}\r\n");
      out.write(".tee_tab::before{\r\n");
      out.write("    /* border-top-left-radius: 5px;\r\n");
      out.write("    border-top-right-radius: 5px;\r\n");
      out.write("    box-shadow: #cacaca 0px 2px 14px 1px;\r\n");
      out.write("    background: white;\r\n");
      out.write("    transform: perspective(150px) rotateX(45deg);*/\r\n");
      out.write("    margin-bottom: -4px;\r\n");
      out.write("    \r\n");
      out.write("    content: '';\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    top: 0;\r\n");
      out.write("    right: 0;\r\n");
      out.write("    bottom: 0;\r\n");
      out.write("    left: 0;\r\n");
      out.write("    border-right:white 1px solid;\r\n");
      out.write("    z-index: -1;\r\n");
      out.write("   \r\n");
      out.write("}\r\n");
      out.write(".tee_tab:hover{color:rgb(0, 158, 246);}\r\n");
      out.write(".tee_tab i{width:12px; height:10px; position:absolute; right:3px; top:11px; background:url(guanbi_1.png) no-repeat; cursor:pointer; z-index:111; display:block;}\r\n");
      out.write(".tee_tab.tee_tab_select i{ display:block; width:12px; height:10px; position:absolute; right:3px; top:11px; background:url(guanbi_1.png) no-repeat; cursor:pointer; z-index:111;}\r\n");
      out.write("#tabs .tee_tab.tee_tab_select{  position:relative; color:rgb(0, 158, 246);/*font-weight:bold;color:white;*/}\r\n");
      out.write(".tee_tab.tee_tab_select::before {\r\n");
      out.write("    content: '';\r\n");
      out.write("    position: absolute;\r\n");
      out.write("    top: 0;\r\n");
      out.write("    right: 0;\r\n");
      out.write("    bottom: 0;\r\n");
      out.write("    left: 0;\r\n");
      out.write("    background:white;\r\n");
      out.write("    z-index: -1;\r\n");
      out.write("    /*transform: perspective(150px) rotateX(45deg);*/\r\n");
      out.write("    }\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write(".logotext{\r\n");
      out.write("display:inline-block;\r\n");
      out.write("height:65px;\r\n");
      out.write("font-size:24px;\r\n");
      out.write("line-height:65px;\r\n");
      out.write("color:white;\r\n");
      out.write("}\r\n");
      out.write(".logoimg{\r\n");
      out.write("display: inline-block;\r\n");
      out.write("    width: 41px;\r\n");
      out.write("    height: 45px;\r\n");
      out.write("    background: url(logo.png);\r\n");
      out.write("    background-size: cover;\r\n");
      out.write("    margin: 13px 5px 0px 10px;\r\n");
      out.write("    vertical-align: top;\r\n");
      out.write("}\r\n");
      out.write(".ul1 {\r\n");
      out.write("\toverflow:auto !important;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body onload=\"doinit();\">\r\n");
      out.write("<div class=\"body1\">\r\n");
      out.write("    <div class=\"nav\" style=\"overflow: hidden\">\r\n");
      out.write("        <!-- <div class=\"logo\">\r\n");
      out.write("            <img src=\"image/logo_1.png\" alt=\"\" style=\"width: 100% ;height: 100%\">\r\n");
      out.write("        </div>  -->\r\n");
      out.write("        <span class=\"logoimg\"></span>\r\n");
      out.write("        <span class=\"logotext\">行政复议工作平台</span>\r\n");
      out.write("        <div class=\"nav1-right\" style=\"float: right\">\r\n");
      out.write("            <span id=\"ss\"></span>\r\n");
      out.write("            <div class=\"tu-b\">\r\n");
      out.write("                <ul>              \r\n");
      out.write("                    <li style=\"margin-right: 10px;\"><span id=\"userName\"></li>\r\n");
      out.write("                    <!--  <li><a href=\"javascript:void(0)\" onclick=\"goBack();\" ><img src=\"image/icon_home.png\" alt=\"\" class=\"img\" ></a></li> -->\r\n");
      out.write("                     <li ><a href=\"javascript:void(0)\" ><img id=\"tip_alert\" src=\"image/tongzhi_1.png\" alt=\"\" class=\"img\" style=\"width:20px; height:20px; margin-right: 20px;title=\"消息提醒\" ></a><div class=\"sign_in_tid\" style=\"display:none\">新的消息！</div></li>\r\n");
      out.write("                     <li><a href=\"javascript:void(0)\" onclick=\"NewPageINfo('桌面模块设置','");
      out.print(contextPath );
      out.write("/system/core/person/setdescktop/index.jsp')\" title=\"桌面模块设置\"> <img src=\"image/set_up.png\"  alt=\"\" class=\"img\" style=\"margin-right: 20px;\"> </a></li>\r\n");
      out.write("               \r\n");
      out.write("                   <!--  <li><a href=\"javascript:void(0)\"><img class=\"sign_img\" src=\"image/5.png\" alt=\"\" class=\"img\"></a>\r\n");
      out.write("                      <div class=\"signin_out\">\r\n");
      out.write("                                <p id=\"signInTime\" class='sign_time' style=\"font-weight: bold;font-size: 16px;\"></p>\r\n");
      out.write("                                <p><button id=\"signInButton\" class='sign_btn' onclick=\"signInFunc();\" style='color:#fff;'>登记</button></p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </li> -->\r\n");
      out.write("                    <li onclick=\"closeLogin();\" title=\"注销\"><img src=\"image/tuichu_1.png\" alt=\"\" class=\"img fl\" style=\"width:20px; height:20px;\"></li>\r\n");
      out.write("                                     <li>\r\n");
      out.write("                        <a href=\"javascript:void(0)\"><img src=\"image/18.png\" alt=\"\" class=\"img group fl\" style=\"margin-right: 10px;\"></a>\r\n");
      out.write("                        <div id='groupContent' style='width:240px;position:fixed;right:-240px;top:77px;bottom:3px;z-index:99999;box-shadow:0 0 15px #a2a2a2;'>\r\n");
      out.write("                            <iframe style='width:100%;height:100%;margin-top:10px;' id='right' src=\"/system/frame/3/right.jsp\" frameborder=\"0\"></iframe>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                   <!--  <li><a href=\"javascript:void(0)\"><img src=\"image/tuichu_1.png\" alt=\"\" class=\"img group fl\" ></a>\r\n");
      out.write("                    <div id='groupContent' style='width:240px;position:fixed;right:-240px;top:77px;bottom:3px;z-index:99999;box-shadow:0 0 15px #a2a2a2;'>\r\n");
      out.write("                    <iframe style='width:100%;height:100%;' id='right' src=\"/system/frame/3/right.jsp\" frameborder=\"0\"></iframe>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    </li> -->\r\n");
      out.write("                    <!-- <li style=\"width: 1px;display: block;position: relative;height: 45px;background: white;top: -21px;right: -225px;\"></li> -->\r\n");
      out.write("                </ul>\r\n");
      out.write("                <!-- <div>\r\n");
      out.write("                    <div id=\"txDiv\" style=\"height: 50px;width: 50px;position: fixed;right: 136px;top: 14px;background:url('/system/frame/classic/image/images/02.png') round ;border-radius: 50%;\">\r\n");
      out.write("                        <div style=\"color: white;letter-spacing: 1px;font-size: 14px;position: relative;top: 5px;right: -70px;width:80px\"><span id=\"userName\"></span></div>\r\n");
      out.write("                        <div style=\"color: white;letter-spacing: 1px;font-size: 12px;position: relative;top: 14px;right: -69px;width:80px\"><span id=\"deptName\"></span></div>\r\n");
      out.write("                        <div style=\"position:absolute;top:28px\"><img class=\"dian\" src=\"image/2222.png\" alt=\"\" style=\"height: 9px;width: 13px;position: relative;top: -22px;right: -160px;cursor: pointer;\"></div>\r\n");
      out.write("                        <div style=\"color: white;letter-spacing: 1px;font-size: 14px;position: fixed;top: 21px;right: 48px;\"><span id=\"userName\"></span></div>\r\n");
      out.write("                        <div style=\"color: white;letter-spacing: 1px;font-size: 12px;position: fixed;top: 42px;right: 48px;\"><span id=\"deptName\"></span></div>\r\n");
      out.write("                        <img class=\"dian\" src=\"image/2222.png\" alt=\"\" style=\"height: 9px;width: 13px;position: fixed;top: 21px;right: 20px;cursor: pointer;\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                <div class=\"bao\" style=\"background: white;z-index: 100;display: none;cursor: pointer;font-size: 12px;border: 1px solid #cccccc;position: fixed;right: 0;top: 76px;width: 125px;color: grey;\">\r\n");
      out.write("                    <div style=\"border-bottom: 1px solid #cccccc;text-align: left;height: 35px;line-height: 35px;\"  onclick=\"doLogout();\">\r\n");
      out.write("                    <img src=\"image/3333.png\" alt=\"\" style=\"padding: 0 10px;\">切换账号</div>\r\n");
      out.write("                    <div style=\"text-align: left;height: 35px;line-height: 35px;height: 35px;line-height: 35px;\" onclick=\"closeLogin();\">\r\n");
      out.write("                        <img src=\"image/4444.png\" alt=\"\" style=\"padding: 0 10px;\">退出登录</div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div> -->\r\n");
      out.write("        </div>\r\n");
      out.write("    </div><!--顶部-->\r\n");
      out.write("    <div id=\"ft\">\r\n");
      out.write("        <div class=\"closes\"> \r\n");
      out.write("            <img src=\"image/dakai.png\" alt=\"\" style=\"margin-left: 170px;cursor: pointer;\" class=\"closes_1\">\r\n");
      out.write("             <img src=\"image/dakai.png\" alt=\"\" style=\"margin: 12px 25px;cursor: pointer;\" class=\"shows\">\r\n");
      out.write("        \r\n");
      out.write("        </div> \r\n");
      out.write("        <div class=\"header-left\" style=\"overflow:hidden;position:absolute;width:210px;left:0px;top:106px;bottom:0px;border-top:0px;padding-bottom: 20px;box-shadow:4px 1px 5px 0px #dddddd\">\r\n");
      out.write("            <div class=\"left-z\" style=\" opacity: 0; position: fixed; top: 50%; left: 60px; z-index: 1000000;\"><img src=\"imgs/index/left-z.png\" alt=\"\"></div>\r\n");
      out.write("           <!--  <div class=\"left-y\" style=\" opacity: 0; position: fixed; top: 50%;   left: 200px; z-index: 1000000;\"><img src=\"imgs/index/left-y.png\" alt=\"\"></div> -->\r\n");
      out.write("            <div class=\"ul1\" style=\"overflow:auto;width:100%;height:100%\">\r\n");
      out.write("                <ul class=\"yiji ul2\" id=\"yijiCanDan\" style=\"overflow:hidden;\">\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div><!--左边--->\r\n");
      out.write("        <div style=\"position: absolute;left:220px;top:69px;bottom:0px;right:0px\" id=\"id\">\r\n");
      out.write("            <div id=\"tabs\" style=\"position: absolute;left:0px;top:0px;height:40px;right:10px;\">\r\n");
      out.write("                \r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"tabs-content\" >\r\n");
      out.write("<!--                <iframe src=\"ceshizishiying.jsp\" frameborder=\"0\" width=\"100%\" height=\"100%\" id=\"main\"></iframe> -->\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- 短消息面板 -->\r\n");
      out.write("        <div class=\"smsbox\" id=\"smsbox\" style=\"display: none;\">\r\n");
      out.write("            <div class=\"title\">\r\n");
      out.write("            <span style=\"float:left;\">消息提醒</span>\r\n");
      out.write("            <span class='sms_close_win' style=\"float:right;font-size:16px;cursor:pointer\" onclick=\"$('#smsbox').hide()\">×</span>\r\n");
      out.write("            <span style=\"float:right;cursor:pointer;margin-top:3px;background-image:url(imgs/index/read.png);\" class=\"sms_list smsbox_icon2\" onclick=\"smsDetails()\">消息列表</span>\r\n");
      out.write("            <span style=\"float:right;cursor:pointer;margin-top:3px;background-image:url(imgs/index/cancel.png);\" class=\"all_check smsbox_icon1\" onclick=\"smsViewAlls()\">全部已阅</span>\r\n");
      out.write("            <div style=\"clear:both\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"content\" id=\"smsBoxContent\">\r\n");
      out.write("                <div class=\"smsbox_loadmore\" id=\"loadMore\">\r\n");
      out.write("                    查看更多\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("<script>\r\n");
      out.write("    $(document).ready(function () {\r\n");
      out.write("    $('.header-left').prepend($(\"#ascrail2000\"));\r\n");
      out.write("        $('.header-left').bind(\"mouseenter\", function () {\r\n");
      out.write("            $(this).unbind(\"mouseleave\").bind(\"mouseleave\", function () {\r\n");
      out.write("              $('.left-z').animate({\r\n");
      out.write("                opacity: 0\r\n");
      out.write("               }, 300);\r\n");
      out.write("\r\n");
      out.write("              });\r\n");
      out.write("             $('.left-z').animate({\r\n");
      out.write("               opacity: 0\r\n");
      out.write("              }, 300);\r\n");
      out.write("    $('.header-left').prepend($(\"#ascrail2000\"));\r\n");
      out.write("             });\r\n");
      out.write("\r\n");
      out.write("       });\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("//二级菜单的点击事件\r\n");
      out.write("\r\n");
      out.write("    //悬停和选中更改背景图\r\n");
      out.write("    $(document).ready(function() { \r\n");
      out.write("            $(document).on('click','.ul2 li ul li',function() { \r\n");
      out.write("                $(this).addClass(\"tabFocus\").siblings().removeClass(\"tabFocus\");\r\n");
      out.write("                $('.ul1 ul li ul li h1').css({\"color\":\"#000000\",\"background\":\"#f5f5f5\"});\r\n");
      out.write("                $(this).children('h1').css({\"color\":\"#fff\",\"background\":\"url(../classic/image/images/tabfocus.png)\"});\r\n");
      out.write("            });\r\n");
      out.write("            $(\".ul2 li ul li h1\").stop();\r\n");
      out.write("            $(document).on('mouseover','.ul2 li ul li',function(){\r\n");
      out.write("            \tif(!$(this).hasClass('tabFocus')){\r\n");
      out.write("            \t\t$(this).children('h1').css({'color':'#fff',\"background\":\"url(../classic/image/images/tabfocus.png)\"});\r\n");
      out.write("            \t\t}  \t           \t\t\r\n");
      out.write("              });\r\n");
      out.write("            $(document).on('mouseout','.ul2 li ul li',function(){\r\n");
      out.write("            \tif(!$(this).hasClass('tabFocus')){\r\n");
      out.write("            \t\t$(this).children('h1').css({'color':'#000000',\"background\":\"#f5f5f5\"});\r\n");
      out.write("            \t\t}  \t           \t\t\r\n");
      out.write("              });\r\n");
      out.write("            $(\".ul2 li ul li h1\").stop();\r\n");
      out.write("\r\n");
      out.write("       \r\n");
      out.write("\r\n");
      out.write("           /* $(document).on('click','.ul1 ul li ul li',function() { \r\n");
      out.write("            \tconsole.log(\"zhixing2\");\r\n");
      out.write("                $(this).addClass(\"tabFocus\").siblings().removeClass(\"tabFocus\"); \r\n");
      out.write("                if($(this).children('.ul1 ul li ul li h1').hasClass(\"inactive\")){\r\n");
      out.write("                    $(this).removeClass(\"tabFocus\");\r\n");
      out.write("               }else{\r\n");
      out.write("                    $(this).addClass(\"tabFocus\");\r\n");
      out.write("               } \r\n");
      out.write("               $(this).siblings().children('.ul1 ul li ul li ul').children('.ul1 ul li ul li ul li').removeClass(\"tabFocus\");\r\n");
      out.write("            });\r\n");
      out.write("           \r\n");
      out.write("                //$(\".ul2 li ul li\").stop();\r\n");
      out.write("            \t$(document).on('mouseover','.ul2 li ul li',function(){\r\n");
      out.write("            \tif(!$(this).hasClass('tabFocus')){\r\n");
      out.write("            \t\t$(this).css('background','#C9E3FF').siblings().css(\"background\",\"#fff\");\r\n");
      out.write("            \t\t}\r\n");
      out.write("            \t$('li.tabFocus').css(\"background\",\"url(../classic/image/images/tabfocus.png)\");\t            \t\t\r\n");
      out.write("            \t}); \r\n");
      out.write("            //$(\".ul2 li ul li\").stop();\r\n");
      out.write("            \t$(document).on('mouseout','.ul2 li ul li',function(){\r\n");
      out.write("                \tif(!$(this).hasClass('tabFocus')){\r\n");
      out.write("                \t\t$(this).css('background','#fff');\r\n");
      out.write("                \t\t$('li.tabFocus').css(\"background\",\"url(../classic/image/images/tabfocus.png)\");\t \r\n");
      out.write("                \t\t}  \t           \t\t\r\n");
      out.write("                \t});  \r\n");
      out.write("           \r\n");
      out.write("           */\r\n");
      out.write("            $(document).on('click','.ul1 ul li ul li ul li',function() { \r\n");
      out.write("                $(this).addClass(\"tabFocus\").siblings().removeClass(\"tabFocus\");                  \r\n");
      out.write("            });\r\n");
      out.write("            $(this).parent('.ul1 ul li ul li ul').parents('.ul1 ul li ul li').siblings('.ul1 ul li ul li').children('.ul1 ul li ul li ul').children('.ul1 ul li ul li ul li').removeClass(\"tabFocus\");  \r\n");
      out.write("      \r\n");
      out.write("    });\r\n");
      out.write("    $(document).ready(function () {\r\n");
      out.write("        $('.header-left').bind(\"mouseenter\", function () {\r\n");
      out.write("            $(this).unbind(\"mouseout\").bind(\"mouseleave\", function () {\r\n");
      out.write("              $('.left-y').animate({\r\n");
      out.write("                opacity: 0\r\n");
      out.write("              }, 300);\r\n");
      out.write("\r\n");
      out.write("           });\r\n");
      out.write("              $('.left-y').animate({\r\n");
      out.write("                opacity: 1\r\n");
      out.write("              }, 300);\r\n");
      out.write("\r\n");
      out.write("           });\r\n");
      out.write("        });\r\n");
      out.write("var autoPopSms = \"");
      out.print(person.getAutoPopSms());
      out.write("\";\r\n");
      out.write("    $(function () {\r\n");
      out.write("        $(\".dian\").click(function(){\r\n");
      out.write("            $(\".bao\").toggle(100);\r\n");
      out.write("    });\r\n");
      out.write("        remindCheck();\r\n");
      out.write("        $(\".left-z,.ul1 ul,.shows\").click(function () {\r\n");
      out.write("        \t $(\".closes\").css({\"width\": \"210px\"});\r\n");
      out.write("        \t $(\".closes_1\").show();\r\n");
      out.write("        \t $(\".shows\").hide();\r\n");
      out.write("        \t/*  $(\".closes img\").css({\"margin-left\": \"170px\"}); */\r\n");
      out.write("            $(\"#id\").css('left', '220px');\r\n");
      out.write("            $(\".header-left\").css('width', '210px');\r\n");
      out.write("            $(\".menu_text\").show();\r\n");
      out.write("         /*    $(\".ul1 ul li .cole\").css('background-color', 'rgb(241,243,255)'); */\r\n");
      out.write("            $(\".ul1\").css({\"width\": \"210px\", \"margin\": \"0px auto 0 auto\"});\r\n");
      out.write("            $(\".header-left .ul1 ul li h1\").css({\"text-align\": \"left\"});\r\n");
      out.write("            $(\".header-left .ul1 ul li i\").css({ \"transform\": \"scale(1)\"});\r\n");
      out.write("            $(\".header-left .ul1 ul li i\").css( \"margin-left\",\"15px\");\r\n");
      out.write("            $(\".header-left .ul1 ul li ul li h1\").css({ \"padding-left\": \"22px\"});\r\n");
      out.write("            $(\".header-left .ul1 ul li img\").css({\r\n");
      out.write("                \"width\": \" 26px\",\r\n");
      out.write("                \"height\": \"26px\",\r\n");
      out.write("                \"margin-top\": \"8px\",\r\n");
      out.write("                \"margin-left\": \"10px\",\r\n");
      out.write("                \"padding-right\": \"10px\"\r\n");
      out.write("            });\r\n");
      out.write("           \r\n");
      out.write("            $(\".ac\").show();\r\n");
      out.write("    $(\".left-y\").show();\r\n");
      out.write("    $(\".left-z\").hide();\r\n");
      out.write("        });\r\n");
      out.write("        $(\".left-z\").click();\r\n");
      out.write("        $(\".closes_1\").click(function () {\r\n");
      out.write("            $(\"#id\").css('left', '80px');\r\n");
      out.write("            $(\".header-left\").css('width', '73px');\r\n");
      out.write("            $(\".menu_text\").hide();\r\n");
      out.write("            $(\".header-left .ul1 ul li img\").css({\"width\": \" 26px\", \"height\": \"26px\", \"margin-left\": \"20px\"});\r\n");
      out.write("            $(\".header-left .ul1 ul li i\").css({ \"transform\": \"scale(1.7)\"});\r\n");
      out.write("            $(\".header-left .ul1 ul li i\").css( \"margin-left\",\"0px\");\r\n");
      out.write("            $(\".header-left .ul1 ul li ul li i\").css({ \"transform\": \"scale(1.275)\"});\r\n");
      out.write("            $(\".header-left .ul1 ul li ul li h1\").css({ \"padding-left\": \"1px\"});\r\n");
      out.write("            \r\n");
      out.write("            $(\".header-left .ul1 ul li h1\").css({\"text-align\": \"center\"});\r\n");
      out.write("           /*  $(\".ul1 ul li .cole\").css('background-color', 'white'); */\r\n");
      out.write("            $(\".ul1\").css({\"width\": \"73px\", \"margin\": \"0px auto 0 auto\"});\r\n");
      out.write("            $(\".closes\").css({\"width\": \"73px\"});\r\n");
      out.write("           $(\".closes_1\").hide();\r\n");
      out.write("           $(\".shows\").show();\r\n");
      out.write("            $(\".ac\").hide();\r\n");
      out.write("    $(\".left-z\").show();\r\n");
      out.write("    $(\".left-y\").hide();\r\n");
      out.write("        });\r\n");
      out.write("       \r\n");
      out.write("      //登记登出\r\n");
      out.write("        $(\".sign_img\").on(\"click\",function(){\r\n");
      out.write("            $(\".signin_out\").slideToggle(50);\r\n");
      out.write("        });\r\n");
      out.write("        $(\".signin_out\").on(\"mouseleave\",function(){\r\n");
      out.write("            $(\".signin_out\").slideToggle(50);\r\n");
      out.write("        });\r\n");
      out.write("        //消息提醒\r\n");
      out.write("        var tip_zhezhao = \"<div class='tip_zhezhao' style='width:100%;height:100%;z-index: 9999;position: fixed;filter:Alpha(opacity=60);background-color: #000;top: 0;left: 0;opacity: 0.6;'></div>\";\r\n");
      out.write("        $(\"#tip_alert\").on(\"click\",function(){\r\n");
      out.write("            $(\"body\").append(tip_zhezhao);\r\n");
      out.write("            $(\".smsbox\").fadeIn(200);\r\n");
      out.write("            smsAlert();\r\n");
      out.write("        });\r\n");
      out.write("        $(\"body\").on(\"click\",\".sms_close_win,.sms_list,.all_check\",function(){\r\n");
      out.write("            $(\".tip_zhezhao\").remove();\r\n");
      out.write("        });\r\n");
      out.write("       \r\n");
      out.write("        //组织架构显示\r\n");
      out.write("        $(\"body\").on(\"click\",\".group\",function(){\r\n");
      out.write("            if($(\"#groupContent\").css(\"right\")==\"0px\"){\r\n");
      out.write("                $(\"#groupContent\").animate({right:\"-240px\"},300);\r\n");
      out.write("            }else{\r\n");
      out.write("                $(\"#groupContent\").animate({right:\"0px\"},300);\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("        });\r\n");
      out.write("    })\r\n");
      out.write("    \r\n");
      out.write("    function getSysMenu(){\r\n");
      out.write("           //获取当前登陆人快捷菜单ids\r\n");
      out.write("           var urls=contextPath+\"/personManager/getQuickMenuIds.action\";\r\n");
      out.write("           var json=tools.requestJsonRs(urls);\r\n");
      out.write("           var quickMenuIds=json.rtData;\r\n");
      out.write("\r\n");
      out.write("        \tif(sysId == 0){\r\n");
      out.write("        \t\tsysId = defultSysId;\r\n");
      out.write("        \t}\r\n");
      out.write("            tools.requestJsonRs(contextPath+\"/teeMenuGroup/getPrivSysMenu2.action\",{sysId:sysId},true,function(json){\r\n");
      out.write("                var data=json.rtData;\r\n");
      out.write("                if(data!=null){\r\n");
      out.write("                    var one=data.one;\r\n");
      out.write("                    var two=data.two;\r\n");
      out.write("                    var three=data.three;\r\n");
      out.write("                    //一级菜单\r\n");
      out.write("                    if(one!=null){\r\n");
      out.write("                        for(var i=0;i<one.length;i++){\r\n");
      out.write("                            var menuId=one[i].menuId;\r\n");
      out.write("                            var menuName=one[i].menuName;\r\n");
      out.write("                            var menuCode=one[i].menuCode;\r\n");
      out.write("                            var icon=one[i].icon;\r\n");
      out.write("                            var caiDanFalg=one[i].caiDanFalg;\r\n");
      out.write("                            var html=\"<li>\";\r\n");
      out.write("                                   if(caiDanFalg){\r\n");
      out.write("                                       html+=\"<h1 class='inactive active cole' style='height: 40px;line-height: 40px;' title=\"+menuName+\">\";\r\n");
      out.write("                                       /** editDate: 2019-03-06\r\n");
      out.write("                                       /*  editPerson: 曹进宇\r\n");
      out.write("                                       /*  editContent:注释掉原有的图片图标，改用标签 \r\n");
      out.write("                                       /*  html+=\"<img src='icons/\"+icon+\"' alt='' style='float: left'>\"; */\r\n");
      out.write("                                       if(icon != null && icon != ''){\r\n");
      out.write("                                           html+=\"<i class='\" + icon + \"' style='width:15px;'></i>&nbsp;\";\r\n");
      out.write("                                           html+=\"<span style='font-size:16px;font-family:微软雅黑' class='menu_text'>\";\r\n");
      out.write("                                           html+=menuName+\"</span>\";\r\n");
      out.write("                                       }else{\r\n");
      out.write("                                           html+=\"<i class='fa fa-bars' style='width:15px;'></i>&nbsp;\";\r\n");
      out.write("                                           html+=\"<span style='font-size:16px;font-family:微软雅黑' class='menu_text'>\"; \r\n");
      out.write("                                           html+=menuName+\"</span>\";\r\n");
      out.write("                                       }\r\n");
      out.write("                                       //html+=\"<span  style='font-size:16px;font-family:微软雅黑' class='menu_text'>\"+menuName+\"</span>\";\r\n");
      out.write("                                       html+=\"</h1>\";\r\n");
      out.write("                                       html+=\"<ul class='' id='one_\"+menuId+\"'></ul>\";\r\n");
      out.write("                                   }else{\r\n");
      out.write("                                       html+=\"<h1 onclick=\\\"NewPageINfo('\"+menuName+\"','\"+menuCode+\"')\\\" class='active cole one-active' style='height: 40px;line-height: 40px;' title=\"+menuName+\">\";\r\n");
      out.write("                                       if(icon != null && icon != ''){\r\n");
      out.write("                                           html+=\"<i class='\" + icon + \"' style='width:15px;'></i>&nbsp;\";\r\n");
      out.write("                                       }else{\r\n");
      out.write("                                           html+=\"<i class='fa fa-bars' style='width:15px;'></i>&nbsp;\";\r\n");
      out.write("                                       }\r\n");
      out.write("                                       // html+=\"<img src='icons/\"+icon+\"''  onerror=\\\"this.src='icons/xtgl.png'\\\" alt='' style='float: left'>\";\r\n");
      out.write("                                       html+=\"<span  style='font-size:16px;font-family:微软雅黑' class='menu_text'>\"+menuName+\"</span>\";\r\n");
      out.write("                                       html+=\"</h1>\";\r\n");
      out.write("                                   }\r\n");
      out.write("                                 html+=\"</li>\"\r\n");
      out.write("                             $(\"#yijiCanDan\").append(html);\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("                    //二级菜单\r\n");
      out.write("                    if(two!=null){\r\n");
      out.write("                        for(var i=0;i<two.length;i++){\r\n");
      out.write("                            var menuId=two[i].menuId;\r\n");
      out.write("                            var menuName=two[i].menuName;\r\n");
      out.write("                            var menuCode=two[i].menuCode;\r\n");
      out.write("                            var icon=two[i].icon;\r\n");
      out.write("                            var caiDanFalg=two[i].caiDanFalg;\r\n");
      out.write("                            var pmenuId=menuId.substring(0,3);\r\n");
      out.write("                            var uuid=two[i].uuid;\r\n");
      out.write("                            //判断是否是快捷菜单\r\n");
      out.write("                            var isQm=isQuickMenu(quickMenuIds,uuid);\r\n");
      out.write("                            \r\n");
      out.write("                            var html=\"<li>\";\r\n");
      out.write("                                   if(caiDanFalg){\r\n");
      out.write("                                       html+=\"<h1 title=\"+menuName+\" class='inactive active hovers' style='height: 30px;line-height: 30px;padding-left: 22px ;'>\";\r\n");
      out.write("                                       if(icon != null && icon != ''){\r\n");
      out.write("                                           html+=\"<i class='\" + icon + \"' style='width:15px;'></i>&nbsp;\";\r\n");
      out.write("                                       }else{\r\n");
      out.write("                                           html+=\"<i class='fa fa-bars' style='width:15px;'></i>&nbsp;\";\r\n");
      out.write("                                       }\r\n");
      out.write("                                       html+=\"<span class='menu_text'>\"+menuName+\"</span></h1>\";\r\n");
      out.write("                                       html+=\"<ul id='two_\"+menuId+\"'>\";\r\n");
      out.write("\r\n");
      out.write("                                       html+=\"</ul>\";\r\n");
      out.write("                                   }else{\r\n");
      out.write("                                       if(isQm==0){\r\n");
      out.write("                                           html+=\"<h1 title=\"+menuName+\" class='active hovers' onclick=\\\"NewPageINfo('\"+menuName+\"','\"+menuCode+\"')\\\" style='height: 35px;line-height: 35px;padding-left:22px ;    '>\";\r\n");
      out.write("                                           if(icon != null && icon != ''){\r\n");
      out.write("                                               html+=\"<i class='\" + icon + \"' style='width:15px;'></i>&nbsp;\";\r\n");
      out.write("                                           }else{\r\n");
      out.write("                                               html+=\"<i class='fa fa-bars' style='width:15px;'></i>&nbsp;\";\r\n");
      out.write("                                           }\r\n");
      out.write("                                           html+=\"<span class='menu_text'>\"+menuName+\"</span></h1>\";\r\n");
      out.write("                                       }else if(isQm==1){\r\n");
      out.write("                                           html+=\"<h1 class='active hovers' onclick=\\\"NewPageINfo('\"+menuName+\"','\"+menuCode+\"')\\\" style='height: 35px;line-height: 35px;padding-left:22px ;'>\";\r\n");
      out.write("                                           if(icon != null && icon != ''){\r\n");
      out.write("                                               html+=\"<i class='\" + icon + \"' style='width:15px;'></i>&nbsp;\";\r\n");
      out.write("                                           }else{\r\n");
      out.write("                                               html+=\"<i class='fa fa-bars' style='width:15px;'></i>&nbsp;\";\r\n");
      out.write("                                           }\r\n");
      out.write("                                           html+=\"<span class='menu_text'>\"+menuName+\"</span></h1>\";\r\n");
      out.write("                                       }\r\n");
      out.write("                                       \r\n");
      out.write("                                   }\r\n");
      out.write("                                html+=\"</li>\";\r\n");
      out.write("                            $(\"#one_\"+pmenuId).append(html);\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("                    //三级菜单\r\n");
      out.write("                    if(three!=null){\r\n");
      out.write("                        for(var i=0;i<three.length;i++){\r\n");
      out.write("                            var menuId=three[i].menuId;\r\n");
      out.write("                            var menuName=three[i].menuName;\r\n");
      out.write("                            var menuCode=three[i].menuCode;\r\n");
      out.write("                            var icon=three[i].icon;\r\n");
      out.write("                            var caiDanFalg=three[i].caiDanFalg;\r\n");
      out.write("                            var pmenuId=menuId.substring(0,6);\r\n");
      out.write("\r\n");
      out.write("                            var uuid=three[i].uuid;\r\n");
      out.write("                            //判断是否是快捷菜单\r\n");
      out.write("                            var isQm=isQuickMenu(quickMenuIds,uuid);\r\n");
      out.write("                            if(isQm==0){\r\n");
      out.write("                                var html=\"<li><h1 class='hovers' title=\"+menuName+\" onclick=\\\"NewPageINfo('\"+menuName+\"','\"+menuCode+\"')\\\" style='height: 35px;line-height: 35px;padding-left: 60px; '>\";\r\n");
      out.write("                                if(icon != null && icon != ''){\r\n");
      out.write("                                    html+=\"&nbsp;&nbsp;<i class='\" + icon + \"' style='width:15px;'></i>&nbsp;\";\r\n");
      out.write("                                }else{\r\n");
      out.write("                                    html+=\"&nbsp;&nbsp;<i class='fa fa-bars' style='width:15px;'></i>&nbsp;\";\r\n");
      out.write("                                }    \r\n");
      out.write("                                html+=\"<span class='menu_text'>\"+menuName+\"</span></h1></li>\";\r\n");
      out.write("                            }else if(isQm==1){\r\n");
      out.write("                                var html=\"<li><h1 class='hovers' title=\"+menuName+\" onclick=\\\"NewPageINfo('\"+menuName+\"','\"+menuCode+\"')\\\" style='height: 35px;line-height: 35px;padding-left: 60px;  '>\";\r\n");
      out.write("                                if(icon != null && icon != ''){\r\n");
      out.write("                                    html+=\"&nbsp;&nbsp;<i class='\" + icon + \"' style='width:15px;'></i>&nbsp;\";\r\n");
      out.write("                                }else{\r\n");
      out.write("                                    html+=\"&nbsp;&nbsp;<i class='fa fa-bars' style='width:15px;'></i>&nbsp;\";\r\n");
      out.write("                                }\r\n");
      out.write("                                html+=\"<span class='menu_text'>\"+menuName+\"</span></h1></li>\";\r\n");
      out.write("                            }\r\n");
      out.write("                            \r\n");
      out.write("                            $(\"#two_\"+pmenuId).append(html);\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                //$(\".kjfs-img\").addClass('img-001'); // 初始化时添加背景1\r\n");
      out.write("                $(\".kjfs-img\").click(function() {\r\n");
      out.write("                    var is001 =$(this).hasClass(\"img-001\");\r\n");
      out.write("                    if(is001){//标为快捷菜单\r\n");
      out.write("                        var uuid=$(this).attr(\"uuid\");\r\n");
      out.write("                        var url=contextPath+\"/personManager/addQuickMenu.action\";\r\n");
      out.write("                        var json=tools.requestJsonRs(url,{menuId:uuid});\r\n");
      out.write("                        if(json.rtState){\r\n");
      out.write("                            $(this).removeClass(\"img-001\");\r\n");
      out.write("                            $(this).addClass(\"img-002\");    \r\n");
      out.write("                        }\r\n");
      out.write("                    }else{//取消快捷菜单\r\n");
      out.write("                        var uuid=$(this).attr(\"uuid\");\r\n");
      out.write("                        var url=contextPath+\"/personManager/removeQuickMenu.action\";\r\n");
      out.write("                        var json=tools.requestJsonRs(url,{menuId:uuid});\r\n");
      out.write("                        if(json.rtState){\r\n");
      out.write("                             $(this).removeClass(\"img-002\");\r\n");
      out.write("                             $(this).addClass(\"img-001\"); \r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("            });\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    //判断菜单是否是快捷菜单\r\n");
      out.write("    function isQuickMenu(quickMenuIds,uuid){\r\n");
      out.write("        if(quickMenuIds!=null&&quickMenuIds!=\"\"){\r\n");
      out.write("            var qmIds = quickMenuIds.split(\",\"); \r\n");
      out.write("            if(qmIds!=null&&qmIds.length>0){\r\n");
      out.write("                for(var j=0;j<qmIds.length;j++){\r\n");
      out.write("                    if(qmIds[j]==uuid){\r\n");
      out.write("                        return 1;\r\n");
      out.write("                    }\r\n");
      out.write("                }\r\n");
      out.write("                  }else{\r\n");
      out.write("                return 0;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("        }else{//之前不是快捷菜单\r\n");
      out.write("            return  0;\r\n");
      out.write("        }\r\n");
      out.write("        return 0;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else log(t.getMessage(), t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
