package org.apache.jsp.system.frame.classic;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import com.tianee.oa.oaconst.TeeConst;
import com.tianee.oa.core.org.bean.TeePerson;
import com.tianee.webframe.util.global.TeeSysProps;
import com.tianee.webframe.util.date.TeeLunarCalendarUtils;
import com.tianee.webframe.util.str.TeeStringUtil;
import com.tianee.webframe.util.global.TeeSysCustomerProps;
import com.tianee.oa.core.org.bean.TeeUserRole;
import com.tianee.oa.core.org.bean.TeeDepartment;
import com.tianee.oa.oaconst.TeeConst;
import com.tianee.webframe.util.date.TeeDateUtil;
import com.tianee.oa.core.org.bean.TeePerson;
import com.tianee.oa.core.org.service.TeePersonService;
import java.util.Date;
import com.tianee.webframe.util.date.TeeDateUtil;
import com.tianee.webframe.util.str.TeeUtility;
import com.tianee.webframe.util.str.TeeStringUtil;
import com.tianee.oa.oaconst.TeeConst;

public final class zfjd_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  static {
    _jspx_dependants = new java.util.ArrayList(1);
    _jspx_dependants.add("/header/userheader.jsp");
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");


	String contextPath = request.getContextPath();
	String basePath = request.getScheme() + "://"
			+ request.getServerName() + ":" + request.getServerPort()
			+ contextPath + "/";
	//获取主题的索引号
	int styleIndex = 1;
	Integer styleInSession = (Integer) request.getSession().getAttribute("STYLE_TYPE_INDEX");
	if (styleInSession != null) {
		styleIndex = styleInSession;
	}
	String stylePath = contextPath + "/common/styles";
	String imgPath = stylePath + "/style" + styleIndex + "/img";
	String cssPath = stylePath + "/style" + styleIndex + "/css";
	String systemImagePath = contextPath+"/common/images";
	
	//第二套风格
	int STYLE_TYPE_INDEX_2 = TeeStringUtil.getInteger( request.getSession().getAttribute("STYLE_TYPE_INDEX_2"), 1);
	String cssPathSecond = contextPath + "/system/frame/2/styles/style" + STYLE_TYPE_INDEX_2 + "/css";
	String imgPathSecond = contextPath + "/system/frame/2/styles/style" + STYLE_TYPE_INDEX_2 + "/img";
	
	
	String loginOutText = TeeSysProps.getString("LOGIN_OUT_TEXT");
	String ieTitle = TeeSysProps.getString("IE_TITLE");
	String secUserMem = (String) request.getSession().getAttribute("SEC_USER_MEM") == null ? "" : (String) request.getSession().getAttribute("SEC_USER_MEM");//是否记忆用户名
    
	//单点跳转参数
	String tzcs=(String) request.getSession().getAttribute("cuo");
	String outUrl=TeeSysCustomerProps.getString("MHLJ");
	
    
	//菜单权限   所属的应用系统
	int sysId=TeeStringUtil.getInteger(request.getParameter("sysId"),0);	

      out.write("\r\n");
      out.write("<!DOCTYPE html >\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=Edge\">\r\n");
      out.write("<title>深圳法治政府信息平台</title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	TeePerson person = (TeePerson)request.getSession().getAttribute(TeeConst.LOGIN_USER);
	boolean isAdminPriv = TeePersonService.checkIsAdminPriv(person);
	boolean isSuperAdmin = TeePersonService.checkIsSuperAdmin(person,"");
	String isAdmin = person.getIsAdmin();

	Date date = person.getLastPassTime();
	String lastPassTime = "";
	if(date != null){
		lastPassTime = TeeDateUtil.getDateTimeStr(date);
	}
	int loginPersonId = person.getUuid();
	
	
	
	
	String SEC_INIT_PASS = (String) request.getSession().getAttribute("SEC_INIT_PASS") == null ? "0" : (String) request.getSession().getAttribute("SEC_INIT_PASS");//初始密码
	String SEC_PASS_FLAG = TeeStringUtil.getString( (String) request.getSession().getAttribute("SEC_PASS_FLAG"), "0");//是否过期
	String SEC_PASS_TIME = TeeStringUtil.getString((String) request.getSession().getAttribute("SEC_PASS_TIME"), "0");//过期时间
	String SEC_SHOW_IP = TeeStringUtil.getString((String) request.getSession().getAttribute("SEC_SHOW_IP"), "0");//是否显示IP
	String SEC_ON_STATUS = TeeStringUtil.getString((String) request.getSession().getAttribute("SEC_ON_STATUS"), "0");//记录在线状态
	
	int AVATAR_UPLOAD = TeeStringUtil.getInteger(request.getSession().getAttribute("AVATAR_UPLOAD"), 0 );//是否允许上传图象
	int AVATAR_WIDTH =  TeeStringUtil.getInteger(request.getSession().getAttribute("AVATAR_WIDTH"), 0 );//图象宽度
	int  AVATAR_HEIGHT = TeeStringUtil.getInteger(request.getSession().getAttribute("AVATAR_HEIGHT"),0);//图象高度
  
	String userName = person.getUserName();
	String userId = person.getUserId();
	int userSid = person.getUuid();
	TeeDepartment dept = person.getDept();
	String currUserDeptName  = "";
	String currUserRoleName = "";
	TeeUserRole role = person.getUserRole();
	if(dept != null){
		currUserDeptName = dept.getDeptName();
	}
	if(role != null){
		currUserRoleName = role.getRoleName();
	}
	String avatar = person.getAvatar();
	//用于判断用户性别
	String avatar_default = "";
	if(("0".equals(person.getSex())) && TeeUtility.isNullorEmpty(person.getAvatar())){
		avatar_default = "0";  //0代表男
	}else if(("1".equals(person.getSex())) && TeeUtility.isNullorEmpty(person.getAvatar())){
		avatar_default = "1";  //1代表女
	}

      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("/** 变量定义 **/\r\n");
      out.write("var isAdminPriv = '");
      out.print(isAdminPriv);
      out.write("';\r\n");
      out.write("var isSuperAdmin = '");
      out.print(isSuperAdmin);
      out.write("';\r\n");
      out.write("var loginPersonId = ");
      out.print(loginPersonId);
      out.write(";\r\n");
      out.write("var lastPassTime = '");
      out.print(lastPassTime);
      out.write("';\r\n");
      out.write("\r\n");
      out.write("var SEC_SHOW_IP =  '");
      out.print(SEC_SHOW_IP);
      out.write("';\r\n");
      out.write("var SEC_ON_STATUS =  '");
      out.print(SEC_ON_STATUS);
      out.write("';\r\n");
      out.write("var AVATAR_UPLOAD =  '");
      out.print(AVATAR_UPLOAD);
      out.write("';\r\n");
      out.write("var AVATAR_WIDTH =  '");
      out.print(AVATAR_WIDTH);
      out.write("';\r\n");
      out.write("var AVATAR_HEIGHT =  '");
      out.print(AVATAR_HEIGHT);
      out.write("';\r\n");
      out.write("var userId = \"");
      out.print(userId);
      out.write("\";\r\n");
      out.write("var userName = \"");
      out.print(userName);
      out.write("\";\r\n");
      out.write("var avatar = \"");
      out.print(avatar);
      out.write("\";\r\n");
      out.write("var avatar_default = \"");
      out.print(avatar_default);
      out.write("\";\r\n");
      out.write("</script>");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/one.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/reset.css\">\r\n");
      out.write("<!-- 其他工具库类 -->\r\n");
      out.write("<script src=\"");
      out.print(contextPath );
      out.write("/common/zt_webframe/js/jquery-1.11.1.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(contextPath );
      out.write("/common/js/tools.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(contextPath );
      out.write("/common/js/sys2.0.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(contextPath );
      out.write("/common/js/sysUtil.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(contextPath );
      out.write("/common/js/src/orgselect.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(contextPath);
      out.write("/common/js/easyuiTools.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(contextPath );
      out.write("/common/zt_webframe/js/package.js\"></script>\r\n");
      out.write("<script src=\"js/divscroll.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" >\r\n");
      out.write("window.UEDITOR_HOME_URL = \"");
      out.print(contextPath);
      out.write("/common/ueditor/\";\r\n");
      out.write("$.browser = {};\r\n");
      out.write("$.browser.mozilla = /firefox/.test(navigator.userAgent.toLowerCase());\r\n");
      out.write("$.browser.webkit = /webkit/.test(navigator.userAgent.toLowerCase());\r\n");
      out.write("$.browser.opera = /opera/.test(navigator.userAgent.toLowerCase());\r\n");
      out.write("$.browser.msie = /msie/.test(navigator.userAgent.toLowerCase());\r\n");
      out.write("</script>\r\n");
      out.write("<!-- 图片预览器 -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(contextPath);
      out.write("/common/js/lazyloader.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/index.css?v=1\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/common/zt_webframe/css/package1.css\">\r\n");
      out.write(" <script type=\"text/javascript\" src=\"");
      out.print(contextPath);
      out.write("/system/frame/3/js/jquery.SuperSlide.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(contextPath);
      out.write("/system/frame/4/js/index2.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(contextPath);
      out.write("/system/frame/2/js/index.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(contextPath);
      out.write("/system/frame/2/js/sms.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(contextPath);
      out.write("/common/jbox-v2.3/jBox/jquery.jBox-2.3.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(contextPath);
      out.write("/common/jbox-v2.3/jBox/i18n/jquery.jBox-zh-CN.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(contextPath);
      out.write("/system/frame/3/js/tabs.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("var loginUserRoleId=0;\r\n");
      out.write("var  sysId=");
      out.print(sysId );
      out.write(";\r\n");
      out.write("/** 常量定义 **/\r\n");
      out.write("var TDJSCONST = {\r\n");
      out.write("  YES: 1,\r\n");
      out.write("  NO: 0\r\n");
      out.write("};\r\n");
      out.write("/** 变量定义 **/\r\n");
      out.write("var contextPath = \"");
      out.print(contextPath );
      out.write("\";\r\n");
      out.write("var imgPath = \"");
      out.print(imgPath );
      out.write("\";\r\n");
      out.write("var cssPath = \"");
      out.print(cssPath);
      out.write("\";\r\n");
      out.write("var stylePath = \"");
      out.print(stylePath);
      out.write("\";\r\n");
      out.write("var cssPathSecond = \"");
      out.print(cssPathSecond);
      out.write("\";\r\n");
      out.write("var imgPathSecond = \"");
      out.print(imgPathSecond);
      out.write("\";\r\n");
      out.write("var loginOutText = \"");
      out.print(loginOutText);
      out.write("\";\r\n");
      out.write("var uploadFlashUrl = \"");
      out.print(contextPath );
      out.write("/common/swfupload/swfupload.swf\";\r\n");
      out.write("var commonUploadUrl = \"");
      out.print(contextPath );
      out.write("/attachmentController/commonUpload.action\";\r\n");
      out.write("var systemImagePath = \"");
      out.print(systemImagePath);
      out.write("\";\r\n");
      out.write("var xparent;\r\n");
      out.write("var tzcs=\"");
      out.print(tzcs);
      out.write("\";\r\n");
      out.write("var outUrl=\"");
      out.print(outUrl);
      out.write("\";\r\n");
      out.write("if(window.dialogArguments){\r\n");
      out.write("\txparent = window.dialogArguments;\r\n");
      out.write("}else if(window.opener){\r\n");
      out.write("\txparent = opener;\r\n");
      out.write("}else{\r\n");
      out.write("\txparent = window;\r\n");
      out.write("}\r\n");
      out.write("function parseNumber(value, defValue) {\r\n");
      out.write("  if (isNaN(value)) {\r\n");
      out.write("    return defValue;\r\n");
      out.write("  }\r\n");
      out.write("  return value * 1;\r\n");
      out.write("}\r\n");
      out.write("/**\r\n");
      out.write("*\r\n");
      out.write("*注销\r\n");
      out.write("*/\r\n");
      out.write("function doLogout(){\r\n");
      out.write("\tvar msg = loginOutText + \"\\n确定要注销吗?\";\r\n");
      out.write("\t$.MsgBox.Confirm(\"提示\",msg,function(){\r\n");
      out.write("\t\tvar url = contextPath + \"/systemAction/doLoginout.action\";\r\n");
      out.write("\t\tvar para = {};\r\n");
      out.write("\t\tvar jsonObj = tools.requestJsonRs(url,para);\r\n");
      out.write("\t\tif(jsonObj){\r\n");
      out.write("\t\t\tvar json = jsonObj.rtData;\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\t$.MsgBox.Alert(\"提示\", jsonObj.rtMsg);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\twindow.location.href =contextPath+\"/login.jsp\";\r\n");
      out.write("});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function closeLogin(){\r\n");
      out.write("\tvar url = contextPath + \"/systemAction/doLoginout.action\";\r\n");
      out.write("\tvar para = {};\r\n");
      out.write("\tvar jsonObj = tools.requestJsonRs(url,para);\r\n");
      out.write("\twindow.close();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function remindCheck(){\r\n");
      out.write("\ttools.requestJsonRs(contextPath+\"/sms/remindCheck.action\",{},true,function(json){\r\n");
      out.write("\t\tif(json.rtState){\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif(json.rtData.smsFlag!=0){//弹出短消息\r\n");
      out.write("\t\t\t\tmsgFrame.playSound(2);\r\n");
      out.write("\t\t\t\tif(autoPopSms==\"0\"){\r\n");
      out.write("\t\t\t\t\tshake();\r\n");
      out.write("\t\t\t\t\t$('.sign_in_tid').show();\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\tsmsAlert();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(json.rtData.msgFlag!=0){//弹出通讯消息\r\n");
      out.write("\t\t\t\tmsgFrame.playSound(1);\r\n");
      out.write("\t\t\t\tvar offlineMsgJson = tools.requestJsonRs(contextPath+\"/messageManage/getOfflineMessages.action\");\r\n");
      out.write("\t\t\t\tfor(var i=0;i<offlineMsgJson.rtData.length;i++){\r\n");
      out.write("\t\t\t\t\tsocketHandler(offlineMsgJson.rtData[i]);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tofflineMsgJson = null;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tsetTimeout(\"remindCheck()\",10*1000);//10秒\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("function smsDetails(){\r\n");
      out.write("\topenFullWindow(contextPath+'/system/core/sms/index.jsp',\"消息事务\");\r\n");
      out.write("\t$(\"#smsbox\").hide();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function openFullWindow(actionUrl, title) {\r\n");
      out.write("\t  var winParam = \"menubar=0,toolbar=0,status=0\";\r\n");
      out.write("\t  winParam += \",scrollbars=1,resizable=1\";\r\n");
      out.write("\t  var left = 0;\r\n");
      out.write("\t  var top = 0;\r\n");
      out.write("\t  var width = window.screen.availWidth;\r\n");
      out.write("\t  var height = window.screen.availHeight;\r\n");
      out.write("//\t  if($.browser.webkit){\r\n");
      out.write("//\t\t  height = parseInt(height)-60;\r\n");
      out.write("//\t  }\r\n");
      out.write("\t  height = parseInt(height)-80;\r\n");
      out.write("\t  winParam += \",width=\" + width;\r\n");
      out.write("\t  winParam += \",height=\" + height;\r\n");
      out.write("\t  winParam += \",top=\" + top;\r\n");
      out.write("\t  winParam += \",left=\" + left;\r\n");
      out.write("\t  winParam += \",location=no\";\r\n");
      out.write("\t  \r\n");
      out.write("\t  try{\r\n");
      out.write("\t\t  if(window.external && window.external.IM_OA){\r\n");
      out.write("\t\t\twindow.external.IM_OpenNavigation(title,actionUrl.replace(contextPath,\"\"),0,0);\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t  }\r\n");
      out.write("\t  }catch(e){\r\n");
      out.write("\t\t  \r\n");
      out.write("\t  }\r\n");
      out.write("\t  \r\n");
      out.write("\t  return window.open(actionUrl, new Date().getTime()+\"\", winParam);\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction souSuo(){\r\n");
      out.write("\t\tvar souSouContent=$(\"#souSouContent\").val();\r\n");
      out.write("\t\topenFullWindow(\"");
      out.print(contextPath );
      out.write("/system/core/base/quicksearch/search_result_new.jsp?souSouContent=\"+souSouContent,\"搜索\");\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction doinit(){\r\n");
      out.write("\t\t$(\".left-z\").click();\r\n");
      out.write("\t\t$.addTab(\"tabs\",\"tabs-content\",{title:\"工作台\",url:contextPath + \"/system/frame/default/mainForSimple.jsp\",active:true,cache:false});\r\n");
      out.write("\t\tgetSysMenu();\r\n");
      out.write("\t\trenderLoginUserInfo();\r\n");
      out.write("\t\t $(\"body\").on(\"click\",\".inactive\",function(){\r\n");
      out.write("\t         if ($(this).siblings('ul:first').css('display') == 'none') {\r\n");
      out.write("\t             $(this).addClass('inactives');\r\n");
      out.write("\t             $(this).siblings('ul:first').slideDown(100);\r\n");
      out.write("\t             if($(this).hasClass(\"cole\")){\r\n");
      out.write("\t                 $(this).siblings('ul:first').addClass(\"ac\");\r\n");
      out.write("\t             }\r\n");
      out.write("\t         } else {\r\n");
      out.write("\t             //控制自身变成+号\r\n");
      out.write("\t             $(this).removeClass('inactives');\r\n");
      out.write("\t             //控制自身菜单下子菜单隐藏\r\n");
      out.write("\t             $(this).siblings('ul:first').slideUp(100);\r\n");
      out.write("\t             //控制自身子菜单变成+号\r\n");
      out.write("\t             $(this).siblings('ul:first').children('li').children('ul').parent('li').children('h1').addClass('inactives');\r\n");
      out.write("\t             //控制自身菜单下子菜单隐藏\r\n");
      out.write("\t             $(this).siblings('ul:first').children('li').children('ul').slideUp(100);\r\n");
      out.write("\t             //控制同级菜单只保持一个是展开的（-号显示）\r\n");
      out.write("\t             $(this).siblings('ul:first').children('li').children('h1').removeClass('inactives');\r\n");
      out.write("\t             if($(this).hasClass(\"cole\")){\r\n");
      out.write("\t                 $(this).siblings('ul:first').removeClass(\"ac\");\r\n");
      out.write("\t             }\r\n");
      out.write("\t         }\r\n");
      out.write("\t\t });\r\n");
      out.write("\t\t $('.ul1').perfectScrollbar();\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction NewPageINfo(title,url){\r\n");
      out.write("\t\t$.addTab(\"tabs\",\"tabs-content\",{title:title,url:contextPath + url,active:true,cache:true,closable:true});\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t//获取当前登陆人基本信息\r\n");
      out.write("\tfunction renderLoginUserInfo(){\r\n");
      out.write("\t   var url=contextPath+\"/personManager/getLoginUserInfo.action\";\r\n");
      out.write("\t   var json=tools.requestJsonRs(url);\r\n");
      out.write("\t   if(json.rtState){\r\n");
      out.write("\t\t   var data=json.rtData;\r\n");
      out.write("\t\t   loginUserRoleId=data.roleId;\r\n");
      out.write("\t\t   $(\"#userName\").text(data.userName);\r\n");
      out.write("\t\t   $(\"#deptName\").text(data.deptName);\r\n");
      out.write("\t\t   if(data.tx!=0){\r\n");
      out.write("\t\t\t   //height: 50px;width: 50px;position: fixed;right: 136px;top: 14px;background:url('/system/frame/classic/image/images/02.png') round ;border-radius: 50%;\r\n");
      out.write("\t\t\t   $(\"#txDiv\").attr(\"style\",\"height: 50px;width: 50px;position: fixed;right: 136px;top: 14px;background:url('/attachmentController/downFile.action?id=\"+data.tx+\"') round ;border-radius: 50%;\");\r\n");
      out.write("\t\t   }\r\n");
      out.write("\t   }\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t//返回\r\n");
      out.write("\tfunction goBack(){\r\n");
      out.write("\t\twindow.location.href = \"");
      out.print(contextPath);
      out.write("/system/frame/html/templates/admin/index.jsp\";\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("<style>\r\n");
      out.write(".active{\r\n");
      out.write("text-color:#000;\r\n");
      out.write("color:#fff;\r\n");
      out.write("}\r\n");
      out.write(".menu{\r\n");
      out.write("\tcolor:#95b8e7;\r\n");
      out.write("cursor: pointer;\r\n");
      out.write("border-radius: 5px;\r\n");
      out.write("border: 1px solid rgb(203,203,203);\r\n");
      out.write("background: white;\r\n");
      out.write("text-align: center;\r\n");
      out.write("top:0;\r\n");
      out.write("left:0;\r\n");
      out.write("z-index: 10000;\r\n");
      out.write("display: none;\r\n");
      out.write("width: 80px; /*设置为0 隐藏自定义菜单*/\r\n");
      out.write("height: 24px;\r\n");
      out.write("line-height: 24px;\r\n");
      out.write("overflow: hidden; /*隐藏溢出的元素*/\r\n");
      out.write("box-shadow: 0 1px 1px #888,1px 0 1px #ccc;\r\n");
      out.write("position: absolute; /*自定义菜单相对与body元素进行定位*/\r\n");
      out.write("}\r\n");
      out.write("\t.menu:hover{\r\n");
      out.write("\tbackground:#95b8e7;\r\n");
      out.write("\tcolor:white;\r\n");
      out.write("\t}\r\n");
      out.write(".tee_tab_pointer_right{ width:18px; height:40px;  background:url(/system/frame/3/style/images/header/nav_left.png) no-repeat; text-indent:-9999px; cursor:pointer;}\r\n");
      out.write(".tee_tab_pointer_left{ width:18px; height:40px;  background:url(/system/frame/3/style/images/header/nav_right.png) no-repeat;text-indent:-9999px; cursor:pointer;}\r\n");
      out.write(".tee_tab{ float:left; height:40px;line-height:40px; text-align:center; color:#000; padding:0 15px; font-size:14px; cursor:pointer;background:#fff;border-top:1px solid #cdcdcd;border-right:1px solid #cdcdcd;}\r\n");
      out.write(".tee_tab i{width:12px; height:10px; position:absolute; right:5px; top:10px; background:url(delete.png) no-repeat; cursor:pointer; z-index:11111111; display:block;}\r\n");
      out.write(".tee_tab.tee_tab_select i{ display:block; width:12px; height:10px; position:absolute; right:1px; top:5px; background:url(delete.png) no-repeat; cursor:pointer; z-index:11111111;}\r\n");
      out.write("#tabs .tee_tab.tee_tab_select{ background:#fff; position:relative; font-weight:bold;color:rgb(67, 129, 230);border-bottom:1px solid rgb(67, 129, 230)}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body onload=\"doinit();\" >\r\n");
      out.write("<div class=\"body1\">\r\n");
      out.write("    <div class=\"nav\" style=\"overflow: hidden\">\r\n");
      out.write("        <div class=\"logo\">\r\n");
      out.write("            <img src=\"image/1.png\" alt=\"\" style=\"width: 100% ;height: 100%\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"nav1-right\" style=\"float: right\">\r\n");
      out.write("            <div class=\"tu-b\">\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li>\r\n");
      out.write("\t\t\t\t\t\t<div style=\"color: white;font-size: 14px;\"><span id=\"userName\"></span></div>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li title=\"返回平台\">\r\n");
      out.write("                    \t<a href=\"javascript:void(0)\" onclick=\"goBack();\" ><img src=\"image/icon_home.png\" alt=\"\" class=\"img\" ></a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li>\r\n");
      out.write("                    \t<a href=\"javascript:void(0)\" onclick=\"NewPageINfo('个人设置','");
      out.print(contextPath );
      out.write("/system/core/person/setdescktop/index.jsp')\" title=\"个人设置\"><img src=\"image/shezhi.png\" alt=\"\" class=\"img\" ></a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li title=\"消息中心\">\r\n");
      out.write("                    \t<a href=\"javascript:void(0)\" ><img id=\"tip_alert\" src=\"image/8.png\" alt=\"\" class=\"img\"></a><div class=\"sign_in_tid\" style=\"display:none\">新的消息！</div>\r\n");
      out.write("                    </li>\r\n");
      out.write("\t\t\t\t\t<li title=\"组织机构\"><a href=\"javascript:void(0)\"><img src=\"image/7.png\" alt=\"\" class=\"img group fl\"></a>\r\n");
      out.write("\t\t\t\t\t\t<div id='groupContent' style='width:240px;position:fixed;right:-240px;top:77px;bottom:3px;z-index:99999;box-shadow:0 0 15px #a2a2a2;'>\r\n");
      out.write("\t\t\t\t\t\t\t<iframe style='width:100%;height:100%;' id='right' src=\"/system/frame/3/right.jsp\" frameborder=\"0\"></iframe>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<!-- 注销 -->\r\n");
      out.write("                     <li>\r\n");
      out.write("                     \t<a href=\"javascript:void(0)\" ><img src=\"image/6.png\" alt=\"\" class=\"img\" onclick=\"doLogout();\"></a>\r\n");
      out.write("                    </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div><!--顶部-->\r\n");
      out.write("    <div id=\"ft\">\r\n");
      out.write("        <div class=\"header-left\" style=\"overflow:hidden;position:absolute;width:73px;left:0px;top:78px;bottom:0px;border-top:0px;padding-bottom: 20px\">\r\n");
      out.write("\t        <div class=\"left-z\" style=\" opacity: 0; position: fixed; top: 50%; left: 60px; z-index: 1000000;\"><img src=\"imgs/index/left-z.png\" alt=\"\"></div>\r\n");
      out.write("\t        <div class=\"left-y\" style=\" opacity: 0; position: fixed; top: 50%; left: 240px; z-index: 0;\"><img src=\"imgs/index/left-y.png\" alt=\"\"></div>\r\n");
      out.write("            <div class=\"ul1\" style=\"overflow:auto;width:100%;height:100%\">\r\n");
      out.write("                <ul class=\"yiji ul2\" id=\"yijiCanDan\">\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div><!--左边--->\r\n");
      out.write("        <div style=\"position: absolute;left:85px;top:80px;bottom:0px;right:0px\" id=\"id\">\r\n");
      out.write("            <div id=\"tabs\" style=\"border-left:1px solid #cdcdcd;position: absolute;left:0px;top:0px;height:40px;right:10px;\">\r\n");
      out.write("            \t\r\n");
      out.write("            </div>\r\n");
      out.write("            <div id=\"tabs-content\" style=\"position: absolute;left:0px;top:41px;bottom:10px;right:10px;border:1px solid #cdcdcd\">\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- 短消息面板 -->\r\n");
      out.write("\t\t<div class=\"smsbox\" id=\"smsbox\" style=\"display: none;\">\r\n");
      out.write("\t\t\t<div class=\"title\">\r\n");
      out.write("\t\t\t<span style=\"float:left;\">消息提醒</span>\r\n");
      out.write("\t\t\t<span class='sms_close_win' style=\"float:right;font-size:16px;cursor:pointer\" onclick=\"$('#smsbox').hide()\">×</span>\r\n");
      out.write("\t\t\t<span style=\"float:right;cursor:pointer;margin-top:3px;background-image:url(imgs/index/read.png);\" class=\"sms_list smsbox_icon2\" onclick=\"smsDetails()\">消息列表</span>\r\n");
      out.write("\t\t\t<span style=\"float:right;cursor:pointer;margin-top:3px;background-image:url(imgs/index/cancel.png);\" class=\"all_check smsbox_icon1\" onclick=\"smsViewAlls()\">全部已阅</span>\r\n");
      out.write("\t\t\t<div style=\"clear:both\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"content\" id=\"smsBoxContent\">\r\n");
      out.write("\t\t\t\t<div class=\"smsbox_loadmore\" id=\"loadMore\">\r\n");
      out.write("\t\t\t\t\t查看更多\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(document).ready(function () {\r\n");
      out.write("\t$('.header-left').prepend($(\"#ascrail2000\"));\r\n");
      out.write("\t    $('.header-left').bind(\"mouseenter\", function () {\r\n");
      out.write("\t        $(this).unbind(\"mouseleave\").bind(\"mouseleave\", function () {\r\n");
      out.write("\t          $('.left-z').animate({\r\n");
      out.write("\t            opacity: 0\r\n");
      out.write("\t           }, 300);\r\n");
      out.write("\r\n");
      out.write("\t          });\r\n");
      out.write("\t         $('.left-z').animate({\r\n");
      out.write("\t           opacity: 1\r\n");
      out.write("\t          }, 300);\r\n");
      out.write("\t$('.header-left').prepend($(\"#ascrail2000\"));\r\n");
      out.write("\t         });\r\n");
      out.write("\r\n");
      out.write("\t   });\r\n");
      out.write("\r\n");
      out.write("\t$(document).ready(function () {\r\n");
      out.write("\t    $('.header-left').bind(\"mouseenter\", function () {\r\n");
      out.write("\t        $(this).unbind(\"mouseout\").bind(\"mouseleave\", function () {\r\n");
      out.write("\t          $('.left-y').animate({\r\n");
      out.write("\t            opacity: 0\r\n");
      out.write("\t          }, 300);\r\n");
      out.write("\r\n");
      out.write("\t       });\r\n");
      out.write("\t          $('.left-y').animate({\r\n");
      out.write("\t            opacity: 1\r\n");
      out.write("\t          }, 300);\r\n");
      out.write("\r\n");
      out.write("\t       });\r\n");
      out.write("\t    });\r\n");
      out.write("var autoPopSms = \"");
      out.print(person.getAutoPopSms());
      out.write("\";\r\n");
      out.write("    $(function () {\r\n");
      out.write("\t\t$(\".dian,#txDiv\").click(function(){\r\n");
      out.write("\t\t\t$(\".bao\").toggle(100);\r\n");
      out.write("\t});\r\n");
      out.write("    \tremindCheck();\r\n");
      out.write("        $(\".left-z,.ul1 ul\").click(function () {\r\n");
      out.write("            $(\"#id\").css('left', '270px');\r\n");
      out.write("            $(\".header-left\").css('width', '260px');\r\n");
      out.write("            $(\".menu_text\").show();\r\n");
      out.write("            $(\".ul1 ul li .cole\").css('background-color', 'rgb(25, 47, 71)');\r\n");
      out.write("            $(\".ul1\").css({\"width\": \"210px\", \"margin\": \"20px auto 0 auto\"});\r\n");
      out.write("            $(\".header-left .ul1 ul li img\").css({\r\n");
      out.write("                \"width\": \" 36px\",\r\n");
      out.write("                \"height\": \"36px\",\r\n");
      out.write("                \"margin-top\": \"8px\",\r\n");
      out.write("                \"margin-left\": \"10px\",\r\n");
      out.write("                \"padding-right\": \"10px\"\r\n");
      out.write("            });\r\n");
      out.write("            $(\".ac\").show();\r\n");
      out.write("\t$(\".left-y\").show();\r\n");
      out.write("\t$(\".left-z\").hide();\r\n");
      out.write("        });\r\n");
      out.write("       \r\n");
      out.write("        $(\".left-y\").click(function () {\r\n");
      out.write("            $(\"#id\").css('left', '80px');\r\n");
      out.write("            $(\".header-left\").css('width', '73px');\r\n");
      out.write("            $(\".menu_text\").hide();\r\n");
      out.write("            $(\".header-left .ul1 ul li img\").css({\"width\": \" 44px\", \"height\": \"44px\", \"margin-left\": \"14px\"});\r\n");
      out.write("            $(\".ul1 ul li .cole\").css('background-color', 'rgb(25, 47, 71)');\r\n");
      out.write("            $(\".ul1\").css({\"width\": \"73px\", \"margin\": \"12px auto 0 auto\"});\r\n");
      out.write("            $(\".ac\").hide();\r\n");
      out.write("\t$(\".left-z\").show();\r\n");
      out.write("\t$(\".left-y\").hide();\r\n");
      out.write("        });\r\n");
      out.write("      //登记登出\r\n");
      out.write("\t\t$(\".sign_img\").on(\"click\",function(){\r\n");
      out.write("\t\t\t$(\".signin_out\").slideToggle(50);\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(\".signin_out\").on(\"mouseleave\",function(){\r\n");
      out.write("\t\t\t$(\".signin_out\").slideToggle(50);\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t//消息提醒\r\n");
      out.write("\t\tvar tip_zhezhao = \"<div class='tip_zhezhao' style='width:100%;height:100%;z-index: 9999;position: fixed;filter:Alpha(opacity=60);background-color: #000;top: 0;left: 0;opacity: 0.6;'></div>\";\r\n");
      out.write("\t\t$(\"#tip_alert\").on(\"click\",function(){\r\n");
      out.write("\t\t\t$(\"body\").append(tip_zhezhao);\r\n");
      out.write("\t\t\t$(\".smsbox\").fadeIn(200);\r\n");
      out.write("\t\t\tsmsAlert();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$(\"body\").on(\"click\",\".sms_close_win,.sms_list,.all_check\",function(){\r\n");
      out.write("\t\t\t$(\".tip_zhezhao\").remove();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t//组织架构显示\r\n");
      out.write("\t\t$(\"body\").on(\"click\",\".group\",function(){\r\n");
      out.write("\t\t\tif($(\"#groupContent\").css(\"right\")==\"0px\"){\r\n");
      out.write("\t\t\t\t$(\"#groupContent\").animate({right:\"-240px\"},300);\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\t$(\"#groupContent\").animate({right:\"0px\"},300);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t \r\n");
      out.write("    })\r\n");
      out.write("    function getSysMenu(){\r\n");
      out.write("    \t   //获取当前登陆人快捷菜单ids\r\n");
      out.write("    \t   var urls=contextPath+\"/personManager/getQuickMenuIds.action\";\r\n");
      out.write("    \t   var json=tools.requestJsonRs(urls);\r\n");
      out.write("    \t   var quickMenuIds=json.rtData;\r\n");
      out.write("    \t\r\n");
      out.write("    \t\r\n");
      out.write("    \t\ttools.requestJsonRs(contextPath+\"/teeMenuGroup/getPrivSysMenu2.action\",{sysId:sysId},true,function(json){\r\n");
      out.write("    \t\t\tvar data=json.rtData;\r\n");
      out.write("    \t\t\tif(data!=null){\r\n");
      out.write("    \t\t\t\tvar one=data.one;\r\n");
      out.write("    \t\t\t\tvar two=data.two;\r\n");
      out.write("    \t\t\t\tvar three=data.three;\r\n");
      out.write("    \t\t\t\t//一级菜单\r\n");
      out.write("    \t\t\t\tif(one!=null){\r\n");
      out.write("    \t\t\t\t\tfor(var i=0;i<one.length;i++){\r\n");
      out.write("    \t\t\t\t\t\tvar menuId=one[i].menuId;\r\n");
      out.write("    \t\t\t\t\t\tvar menuName=one[i].menuName;\r\n");
      out.write("    \t\t\t\t\t\tvar menuCode=one[i].menuCode;\r\n");
      out.write("    \t\t\t\t\t\tvar icon=one[i].icon;\r\n");
      out.write("    \t\t\t\t\t\tvar caiDanFalg=one[i].caiDanFalg;\r\n");
      out.write("    \t\t\t\t\t\tvar html=\"<li>\";\r\n");
      out.write("    \t\t\t\t\t\t       if(caiDanFalg){\r\n");
      out.write("\t    \t\t\t\t\t\t       html+=\"<h1 class='inactive active cole' style='height: 50px;line-height: 50px;border-radius:5px;' title='\"+menuName+\"'>\";\r\n");
      out.write("\t    \t\t\t\t\t\t         html+=\"<img src='icons/\"+icon+\"' onerror=\\\"this.src='icons/xtgl.png'\\\" alt='' style='float: left'>\";\r\n");
      out.write("\r\n");
      out.write("\t    \t\t\t\t\t\t         html+=\"<span  style='display: none;font-size:16px;font-family:微软雅黑' class='menu_text'>\"+menuName+\"</span>\";\r\n");
      out.write("\t    \t\t\t\t\t\t       html+=\"</h1>\";\r\n");
      out.write("    \t\t\t\t\t\t    \t   html+=\"<ul class='' id='one_\"+menuId+\"'></ul>\";\r\n");
      out.write("    \t\t\t\t\t\t       }else{\r\n");
      out.write("    \t\t\t\t\t\t    \t   html+=\"<h1 onclick=\\\"NewPageINfo('\"+menuName+\"','\"+menuCode+\"')\\\" class='active cole' style='height: 50px;line-height: 50px;border-radius:5px;'>\";\r\n");
      out.write("      \t\t\t\t\t\t             html+=\"<img src='icons/\"+icon+\"''  onerror=\\\"this.src='icons/xtgl.png'\\\" alt='' style='float: left'>\";\r\n");
      out.write("      \t\t\t\t\t\t             html+=\"<span  style='display: none;font-size:16px;font-family:微软雅黑' class='menu_text'>\"+menuName+\"</span>\";\r\n");
      out.write("      \t\t\t\t\t\t           html+=\"</h1>\";\r\n");
      out.write("    \t\t\t\t\t\t       }\r\n");
      out.write("    \t\t\t\t\t\t     html+=\"</li>\"\r\n");
      out.write("    \t\t\t\t\t\t $(\"#yijiCanDan\").append(html);\r\n");
      out.write("    \t\t\t\t\t}\r\n");
      out.write("    \t\t\t\t}\r\n");
      out.write("    \t\t\t\t//二级菜单\r\n");
      out.write("    \t\t\t\tif(two!=null){\r\n");
      out.write("    \t\t\t\t\tfor(var i=0;i<two.length;i++){\r\n");
      out.write("    \t\t\t\t\t\tvar menuId=two[i].menuId;\r\n");
      out.write("    \t\t\t\t\t\tvar menuName=two[i].menuName;\r\n");
      out.write("    \t\t\t\t\t\tvar menuCode=two[i].menuCode;\r\n");
      out.write("    \t\t\t\t\t\tvar icon=two[i].icon;\r\n");
      out.write("    \t\t\t\t\t\tvar caiDanFalg=two[i].caiDanFalg;\r\n");
      out.write("    \t\t\t\t\t\tvar pmenuId=menuId.substring(0,3);\r\n");
      out.write("    \t\t\t\t\t\tvar uuid=two[i].uuid;\r\n");
      out.write("    \t\t\t\t\t\t//判断是否是快捷菜单\r\n");
      out.write("    \t\t\t\t\t\tvar isQm=isQuickMenu(quickMenuIds,uuid);\r\n");
      out.write("    \t\t\t\t\t\t\r\n");
      out.write("    \t\t\t\t\t\tvar html=\"<li>\";\r\n");
      out.write("    \t\t\t\t\t\t       if(caiDanFalg){\r\n");
      out.write("    \t\t\t\t\t\t           html+=\"<h1 class='inactive active' style='height: 50px;line-height: 50px;padding-left: 65px ;margin-top: -5px;margin-bottom:-5px' title='\"+menuName+\"'><span class='menu_text'>\"+menuName+\"</span></h1>\";\r\n");
      out.write("    \t\t\t\t\t\t    \t   html+=\"<ul id='two_\"+menuId+\"'>\";\r\n");
      out.write("\r\n");
      out.write("    \t\t\t\t\t\t    \t   html+=\"</ul>\";\r\n");
      out.write("    \t\t\t\t\t\t       }else{\r\n");
      out.write("    \t\t\t\t\t\t    \t   if(isQm==0){\r\n");
      out.write("    \t\t\t\t\t\t    \t\t   html+=\"<div uuid='\"+uuid+\"'  style='position: relative;left: 35px;float: left;width: 20px;height: 20px;top: 15px;' class='kjfs-img img-001'></div><h1 title='\"+menuName+\"' class='active' onclick=\\\"NewPageINfo('\"+menuName+\"','\"+menuCode+\"')\\\" style='height: 50px;line-height: 50px;padding-left:65px ;margin-top: -5px;margin-bottom:-5px'><span class='menu_text'>\"+menuName+\"</span></h1>\";\r\n");
      out.write("    \t\t\t\t\t\t    \t   }else if(isQm==1){\r\n");
      out.write("    \t\t\t\t\t\t    \t\t   html+=\"<div uuid='\"+uuid+\"' style='position: relative;left: 35px;float: left;width: 20px;height: 20px;top: 15px;' class='kjfs-img img-002'></div><h1 title='\"+menuName+\"' class='active' onclick=\\\"NewPageINfo('\"+menuName+\"','\"+menuCode+\"')\\\" style='height: 50px;line-height: 50px;padding-left:65px ;margin-top: -5px;margin-bottom:-5px'><span class='menu_text'>\"+menuName+\"</span></h1>\";\r\n");
      out.write("    \t\t\t\t\t\t    \t   }\r\n");
      out.write("    \t\t\t\t\t\t           \r\n");
      out.write("    \t\t\t\t\t\t       }\r\n");
      out.write("    \t\t\t\t\t\t    html+=\"</li>\";\r\n");
      out.write("    \t\t\t\t\t\t$(\"#one_\"+pmenuId).append(html);\r\n");
      out.write("    \t\t\t\t\t}\r\n");
      out.write("    \t\t\t\t}\r\n");
      out.write("    \t\t\t\t//三级菜单\r\n");
      out.write("    \t\t\t\tif(three!=null){\r\n");
      out.write("    \t\t\t\t\tfor(var i=0;i<three.length;i++){\r\n");
      out.write("    \t\t\t\t\t\tvar menuId=three[i].menuId;\r\n");
      out.write("    \t\t\t\t\t\tvar menuName=three[i].menuName;\r\n");
      out.write("    \t\t\t\t\t\tvar menuCode=three[i].menuCode;\r\n");
      out.write("    \t\t\t\t\t\tvar icon=three[i].icon;\r\n");
      out.write("    \t\t\t\t\t\tvar caiDanFalg=three[i].caiDanFalg;\r\n");
      out.write("    \t\t\t\t\t\tvar pmenuId=menuId.substring(0,6);\r\n");
      out.write("\r\n");
      out.write("    \t\t\t\t\t\tvar uuid=three[i].uuid;\r\n");
      out.write("    \t\t\t\t\t\t//判断是否是快捷菜单\r\n");
      out.write("    \t\t\t\t\t\tvar isQm=isQuickMenu(quickMenuIds,uuid);\r\n");
      out.write("    \t\t\t\t\t\tif(isQm==0){\r\n");
      out.write("    \t\t\t\t\t\t\tvar html=\"<li><div uuid='\"+uuid+\"' style='position: relative;left: 35px;float: left;width: 20px;height: 20px;top: 15px;' class='kjfs-img img-001'></div><h1 title='\"+menuName+\"' onclick=\\\"NewPageINfo('\"+menuName+\"','\"+menuCode+\"')\\\" style='height: 50px;line-height: 50px;padding-left: 80px;margin-top: -5px;margin-bottom: -5px'><span class='menu_text'>\"+menuName+\"</span></h1></li>\";\r\n");
      out.write("    \t\t\t\t\t\t}else if(isQm==1){\r\n");
      out.write("    \t\t\t\t\t\t\tvar html=\"<li><div  uuid='\"+uuid+\"' style='position: relative;left: 35px;float: left;width: 20px;height: 20px;top: 15px;' class='kjfs-img img-002'></div><h1 title='\"+menuName+\"' onclick=\\\"NewPageINfo('\"+menuName+\"','\"+menuCode+\"')\\\" style='height: 50px;line-height: 50px;padding-left: 80px;margin-top: -5px;margin-bottom: -5px'><span class='menu_text'>\"+menuName+\"</span></h1></li>\";\r\n");
      out.write("    \t\t\t\t\t\t}\r\n");
      out.write("    \t\t\t\t\t\t\r\n");
      out.write("    \t\t\t\t\t\t$(\"#two_\"+pmenuId).append(html);\r\n");
      out.write("    \t\t\t\t\t}\r\n");
      out.write("    \t\t\t\t}\r\n");
      out.write("    \t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t//$(\".kjfs-img\").addClass('img-001'); // 初始化时添加背景1\r\n");
      out.write("\t\t\t\t$(\".kjfs-img\").click(function() {\r\n");
      out.write("\t\t\t\t\tvar is001 =$(this).hasClass(\"img-001\");\r\n");
      out.write("\t\t\t\t\tif(is001){//标为快捷菜单\r\n");
      out.write("\t\t\t\t\t\tvar uuid=$(this).attr(\"uuid\");\r\n");
      out.write("\t\t\t\t\t\tvar url=contextPath+\"/personManager/addQuickMenu.action\";\r\n");
      out.write("\t\t\t\t\t\tvar json=tools.requestJsonRs(url,{menuId:uuid});\r\n");
      out.write("\t\t\t\t\t\tif(json.rtState){\r\n");
      out.write("\t\t\t\t\t\t\t$(this).removeClass(\"img-001\");\r\n");
      out.write("\t\t\t\t\t\t\t$(this).addClass(\"img-002\");\t\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}else{//取消快捷菜单\r\n");
      out.write("\t\t\t\t\t\tvar uuid=$(this).attr(\"uuid\");\r\n");
      out.write("\t\t\t\t\t\tvar url=contextPath+\"/personManager/removeQuickMenu.action\";\r\n");
      out.write("\t\t\t\t\t\tvar json=tools.requestJsonRs(url,{menuId:uuid});\r\n");
      out.write("\t\t\t\t\t\tif(json.rtState){\r\n");
      out.write("\t\t\t\t\t\t\t $(this).removeClass(\"img-002\");\r\n");
      out.write("\t\t\t\t\t\t\t $(this).addClass(\"img-001\"); \r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t $(\".left-z\").click();\r\n");
      out.write("\t\t\t\t $('.ul1').perfectScrollbar();\r\n");
      out.write("    \t\t});\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    //判断菜单是否是快捷菜单\r\n");
      out.write("    function isQuickMenu(quickMenuIds,uuid){\r\n");
      out.write("    \tif(quickMenuIds!=null&&quickMenuIds!=\"\"){\r\n");
      out.write("    \t\tvar qmIds = quickMenuIds.split(\",\"); \r\n");
      out.write("    \t\tif(qmIds!=null&&qmIds.length>0){\r\n");
      out.write("    \t\t\tfor(var j=0;j<qmIds.length;j++){\r\n");
      out.write("    \t\t\t\tif(qmIds[j]==uuid){\r\n");
      out.write("    \t\t\t\t\treturn 1;\r\n");
      out.write("    \t\t\t\t}\r\n");
      out.write("    \t\t\t}\r\n");
      out.write("    \t\t}else{\r\n");
      out.write("    \t\t\treturn 0;\r\n");
      out.write("    \t\t}\r\n");
      out.write("    \t\t\r\n");
      out.write("    \t}else{//之前不是快捷菜单\r\n");
      out.write("    \t\treturn  0;\r\n");
      out.write("    \t}\r\n");
      out.write("    \treturn 0;\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else log(t.getMessage(), t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
