package org.apache.jsp.system.core.menuGroup;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import org.apache.log4j.Logger;
import com.tianee.oa.oaconst.TeeConst;
import com.tianee.oa.oaconst.TeeModelIdConst;
import com.tianee.oa.core.org.bean.TeePerson;
import com.tianee.webframe.servlet.TeeResPrivServlet;
import com.tianee.webframe.util.str.TeeUtility;
import com.tianee.webframe.util.date.TeeDateUtil;
import com.tianee.webframe.util.global.TeeSysProps;
import com.tianee.webframe.util.str.TeeStringUtil;
import org.springframework.core.io.ClassPathResource;
import com.tianee.oa.core.org.service.TeePersonService;

public final class manageGroup_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  static {
    _jspx_dependants = new java.util.ArrayList(1);
    _jspx_dependants.add("/header/header.jsp");
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=Edge\"/>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"/>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	String contextPath = request.getContextPath();
	String basePath = request.getScheme() + "://"
			+ request.getServerName() + ":" + request.getServerPort()
			+ contextPath + "/";
	//获取主题的索引号
	int styleIndex = 1;
	Integer styleInSession = (Integer) request.getSession().getAttribute("STYLE_TYPE_INDEX");
	if (styleInSession != null) {
		styleIndex = styleInSession;
	}
	String stylePath = contextPath + "/common/styles";
	String imgPath = stylePath + "/style" + styleIndex + "/img";
	String cssPath = stylePath + "/style" + styleIndex + "/css";
	String systemImagePath = contextPath+"/common/images";
	
	//第二套风格
	int STYLE_TYPE_INDEX_2 = TeeStringUtil.getInteger( request.getSession().getAttribute("STYLE_TYPE_INDEX_2"), 1);
	String cssPathSecond = contextPath + "/system/frame/2/styles/style" + STYLE_TYPE_INDEX_2 + "/css";
	String imgPathSecond = contextPath + "/system/frame/2/styles/style" + STYLE_TYPE_INDEX_2 + "/img";
	
	
	String loginOutText = TeeSysProps.getString("LOGIN_OUT_TEXT");
	String ieTitle = TeeSysProps.getString("IE_TITLE");
	String secUserMem = TeeSysProps.getString("SEC_USER_MEM");




      out.write("\r\n");
      out.write("<!-- jQuery库 -->\r\n");
      out.write("<script src=\"");
      out.print(contextPath );
      out.write("/common/zt_webframe/js/jquery-1.7.1.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(cssPath);
      out.write("/style.css\"/>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" >\r\n");
      out.write("window.UEDITOR_HOME_URL = \"");
      out.print(contextPath);
      out.write("/common/ueditor/\";\r\n");
      out.write("$.browser = {};\r\n");
      out.write("$.browser.mozilla = /firefox/.test(navigator.userAgent.toLowerCase());\r\n");
      out.write("$.browser.webkit = /webkit/.test(navigator.userAgent.toLowerCase());\r\n");
      out.write("$.browser.opera = /opera/.test(navigator.userAgent.toLowerCase());\r\n");
      out.write("$.browser.msie = /msie/.test(navigator.userAgent.toLowerCase());\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap通用UI组件 -->\r\n");
      out.write("<script src=\"");
      out.print(contextPath );
      out.write("/common/bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(contextPath );
      out.write("/common/bootstrap/css/bootstrap.css\"/>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- JBOX通用UI组件 -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(contextPath);
      out.write("/common/jbox-v2.3/jBox/jquery.jBox-2.3.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(contextPath);
      out.write("/common/jbox-v2.3/jBox/i18n/jquery.jBox-zh-CN.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(contextPath);
      out.write("/common/jbox-v2.3/jBox/Skins/Blue/jbox.css\" />\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<!-- 其他工具库类 -->\r\n");
      out.write("<script src=\"");
      out.print(contextPath );
      out.write("/common/js/tools.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(contextPath );
      out.write("/common/js/sys.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(contextPath );
      out.write("/common/js/sysUtil.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(contextPath );
      out.write("/common/js/src/orgselect.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(contextPath);
      out.write("/common/js/easyuiTools.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- jQuery Tooltip -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(contextPath);
      out.write("/common/tooltip/jquery.tooltip.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(contextPath );
      out.write("/common/tooltip/jquery.tooltip.css\" type=\"text/css\"/>\r\n");
      out.write("\r\n");
      out.write("<!-- 图片预览器 -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath() );
      out.write("/common/js/picexplore/jquery.mousewheel.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath() );
      out.write("/common/js/picexplore/picexplore.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(contextPath );
      out.write("/common/js/picexplore/picexplore.css\" type=\"text/css\"/>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/common/js/TeeMenu.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("/** 常量定义 **/\r\n");
      out.write("var TDJSCONST = {\r\n");
      out.write("  YES: 1,\r\n");
      out.write("  NO: 0\r\n");
      out.write("};\r\n");
      out.write("/** 变量定义 **/\r\n");
      out.write("var contextPath = \"");
      out.print(contextPath );
      out.write("\";\r\n");
      out.write("var imgPath = \"");
      out.print(imgPath );
      out.write("\";\r\n");
      out.write("var cssPath = \"");
      out.print(cssPath);
      out.write("\";\r\n");
      out.write("var stylePath = \"");
      out.print(stylePath);
      out.write("\";\r\n");
      out.write("\r\n");
      out.write("var cssPathSecond = \"");
      out.print(cssPathSecond);
      out.write("\";\r\n");
      out.write("var imgPathSecond = \"");
      out.print(imgPathSecond);
      out.write("\";\r\n");
      out.write("var loginOutText = \"");
      out.print(loginOutText);
      out.write("\";\r\n");
      out.write("var uploadFlashUrl = \"");
      out.print(contextPath );
      out.write("/common/swfupload/swfupload.swf\";\r\n");
      out.write("var commonUploadUrl = \"");
      out.print(contextPath );
      out.write("/attachmentController/commonUpload.action;jsessionid=");
      out.print(session.getId());
      out.write("\";\r\n");
      out.write("var systemImagePath = \"");
      out.print(systemImagePath);
      out.write("\";\r\n");
      out.write("var gezAddr =  \"");
      out.print(TeeSysProps.getString("GENZ_ADDR"));
      out.write("\";\r\n");
      out.write("var xparent;\r\n");
      out.write("if(window.dialogArguments){\r\n");
      out.write("\txparent = window.dialogArguments;\r\n");
      out.write("}else if(window.opener){\r\n");
      out.write("\txparent = opener;\r\n");
      out.write("}else{\r\n");
      out.write("\txparent = window;\r\n");
      out.write("}\r\n");
      out.write("function parseNumber(value, defValue) {\r\n");
      out.write("  if (isNaN(value)) {\r\n");
      out.write("    return defValue;\r\n");
      out.write("  }\r\n");
      out.write("  return value * 1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<style>\r\n");
      out.write("body {\r\n");
      out.write("scrollbar-arrow-color: #a3a3a3;  /*图6,三角箭头的颜色*/\r\n");
      out.write("scrollbar-face-color: #bcbcbc;  /*图5,立体滚动条的颜色*/\r\n");
      out.write("scrollbar-3dlight-color: #b2b2b2;  /*图1,立体滚动条亮边的颜色*/\r\n");
      out.write("scrollbar-highlight-color: #e9e9e9;  /*图2,滚动条空白部分的颜色*/\r\n");
      out.write("scrollbar-shadow-color: #b2b2b2;  /*图3,立体滚动条阴影的颜色*/\r\n");
      out.write("scrollbar-darkshadow-color: #666;  /*图4,立体滚动条强阴影的颜色*/\r\n");
      out.write("scrollbar-track-color: #f1f1f1;  /*图7,立体滚动条背景颜色*/\r\n");
      out.write("scrollbar-base-color:#bcbcbc;  /*滚动条的基本颜色*/\r\n");
      out.write("}\r\n");
      out.write("</style>");
      out.write("\r\n");
      out.write("<title>权限管理</title>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(contextPath);
      out.write("/common/easyui/themes/icon.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(contextPath);
      out.write("/common/easyui/themes/gray/easyui.css\"/>\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(cssPath);
      out.write("/style.css\"/>\r\n");
      out.write("<link  rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(cssPath );
      out.write("/stylebootstrap.css\" />\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(contextPath);
      out.write("/common/easyui/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(contextPath);
      out.write("/common/easyui/jquery.easyui.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(contextPath);
      out.write("/common/easyui/locale/easyui-lang-zh_CN.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(contextPath);
      out.write("/common/js/src/teeValidagteBox.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(contextPath);
      out.write("/common/js/sys.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(contextPath);
      out.write("/common/js/tools.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" charset=\"UTF-8\">\r\n");
      out.write("\tvar contextPath = '");
      out.print(contextPath);
      out.write("';\r\n");
      out.write("\tvar datagrid;\r\n");
      out.write("\tvar userDialog;\r\n");
      out.write("\tvar userForm;\r\n");
      out.write("\tvar passwordInput;\r\n");
      out.write("\tvar userRoleDialog;\r\n");
      out.write("\tvar userRoleForm;\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\tuserForm = $('#userForm').form();\r\n");
      out.write("\t\r\n");
      out.write("\t\tdatagrid = $('#datagrid').datagrid({\r\n");
      out.write("\t\t\turl : contextPath + '/teeMenuGroup/getMenuGroupList.action?sort',\r\n");
      out.write("\t\t\ttoolbar : '#toolbar',\r\n");
      out.write("\t\t\ttitle : '',\r\n");
      out.write("\t\t\ticonCls : 'icon-save',\r\n");
      out.write("\t\t\tpagination : true,\r\n");
      out.write("\t\t\tpageSize : 10,\r\n");
      out.write("\t\t\tpageList : [ 10, 20, 30, 40, 50, 60, 70, 80, 90, 100 ],\r\n");
      out.write("\t\t\tfit : true,\r\n");
      out.write("\t\t\tfitColumns : false,\r\n");
      out.write("\t\t\tnowrap : false,\r\n");
      out.write("\t\t\tborder : false,\r\n");
      out.write("\t\t\tidField : 'uuid',\r\n");
      out.write("\t\t\tsingleSelect:true,\r\n");
      out.write("\t\t\tfrozenColumns : [ [ {\r\n");
      out.write("\t\t\t\ttitle : 'UUID',\r\n");
      out.write("\t\t\t\tfield : 'uuid',\r\n");
      out.write("\t\t\t\thidden:true,\r\n");
      out.write("\t\t\t\tsortable : true\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t}, {\r\n");
      out.write("\t\t\t\tfield : 'deptsIdStr',\r\n");
      out.write("\t\t\t\thidden:true\r\n");
      out.write("\t\t\t},{\r\n");
      out.write("\t\t\t\tfield : 'deptsNameStr',\r\n");
      out.write("\t\t\t\thidden:true\r\n");
      out.write("\t\t\t},{\r\n");
      out.write("\t\t\t\tfield : 'menuGroupType',\r\n");
      out.write("\t\t\t\ttitle : '模块权限类型',\r\n");
      out.write("\t\t\t\twidth : 100,\r\n");
      out.write("\t\t\t\tformatter : function(value, rowData, rowIndex) {\r\n");
      out.write("\t\t\t\t\tvar val = \"\"\r\n");
      out.write("\t\t\t\t\tif('00' == value){\r\n");
      out.write("\t\t\t\t\t\tval = \"其他\";\r\n");
      out.write("\t\t\t\t\t}else if('01' == value){\r\n");
      out.write("\t\t\t\t\t\tval = \"执法\";\r\n");
      out.write("\t\t\t\t\t}else if('02' == value){\r\n");
      out.write("\t\t\t\t\t\tval = \"监督\";\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t}else if('03' == value){\r\n");
      out.write("\t\t\t\t\t\tval = \"复议\";\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\treturn val;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},{\r\n");
      out.write("\t\t\t\tfield : 'menuGroupName',\r\n");
      out.write("\t\t\t\ttitle : '模块权限名称',\r\n");
      out.write("\t\t\t\twidth : 200,\r\n");
      out.write("\t\t\t\tsortable : true\r\n");
      out.write("\t\t\t},{\r\n");
      out.write("\t\t\t\tfield : 'deptName',\r\n");
      out.write("\t\t\t\ttitle : '创建部门',\r\n");
      out.write("\t\t\t\twidth : 150,\r\n");
      out.write("\t\t\t\tsortable : true\r\n");
      out.write("\t\t\t},{\r\n");
      out.write("\t\t\t\tfield : 'unitName',\r\n");
      out.write("\t\t\t\ttitle : '所属单位',\r\n");
      out.write("\t\t\t\twidth : 150,\r\n");
      out.write("\t\t\t\tsortable : true\r\n");
      out.write("\t\t\t}] ],\r\n");
      out.write("\t\t\tcolumns : [ [ {\r\n");
      out.write("\t\t\t\tfield : 'menuGroupNo',\r\n");
      out.write("\t\t\t\ttitle : '模块权限排序',\r\n");
      out.write("\t\t\t\tsortable : true,\r\n");
      out.write("\t\t\t\twidth : 100\r\n");
      out.write("\t\t\t},{\r\n");
      out.write("\t\t\t\tfield : 'userNum',\r\n");
      out.write("\t\t\t\ttitle : '拥有权限组用户数',\r\n");
      out.write("\t\t\t\twidth : 100 \r\n");
      out.write("\t\t\t },{\r\n");
      out.write("\t\t\t\tfield : '_optmanage',\r\n");
      out.write("\t\t\t\ttitle : '操作',\r\n");
      out.write("\t\t\t\twidth : 400,\r\n");
      out.write("\t\t\t\tformatter : function(value, rowData, rowIndex) {\r\n");
      out.write("\t\t\t\t\tvar render = [\"<a href='#' onclick='viewStatistics(\\\"\" +rowData.uuid + \"\\\");'> 关联用户 </a>&nbsp;&nbsp;\"];\r\n");
      out.write("\t\t\t\t\trender.push(\"<a href='#' onclick='setMenuGroup(\\\"\" +rowData.uuid + \"\\\");'> 设置权限 </a>&nbsp;&nbsp;\");\r\n");
      out.write("\t\t\t\t\trender.push(\"<a href='#' onclick='setDepts(\\\"\" +rowData.uuid + \"\\\");'> 设置部门 </a>&nbsp;&nbsp;\");\r\n");
      out.write("\t\t\t\t\trender.push(\"<a href='javascript:void(0);' onclick='toAddUpdate(\\\"\" +rowData.uuid + \"\\\");'> 编辑 </a>&nbsp;&nbsp;\");\r\n");
      out.write("\t\t\t     \tif(rowData.uuid!=1){\r\n");
      out.write("\t\t\t     \t\trender.push(\"<a href='javascript:void(0);' onclick='remove1(\\\"\" +rowData.uuid + \"\\\");'> 删除 </a>\");\r\n");
      out.write("\t\t\t     \t}\r\n");
      out.write("\t\t\t\t\treturn render.join(\"\");\r\n");
      out.write("\t\t\t}} ] ],\r\n");
      out.write("\t\t\tonRowContextMenu : function(e, rowIndex, rowData) {\r\n");
      out.write("\t\t\t\te.preventDefault();\r\n");
      out.write("\t\t\t\t//$(this).datagrid('unselectAll');\r\n");
      out.write("\t\t\t\t//$(this).datagrid('selectRow', rowIndex);\r\n");
      out.write("\t\t\t\t//$('#menu').menu('show', {\r\n");
      out.write("\t\t\t\t//\tleft : e.pageX,\r\n");
      out.write("\t\t\t\t//\ttop : e.pageY\r\n");
      out.write("\t\t\t\t//});\r\n");
      out.write("\t\t\t\t//alert(\"dd\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t})\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("//查看关联用户情况\r\n");
      out.write("function viewStatistics(menuGroupId){\r\n");
      out.write("\tvar url=contextPath+\"/system/core/menuGroup/statistics.jsp?menuGroupId=\"+menuGroupId;\r\n");
      out.write("\topenFullWindow(url);\r\n");
      out.write("}\r\n");
      out.write("/**\r\n");
      out.write("*删除菜单组\r\n");
      out.write("*/\r\n");
      out.write("function remove1(id){\r\n");
      out.write("\t//alert();\r\n");
      out.write("\tvar rows = datagrid.datagrid('getSelections');\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tif(confirm(\"确认要删除所选记录吗，删除后将不可恢复？\")){\r\n");
      out.write("\t\tvar url = \"");
      out.print(contextPath );
      out.write("/teeMenuGroup/delMenuGroup.action\";\r\n");
      out.write("\t\tvar jsonRs = tools.requestJsonRs(url,{uuids:id});\r\n");
      out.write("\t\t$.messager.show({\r\n");
      out.write("\t\t\tmsg : jsonRs.rtMsg,\r\n");
      out.write("\t\t\ttitle : '提示'\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\tdatagrid.datagrid('reload');\r\n");
      out.write("\t}\r\n");
      out.write("}\t\r\n");
      out.write("/**\r\n");
      out.write(" * 跳转至设置权限页面\r\n");
      out.write(" */\r\n");
      out.write("function setMenuGroup(uuid){\r\n");
      out.write("\t window.location.href = \"");
      out.print(contextPath );
      out.write("/system/core/menuGroup/setMenuGroupPrivNew.jsp?uuid=\" + uuid;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function setDepts(uuid){\r\n");
      out.write("\twindow.location.href = \"");
      out.print(contextPath );
      out.write("/system/core/menuGroup/setMenuGroupDepts.jsp?uuid=\" + uuid;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function selectDept(retArray , moduleId, privNoFlag , noAllDept, callBackFunc) {\r\n");
      out.write("\tdeptRetNameArray = retArray;\r\n");
      out.write("\tobjSelectType  = retArray[2] || \"\";\r\n");
      out.write("\tvar url = contextPath + \"/system/core/orgselect/selectMultiDeptPost.jsp?objSelectType=\" + objSelectType;\r\n");
      out.write("\tvar has = false;\r\n");
      out.write("\tif (moduleId) {\r\n");
      out.write("\t\turl += \"&moduleId=\" + moduleId ;\r\n");
      out.write("\t}\r\n");
      out.write("\tif (privNoFlag) {\r\n");
      out.write("\t\turl += \"&privNoFlag=\" + privNoFlag ;\r\n");
      out.write("\t}\r\n");
      out.write("\tif (noAllDept) {\r\n");
      out.write("\t\turl += \"&noAllDept=\" + noAllDept ;\r\n");
      out.write("\t}\r\n");
      out.write("\tif(callBackFunc){\r\n");
      out.write("\t\turl += \"&callBackPara=\" + callBackFunc ;\r\n");
      out.write("\t}\r\n");
      out.write("\tvar IM_OA;\r\n");
      out.write("\t\r\n");
      out.write("\ttry{\r\n");
      out.write("\t\tIM_OA = window.external.IM_OA;\r\n");
      out.write("\t}catch(e){}\r\n");
      out.write("\r\n");
      out.write("\tif(window.showModelDialog || IM_OA){\r\n");
      out.write("\t\tdialogChangesize(url, 560, 400);\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\topenWindow(url,\"选择人员\", 560, 400);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function selectDeptCallBack(){\r\n");
      out.write("\t\r\n");
      out.write("\t//alert($(\"#deptsIdStr\").val());\r\n");
      out.write("\t\r\n");
      out.write("\tvar url = contextPath+\"/teeMenuGroup/setDeptPriv.action\";\r\n");
      out.write("\tvar jsonObj = tools.requestJsonRs(url,{groupId:$(\"#groupId\").val(),deptsIdStr:$(\"#deptsIdStr\").val()});\r\n");
      out.write("\tif(jsonObj.rtState){\r\n");
      out.write("\t\t//location='manageGroup.jsp';\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\t$.MsgBox.Alert_auto(jsonObj.rtMsg);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function toAddUpdate(uuid){\r\n");
      out.write("\tvar url =  \"");
      out.print(contextPath);
      out.write("/system/core/menuGroup/addupdate.jsp?uuid=\" + uuid;\r\n");
      out.write("\tdialogChangesize(url , 400, 260);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"easyui-layout\" fit=\"true\">\r\n");
      out.write("\t<div region=\"center\" border=\"false\" style=\"overflow: hidden;\">\r\n");
      out.write("\t\t<div id=\"toolbar\" class=\"datagrid-toolbar\" style=\"height: auto;display: none;\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\t<a class=\"easyui-linkbutton\" iconCls=\"icon-add\" onclick=\"toAddUpdate('');\" plain=\"true\" href=\"javascript:void(0);\">增加模块权限</a>\r\n");
      out.write("\t\t\t\t<!-- <a class=\"easyui-linkbutton\" iconCls=\"icon-remove\" onclick=\"remove();\" plain=\"true\" href=\"javascript:void(0);\">删除</a> -->\r\n");
      out.write("\t\t\t\t<!-- <a class=\"easyui-linkbutton\" iconCls=\"icon-undo\" onclick=\"datagrid.datagrid('unselectAll');\" plain=\"true\" href=\"javascript:void(0);\">取消选中</a> -->\r\n");
      out.write("\t\t \t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<table id=\"datagrid\"></table>\r\n");
      out.write("\t\t<input type=\"hidden\" id=\"groupId\" value=\"\"/>\r\n");
      out.write("\t\t<input type=\"hidden\" id=\"deptsIdStr\" value=\"\"/>\r\n");
      out.write("\t\t<input type=\"hidden\" id=\"deptsNameStr\" value=\"\"/>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else log(t.getMessage(), t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
