package org.apache.jsp.system.core.person;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.tianee.oa.core.partthree.util.TeePartThreeUtil;
import com.tianee.webframe.util.servlet.TeeCookieUtils;
import java.util.*;
import com.tianee.oa.oaconst.TeeConst;
import com.tianee.oa.core.org.bean.TeePerson;
import com.tianee.webframe.util.str.TeeUtility;
import com.tianee.webframe.util.date.TeeDateUtil;
import com.tianee.webframe.util.global.TeeSysProps;
import com.tianee.webframe.util.str.TeeStringUtil;
import com.tianee.oa.core.org.service.TeePersonService;
import com.tianee.oa.oaconst.TeeModelIdConst;
import com.tianee.webframe.util.str.TeeStringUtil;
import com.tianee.webframe.util.global.TeeSysProps;
import com.tianee.oa.core.org.bean.TeeUserRole;
import com.tianee.oa.core.org.bean.TeeDepartment;
import com.tianee.oa.oaconst.TeeConst;
import com.tianee.webframe.util.date.TeeDateUtil;
import com.tianee.oa.core.org.bean.TeePerson;
import com.tianee.oa.core.org.service.TeePersonService;
import java.util.Date;
import com.tianee.webframe.util.date.TeeDateUtil;
import com.tianee.webframe.util.str.TeeUtility;
import com.tianee.webframe.util.str.TeeStringUtil;
import com.tianee.oa.oaconst.TeeConst;
import com.tianee.webframe.util.servlet.TeeCookieUtils;

public final class addupdate_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  static {
    _jspx_dependants = new java.util.ArrayList(5);
    _jspx_dependants.add("/header/header2.0.jsp");
    _jspx_dependants.add("/header/upload.jsp");
    _jspx_dependants.add("/header/userheader.jsp");
    _jspx_dependants.add("/header/easyui2.0.jsp");
    _jspx_dependants.add("/header/validator2.0.jsp");
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	String uuid = request.getParameter("uuid") == null ? "0" : request.getParameter("uuid");
	String deptId = request.getParameter("deptId") == null? "": request.getParameter("deptId");
	String deptName = request.getParameter("deptName") == null ? "" : request.getParameter("deptName");

	TeePerson  loginUser=(TeePerson)request.getSession().getAttribute(TeeConst.LOGIN_USER);
    boolean adminPriv=TeePartThreeUtil.checkHasPriv(loginUser, "SYS_USER_MANAGE");
    boolean saferPriv=TeePartThreeUtil.checkHasPriv(loginUser, "SYS_USER_PRIV");
    
    if(!adminPriv&&!saferPriv){
    	response.sendRedirect("/system/core/system/partthree/error.jsp");
    }


      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=Edge\"/>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"/>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

String contextPath = request.getContextPath();
String basePath = request.getScheme() + "://"
		+ request.getServerName() + ":" + request.getServerPort()
		+ contextPath + "/";
//获取主题的索引号
int styleIndex = 1;
Integer styleInSession = (Integer) request.getSession().getAttribute("STYLE_TYPE_INDEX");
if (styleInSession != null) {
	styleIndex = styleInSession;
}
String stylePath = contextPath + "/common/styles";
String imgPath = stylePath + "/style" + styleIndex + "/img";
String cssPath = stylePath + "/style" + styleIndex + "/css";
String systemImagePath = contextPath+"/common/images";

//第二套风格
int STYLE_TYPE_INDEX_2 = TeeStringUtil.getInteger( request.getSession().getAttribute("STYLE_TYPE_INDEX_2"), 1);
String cssPathSecond = contextPath + "/system/frame/2/styles/style" + STYLE_TYPE_INDEX_2 + "/css";
String imgPathSecond = contextPath + "/system/frame/2/styles/style" + STYLE_TYPE_INDEX_2 + "/img";


String loginOutText = TeeSysProps.getString("LOGIN_OUT_TEXT");
String ieTitle = TeeSysProps.getString("IE_TITLE");
String secUserMem = TeeSysProps.getString("SEC_USER_MEM");

Cookie cookie = TeeCookieUtils.getCookie(request, "skin_new");
String skinNew = "1";
if(cookie!=null){
	skinNew = cookie.getValue();
}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- zt_webframe框架引入 jquery -->\r\n");
      out.write("<script src=\"");
      out.print(contextPath );
      out.write("/common/jquery-easyui-1.6.11/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- zt_webframe框架引入 核心库 -->\r\n");
      out.write("<script src=\"");
      out.print(contextPath );
      out.write("/common/zt_webframe/js/package.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(contextPath );
      out.write("/common/js/sys2.0.js?v=2\"></script>\r\n");
      out.write("<script src=\"");
      out.print(contextPath );
      out.write("/common/js/sysUtil.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(contextPath );
      out.write("/common/js/src/orgselect.js\"></script>\n");
      out.write("<!--\n");
      out.write("\n");
      out.write("//-->\r\n");
      out.write("<!-- zt_webframe框架引入 css样式 -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/common/zt_webframe/css/init");
      out.print(skinNew );
      out.write(".css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/common/zt_webframe/css/package");
      out.print(skinNew );
      out.write(".css\">\r\n");
      out.write("\r\n");
      out.write("<script src=\"");
      out.print(contextPath );
      out.write("/common/js/tools2.0.js?v=1\"></script>\r\n");
      out.write("<script src=\"");
      out.print(contextPath );
      out.write("/common/js/TeeMenu.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("/** 变量定义 **/\r\n");
      out.write("var contextPath = \"");
      out.print(contextPath );
      out.write("\";\r\n");
      out.write("var systemImagePath = contextPath+\"/common/images\";\r\n");
      out.write("var uploadFlashUrl = \"");
      out.print(contextPath );
      out.write("/common/swfupload/swfupload.swf\";\r\n");
      out.write("var commonUploadUrl = \"");
      out.print(contextPath );
      out.write("/attachmentController/commonUpload.action;jsessionid=");
      out.print(session.getId());
      out.write("\";\r\n");
      out.write("var xparent;\r\n");
      out.write("var stylePath = \"");
      out.print(stylePath);
      out.write("\";\r\n");
      out.write("if(window.dialogArguments){\r\n");
      out.write("\txparent = window.dialogArguments;\r\n");
      out.write("}else if(window.opener){\r\n");
      out.write("\txparent = opener;\r\n");
      out.write("}else{\r\n");
      out.write("\txparent = window;\r\n");
      out.write("}\r\n");
      out.write("window.UEDITOR_HOME_URL = \"");
      out.print(contextPath);
      out.write("/common/ueditor/\";\r\n");
      out.write("$.browser = {};\r\n");
      out.write("$.browser.mozilla = /firefox/.test(navigator.userAgent.toLowerCase());\r\n");
      out.write("$.browser.webkit = /webkit/.test(navigator.userAgent.toLowerCase());\r\n");
      out.write("$.browser.opera = /opera/.test(navigator.userAgent.toLowerCase());\r\n");
      out.write("$.browser.msie = /msie/.test(navigator.userAgent.toLowerCase());\r\n");
      out.write("</script>\r\n");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/common/swfupload/css/default.css\" />\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/common/js/jquery.form.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/common/swfupload/swfupload.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/common/swfupload/swfupload.queue.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/common/swfupload/fileprogress.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/common/swfupload/handlers.js?v=1\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/common/js/upload.js?v=9\"></script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("var UPLOAD_ATTACH_LIMIT_GLOBAL = \"");
      out.print(TeeSysProps.getString("UPLOAD_ATTACH_LIMIT"));
      out.write("\";\r\n");
      out.write("var GLOBAL_ATTACH_TYPE=\"");
      out.print(TeeStringUtil.getString(TeeSysProps.getString("GLOBAL_ATTACH_TYPE")) );
      out.write("\";\r\n");
      out.write("</script>");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	TeePerson person = (TeePerson)request.getSession().getAttribute(TeeConst.LOGIN_USER);
	boolean isAdminPriv = TeePersonService.checkIsAdminPriv(person);
	boolean isSuperAdmin = TeePersonService.checkIsSuperAdmin(person,"");
	String isAdmin = person.getIsAdmin();

	Date date = person.getLastPassTime();
	String lastPassTime = "";
	if(date != null){
		lastPassTime = TeeDateUtil.getDateTimeStr(date);
	}
	int loginPersonId = person.getUuid();
	
	
	
	
	String SEC_INIT_PASS = (String) request.getSession().getAttribute("SEC_INIT_PASS") == null ? "0" : (String) request.getSession().getAttribute("SEC_INIT_PASS");//初始密码
	String SEC_PASS_FLAG = TeeStringUtil.getString( (String) request.getSession().getAttribute("SEC_PASS_FLAG"), "0");//是否过期
	String SEC_PASS_TIME = TeeStringUtil.getString((String) request.getSession().getAttribute("SEC_PASS_TIME"), "0");//过期时间
	String SEC_SHOW_IP = TeeStringUtil.getString((String) request.getSession().getAttribute("SEC_SHOW_IP"), "0");//是否显示IP
	String SEC_ON_STATUS = TeeStringUtil.getString((String) request.getSession().getAttribute("SEC_ON_STATUS"), "0");//记录在线状态
	
	int AVATAR_UPLOAD = TeeStringUtil.getInteger(request.getSession().getAttribute("AVATAR_UPLOAD"), 0 );//是否允许上传图象
	int AVATAR_WIDTH =  TeeStringUtil.getInteger(request.getSession().getAttribute("AVATAR_WIDTH"), 0 );//图象宽度
	int  AVATAR_HEIGHT = TeeStringUtil.getInteger(request.getSession().getAttribute("AVATAR_HEIGHT"),0);//图象高度
  
	String userName = person.getUserName();
	String userId = person.getUserId();
	int userSid = person.getUuid();
	TeeDepartment dept = person.getDept();
	String currUserDeptName  = "";
	String currUserRoleName = "";
	TeeUserRole role = person.getUserRole();
	if(dept != null){
		currUserDeptName = dept.getDeptName();
	}
	if(role != null){
		currUserRoleName = role.getRoleName();
	}
	String avatar = person.getAvatar();
	//用于判断用户性别
	String avatar_default = "";
	if(("0".equals(person.getSex())) && TeeUtility.isNullorEmpty(person.getAvatar())){
		avatar_default = "0";  //0代表男
	}else if(("1".equals(person.getSex())) && TeeUtility.isNullorEmpty(person.getAvatar())){
		avatar_default = "1";  //1代表女
	}

      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("/** 变量定义 **/\r\n");
      out.write("var isAdminPriv = '");
      out.print(isAdminPriv);
      out.write("';\r\n");
      out.write("var isSuperAdmin = '");
      out.print(isSuperAdmin);
      out.write("';\r\n");
      out.write("var loginPersonId = ");
      out.print(loginPersonId);
      out.write(";\r\n");
      out.write("var lastPassTime = '");
      out.print(lastPassTime);
      out.write("';\r\n");
      out.write("\r\n");
      out.write("var SEC_SHOW_IP =  '");
      out.print(SEC_SHOW_IP);
      out.write("';\r\n");
      out.write("var SEC_ON_STATUS =  '");
      out.print(SEC_ON_STATUS);
      out.write("';\r\n");
      out.write("var AVATAR_UPLOAD =  '");
      out.print(AVATAR_UPLOAD);
      out.write("';\r\n");
      out.write("var AVATAR_WIDTH =  '");
      out.print(AVATAR_WIDTH);
      out.write("';\r\n");
      out.write("var AVATAR_HEIGHT =  '");
      out.print(AVATAR_HEIGHT);
      out.write("';\r\n");
      out.write("var userId = \"");
      out.print(userId);
      out.write("\";\r\n");
      out.write("var userName = \"");
      out.print(userName);
      out.write("\";\r\n");
      out.write("var avatar = \"");
      out.print(avatar);
      out.write("\";\r\n");
      out.write("var avatar_default = \"");
      out.print(avatar_default);
      out.write("\";\r\n");
      out.write("</script>");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- zt_webframe框架引入 核心库 -->\r\n");
      out.write("<script type=\"text/javascript\" src = '");
      out.print(request.getContextPath() );
      out.write("/common/jquery-easyui-1.6.11/jquery.easyui.min.js'></script>\r\n");
      out.write("<script type=\"text/javascript\" src = '");
      out.print(request.getContextPath() );
      out.write("/common/zt_webframe/js/jquery.datagrid.extend.js'></script>\r\n");
      out.write("<script type=\"text/javascript\" src = '");
      out.print(request.getContextPath() );
      out.write("/common/jquery-easyui-1.6.11/locale/easyui-lang-zh_CN.js'></script>\r\n");
      out.write("\r\n");

Cookie __cookie = TeeCookieUtils.getCookie(request, "skin_new");
String __skinNew = "1";
if(__cookie!=null){
	__skinNew = __cookie.getValue();
}

      out.write("\r\n");
      out.write("<!-- zt_webframe框架引入 css样式 -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/common/jquery-easyui-1.6.11/themes/metro/easyui.css\">\r\n");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- zt_webframe框架引入 核心库 -->\r\n");
      out.write("<script type=\"text/javascript\" src = \"");
      out.print(request.getContextPath());
      out.write("/common/zt_webframe/js/jquery.validate.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src = \"");
      out.print(request.getContextPath());
      out.write("/common/zt_webframe/js/additional-methods.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src = \"");
      out.print(request.getContextPath());
      out.write("/common/zt_webframe/js/messages_zh.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src = \"");
      out.print(request.getContextPath());
      out.write("/common/zt_webframe/js/jquery.validate.extend.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<title>人员管理</title>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".imgMiddle{\r\n");
      out.write("\tfloat:left;\r\n");
      out.write("\tmargin-top:5px;\r\n");
      out.write("}\r\n");
      out.write(".imgMiddleSpan{\r\n");
      out.write("\tfloat:left;\r\n");
      out.write("\tmargin-top:4px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(contextPath );
      out.write("/common/My97DatePicker/WdatePicker.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(contextPath );
      out.write("/system/core/person/js/person.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("var deptId = '");
      out.print(deptId);
      out.write("';\r\n");
      out.write("var uuid = '");
      out.print(uuid);
      out.write("';\t\r\n");
      out.write("var deptName = '");
      out.print(deptName);
      out.write("';\r\n");
      out.write("var keySN=\"\";//绑定ukey的code\r\n");
      out.write("var oldUserId=\"\";\r\n");
      out.write("var swfUploadObj;\r\n");
      out.write("function doInit(){\r\n");
      out.write("\t//单附件简单上传组件\r\n");
      out.write("\tnew TeeSingleUpload({\r\n");
      out.write("\t\tuploadBtn:\"uploadBtn\",\r\n");
      out.write("\t\tcallback:function(json){//回调函数，json.rtData\r\n");
      out.write("\t\t\tvar list=json.rtData;\r\n");
      out.write("\t\t    if(list!=null && list.length>0){\r\n");
      out.write("\t\t    \tvar data=list[0];\r\n");
      out.write("\t\t    \t//$(\"#attachName\").val(data.fileName);\r\n");
      out.write("\t\t    \t$(\"#attachId\").val(data.sid);\r\n");
      out.write("\t\t\t\tvar html=\"<img src='");
      out.print(contextPath );
      out.write("/attachmentController/downFile.action?id=\"+data.sid+\"' />\";\r\n");
      out.write("\t\t    \t$(\"#uploadDiv\").html(html);\r\n");
      out.write("\t\t    }\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\tpost_params:{model:\"workFlow\"}//后台传入值，model为模块标志\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t\t//添加例子一\r\n");
      out.write("\t\t//获取角色\r\n");
      out.write("\t\tgetAllAttendConfig();\r\n");
      out.write("\t\tgetPortalTemplate();\r\n");
      out.write("\t\tvar isSuperAdmin = false;\r\n");
      out.write("\t\tvar userRoleStrName = \"\";\r\n");
      out.write("\t\tvar userRoleStr = \"\";\r\n");
      out.write("\t\tif(uuid != \"\" && uuid != '0'){\r\n");
      out.write("\t\t\tvar url = \"");
      out.print(contextPath);
      out.write("/personManager/getPersonById.action\";\r\n");
      out.write("\t\t\tvar para = {uuid:uuid};\r\n");
      out.write("\t\t\tvar jsonObj = tools.requestJsonRs(url,para);\r\n");
      out.write("\t\t\tif(jsonObj.rtState){\r\n");
      out.write("\t\t\t\tvar json = jsonObj.rtData;\r\n");
      out.write("\t\t\t\tkeySN=json.keySN;//记录绑定设备   \r\n");
      out.write("\t\t\t\toldUserId=json.userId;//记录原来的用户名\r\n");
      out.write("\t\t\t\tif(json && json.uuid){\r\n");
      out.write("\t\t\t\t\tif(json.userId == 'admin'){\r\n");
      out.write("\t\t\t\t\t   isSuperAdmin = true;\r\n");
      out.write("\t\t\t\t\t    $(\"#userRoleStr\").append(\"<option value='\" + json.userRoleStr + \"'>系统管理员<option>\");\r\n");
      out.write("\t\t\t\t\t   userRoleStrName = json.userRoleStrName;\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\tselectUserPrivList('userRoleStr','1');\r\n");
      out.write("\t\t\t\t\t\t$(\"#userRoleStr\").val(userRoleStr);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tuserRoleStr = json.userRoleStr;\r\n");
      out.write("\t\t\t\t   bindJsonObj2Cntrl(json);\r\n");
      out.write("\t\t\t\t   if(json.attachId>0){\r\n");
      out.write("\t\t\t\t    var html=\"<img src='");
      out.print(contextPath );
      out.write("/attachmentController/downFile.action?id=\"+json.attachId+\"' />\";\r\n");
      out.write("\t\t\t    \t$(\"#uploadDiv\").html(html);\r\n");
      out.write("\t\t\t\t   }\r\n");
      out.write("\t\t\t\t   deptId = json.deptId;\r\n");
      out.write("\t\t\t\t   deptName = json.deptName;\r\n");
      out.write("\t\t           document.getElementById(\"userRoleStr\").value = json.userRoleStr;\r\n");
      out.write("\t\t           if(json.userRoleOtherId != \"\"){//辅助角色\r\n");
      out.write("\t\t        \t   $(\"#priv\").show();\r\n");
      out.write("\t\t           }\r\n");
      out.write("\t\t           \r\n");
      out.write("\t\t           if(json.deptIdOtherStr != \"\"){//辅助部门\r\n");
      out.write("\t\t        \t   $(\"#dept_other\").show();\r\n");
      out.write("\t\t           }\r\n");
      out.write("\t\t           var postPriv = json.postPriv;\r\n");
      out.write("\t\t          // var postDeptStr = json.postDeptStr;\r\n");
      out.write("\t\t           //if(postPriv == '2' &&  postDeptStr != \"\"){\r\n");
      out.write("\t\t        \tif(postPriv == '2'){   \r\n");
      out.write("\t\t       \t\t\t$(\"#post_dept\").show();\r\n");
      out.write("\t\t       \t\t}\r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t\t\t\t//$(\"#deptIdName\").val(json.deptIdName);\r\n");
      out.write("\t\t        \tselectViewDept();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\t$.MsgBox.Alert_auto(jsonObj.rtMsrg);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tselectUserPrivList('userRoleStr','1');\r\n");
      out.write("\t\t\t$(\"#deptId\").val(deptId);\r\n");
      out.write("\t\t\t$(\"#deptIdName\").val(deptName);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\tif(isSuperAdmin){\r\n");
      out.write("\t\t\t$(\"#isNotSuperAdmin\").hide();\r\n");
      out.write("\t\t\t$(\"#isNotSuperAdminRole\").append(userRoleStrName);//给角色\r\n");
      out.write("\t\t\t$(\"#userRoleStr\").hide();//隐藏角色\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//清空\r\n");
      out.write("function qingkou(){\r\n");
      out.write("\t$(\"#attachId\").val(\"0\");\r\n");
      out.write("\t$(\"#uploadDiv\").html(\"\");\r\n");
      out.write("}\r\n");
      out.write("/**\r\n");
      out.write(" * 保存\r\n");
      out.write(" */\r\n");
      out.write("function doSave(){\r\n");
      out.write("\tif (check()){\r\n");
      out.write("\t\tvar url = \"");
      out.print(contextPath);
      out.write("/personManager/addOrUpdate.action\";\r\n");
      out.write("\t\tvar para =  tools.formToJson($(\"#form1\")) ;\r\n");
      out.write("\t\tvar jsonRs = tools.requestJsonRs(url,para);\r\n");
      out.write("\t\tif(jsonRs.rtState){\r\n");
      out.write("\t\t\t//alert();\r\n");
      out.write("\t\t\t$.MsgBox.Alert_auto(jsonRs.rtMsg,function(){\r\n");
      out.write("\t\t\twindow.parent.changePage(\"");
      out.print(contextPath);
      out.write("/system/core/person/personList.jsp?deptId=\" + deptId + \"&deptName=\" + encodeURIComponent(deptName));\r\n");
      out.write("\t\t\tparent.refreshTargetNode($(\"#deptId\").val()+\";dept\");\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\t $.MsgBox.Alert_auto(jsonRs.rtMsg);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t//window.opener.location.reload();\r\n");
      out.write("\t       // window.location.reload();\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function check() {\r\n");
      out.write("\tvar checkStatus =  $(\"#form1\").valid();\r\n");
      out.write("\tif(checkStatus == false ){\r\n");
      out.write("\t\treturn checkStatus;\r\n");
      out.write("\t}\r\n");
      out.write("\tvar deptId = $(\"#deptId\");\r\n");
      out.write("\tif(!deptId.val()){\r\n");
      out.write("\t\t$.MsgBox.Alert_auto(\"部门是必填项！\");\r\n");
      out.write("\t\treturn false ;\r\n");
      out.write("\t}\r\n");
      out.write("\tvar userRoleUuid = $(\"#userRoleStr\");\r\n");
      out.write("\tif(!userRoleUuid.val()){\r\n");
      out.write("\t\t//$(\"#userRoleStr\").addClass(\"easyui-combogrid combogrid-f combo-f\");\r\n");
      out.write("\t\t$.MsgBox.Alert_auto(\"用户角色是必填项！\");\r\n");
      out.write("\t\treturn false ;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tif(uuid>0){//编辑用户 的時候  判断用户是不是绑定了ukey \r\n");
      out.write("\t\tif(keySN!=\"undefined\"&&keySN!=\"null\"&&keySN!=null){//绑定了ukey设备\r\n");
      out.write("\t\t     var newUserId=$(\"#userId\").val();\r\n");
      out.write("              if(newUserId!=oldUserId){\r\n");
      out.write("            \t  $.MsgBox.Alert_auto(\"该用户绑定了Ukey设备，不能更改用户名！\");\r\n");
      out.write("            \t  return false;\r\n");
      out.write("              }\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\treturn true;\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function getAllAttendConfig(){\r\n");
      out.write("\tvar url = contextPath+\"/TeeAttendConfigController/getConfig.action\";\r\n");
      out.write("\tvar json = tools.requestJsonRs(url);\r\n");
      out.write("\tif(json.rtState){\r\n");
      out.write("\t\tvar data=json.rtData;\r\n");
      out.write("\t\tvar html = \"<option value=\\\"0\\\">请选择</option>\";\r\n");
      out.write("\t\tfor(var i=0;i<data.length;i++){\r\n");
      out.write("\t\t\thtml+=\"<option value=\\\"\"+data[i].sid+\"\\\">\"+data[i].dutyName+\"</option>\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t$(\"#dutyType\").html(html);\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\t$.MsgBox.Alert_auto(json.rtMsg);\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/**\r\n");
      out.write(" * 获取有权限的桌面模块\r\n");
      out.write(" */\r\n");
      out.write("function getPortalTemplate(){\r\n");
      out.write("\tvar url = contextPath+\"/teePortalTemplateController/getTemplateList.action?uuid=\"+uuid+\"&deptId=\"+deptId;\r\n");
      out.write("\tvar json = tools.requestJsonRs(url);\r\n");
      out.write("\tif(json.rtState){\r\n");
      out.write("\t\tvar data=json.rtData;\r\n");
      out.write("\t\tvar html=\"\";\r\n");
      out.write("\t\tif(data.length>0){\r\n");
      out.write("\t\t\tfor(var i=0;i<data.length;i++){\r\n");
      out.write("\t\t\t\thtml+=\"<option value=\\\"\"+data[i].sid+\"\\\">\"+data[i].templateName+\"</option>\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\thtml = \"<option value=\\\"0\\\">无</option>\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t$(\"#desktop\").html(html);\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\t$.MsgBox.Alert_auto(json.rtMsg);\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/**\r\n");
      out.write(" * 隐藏显示\r\n");
      out.write(" */\r\n");
      out.write("function setOption(id){\r\n");
      out.write("\t$('#' + id).toggle();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function selectViewDept(){\r\n");
      out.write("\tif($(\"#viewPriv\").val()==\"2\"){//指定部门\r\n");
      out.write("\t\t$(\"#view_dept\").show();\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\t$(\"#view_dept\").hide();\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/**\r\n");
      out.write(" * 选择菜单组\r\n");
      out.write(" * @return\r\n");
      out.write(" */\r\n");
      out.write("function selectMenuGroup(retArray, moduleId,privNoFlag , privOp) {\r\n");
      out.write("  var deptId = $(\"#deptId\").val();\r\n");
      out.write("  if(!deptId){\r\n");
      out.write("    $.MsgBox.Alert_auto(\"先选择部门！\");\r\n");
      out.write("\treturn false ;\r\n");
      out.write("  }\r\n");
      out.write("\t\r\n");
      out.write("  roleRetNameArray = retArray;\r\n");
      out.write("  objSelectType = retArray[2] || \"\";\r\n");
      out.write(" \r\n");
      out.write("  var url =contextPath + \"/system/core/orgselect/selectMultiMenuGroupNew.jsp?deptUuid=\" + deptId + \"&objSelectType=\" + objSelectType;\r\n");
      out.write("  var has = false;\r\n");
      out.write("  if (moduleId) {\r\n");
      out.write("    url += \"?moduleId=\" + moduleId;\r\n");
      out.write("    if (!privNoFlag) {\r\n");
      out.write("      privNoFlag = 0;\r\n");
      out.write("    }\r\n");
      out.write("    url += \"&privNoFlag=\" + privNoFlag + \"&objSelectType=\" + objSelectType;\r\n");
      out.write("    has = true;\r\n");
      out.write("  }\r\n");
      out.write("  if (privOp) {\r\n");
      out.write("    if (has) {\r\n");
      out.write("      url += \"&privOp=\" + privOp + \"&objSelectType=\" + objSelectType;\r\n");
      out.write("    } else {\r\n");
      out.write("      url += \"?privOp=\" + privOp+ \"&objSelectType=\" + objSelectType;\r\n");
      out.write("    }\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("  var IM_OA;\r\n");
      out.write("  try{\r\n");
      out.write("    IM_OA = window.external.IM_OA;\r\n");
      out.write("  }catch(e){}\r\n");
      out.write("\r\n");
      out.write("  if(window.showModelDialog || IM_OA){\r\n");
      out.write("\t  dialogChangesize(url , 280, 400);\r\n");
      out.write("  }else{\r\n");
      out.write("\t  openWindow(url,\"选择菜单组\", 280, 400);\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body onload=\"doInit()\" style=\"padding-left: 10px;padding-right: 10px;\">\r\n");
      out.write("<div id=\"toolbar\" class = \"setHeight clearfix\" style=\"margin-bottom: 10px;margin-top: 10px;\">\r\n");
      out.write("<div class=\" fl \">\r\n");
      out.write("               ");

					if (TeeUtility.isNullorEmpty(uuid)||uuid=="0") {
				
      out.write(" \r\n");
      out.write("   <h4 style=\"font-size: 16px;font-family:MicroSoft YaHei;\">\r\n");
      out.write("\t\t\t\t新增人员\r\n");
      out.write("\t\t\t\t</h4>\r\n");
      out.write("\t\t\t\t");

 					} else {
 				
      out.write(" \r\n");
      out.write(" \t\t\t\t <h4 style=\"font-size: 16px;font-family:MicroSoft YaHei;\">\r\n");
      out.write("\t\t\t\t编辑人员\r\n");
      out.write("\t\t\t\t</h4>\r\n");
      out.write(" \t\t\t\t");

 					}
 				
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write(" \t<span class=\"basic_border\" style=\"margin-top: 10px;\"></span>\r\n");
      out.write("</div>\r\n");
      out.write("\t<form  method=\"post\" name=\"form1\" id=\"form1\" >\r\n");
      out.write("<table class=\"TableBlock_page\" width=\"90%\" align=\"center\">\r\n");
      out.write("\t<tbody style=\"");
      out.print(adminPriv?"":"display:none");
      out.write("\">\r\n");
      out.write("\t\t   <tr>\r\n");
      out.write("\t\t    <td colspan=\"2\" style='vertical-align: middle;font-family: MicroSoft YaHei;font-size: 14px;line-height: 30px;'><img src=\"");
      out.print(contextPath );
      out.write("/common/zt_webframe/imgs/common_img/icon_yhcx.png\" align=\"absMiddle\">&nbsp;&nbsp; <span>用户基本信息</span></td>\r\n");
      out.write("\t\t   </tr>\r\n");
      out.write("\t\t   <tr>\r\n");
      out.write("\t\t    <td style=\"text-indent: 10px;\" nowrap class=\"TableData\" width=\"120\">用户名：<span style=\"\"></span></td>\r\n");
      out.write("\t\t    <td nowrap class=\"TableData\">\r\n");
      out.write("\t\t        <input style=\"height: 25px;font-family: MicroSoft YaHei;font-size: 12px;\" type=\"text\" id=\"userId\" name=\"userId\" class=\"BigInput\"  required  size=\"15\" newMaxLength=\"20\" onBlur=\"check_user(this.value)\"/>&nbsp;<span id=\"user_id_msg\"></span> \r\n");
      out.write("\t\t    </td>\r\n");
      out.write("\t\t   </tr>\r\n");
      out.write("\t\t   <tr>\r\n");
      out.write("\t\t    <td style=\"text-indent: 10px;\" nowrap class=\"TableData\">用户姓名：</td>\r\n");
      out.write("\t\t    <td nowrap class=\"TableData\">\r\n");
      out.write("\t\t    <input style=\"height: 25px;font-family: MicroSoft YaHei;font-size: 12px;\" type=\"text\" name=\"userName\" id=\"userName\" size=\"15\" newMaxLength=\"20\" class=\"easyui-validatebox BigInput\"  required/>\r\n");
      out.write("\t\t         </td>\r\n");
      out.write("\t\t   </tr>\r\n");
      out.write("\t\t   \t\t   <tr>\r\n");
      out.write("\t\t    <td style=\"text-indent: 10px;\" nowrap class=\"TableData\">执法证号：</td>\r\n");
      out.write("\t\t    <td nowrap class=\"TableData\">\r\n");
      out.write("\t\t    <input style=\"height: 25px;font-family: MicroSoft YaHei;font-size: 12px;\" type=\"text\" name=\"performCode\" id=\"performCode\" size=\"15\" newMaxLength=\"20\" class=\"easyui-validatebox BigInput\"/>\r\n");
      out.write("\t\t         </td>\r\n");
      out.write("\t\t   </tr>\r\n");
      out.write("\t\t   <tr>\r\n");
      out.write("\t\t    <td style=\"text-indent: 10px;\" nowrap class=\"TableData\">部门：</td>\r\n");
      out.write("\t\t    <td nowrap class=\"TableData\">\r\n");
      out.write("\t\t\t\t<input id=\"deptId\" name=\"deptId\"  type=\"text\" style=\"display:none;\" value=\"");
      out.print(deptId );
      out.write("\"/>\t\t\r\n");
      out.write("\t\t\t\t<input style=\"height: 25px;font-family: MicroSoft YaHei;font-size: 12px;\" id=\"deptIdName\" name=\"deptIdName\"  type=\"text\" class=\"BigInput\" readonly/>\t\r\n");
      out.write("\t\t\t\t<span class='addSpan'>\r\n");
      out.write("\t\t\t\t         \t<img src=\"");
      out.print(contextPath );
      out.write("/common/zt_webframe/imgs/xtgl/zzjggl/yhgl/add.png\" onclick=\"selectSingleDept(['deptId','deptIdName'],'0')\" value=\"选择\"/>\r\n");
      out.write("\t\t\t\t </span>\r\n");
      out.write("\t\t<!-- \t\t<ul id=\"deptIdZTree\" class=\"ztree\" style=\"margin-top:0; width:247px; display:none;\"></ul> -->\r\n");
      out.write("\t\t\t\t\t&nbsp;&nbsp;<a href=\"javascript:selectDeptOther()\">指定其它所属部门</a>\r\n");
      out.write("\t\t         </td>\r\n");
      out.write("\t\t   </tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t   <tr id=\"dept_other\" style=\"display:none;\">\r\n");
      out.write("\t\t      <td style=\"text-indent: 10px;\" nowrap class=\"TableData\">所属部门：</td>\r\n");
      out.write("\t\t      <td class=\"TableData\">\r\n");
      out.write("\t\t      \r\n");
      out.write("\t\t     <!-- <select multiple=\"multiple\" size=\"10\" id=\"deptIdOtherStr\" style=\"width:150px;\">\r\n");
      out.write("\t\t     </select> -->\r\n");
      out.write("\t\t       <input type=\"hidden\" name=\"deptIdOtherStr\" id=\"deptIdOtherStr\" value=\"\"/>\r\n");
      out.write("\t\t        <textarea cols=30 name=\"deptIdOtherStrName\" id=\"deptIdOtherStrName\" style=\"font-family: MicroSoft YaHei;font-size: 12px;\"  rows=2 class=\"SmallStatic  BigTextarea\" wrap=\"yes\" readonly ></textarea>\r\n");
      out.write("\t\t        <span class='addSpan'>\r\n");
      out.write("\t\t\t\t         \t<img src=\"");
      out.print(contextPath );
      out.write("/common/zt_webframe/imgs/xtgl/zzjggl/yhgl/add.png\" onclick=\"selectDept(['deptIdOtherStr','deptIdOtherStrName'],'1')\" value=\"选择\"/>\r\n");
      out.write("\t\t\t\t\t        <img src=\"");
      out.print(contextPath );
      out.write("/common/zt_webframe/imgs/xtgl/zzjggl/yhgl/clear.png\"  onclick=\"clearData('deptIdOtherStr','deptIdOtherStrName')\" value=\"清空\"/>\r\n");
      out.write("\t\t\t\t </span>\r\n");
      out.write("\t\t      </td>\r\n");
      out.write("\t\t   </tr>\r\n");
      out.write("\t\t   <tr>\r\n");
      out.write("\t\t    <td style=\"text-indent: 10px;\" nowrap class=\"TableData\">主角色：</td>\r\n");
      out.write("\t\t    <td nowrap class=\"TableData\">\r\n");
      out.write("\t\t        <select style=\"height: 25px;font-family: MicroSoft YaHei;font-size: 12px;\" name=\"userRoleStr\"  id=\"userRoleStr\"  class=\"BigSelect\"  >\r\n");
      out.write("\t\t     \r\n");
      out.write("\t\t     \t </select>\r\n");
      out.write("\t\t     \t  <span id=\"isNotSuperAdminRole\" >\r\n");
      out.write("\t\t     \t     </span>\r\n");
      out.write("\t\t     \t     \r\n");
      out.write("\t\t     \t     \r\n");
      out.write("\t\t     <span>\r\n");
      out.write("\t\t     &nbsp;&nbsp;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t      <a href=\"javascript:select_priv();\">指定辅助角色</a>\r\n");
      out.write("\t\t     </span>\r\n");
      out.write("\t\t     \r\n");
      out.write("\t\t      <br>\r\n");
      out.write("\t\t    </td>\r\n");
      out.write("\t\t   </tr>\r\n");
      out.write("\t\t   <tr id=\"priv\" style=\"display:none;\">\r\n");
      out.write("\t\t      <td style=\"text-indent: 10px;\" nowrap class=\"TableData\">辅助角色：</td>\r\n");
      out.write("\t\t \r\n");
      out.write("\t\t      <td class=\"TableData\">\r\n");
      out.write("\t\t      <!-- <select multiple=\"multiple\" size=\"10\" id=\"privIdStr\" style=\"width:150px;\">\r\n");
      out.write("\t\t     </select> -->\r\n");
      out.write("\t\t    \t<input type=\"hidden\" name=\"userRoleOtherId\"  id=\"userRoleOtherId\" value=\"\"/> \r\n");
      out.write("\t\t        <textarea style=\"font-family: MicroSoft YaHei;font-size: 12px;\" cols=30 id=\"userRoleOtherName\" name=\"userRoleOtherName\" rows=2 class=\"SmallStatic  BigTextarea\" wrap=\"yes\" readonly></textarea>\r\n");
      out.write("\t\t        <span class='addSpan'>\r\n");
      out.write("\t\t\t\t         \t<img src=\"");
      out.print(contextPath );
      out.write("/common/zt_webframe/imgs/xtgl/zzjggl/yhgl/add.png\" onclick=\"selectRole(['userRoleOtherId','userRoleOtherName'],'','','2')\" value=\"选择\"/>\r\n");
      out.write("\t\t\t\t\t        <img src=\"");
      out.print(contextPath );
      out.write("/common/zt_webframe/imgs/xtgl/zzjggl/yhgl/clear.png\"  onclick=\"clearData('userRoleOtherId', 'userRoleOtherName')\" value=\"清空\"/>\r\n");
      out.write("\t\t\t\t </span>\r\n");
      out.write("\t\t        <br >（辅助角色仅用于扩展主角色）      </td>\r\n");
      out.write("\t\t   </tr>\r\n");
      out.write("\t\t    <tr>\r\n");
      out.write("\t\t    <td style=\"text-indent: 10px;\" nowrap class=\"TableData\">用户排序号：</td>\r\n");
      out.write("\t\t    <td nowrap class=\"TableData\">\r\n");
      out.write("\t\t        <input style=\"height: 25px;font-family: MicroSoft YaHei;font-size: 12px;\" type=\"text\" name=\"userNo\" class=\" BigInput\" size=\"5\"  newMaxLength=\"4\"  value=\"\" required positive_integer=\"true\">&nbsp;\r\n");
      out.write("\t\t        <span>（用于同角色用户的排序 ）</span>   </td>\r\n");
      out.write("\t\t   </tr>\r\n");
      out.write("\t\t    <tr>\r\n");
      out.write("\t\t    <td style=\"text-indent: 10px;\" nowrap class=\"TableData\">直属上级：</td>\r\n");
      out.write("\t\t    <td  class=\"TableData\">\r\n");
      out.write("\t\t    \t<input id=\"leaderIds\" name=\"leaderIds\" type=\"hidden\"/>\r\n");
      out.write("\t\t    \t<input type=\"text\" style=\"height: 25px;font-family: MicroSoft YaHei;font-size: 12px;\"  id=\"leaderNames\" class=\"BigInput\" readonly />\r\n");
      out.write("\t\t    \t <span class='addSpan'>\r\n");
      out.write("\t\t\t\t         \t<img src=\"");
      out.print(contextPath );
      out.write("/common/zt_webframe/imgs/xtgl/zzjggl/yhgl/add.png\" onclick=\"selectSingleUser(['leaderIds','leaderNames'])\" value=\"选择\"/>\r\n");
      out.write("\t\t\t\t\t        <img src=\"");
      out.print(contextPath );
      out.write("/common/zt_webframe/imgs/xtgl/zzjggl/yhgl/clear.png\"  onclick=\"clearData('leaderIds','leaderNames')\" value=\"清空\"/>\r\n");
      out.write("\t\t\t\t </span>\r\n");
      out.write("\t\t    </td>\r\n");
      out.write("\t\t   </tr>\r\n");
      out.write("\t\t    <tr style=\"display:none\">\r\n");
      out.write("\t\t    <td style=\"text-indent: 10px;\" nowrap class=\"TableData\">直属下级：</td>\r\n");
      out.write("\t\t    <td  class=\"TableData\">\r\n");
      out.write("\t\t    \t<input id=\"underlingIds\" name=\"underlingIds\" type=\"hidden\"/>\r\n");
      out.write("\t\t    \t<textarea style=\"font-family: MicroSoft YaHei;font-size: 12px;\" rows=\"2\" cols=\"30\" id=\"underlingNames\" class=\"BigTextarea readonly\" readonly></textarea>\r\n");
      out.write("\t\t    \t <span class='addSpan'>\r\n");
      out.write("\t\t\t\t         \t<img src=\"");
      out.print(contextPath );
      out.write("/common/zt_webframe/imgs/xtgl/zzjggl/yhgl/add.png\" onclick=\"selectUser(['underlingIds','underlingNames'])\" value=\"选择\"/>\r\n");
      out.write("\t\t\t\t\t        <img src=\"");
      out.print(contextPath );
      out.write("/common/zt_webframe/imgs/xtgl/zzjggl/yhgl/clear.png\"  onclick=\"clearData('underlingIds','underlingNames')\" value=\"清空\"/>\r\n");
      out.write("\t\t\t\t </span>\r\n");
      out.write("\t\t    \t\r\n");
      out.write("\t\t   \t</td>\r\n");
      out.write("\t\t   </tr>\r\n");
      out.write("\t</tbody>\r\n");
      out.write("\t\r\n");
      out.write("   \r\n");
      out.write("\t\t <tr ");
      out.print("4".equals(uuid)?"style='display:none'":"" );
      out.write("  style=\"");
      out.print(saferPriv?"":"display:none");
      out.write("\" >\r\n");
      out.write("\t\t   <td  colspan=\"2\" style='vertical-align: middle;font-family: MicroSoft YaHei;font-size: 14px;line-height: 30px;'><img src=\"");
      out.print(contextPath );
      out.write("/common/zt_webframe/imgs/common_img/icon_yhcx.png\">&nbsp;&nbsp; <span>用户权限信息</span></td>\r\n");
      out.write("\t\t  </tr>\r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t<tbody id=\"isNotSuperAdmin\" style=\"");
      out.print(saferPriv?"":"display:none");
      out.write("\">   \r\n");
      out.write("\t\t   <tr >  \r\n");
      out.write("\t\t   <td style=\"text-indent: 10px;\" nowrap class=\"TableData\" width=\"120\">可见范围：</td>\r\n");
      out.write("\t\t   <td nowrap class=\"TableData\">\r\n");
      out.write("\t\t       <select style=\"height: 25px;font-family: MicroSoft YaHei;font-size: 12px;\" name=\"viewPriv\"  id=\"viewPriv\" class=\"BigSelect\" OnChange=\"selectViewDept()\">\r\n");
      out.write("\t\t       \t<option value=\"0\">请选择</option>\r\n");
      out.write("\t\t       \t<option value=\"1\">本机构</option>\r\n");
      out.write("\t\t       \t<option value=\"3\">本部门</option>\r\n");
      out.write("\t\t       \t<option value=\"4\">本部门及以下部门</option>\r\n");
      out.write("\t\t       \t<option value=\"2\">指定部门</option>\r\n");
      out.write("\t\t       </select>\r\n");
      out.write("\t\t       <br/>\r\n");
      out.write("\t\t       （可见范围是指用户在选人、选部门、查看组织机构等信息时，可查看到的指定部门及机构信息。）\r\n");
      out.write("\t\t   </td>\r\n");
      out.write("\t\t  </tr>\r\n");
      out.write("\t\t  <tr id=\"view_dept\" style=\"display:none;\">\r\n");
      out.write("\t\t     <td style=\"text-indent: 10px;\" nowrap class=\"TableData\">可见范围（部门/机构）：</td>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t     <td class=\"TableData\">\r\n");
      out.write("\t\t \t <input type=\"hidden\" name=\"viewDeptIds\" id=\"viewDeptIds\" value=\"\">\r\n");
      out.write("\t\t       <textarea cols=30 name=\"viewDeptNames\" id=\"viewDeptNames\" rows=2 class=\"SmallStatic   BigTextarea\" wrap=\"yes\" readonly ></textarea>\r\n");
      out.write("\t\t       <a href=\"javascript:void(0);\" class=\"orgAdd\" onClick=\"selectDept(['viewDeptIds','viewDeptNames'],'1')\">选择</a>\r\n");
      out.write("\t\t       <a href=\"javascript:void(0);\" class=\"orgClear\" onClick=\"clearData('viewDeptIds','viewDeptNames')\">清空</a>\r\n");
      out.write("\t\t     </td>\r\n");
      out.write("\t\t   </tr>\r\n");
      out.write("\t\t   \r\n");
      out.write("\t\t   \r\n");
      out.write("\t\t    <tr >\r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t   <td style=\"text-indent: 10px;\" nowrap class=\"TableData\" width=\"120\">管理范围：</td>\r\n");
      out.write("\t\t   <td nowrap class=\"TableData\">\r\n");
      out.write("\t\t       <select style=\"height: 25px;font-family: MicroSoft YaHei;font-size: 12px;\" name=\"postPriv\"  id=\"postPriv\" class=\"BigSelect\" OnChange=\"selectPostDept()\">\r\n");
      out.write("\t\t         <option value=\"-1\">请选择</option>\r\n");
      out.write("\t\t         <option value=\"0\">本部门</option>\r\n");
      out.write("\t\t         <option value=\"3\">本部门以及下级所有部门</option>\r\n");
      out.write("\t\t         <option value=\"4\">本机构</option>\r\n");
      out.write("\t\t         <option value=\"1\">全体</option>\r\n");
      out.write("\t\t         <option value=\"2\">指定部门</option>\r\n");
      out.write("\t\t       </select>\r\n");
      out.write("\t\t       \r\n");
      out.write("\t\t    \t\t&nbsp;&nbsp;<a href=\"javascript:module_priv();\">按模块设置管理范围</a>\r\n");
      out.write("\t\t      \t\t（ 在管理型模块中起约束作用 ）\r\n");
      out.write("\t\t     \r\n");
      out.write("\t\t       \r\n");
      out.write("\t\t         </td>\r\n");
      out.write("\t\t  </tr>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t  <tr id=\"post_dept\" style=\"display:none;\">\r\n");
      out.write("\t\t     <td style=\"text-indent: 10px;\" nowrap class=\"TableData\">管理范围（部门）：</td>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t     <td class=\"TableData\">\r\n");
      out.write("\t\t \t <input type=\"hidden\" name=\"postDeptStr\" id=\"postDeptStr\" value=\"\">\r\n");
      out.write("\t\t       <textarea style=\"height: 25px;\" cols=30 name=\"postDeptStrName\" id=\"postDeptStrName\" rows=2 class=\"SmallStatic\" wrap=\"yes\" readonly ></textarea>\r\n");
      out.write("\t\t       <a href=\"javascript:void(0);\" class=\"orgAdd\" onClick=\"selectDept(['postDeptStr','postDeptStrName'],'1')\">选择</a>\r\n");
      out.write("\t\t       <a href=\"javascript:void(0);\" class=\"orgClear\" onClick=\"clearData('postDeptStr','postDeptStrName')\">清空</a>\r\n");
      out.write("\t\t  \r\n");
      out.write("\t\t     </td>\r\n");
      out.write("\t\t   </tr>\r\n");
      out.write("\t\t   \r\n");
      out.write("\t\t   \r\n");
      out.write("\t\t   \r\n");
      out.write("\t\t  <tr>\r\n");
      out.write("\t\t   <td style=\"text-indent: 10px;\" nowrap class=\"TableData\">访问控制：</td>\r\n");
      out.write("\t\t   <td nowrap class=\"TableData\">\r\n");
      out.write("\t\t       <input type=\"checkbox\" name=\"notLogin\" id=\"notLogin\" value=\"1\"><label for=\"notLogin\" style=\"cursor: hand\">禁止登录OA系统</label>&nbsp;\r\n");
      out.write("\t\t   \t<input type=\"checkbox\" name=\"notViewUser\" id=\"notViewUser\" value=\"1\" ><label for=\"notViewUser\" style=\"cursor: hand\">禁止查看用户列表</label>&nbsp;\r\n");
      out.write("\t\t   \t<input type=\"checkbox\" name=\"notWebLogin\" id=\"notWebLogin\" value=\"1\" ><label for=\"notWebLogin\" style=\"cursor: hand\">禁止WEB登陆</label>&nbsp;\r\n");
      out.write("\t\t   \t<input type=\"checkbox\" name=\"notMobileLogin\" id=\"notMobileLogin\" value=\"1\" ><label for=\"notMobileLogin\" style=\"cursor: hand\">禁止移动端登陆</label>&nbsp;\r\n");
      out.write("\t\t   \t<input type=\"checkbox\" name=\"notPcLogin\" id=\"notPcLogin\" value=\"1\" ><label for=\"notPcLogin\" style=\"cursor: hand\">禁止PC端登陆</label>&nbsp;\r\n");
      out.write("\t\t   \t<!-- <input type=\"checkbox\" name=\"notViewTable\" id=\"notViewTable\" value=\"1\" ><label for=\"notViewTable\" style=\"cursor: hand\">禁止显示桌面</label>-->\r\n");
      out.write("\t\t       <!--<input type=\"checkbox\" name=\"notSearch\" id=\"notSearch\" value=\"1\" ><label for=\"notSearch\" style=\"cursor: hand\">禁止OA搜索</label> -->\r\n");
      out.write("\t\t     </td>\r\n");
      out.write("\t\t   </tr>\r\n");
      out.write("\t\t</tbody>\r\n");
      out.write("\t\t  <tr ");
      out.print("4".equals(uuid)?"style='display:none'":"" );
      out.write("  style=\"");
      out.print(saferPriv?"":"display:none");
      out.write("\">\r\n");
      out.write("\t\t     <td style=\"text-indent: 10px;\" nowrap class=\"TableData\">菜单组（菜单权限设置）：</td>\r\n");
      out.write("\t\t     <td class=\"TableData\">\r\n");
      out.write("\t\t    \r\n");
      out.write("\t\t      <input type=\"hidden\" name=\"menuGroupsStr\" id=\"menuGroupsStr\" value=\"\">\r\n");
      out.write("\t\t       <textarea style=\"font-family: MicroSoft YaHei;font-size: 12px;\" cols=30 name=\"menuGroupsStrName\" id=\"menuGroupsStrName\" rows=2 class=\"BigTextarea\" wrap=\"yes\" readonly ></textarea>\r\n");
      out.write("\t\t        <span class='addSpan'>\r\n");
      out.write("\t\t\t         \t<img src=\"");
      out.print(contextPath );
      out.write("/common/zt_webframe/imgs/xtgl/zzjggl/yhgl/add.png\" onclick=\"selectMenuGroup(['menuGroupsStr','menuGroupsStrName'],'1')\" value=\"选择\"/>\r\n");
      out.write("\t\t\t\t        <img src=\"");
      out.print(contextPath );
      out.write("/common/zt_webframe/imgs/xtgl/zzjggl/yhgl/clear.png\"  onclick=\"clearData('menuGroupsStr','menuGroupsStrName')\" value=\"清空\"/>\r\n");
      out.write("\t\t\t </span>\r\n");
      out.write("\t\t       \r\n");
      out.write("\t\t     </td>\r\n");
      out.write("\t\t  </tr>\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("  <tr onClick=\"setOption('option1')\"  style=\"");
      out.print(adminPriv?"cursor: pointer;":"display:none;cursor: pointer;");
      out.write("\" title=\"点击展开/收缩选项\" >\r\n");
      out.write("    <td colspan=\"2\" style='vertical-align: middle;font-family: MicroSoft YaHei;font-size: 14px;line-height: 30px;'><img src=\"");
      out.print(contextPath );
      out.write("/common/zt_webframe/imgs/common_img/icon_yhcx.png\">&nbsp;&nbsp; <span>其它选项</span></td>\r\n");
      out.write("   </tr>\r\n");
      out.write("   <tbody id=\"option1\"  style=\"");
      out.print(adminPriv?"":"display:none;");
      out.write("\">\r\n");
      out.write("   <tr style=\"display: none\">\r\n");
      out.write("    <td style=\"text-indent: 10px;\" nowrap class=\"TableData\">考勤排班类型：</td>\r\n");
      out.write("    <td nowrap class=\"TableData\">\r\n");
      out.write("        <select style=\"height: 25px;font-family: MicroSoft YaHei;font-size: 12px;\" name=\"dutyType\" id=\"dutyType\" class=\"BigSelect\">\r\n");
      out.write("        </select>\r\n");
      out.write("    </td>\r\n");
      out.write("   </tr>\r\n");
      out.write("   <tr>\r\n");
      out.write("    <td style=\"text-indent: 10px;\" nowrap class=\"TableData\">考勤签到方式：</td>\r\n");
      out.write("    <td nowrap class=\"TableData\">\r\n");
      out.write("        <select style=\"height: 25px;width:150px; font-family: MicroSoft YaHei;font-size: 12px;\" name=\"signWay\" id=\"signWay\" class=\"BigSelect\">\r\n");
      out.write("             <option value=\"1\">组合签到</option>\r\n");
      out.write("             <option value=\"2\">移动端签到</option>\r\n");
      out.write("             <option value=\"3\">网页签到</option>\r\n");
      out.write("        </select>\r\n");
      out.write("    </td>\r\n");
      out.write("   </tr>\r\n");
      out.write("   <tr>\r\n");
      out.write("    <td style=\"text-indent: 10px;\" nowrap class=\"TableData\">默认桌面模块：</td>\r\n");
      out.write("    <td nowrap class=\"TableData\">\r\n");
      out.write("        <select style=\"height: 25px;font-family: MicroSoft YaHei;font-size: 12px;\" name=\"desktop\" id=\"desktop\" class=\"BigSelect\">\r\n");
      out.write("        </select>\r\n");
      out.write("    </td>\r\n");
      out.write("   </tr>\r\n");
      out.write("   <tr>\r\n");
      out.write("    <td style=\"text-indent: 10px;\" nowrap class=\"TableData\">内部邮箱容量：</td>\r\n");
      out.write("    <td nowrap class=\"TableData\">\r\n");
      out.write("        <input style=\"height: 25px;font-family: MicroSoft YaHei;font-size: 12px;\" type=\"text\" name=\"emailCapacity\"   class=\"easyui-validatebox BigInput\" validType ='integeZero[]' size=\"5\" newMaxLength=\"11\" value=\"500\">&nbsp;MB\r\n");
      out.write("        （0为空则表示不限制大小）    </td>\r\n");
      out.write("   </tr>\r\n");
      out.write("   <tr>\r\n");
      out.write("    <td style=\"text-indent: 10px;\" nowrap class=\"TableData\">个人网盘容量：</td>\r\n");
      out.write("    <td nowrap class=\"TableData\">\r\n");
      out.write("        <input style=\"height: 25px;font-family: MicroSoft YaHei;font-size: 12px;\" type=\"text\" name=\"folderCapacity\"  class=\" BigInput\" validType ='integeZero[]' size=\"5\" newMaxLength=\"11\" value=\"500\">&nbsp;MB\r\n");
      out.write("        （0为空则表示不限制大小 ）   </td>\r\n");
      out.write("   </tr>\r\n");
      out.write("     <tr style=\"display:none;\">\r\n");
      out.write("    <td style=\"text-indent: 10px;\" nowrap class=\"TableData\">是否启用POP3功能：</td>\r\n");
      out.write("    <td nowrap class=\"TableData\">\r\n");
      out.write("       <input type=\"checkbox\" name=\"usePops\" id=\"usePops\" value=\"1\" ><label for=\"usePops\" style=\"cursor: hand\">是</label>\r\n");
      out.write("    </td>\r\n");
      out.write("   </tr>\r\n");
      out.write("   \r\n");
      out.write(" \r\n");
      out.write("   <tr id=\"internet1\" style=\"display:none;\">\r\n");
      out.write("    <td style=\"text-indent: 10px;\" nowrap class=\"TableData\">Internet邮箱数量：</td>\r\n");
      out.write("    <td nowrap class=\"TableData\">\r\n");
      out.write("        <input type=\"text\" name=\"webmailNum\"  class=\"BigInput\" validType =''  size=\"5\" newMaxLength=\"11\" value=\"\">&nbsp;个        为空则表示不限制数量    </td>\r\n");
      out.write("   </tr>\r\n");
      out.write("   <tr id=\"internet2\" style=\"display:none;\">\r\n");
      out.write("    <td style=\"text-indent: 10px;\" nowrap class=\"TableData\">每个Internet邮箱容量：</td>\r\n");
      out.write("    <td nowrap class=\"TableData\">\r\n");
      out.write("        <input type=\"text\" name=\"webmailCapacity\" class=\"BigInput\" validType =''  size=\"5\" newMaxLength=\"11\" value=\"\">&nbsp;MB\r\n");
      out.write("        为空则表示不限制大小    </td>\r\n");
      out.write("   </tr>\r\n");
      out.write(" \r\n");
      out.write("   <tr>\r\n");
      out.write("    <td style=\"text-indent: 10px;\" nowrap class=\"TableData\">绑定IP地址：</td>\r\n");
      out.write("    <td nowrap class=\"TableData\">\r\n");
      out.write("      <textarea style=\"font-family: MicroSoft YaHei;font-size: 12px;\" name=\"bindIp\" cols=\"60\" rows=\"2\" id='bindIp' class=\"BigTextarea\" validType='ipValid[]'></textarea><br>\r\n");
      out.write("        （为空则该用户不绑定固定的IP地址，绑定多个IP地址用英文逗号(,)隔开<br>也可以绑定IP段，如“192.168.0.60,192.168.0.100-192.168.0.200”<br>表示192.168.0.60或192.168.0.100到192.168.0.200这个范围内都可以登录 ）\r\n");
      out.write("    </td>\r\n");
      out.write("   </tr>\r\n");
      out.write("   <tr>\r\n");
      out.write("    <td style=\"text-indent: 10px;\" nowrap class=\"TableData\">绑定MAC地址：</td>\r\n");
      out.write("    <td  class=\"TableData\"> \r\n");
      out.write("      <textarea style=\"font-family: MicroSoft YaHei;font-size: 12px;\" name=\"bindMac\" cols=\"60\" rows=\"3\" id='bindMac' class=\"easyui-validatebox BigTextarea\" validType='macValid[]'></textarea><br>\r\n");
      out.write("     （ 为空则该用户不绑定固定的MAC地址，绑定多个MAC地址用英文逗号(,)隔开，<br/>比如：A4:DB:30:5B:ED:40,A4:DB:30:5B:ED:41）\r\n");
      out.write("    </td>\r\n");
      out.write("   </tr>\r\n");
      out.write("   <tr>\r\n");
      out.write("    <td style=\"text-indent: 10px;\" nowrap class=\"TableData\">移动设备ID：</td>\r\n");
      out.write("    <td nowrap class=\"TableData\">\r\n");
      out.write("      <input style=\"font-family: MicroSoft YaHei;font-size: 12px;\" type=\"text\" name=\"deviceId\"  class=\"BigInput\" />\r\n");
      out.write("      <br/>\r\n");
      out.write("      （绑定移动设备ID，仅允许指定移动终端进行登录。为空则不限制）\r\n");
      out.write("    </td>\r\n");
      out.write("   </tr>\r\n");
      out.write("   <tr>\r\n");
      out.write("    <td style=\"text-indent: 10px;\" nowrap class=\"TableData\">IMEI码：</td>\r\n");
      out.write("    <td nowrap class=\"TableData\">\r\n");
      out.write("      <input style=\"font-family: MicroSoft YaHei;font-size: 12px;\" type=\"text\" name=\"secureKeySn\"  class=\"BigInput\" />\r\n");
      out.write("      <br/>\r\n");
      out.write("      （设备的IMEI码，用于点聚AIP版式文件授权）\r\n");
      out.write("    </td>\r\n");
      out.write("   </tr>\r\n");
      out.write("   <tr>\r\n");
      out.write("    <td style=\"text-indent: 10px;\" nowrap class=\"TableData\">点聚AIP授权码：</td>\r\n");
      out.write("    <td nowrap class=\"TableData\">\r\n");
      out.write("      <input style=\"font-family: MicroSoft YaHei;font-size: 12px;\" type=\"text\" name=\"icq_no\"  class=\"BigInput\" />\r\n");
      out.write("    </td>\r\n");
      out.write("   </tr>\r\n");
      out.write("   <tr>\r\n");
      out.write("    <td style=\"text-indent: 10px;\" nowrap class=\"TableData\">统计图地址：</td>\r\n");
      out.write("    <td nowrap class=\"TableData\">\r\n");
      out.write("    \t<input style=\"font-family: MicroSoft YaHei;font-size: 12px;\" type=\"text\" name=\"bkground\" id=\"bkground\" class=\"BigInput\" />\r\n");
      out.write("    </td>\r\n");
      out.write("   </tr>\r\n");
      out.write("   </tbody>\r\n");
      out.write("   \r\n");
      out.write("   <tr onClick=\"setOption('option2')\" style=\"");
      out.print(adminPriv?"cursor: pointer;":"display:none;cursor: pointer;");
      out.write("\" title=\"点击展开/收缩选项\">\r\n");
      out.write("    <td colspan=\"2\" style='vertical-align: middle;font-family: MicroSoft YaHei;font-size: 14px;line-height: 30px;'><img src=\"");
      out.print(contextPath );
      out.write("/common/zt_webframe/imgs/common_img/icon_yhcx.png\">&nbsp;&nbsp; <span>扩展信息</span></td>\r\n");
      out.write("   </tr>\r\n");
      out.write("   <tbody id=\"option2\" style=\"");
      out.print(adminPriv?"":"display:none;");
      out.write("\">\r\n");
      out.write("   <tr>\r\n");
      out.write("    <td style=\"text-indent: 10px;\" nowrap class=\"TableData\" width=\"120\">别名：</td>\r\n");
      out.write("    <td nowrap class=\"TableData\">\r\n");
      out.write("        <input style=\"height:25px;font-family: MicroSoft YaHei;font-size: 12px;\" type=\"text\" name=\"byname\" class=\"BigInput\" size=\"10\" newMaxLength=\"20\">\r\n");
      out.write("    </td>\r\n");
      out.write("   </tr>\r\n");
      out.write("   ");

					if (TeeUtility.isNullorEmpty(uuid)) {
				
      out.write("    <tr>\r\n");
      out.write("    <td style=\"text-indent: 10px;\" nowrap class=\"TableData\">密码：</td>\r\n");
      out.write("    <td nowrap class=\"TableData\">\r\n");
      out.write("        <input style=\"height:25px; font-family: MicroSoft YaHei;font-size: 12px;\" type=\"password\" name=\"password\" class=\"BigInput\" size=\"20\" newMaxLength=\"20\"> 8-20位，必须同时包含字母和数字    </td>\r\n");
      out.write("   </tr> ");

 					} 
 				
      out.write(" \r\n");
      out.write("\r\n");
      out.write("   <tr>\r\n");
      out.write("    <td style=\"text-indent: 10px;\" nowrap class=\"TableData\">性别：</td>\r\n");
      out.write("    <td nowrap class=\"TableData\">\r\n");
      out.write("        <select style=\"height:25px; font-family: MicroSoft YaHei;font-size: 12px;\" name=\"sex\" class=\"BigSelect\">\r\n");
      out.write("        <option value=\"0\">男</option>\r\n");
      out.write("        <option value=\"1\">女</option>\r\n");
      out.write("        </select>\r\n");
      out.write("    </td>\r\n");
      out.write("   </tr>\r\n");
      out.write("   <tr>\r\n");
      out.write("    <td style=\"text-indent: 10px;\" nowrap class=\"TableData\">生日：</td>\r\n");
      out.write("    <td nowrap class=\"TableData\">\r\n");
      out.write("        <input style=\"height:25px; font-family: MicroSoft YaHei;font-size: 12px;\" type=\"text\" name=\"birthdayStr\" size=\"10\" newMaxLength=\"10\" value=\"\" class=\"BigInput\" onClick=\"WdatePicker()\"  class=\"easyui-validatebox\" validType ='date[]'/>&nbsp;&nbsp;\r\n");
      out.write("       <!--  <input type=\"checkbox\" name=\"isLunar\" id=\"isLunar\"><label for=\"isLunar\">是农历生日</label>      -->\r\n");
      out.write("    </td>\r\n");
      out.write("   </tr>\r\n");
      out.write("   <tr>\r\n");
      out.write("      <td style=\"text-indent: 10px;\" nowrap class=\"TableData\">界面主题：</td>\r\n");
      out.write("      <td class=\"TableData\">\r\n");
      out.write("        <select style=\"height:25px; font-family: MicroSoft YaHei;font-size: 12px;\" name=\"theme\" class=\"BigSelect\">\r\n");
      out.write("\t  \t\t<option value=\"4\" >现代门户</option>\r\n");
      out.write("\t  \t\t<option value=\"8\" >智慧政务</option>\r\n");
      out.write("\t  \t\t<option value=\"classic\" selected>2017版经典</option>\r\n");
      out.write("        </select>\r\n");
      out.write("      </td>\r\n");
      out.write("    </tr>\r\n");
      out.write("   <tr>\r\n");
      out.write("      <td style=\"text-indent: 10px;\" nowrap class=\"TableData\"> 手机：</td>\r\n");
      out.write("      <td class=\"TableData\">\r\n");
      out.write("        <input style=\"height:25px; font-family: MicroSoft YaHei;font-size: 12px;\" type=\"text\" name=\"mobilNo\" size=\"16\" newMaxLength=\"23\" class=\"BigInput\" value=\"\">\r\n");
      out.write("        <input type=\"checkbox\" name=\"mobilNoHidden\" id=\"mobilNoHidden\" value='1'><label for=\"mobilNoHidden\" style=\"cursor: hand;\">手机号码不公开</label><br>\r\n");
      out.write("        （填写后可接收OA系统发送的手机短信，手机号码不公开仍可接收短信）      </td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <td style=\"text-indent: 10px;\" nowrap class=\"TableData\"> 电子邮件：</td>\r\n");
      out.write("      <td class=\"TableData\">\r\n");
      out.write("        <input style=\"height:25px; font-family: MicroSoft YaHei;font-size: 12px;\" type=\"text\" name=\"email\" size=\"25\" newMaxLength=\"50\" class=\"BigInput\" value=\"\">\r\n");
      out.write("      </td>\r\n");
      out.write("    </tr>\r\n");
      out.write("     <tr>\r\n");
      out.write("      <td style=\"text-indent: 10px;\" nowrap class=\"TableData\"> QQ：</td>\r\n");
      out.write("      <td class=\"TableData\">\r\n");
      out.write("        <input style=\"height:25px; font-family: MicroSoft YaHei;font-size: 12px;\" type=\"text\" name=\"oicqNo\" size=\"25\" newMaxLength=\"20\" class=\"BigInput\" value=\"\">\r\n");
      out.write("      </td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <tr>\r\n");
      out.write("      <td style=\"text-indent: 10px;\" nowrap class=\"TableData\"> 微信号：</td>\r\n");
      out.write("      <td class=\"TableData\">\r\n");
      out.write("        <input style=\"height:25px; font-family: MicroSoft YaHei;font-size: 12px;\" type=\"text\" name=\"weixinNo\" size=\"16\" newMaxLength=\"23\" class=\"BigInput\" value=\"\">\r\n");
      out.write("      </td>\r\n");
      out.write("    </tr>\r\n");
      out.write("   <tr>\r\n");
      out.write("      <td style=\"text-indent: 10px;\" nowrap class=\"TableData\"> 工作电话：</td>\r\n");
      out.write("      <td class=\"TableData\">\r\n");
      out.write("        <input style=\"height:25px; font-family: MicroSoft YaHei;font-size: 12px;\" type=\"text\" name=\"telNoDept\" size=\"16\" newMaxLength=\"23\" class=\"BigInput\" value=\"\">\r\n");
      out.write("      </td>\r\n");
      out.write("    </tr>\r\n");
      out.write("\r\n");
      out.write("    <tr>\r\n");
      out.write("      <td style=\"text-indent: 10px;\" nowrap class=\"TableData\"> 工作传真：</td>\r\n");
      out.write("      <td class=\"TableData\">\r\n");
      out.write("        <input style=\"height:25px; font-family: MicroSoft YaHei;font-size: 12px;\" type=\"text\" name=\"faxNoDept\" size=\"16\" newMaxLength=\"23\" class=\"BigInput\" value=\"\">\r\n");
      out.write("      </td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <tr>\r\n");
      out.write("      <td style=\"text-indent: 10px;\" nowrap class=\"TableData\"> 家庭住址：</td>\r\n");
      out.write("      <td class=\"TableData\">\r\n");
      out.write("        <input style=\"height:25px; font-family: MicroSoft YaHei;font-size: 12px;\" type=\"text\" name=\"addHome\" size=\"16\" newMaxLength=\"23\" class=\"BigInput\" value=\"\">\r\n");
      out.write("      </td>\r\n");
      out.write("    </tr>\r\n");
      out.write("     \r\n");
      out.write("   <tr>\r\n");
      out.write("      <td style=\"text-indent: 10px;\" nowrap class=\"TableData\"> 家庭邮编：</td>\r\n");
      out.write("      <td class=\"TableData\">\r\n");
      out.write("        <input style=\"height:25px; font-family: MicroSoft YaHei;font-size: 12px;\" type=\"text\" name=\"postNoHome\" size=\"16\" newMaxLength=\"23\" class=\"BigInput\" value=\"\">\r\n");
      out.write("      </td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <td style=\"text-indent: 10px;\" nowrap class=\"TableData\"> 家庭电话：</td>\r\n");
      out.write("      <td class=\"TableData\">\r\n");
      out.write("        <input style=\"height:25px; font-family: MicroSoft YaHei;font-size: 12px;\" type=\"text\" name=\"telNoHome\" size=\"16\" newMaxLength=\"23\" class=\"BigInput\" value=\"\">\r\n");
      out.write("      </td>\r\n");
      out.write("    </tr>\r\n");
      out.write("     <tr>\r\n");
      out.write("      <td style=\"text-indent: 10px;\" nowrap class=\"TableData\"> 身份证号：</td>\r\n");
      out.write("      <td class=\"TableData\">\r\n");
      out.write("        <input style=\"height:25px; font-family: MicroSoft YaHei;font-size: 12px;\" type=\"text\" name=\"certUniqueId\" size=\"16\" newMaxLength=\"23\" class=\"BigInput\" value=\"\">\r\n");
      out.write("      </td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <td style=\"text-indent: 10px;\" nowrap class=\"TableData\"> 个人签名图片：</td>\r\n");
      out.write("      <td class=\"TableData\">\r\n");
      out.write("        <input type=\"hidden\" id=\"attachId\" name=\"attachId\"></input>\r\n");
      out.write("        <div id=\"uploadDiv\" ></div>\r\n");
      out.write("        <div style=\"margin-top:6px;\">\r\n");
      out.write("        <input class=\"btn-win-white\" id=\"uploadBtn\" type=\"button\" value=\"上传\"/>\r\n");
      out.write("        <input class=\"btn-win-white\"  type=\"button\" value=\"清空\" onclick=\"qingkou();\"/>\r\n");
      out.write("        </div>\r\n");
      out.write("      </td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    \r\n");
      out.write("   </tbody>\r\n");
      out.write("    \t\r\n");
      out.write("   \r\n");
      out.write("   <tr>\r\n");
      out.write("    <td  nowrap style=\"text-align: center;\" colspan=\"2\" align=\"center\">\r\n");
      out.write("        <input type=\"hidden\" id=\"uuid\" name=\"uuid\"  value=\"");
      out.print(uuid );
      out.write("\">\r\n");
      out.write("        <input style=\"width:45px;height: 25px;\" type=\"button\" value=\"保存\" class=\"btn-win-white\" title=\"保存用户\" onclick=\"doSave()\" >&nbsp;&nbsp;\r\n");
      out.write("        <input style=\"width:45px;height: 25px;\" type=\"button\" value=\"返回\" class=\"btn-win-white\" title=\"返回人员列表\" onClick=\"history.go(-1)\">\r\n");
      out.write("    </td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t\r\n");
      out.write("</table>\r\n");
      out.write("  </form>\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(\"#form1\").validate();\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t/**\r\n");
      out.write("\t * 选择部门\r\n");
      out.write("\t * @return\r\n");
      out.write("\t */\r\n");
      out.write("\tfunction selectDept(retArray , moduleId,privNoFlag , noAllDept,callBackFunc) {\r\n");
      out.write("\t  deptRetNameArray = retArray;\r\n");
      out.write("\t  objSelectType  = retArray[2] || \"\";\r\n");
      out.write("\t  var url = contextPath + \"/system/core/orgselect/selectMultiDeptPost.jsp?objSelectType=\" + objSelectType;\r\n");
      out.write("\t  var has = false;\r\n");
      out.write("\t  if (moduleId) {\r\n");
      out.write("\t    url += \"&moduleId=\" + moduleId ;\r\n");
      out.write("\t  }\r\n");
      out.write("\t  if (privNoFlag) {\r\n");
      out.write("\t    url += \"&privNoFlag=\" + privNoFlag ;\r\n");
      out.write("\t  }\r\n");
      out.write("\t  if (noAllDept) {\r\n");
      out.write("\t    url += \"&noAllDept=\" + noAllDept ;\r\n");
      out.write("\t  }\r\n");
      out.write("\t  if(callBackFunc){\r\n");
      out.write("\t\t  url += \"&callBackPara=\" + callBackFunc ;\r\n");
      out.write("\t  }\r\n");
      out.write("\t  var IM_OA;\r\n");
      out.write("\ttry{\r\n");
      out.write("\t    IM_OA = window.external.IM_OA;\r\n");
      out.write("\t}catch(e){}\r\n");
      out.write("\r\n");
      out.write("\tif(window.showModelDialog || IM_OA){\r\n");
      out.write("\t\t  dialogChangesize(url, 560, 400);\r\n");
      out.write("\t  }else{\r\n");
      out.write("\t\t  openWindow(url,\"选择人员\", 560, 400);\r\n");
      out.write("\t  }\r\n");
      out.write("\t  \r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t/**\r\n");
      out.write("\t * 选择单个部门\r\n");
      out.write("\t * @return\r\n");
      out.write("\t */\r\n");
      out.write("\tfunction selectSingleDept(retArray , moduleId,privNoFlag , noAllDept) {\r\n");
      out.write("\t  deptRetNameArray = retArray;\r\n");
      out.write("\t  objSelectType  = retArray[2] || \"\";\r\n");
      out.write("\t  var url = contextPath + \"/system/core/orgselect/selectMultiDeptPost.jsp?objSelectType=\" + objSelectType + \"&isSingle=1\";\r\n");
      out.write("\t  var has = false;\r\n");
      out.write("\t  if (moduleId) {\r\n");
      out.write("\t    url += \"&moduleId=\" + moduleId ;\r\n");
      out.write("\t  }\r\n");
      out.write("\t  if (privNoFlag) {\r\n");
      out.write("\t    url += \"&privNoFlag=\" + privNoFlag ;\r\n");
      out.write("\t  }\r\n");
      out.write("\t  if (noAllDept) {\r\n");
      out.write("\t    url += \"&noAllDept=\" + noAllDept ;\r\n");
      out.write("\t  }\r\n");
      out.write("\t  var IM_OA;\r\n");
      out.write("\ttry{\r\n");
      out.write("\t    IM_OA = window.external.IM_OA;\r\n");
      out.write("\t}catch(e){}\r\n");
      out.write("\r\n");
      out.write("\tif(window.showModelDialog || IM_OA){\r\n");
      out.write("\t\t  dialogChangesize(url, 560, 400);\r\n");
      out.write("\t  }else{\r\n");
      out.write("\t\t  openWindow(url,\"选择人员\", 560, 400);\r\n");
      out.write("\t  }\r\n");
      out.write("\t  \r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</html>\r\n");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else log(t.getMessage(), t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
