
//登记信息-接待模板
var a_tpl = [
'<table>',
	'<tr class="lanky-tr">',
		'<th class="lanky-th" colspan="8">接待信息</th>',
	'</tr>',
	'<tr>',
	    '<td class="lanky-item">申请方式：</td>',
	    '<td class="lanky-td"><input class="lanky-input" type="text" value="${applicationType}"></td>',
	    '<td class="lanky-item">接待日期：</td>',
	    '<td class="lanky-td"><input class="lanky-input" type="text" value="${reception[0].receptionDate}"></td>',
	    '<td class="lanky-item">接待人名称：</td>',
	    '<td class="lanky-td"><input class="lanky-input" type="text" value="${reception[0].dealMan1Id}"></td>',
	    '<td class="lanky-item">第二接待人：</td>',
	    '<td class="lanky-td"><input class="lanky-input" type="text" value="${reception[0].dealMan2Id}"></td>',
	'</tr>',
	'<tr>',
	    '<td class="lanky-item">接待地点：</td>',
	    '<td class="lanky-td" colspan="7"><input class="lanky-input" type="text" value="${reception[0].place}"></td>',
	'</tr>',
	'<tr>',
	    '<td class="lanky-item">复议请求：</td>',
	    '<td class="lanky-td"><input class="lanky-input" type="text" value="${reception[0].recertionTypeCode}"></td>',
	    '<td class="lanky-item">处理结果：</td>',
	    '<td class="lanky-td"><input class="lanky-input" type="text" value="${reception[0].dealResultCode}"></td>',
	    '<td class="lanky-item">是否接受材料：</td>',
	    '<td class="lanky-td"><input class="lanky-input" type="text" value="${reception[0].isReceivingMaterial}"></td>',
	    '<td class="lanky-item"></td>',
	    '<td class="lanky-td"><input type="text" value=""></td>',
	'</tr>',
	'<tr>',
	    '<td class="lanky-item">被接待人信息：</td>',
	    '<td class="lanky-td" colspan="7">',
	        '<textarea class="lanky-input" rows="3" cols="100">',
	        	'{@each reception[0].visitorVo as it, index}',
	  	      	'${it.visitorName};${it.sexCode};身份证号码${it.cardNum};${it.postAddress};邮编${it.postCode};电话${it.phoneNum}</br>',
	  	      	'{@/each}',
	  	      	'&nbsp;共${index}人',
	        '</textarea>',
	    '</td>',
	'</tr>',
	'<tr>',
	    '<td class="lanky-item">接待情况：</td>',
	    '<td class="lanky-td" colspan="7">',
	        '<textarea class="lanky-input" rows="3" cols="100">',
	        	'${reception[0].receptionDetail}',
	        '</textarea>',
	    '</td>',
	'</tr>',
	'<tr>',
	    '<td class="lanky-item">材料信息：</td>',
	    '<td class="lanky-td" colspan="7">',
	        '<textarea class="lanky-input" rows="3" cols="100">',
	        '{@each reception[0].listFyMaterial as it, index}',
	        '${it.fileName};',
	        '{@/each}',
	        '</textarea>',
	    '</td>',
	'</tr>',
'</table>',
].join('\n');



//登记信息-来件模板
var b_tpl = [
'<table id="">',
	'<tr class="lanky-tr">',
	'<th class="lanky-th" colspan="8">来件信息</th>',
	'</tr>',
	'<tr>',
		'<td class="lanky-item">来信人姓名：</td>',
		'<td class="lanky-td"><input class="lanky-input" type="text" value="${letter[0].senderName}"></td>',
		'<td class="lanky-item">来行人电话：</td>',
		'<td class="lanky-td"><input class="lanky-input" type="text" value="${letter[0].senderPhone}"></td>',
		'<td class="lanky-item">收件日期：</td>',
		'<td class="lanky-td"><input class="lanky-input" type="text" value="${letter[0].receiveDate}"></td>',
		'<td class="lanky-item">收件类型：</td>',
		'<td class="lanky-td"><input class="lanky-input" type="text" value="${letter[0].letterType}"></td>',
	'</tr>',
	'<tr>',
		'<td class="lanky-item">来信人邮编：</td>',
		'<td class="lanky-td"><input class="lanky-input" type="text" value="${letter[0].senderPostCode}"></td>',
		'<td class="lanky-item">来件编号：</td>',
		'<td class="lanky-td"><input class="lanky-input" type="text" value=""></td>',
		'<td class="lanky-item"></td>',
        '<td class="lanky-td"></td>',
        '<td class="lanky-item"></td>',
        '<td class="lanky-td"></td>',
	'</tr>',
	'<tr>',
		'<td class="lanky-item">来信人通信地址：</td>',
		'<td class="lanky-td" colspan="7"><input class="lanky-input" type="text" value="${letter[0].senderAddress}"></td>',
	'</tr>',
'</table>',
].join('\n');


//案件信息-当事人
var c_tpl = [
'<table>',
    '<tr class="lanky-tr">',
        '<th class="lanky-th" colspan="8">当事人信息</th>',
    '</tr>',
    '<tr>',
        '<td class="lanky-item">申请人类型：</td>',
        '<td class="lanky-td">',
            '<select class="lanky-input" id="applicantType" name="applicantType">',
            '</select>',
        '</td>',
        '<td class="lanky-item">是否有代理人：</td>',
        '<td class="lanky-td">',
            '&nbsp是&nbsp;<input type="radio" id="isAgentA" name="isAgent" value="" ${clientInfo.isAgent == 1 ? "checked":""}>',
            '&nbsp否&nbsp;<input type="radio" id="isAgentB" name="isAgent" value="" ${clientInfo.isAgent == 0 ? "checked":""}>',
        '</td>',
        '<td class="lanky-item">是否有第三人：</td>',
        '<td class="lanky-td">',
            '&nbsp是&nbsp;<input type="radio" id="isThirdPartyA" name="isThirdParty" value="" ${clientInfo.isThirdParty == 1 ? "checked":""}>',
            '&nbsp否&nbsp;<input type="radio" id="isThirdPartyB" name="isThirdParty" value="" ${clientInfo.isThirdParty == 0 ? "checked":""}>',
        '</td>',
        '<td class="lanky-item">是否有第三人代理人：</td>',
        '<td class="lanky-td">',
            '&nbsp是&nbsp;<input type="radio" id="isThirdPartyAgentA" name="isThirdPartyAgent" value="" ${clientInfo.isThirdPartyAgent == 0 ? "checked":""}>',
            '&nbsp否&nbsp;<input type="radio" id="isThirdPartyAgentB" name="isThirdPartyAgent" value="" ${clientInfo.isThirdPartyAgent == 0 ? "checked":""}>',
        '</td>',
    '</tr>',
    '<tr>',
        '<td class="lanky-item">申请人总数：</td>',
        '<td class="lanky-td">',
            '<input class="lanky-input" type="text" id="" name="" value="${clientInfo.applicant.length}">',
        '</td>',
        '<td class="lanky-item"></td>',
        '<td class="lanky-td"></td>',
        '<td class="lanky-item"></td>',
        '<td class="lanky-td"></td>',
        '<td class="lanky-item"></td>',
        '<td class="lanky-td"></td>',
    '</tr>',
    '<tr>',
        '<td class="lanky-item">申请人信息：</td>',
        '<td class="lanky-td" colspan="7">',
            '<textarea class="lanky-input" rows="3" cols="100">',
            	'{@each clientInfo.applicant as it, index}',
  	      		'${it.name};${it.sexCode};身份证号码${it.ceritificateId};${it.postAddress};邮编${it.postCode};电话${it.phoneNum};&#10;',
  	      		'{@/each}',
            '</textarea>',
        '</td>',
    '</tr>',
    '<tr>',
        '<td class="lanky-item">其他申请人信息：</td>',
        '<td class="lanky-td" colspan="7">',
            '<textarea class="lanky-input" rows="3" cols="100">',
            	
            '</textarea>',
        '</td>',
    '</tr>',
    '<tr>',
        '<td class="lanky-item">代理人信息：</td>',
        '<td class="lanky-td" colspan="7">',
            '<textarea class="lanky-input" rows="3" cols="100">',
		        '{@each clientInfo.agent as it, index}',
		  		'${it.agentName};${it.agentPhoneNum};是否授权${it.isAuthorization};&#10;',
		  		'{@/each}',
            '</textarea>',
        '</td>',
    '</tr>',
    '<tr>',
        '<td class="lanky-item">第三人信息：</td>',
        '<td class="lanky-td" colspan="7">',
            '<textarea class="lanky-input" rows="3" cols="100">',
	            '{@each clientInfo.thirdParty as it, index}',
		  		'${it.thirdPartyName};电话${it.thirdPartyPhoneNum};&#10;',
		  		'{@/each}',
            '</textarea>',
        '</td>',
    '</tr>',
    '<tr>',
        '<td class="lanky-item">被申请人信息：</td>',
        '<td class="lanky-td" colspan="7">',
            '<textarea class="lanky-input" rows="3" cols="100">',
                '${clientInfo.respondent[0].respondentName}',
            '</textarea>',
        '</td>',
    '</tr>',
'</table>',
].join('\n');
  

//案件信息-复议事项
var d_tpl = [
'<table>',
	'<tr class="lanky-tr">',
	    '<th class="lanky-th" colspan="8">复议事项</th>',
	'</tr>',
	'<tr>',
	    '<td class="lanky-item">申请日期：</td>',
	    '<td class="lanky-td">',
	        '<input class="lanky-input" type="text" id="applicationDate" name="applicationDate" value=${caseHandling[0].applicationDate}>',
	    '</td>',
	    '<td class="lanky-item">行政类别管理：</td>',
	    '<td class="lanky-td">',
	        '<select class="lanky-input" id="category" name="category">',
	        '</select>',
	    '</td>',
	    '<td class="lanky-item">申请事项：</td>',
	    '<td class="lanky-td">',
	          '<select class="lanky-input" id="applicationItem" name="applicationItem">',
	          '</select>',
	    '</td>',
	    '<td class="lanky-item">具体行政行为名称：</td>',
	    '<td class="lanky-td">',
	        '<input class="lanky-input" type="text" id="specificAdministrativeName" name="specificAdministrativeName" value="${caseHandling[0].specificAdministrativeName}">',
	    '</td>',
	'</tr>',
	'<tr>',
	    '<td class="lanky-item">具体行政行为文号：</td>',
	    '<td class="lanky-td">',
	        '<input class="lanky-input" type="text" id="specificAdministrativeNo" name="specificAdministrativeNo" value="${caseHandling[0].specificAdministrativeNo}">',
	    '</td>',
	    '<td class="lanky-item">具体行政行为做出日期：</td>',
	    '<td class="lanky-td">',
	        '<input class="lanky-input" type="text" id="specificAdministrativeDate" name="specificAdministrativeDate" value="${caseHandling[0].specificAdministrativeDate}">',
	    '</td>',
	    '<td class="lanky-item">收到处罚决定书日期：</td>',
	    '<td class="lanky-td">',
	        '<input class="lanky-input" type="text" id="receivedPunishDate" name="receivedPunishDate" value="${caseHandling[0].receivedPunishDate}">',
	    '</td>',
	    '<td class="lanky-item">得知该具体行为途径：</td>',
	    '<td class="lanky-td">',
	          '<input class="lanky-input" type="text" id="receivedSpecificWay" name="receivedSpecificWay" value=${caseHandling[0].receivedSpecificWay}>',
	    '</td>',
	'</tr>',
	'<tr>',
	    '<td class="lanky-item">具体行政行为：</td>',
	    '<td class="lanky-td" colspan="7">',
	          '<textarea class="lanky-input" rows="3" cols="100" id="specificAdministrativeDetail" name="specificAdministrativeDetail">${caseHandling[0].specificAdministrativeDetail}</textarea>',
	    '</td>',
	'</tr>',
	'<tr>',
	    '<td class="lanky-item">行政复议请求：</td>',
	    '<td class="lanky-td" colspan="7">',
	          '<textarea class="lanky-input" rows="3" cols="100" id="factsAndReasons" name="factsAndReasons">${caseHandling[0].factsAndReasons}</textarea>',
	    '</td>',
	'</tr>',
	'<tr>',
	    '<td class="lanky-item">行政复议前置：</td>',
	    '<td class="lanky-td">',
	        '&nbsp是&nbsp;<input type="radio" id="isReviewA" name="isReview" value="" ${caseHandling[0].isReview == 1 ? "checked":""}>',
	        '&nbsp否&nbsp;<input type="radio" id="isReviewB" name="isReview" value="" ${caseHandling[0].isReview == 0 ? "checked":""}>',
	    '</td>',
	    '<td class="lanky-item">行政不作为：</td>',
	    '<td class="lanky-td">',
	          '&nbsp是&nbsp;<input type="radio" id="isNonfeasanceA" name="isNonfeasance" value="" ${caseHandling[0].isNonfeasance == 1 ? "checked":""}>',
	          '&nbsp否&nbsp;<input type="radio" id="isNonfeasanceB" name="isNonfeasance" value="" ${caseHandling[0].isNonfeasance == 0 ? "checked":""}>',
	    '</td>',
	    '<td class="lanky-item">申请举行听证会：</td>',
	    '<td class="lanky-td">',
	          '&nbsp是&nbsp;<input type="radio" id="isHoldHearingA" name="isHoldHearing" value="" ${caseHandling[0].isHoldHearing == 1 ? "checked":""}>',
	          '&nbsp否&nbsp;<input type="radio" id="isHoldHearingB" name="isHoldHearing" value="" ${caseHandling[0].isHoldHearing == 0 ? "checked":""}>',
	    '</td>',
	    '<td class="lanky-item">申请赔偿：</td>',
	    '<td class="lanky-td">',
	            '&nbsp是&nbsp;<input type="radio" id="isCompensationA" name="isCompensation" value="" ${caseHandling[0].isCompensation == 1 ? "checked":""}>',
	            '&nbsp否&nbsp;<input type="radio" id="isCompensationB" name="isCompensation" value="" ${caseHandling[0].isCompensation == 0 ? "checked":""}>',
	    '</td>',
	'</tr>',
	'<tr>',
	    '<td class="lanky-item">申请对规范性文件审查：</td>',
	    '<td class="lanky-td">',
	        '&nbsp是&nbsp;<input type="radio" id="isDocumentReviewA" name="isDocumentReview" value="" ${caseHandling[0].isDocumentReview == 1 ? "checked":""}>',
	        '&nbsp否&nbsp;<input type="radio" id="isDocumentReviewB" name="isDocumentReview" value="" ${caseHandling[0].isDocumentReview == 0 ? "checked":""}>',
	    '</td>',
	    '<td class="lanky-item">规范性文件名称：</td>',
	    '<td class="lanky-td">',
	        '<input class="lanky-input" type="text" id="" name="" value="${caseHandling[0].documentReviewName}">',
	    '</td>',
	    '<td class="lanky-item">赔偿请求类型：</td>',
	    '<td class="lanky-td">',
	    	'<select class="lanky-input" id="compensationTypeCode" name="compensationTypeCode">',
	    	'</select>',
	    '</td>',
	    '<td class="lanky-item">赔偿请求金额：</td>',
	    '<td class="lanky-td">',
	         '<input class="lanky-input" type="text" id="pay" name="pay" >',
	    '</td>',
	'</tr>',
'</table>',
].join('\n');




//案件信息-立案审查
var e_tpl = [
'<table id="">',
	'<tr class="lanky-tr">',
	'<th class="lanky-th" colspan="8">立案审查</th>',
	'</tr>',
	'<tr>',
		'<td class="lanky-item">申请行政复议日期：</td>',
		'<td class="lanky-td">',
			'<input class="lanky-input" type="text" value="">',
		'</td>',
		'<td class="lanky-item">是否进过补正：</td>',
		'<td class="lanky-td">',
		 	'&nbsp是&nbsp;<input type="radio" id="" name="a" value="" >',
	        '&nbsp否&nbsp;<input type="radio" id="" name="a" value="" >',
		'</td>',
		'<td class="lanky-item">是否补正过期：</td>',
		'<td class="lanky-td">',
		 	'&nbsp是&nbsp;<input type="radio" id="" name="b" value="" >',
	        '&nbsp否&nbsp;<input type="radio" id="" name="b" value="" >',
		'</td>',
		'<td class="lanky-item">通知补正时间：</td>',
		'<td class="lanky-td">',
			'<input class="lanky-input" type="text" value="">',
		'</td>',
	'</tr>',
	'<tr>',
		'<td class="lanky-item">补正时间：</td>',
		'<td class="lanky-td">',
			'<input class="lanky-input" type="text" value="">',
		'</td>',
		'<td class="lanky-item">处理意见：</td>',
		'<td class="lanky-td">',
			'<input class="lanky-input" type="text" value="">',
		'</td>',
		'<td class="lanky-item">立案时间：</td>',
		'<td class="lanky-td">',
			'<input class="lanky-input" type="text" value="">',
		'</td>',
		'<td class="lanky-item">案件号</td>',
		'<td class="lanky-td">',
			'<input class="lanky-input" type="text" value="">',
		'</td>',
	'</tr>',
	'<tr>',
		'<td class="lanky-item">审查人：</td>',
		'<td class="lanky-td">',
			'<input class="lanky-input" type="text" value="">',
		'</td>',
		'<td class="lanky-item">是否延期审查：</td>',
		'<td class="lanky-td">',
			'&nbsp是&nbsp;<input type="radio" id="" name="c" value="" >',
			'&nbsp否&nbsp;<input type="radio" id="" name="c" value="" >',
		'</td>',
	'</tr>',
'</table>',
].join('\n');




//案件信息-案件审理
var f_tpl = [
'<table id="">',
	'<tr class="lanky-tr">',
	'<th class="lanky-th" colspan="8">案件审理</th>',
	'</tr>',
	'<tr>',
		
		'<td class="lanky-item">是否中止审理：</td>',
		'<td class="lanky-td">',
		 	'&nbsp是&nbsp;<input type="radio" id="" name="a" value="" >',
	        '&nbsp否&nbsp;<input type="radio" id="" name="a" value="" >',
		'</td>',
		'<td class="lanky-item">中止日期：</td>',
		'<td class="lanky-td">',
			'<input class="lanky-input" type="text" value="">',
		'</td>',
		'<td class="lanky-item">恢复审理时间：</td>',
		'<td class="lanky-td">',
			'<input class="lanky-input" type="text" value="">',
		'</td>',
	'</tr>',
	'<tr>',
		'<td class="lanky-item">审理结果：</td>',
		'<td class="lanky-td">',
			'<input class="lanky-input" type="text" value="">',
		'</td>',
		'<td class="lanky-item">结案日期：</td>',
		'<td class="lanky-td">',
			'<input class="lanky-input" type="text" value="">',
		'</td>',
		'<td class="lanky-item">国家赔偿：</td>',
		'<td class="lanky-td">',
			'<input class="lanky-input" type="text" value="">',
		'</td>',
		'<td class="lanky-item">赔偿金额：</td>',
		'<td class="lanky-td">',
			'<input class="lanky-input" type="text" value="">',
		'</td>',
	'</tr>',
	'<tr>',
		'<td class="lanky-item">承办人：</td>',
		'<td class="lanky-td">',
			'<input class="lanky-input" type="text" value="">',
		'</td>',
		'<td class="lanky-item">结案文书：</td>',
		'<td class="lanky-td">',
			'<input class="lanky-input" type="text" value="">',
		'</td>',
	'</tr>',
'</table>',
].join('\n');
