package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.tianee.webframe.util.global.TeeSysProps;
import java.io.FileInputStream;
import java.io.File;
import org.jdom.input.SAXBuilder;
import org.jdom.Element;
import org.jdom.Document;
import com.tianee.webframe.util.servlet.TeeCookieUtils;
import java.util.*;
import com.tianee.oa.oaconst.TeeConst;
import com.tianee.oa.core.org.bean.TeePerson;
import com.tianee.webframe.util.str.TeeUtility;
import com.tianee.webframe.util.date.TeeDateUtil;
import com.tianee.webframe.util.global.TeeSysProps;
import com.tianee.webframe.util.str.TeeStringUtil;
import com.tianee.oa.core.org.service.TeePersonService;
import com.tianee.oa.oaconst.TeeModelIdConst;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final JspFactory _jspxFactory = JspFactory.getDefaultFactory();

  private static java.util.List _jspx_dependants;

  static {
    _jspx_dependants = new java.util.ArrayList(2);
    _jspx_dependants.add("/header/header2.0.jsp");
    _jspx_dependants.add("/header/validator2.0.jsp");
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

   //读取ukcode
   File file=new File(TeeSysProps.getRootPath()+"/system/ukey/auth_code.xml");
   FileInputStream  in=new FileInputStream(file);
   SAXBuilder builder = new SAXBuilder();
     Document doc = null;
    try {
        doc = builder.build(in);
    } catch (Exception e1) {
        // TODO Auto-generated catch block
        e1.printStackTrace();
    }
    Element root = doc.getRootElement();
    String UkCode=root.getChild("authcode").getText();



      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=Edge\">\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>行政复议工作平台</title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

String contextPath = request.getContextPath();
String basePath = request.getScheme() + "://"
		+ request.getServerName() + ":" + request.getServerPort()
		+ contextPath + "/";
//获取主题的索引号
int styleIndex = 1;
Integer styleInSession = (Integer) request.getSession().getAttribute("STYLE_TYPE_INDEX");
if (styleInSession != null) {
	styleIndex = styleInSession;
}
String stylePath = contextPath + "/common/styles";
String imgPath = stylePath + "/style" + styleIndex + "/img";
String cssPath = stylePath + "/style" + styleIndex + "/css";
String systemImagePath = contextPath+"/common/images";

//第二套风格
int STYLE_TYPE_INDEX_2 = TeeStringUtil.getInteger( request.getSession().getAttribute("STYLE_TYPE_INDEX_2"), 1);
String cssPathSecond = contextPath + "/system/frame/2/styles/style" + STYLE_TYPE_INDEX_2 + "/css";
String imgPathSecond = contextPath + "/system/frame/2/styles/style" + STYLE_TYPE_INDEX_2 + "/img";


String loginOutText = TeeSysProps.getString("LOGIN_OUT_TEXT");
String ieTitle = TeeSysProps.getString("IE_TITLE");
String secUserMem = TeeSysProps.getString("SEC_USER_MEM");

Cookie cookie = TeeCookieUtils.getCookie(request, "skin_new");
String skinNew = "1";
if(cookie!=null){
	skinNew = cookie.getValue();
}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- zt_webframe框架引入 jquery -->\r\n");
      out.write("<script src=\"");
      out.print(contextPath );
      out.write("/common/jquery-easyui-1.6.11/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- zt_webframe框架引入 核心库 -->\r\n");
      out.write("<script src=\"");
      out.print(contextPath );
      out.write("/common/zt_webframe/js/package.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(contextPath );
      out.write("/common/js/sys2.0.js?v=2\"></script>\r\n");
      out.write("<script src=\"");
      out.print(contextPath );
      out.write("/common/js/sysUtil.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(contextPath );
      out.write("/common/js/src/orgselect.js\"></script>\r\n");
      out.write("<!--\r\n");
      out.write("\r\n");
      out.write("//-->\r\n");
      out.write("<!-- zt_webframe框架引入 css样式 -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/common/zt_webframe/css/init");
      out.print(skinNew );
      out.write(".css\">\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(request.getContextPath());
      out.write("/common/zt_webframe/css/package");
      out.print(skinNew );
      out.write(".css\">\r\n");
      out.write("\r\n");
      out.write("<script src=\"");
      out.print(contextPath );
      out.write("/common/js/tools2.0.js?v=1\"></script>\r\n");
      out.write("<script src=\"");
      out.print(contextPath );
      out.write("/common/js/TeeMenu.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("/** 变量定义 **/\r\n");
      out.write("var contextPath = \"");
      out.print(contextPath );
      out.write("\";\r\n");
      out.write("var systemImagePath = contextPath+\"/common/images\";\r\n");
      out.write("var uploadFlashUrl = \"");
      out.print(contextPath );
      out.write("/common/swfupload/swfupload.swf\";\r\n");
      out.write("var commonUploadUrl = \"");
      out.print(contextPath );
      out.write("/attachmentController/commonUpload.action;jsessionid=");
      out.print(session.getId());
      out.write("\";\r\n");
      out.write("var xparent;\r\n");
      out.write("var stylePath = \"");
      out.print(stylePath);
      out.write("\";\r\n");
      out.write("if(window.dialogArguments){\r\n");
      out.write("\txparent = window.dialogArguments;\r\n");
      out.write("}else if(window.opener){\r\n");
      out.write("\txparent = opener;\r\n");
      out.write("}else{\r\n");
      out.write("\txparent = window;\r\n");
      out.write("}\r\n");
      out.write("window.UEDITOR_HOME_URL = \"");
      out.print(contextPath);
      out.write("/common/ueditor/\";\r\n");
      out.write("$.browser = {};\r\n");
      out.write("$.browser.mozilla = /firefox/.test(navigator.userAgent.toLowerCase());\r\n");
      out.write("$.browser.webkit = /webkit/.test(navigator.userAgent.toLowerCase());\r\n");
      out.write("$.browser.opera = /opera/.test(navigator.userAgent.toLowerCase());\r\n");
      out.write("$.browser.msie = /msie/.test(navigator.userAgent.toLowerCase());\r\n");
      out.write("</script>\r\n");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- zt_webframe框架引入 核心库 -->\r\n");
      out.write("<script type=\"text/javascript\" src = \"");
      out.print(request.getContextPath());
      out.write("/common/zt_webframe/js/jquery.validate.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src = \"");
      out.print(request.getContextPath());
      out.write("/common/zt_webframe/js/additional-methods.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src = \"");
      out.print(request.getContextPath());
      out.write("/common/zt_webframe/js/messages_zh.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src = \"");
      out.print(request.getContextPath());
      out.write("/common/zt_webframe/js/jquery.validate.extend.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"/common/font-awesome/css/font-awesome.min.css\" />\r\n");
      out.write("<link href=\"");
      out.print(contextPath );
      out.write("/common/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("<link href=\"");
      out.print(contextPath );
      out.write("/common/supervise-common/components.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("<link href=\"");
      out.print(contextPath );
      out.write("/common/supervise-common/plugins.css\" rel=\"stylesheet\"  type=\"text/css\"/>\r\n");
      out.write("<link href=\"");
      out.print(contextPath );
      out.write("/common/supervise-common/layout.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("<link href=\"");
      out.print(contextPath );
      out.write("/common/supervise-common/themes/default.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("<link href=\"");
      out.print(contextPath );
      out.write("/common/supervise-common/custom.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("<link href=\"");
      out.print(contextPath );
      out.write("/common/supervise-common/login.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("<script src=\"./style/jquery.cookie.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(contextPath );
      out.write("/common/js/sys.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(contextPath );
      out.write("/common/js/sysUtil.js\"></script>\r\n");
      out.write("<script src=\"");
      out.print(contextPath );
      out.write("/common/backstretch/jquery.backstretch.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"");
      out.print(contextPath );
      out.write("/common/bootstrap/js/bootstrap.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("var UkCode=\"");
      out.print(UkCode);
      out.write("\";\r\n");
      out.write("var dogId=\"\";\r\n");
      out.write("var dogName=\"\"; \r\n");
      out.write("\r\n");
      out.write("var contextPath = \"");
      out.print(request.getContextPath());
      out.write("\";\r\n");
      out.write("\r\n");
      out.write("var secUserMem = \"");
      out.print(secUserMem);
      out.write("\";//是否允许记忆用户名  1- 记录\r\n");
      out.write("var loginByCode = \"");
      out.print(TeeSysProps.getString("LOGIN_BY_CODE"));
      out.write("\";\r\n");
      out.write("\r\n");
      out.write("function doInit(){  \r\n");
      out.write("    refreshCode($(\"#vimage\"));\r\n");
      out.write("    $('#myId').backstretch([\r\n");
      out.write("                    /* \"/common/zt_webframe/imgs/login/supervise-login-01.jpg\",\r\n");
      out.write("                    /* \"/common/zt_webframe/imgs/login/supervise-login-02.jpg\", \r\n");
      out.write("                    \"/common/zt_webframe/imgs/login/supervise-login-03.jpg\",\r\n");
      out.write("                    \"/common/zt_webframe/imgs/login/supervise-login-04.jpg\"\r\n");
      out.write("                    \"/common/zt_webframe/imgs/login/bg_1.png\",\r\n");
      out.write("                    \"/common/zt_webframe/imgs/login/bg_2.png\",\r\n");
      out.write("                    \"/common/zt_webframe/imgs/login/bg_3.png\"*/\r\n");
      out.write("                    \"/common/zt_webframe/imgs/login/xzfy_login01.png\"\r\n");
      out.write("                    \r\n");
      out.write("                ], {\r\n");
      out.write("                    fade: 1000,\r\n");
      out.write("                    duration: 8000\r\n");
      out.write("                }\r\n");
      out.write("            );\r\n");
      out.write("    \r\n");
      out.write("}\r\n");
      out.write("/**\r\n");
      out.write(" * 保存\r\n");
      out.write(" */\r\n");
      out.write("function doLogin(){\r\n");
      out.write("    try{\r\n");
      out.write("        //获取uk用户名  和  uk的dogid\r\n");
      out.write("        var res = AuthIE.Open(\"<dogscope/>\", UkCode);\r\n");
      out.write("        if(res==0){\r\n");
      out.write("            AuthIE.GetDogID();\r\n");
      out.write("            dogId = AuthIE.DogIdStr;\r\n");
      out.write("            AuthIE.GetUserName();\r\n");
      out.write("            dogName = AuthIE.UserNameStr;    \r\n");
      out.write("        }else{\r\n");
      out.write("            dogId =\"\";\r\n");
      out.write("            dogName =\"\";     \r\n");
      out.write("        }\r\n");
      out.write("        AuthIE.Close();\r\n");
      out.write("    }catch(e){\r\n");
      out.write("        dogId=\"\";\r\n");
      out.write("        dogName=\"\";\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    if (checkForm()){\r\n");
      out.write("        var url = \"");
      out.print(contextPath);
      out.write("/systemAction/doLoginIn.action\";\r\n");
      out.write("        var para =  tools.formToJson($(\"#form1\")) ;\r\n");
      out.write("        para[\"dogId\"]=dogId;\r\n");
      out.write("        para[\"dogName\"]=dogName;\r\n");
      out.write("        \r\n");
      out.write("        var json = tools.requestJsonRs(url,para);\r\n");
      out.write("        console.log(JSON.stringify(json));\r\n");
      out.write("        if (json.rtState){\r\n");
      out.write("               /*  //记录上次成功登陆的用户名\r\n");
      out.write("                if (json.rtData.saveUserName == \"1\") {\r\n");
      out.write("                  setCookie('userName',$('userName').value , 30);\r\n");
      out.write("                }else {\r\n");
      out.write("                  setCookie('userName','' , 30);\r\n");
      out.write("                }\r\n");
      out.write("                if (json.rtData.sessionToken) {\r\n");
      out.write("                  setCookie('SID_'  + json.rtData.seqId ,json.rtData.sessionToken , 1);\r\n");
      out.write("                } */\r\n");
      out.write("                if(secUserMem == '1'){//允许记忆卡\r\n");
      out.write("                    setCookie('userName',$('#userName').val() , 30);\r\n");
      out.write("                }\r\n");
      out.write("                var data = json.rtData;\r\n");
      out.write("                var theme = data.theme;\r\n");
      out.write("//              var themeIndex = 1;\r\n");
      out.write("//              var index = 1;\r\n");
      out.write("//              if(theme.length == 2){\r\n");
      out.write("//                  themeIndex = theme.substring(0,1);\r\n");
      out.write("//                  index = theme.substring(1,2);\r\n");
      out.write("//              }\r\n");
      out.write("                if(json.rtData.isAdmin == '9' || json.rtData.isAdmin == '1' ){\r\n");
      out.write("\t\t\t\t    window.location.href = \"");
      out.print(contextPath);
      out.write("/gzpt/admin/index.jsp\";\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("                \twindow.location.href = \"");
      out.print(contextPath);
      out.write("/system/frame/\"+theme+\"/index.jsp\";\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("        } else{ \r\n");
      out.write("             switch(json.rtData.code){\r\n");
      out.write("                  case 0:{\r\n");
      out.write("                    $.MsgBox.newAlert(\"提示\", json.rtMsg,function(){\r\n");
      out.write("                         $('#userName').focus();    \r\n");
      out.write("                    });\r\n");
      out.write("                    \r\n");
      out.write("            /*         $('loginForm').reset();\r\n");
      out.write("                    $('layout').show(); */\r\n");
      out.write("                    \r\n");
      out.write("                   \r\n");
      out.write("                   // window.location.href = \"");
      out.print(contextPath);
      out.write("/system/frame/default/index.jsp\";\r\n");
      out.write("                    break;\r\n");
      out.write("                  }\r\n");
      out.write("                  case 1:{\r\n");
      out.write("                  }\r\n");
      out.write("                  case 2:{\r\n");
      out.write("                  }\r\n");
      out.write("                  case 3:{\r\n");
      out.write("                  }\r\n");
      out.write("                  case 9:{\r\n");
      out.write("                  }\r\n");
      out.write("                  case 10:{\r\n");
      out.write("                  }\r\n");
      out.write("                  case 11:{\r\n");
      out.write("                  }\r\n");
      out.write("                  case 12:{\r\n");
      out.write("                    $.MsgBox.newAlert(\"提示\", json.rtMsg,function(){\r\n");
      out.write("                        $('#pwd').value = '';\r\n");
      out.write("                        $('#layout').show();\r\n");
      out.write("                        $('#userName').focus();\r\n");
      out.write("                        \r\n");
      out.write("                    });\r\n");
      out.write("                    \r\n");
      out.write("                    break;\r\n");
      out.write("                  }\r\n");
      out.write("                  case 13:{\r\n");
      out.write("                      window.location.href = \"");
      out.print(contextPath);
      out.write("/system/frame/default/index.jsp\";\r\n");
      out.write("                    break;\r\n");
      out.write("                  }\r\n");
      out.write("                  case 4:{\r\n");
      out.write("                    $.MsgBox.newAlert(\"提示\", json.rtMsg,function(){\r\n");
      out.write("                         $('layout').show();\r\n");
      out.write("                    });\r\n");
      out.write("                   \r\n");
      out.write("                    break;\r\n");
      out.write("                  }\r\n");
      out.write("                  case 5:{\r\n");
      out.write("                    $.MsgBox.newAlert(\"提示\", json.rtMsg,function(){\r\n");
      out.write("                        $('#pwd').value = '';\r\n");
      out.write("                        $('#layout').show();\r\n");
      out.write("                        $('#pwd').focus();\r\n");
      out.write("                        \r\n");
      out.write("                    });\r\n");
      out.write("                    \r\n");
      out.write("                    break;\r\n");
      out.write("                  }\r\n");
      out.write("                  case 6:{\r\n");
      out.write("                      if(secUserMem == '1'){//允许记忆卡\r\n");
      out.write("                          setCookie('userName',$('#userName').val() , 1);\r\n");
      out.write("                      }\r\n");
      out.write("                    window.location = contextPath + \"/system/core/system/security/editPwd.jsp?code=6\";\r\n");
      out.write("                    break;\r\n");
      out.write("                  }\r\n");
      out.write("                  case 7:{\r\n");
      out.write("                      if(secUserMem == '1'){//允许记忆卡\r\n");
      out.write("                          setCookie('userName',$('#userName').val() , 1);\r\n");
      out.write("                      }\r\n");
      out.write("                      window.location = contextPath + \"/system/core/system/security/editPwd.jsp?code=7\";\r\n");
      out.write("                      break;\r\n");
      out.write("                  }\r\n");
      out.write("                  case 8:{\r\n");
      out.write("                    $.MsgBox.newAlert(\"提示\", json.rtMsg,function(){\r\n");
      out.write("                        $('#pwd').value = '';\r\n");
      out.write("                        $('#layout').show();\r\n");
      out.write("                        $('#pwd').focus();\r\n");
      out.write("                        \r\n");
      out.write("                    });\r\n");
      out.write("                    break;\r\n");
      out.write("                  }\r\n");
      out.write("                  case 14: {\r\n");
      out.write("                    $.MsgBox.newAlert(\"提示\", '验证码错误',function(){\r\n");
      out.write("                         $('#pwd').value = '';\r\n");
      out.write("                         $('#layout').show();\r\n");
      out.write("                         $('#pwd').focus();\r\n");
      out.write("                         refreshCode();\r\n");
      out.write("                    });\r\n");
      out.write("                   \r\n");
      out.write("                    break;\r\n");
      out.write("                  }\r\n");
      out.write("                  case 15: {\r\n");
      out.write("                     $.MsgBox.newAlert(\"提示\", json.rtMsg);\r\n");
      out.write("                       break;\r\n");
      out.write("                  }\r\n");
      out.write("                  case 16: {\r\n");
      out.write("                      window.location = \"/system/core/system/auth_info.jsp\";\r\n");
      out.write("                      break;\r\n");
      out.write("                  }\r\n");
      out.write("                  case 21: {\r\n");
      out.write("                      $.MsgBox.newAlert(\"提示\", 'Ukey认证失败！');\r\n");
      out.write("                      break;\r\n");
      out.write("                  }\r\n");
      out.write("                  default:{\r\n");
      out.write("                    $.MsgBox.newAlert(\"提示\",\"登录失败!\",function(){\r\n");
      out.write("                        $('#layout').show();\r\n");
      out.write("                    });\r\n");
      out.write("                    \r\n");
      out.write("                  }\r\n");
      out.write("             }\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/**\r\n");
      out.write(" * 校验有没有字符串\r\n");
      out.write(" */\r\n");
      out.write("function isValidateUserName(value){\r\n");
      out.write("    return /[\\~!`@;=#\\+\\|$%\\^&\\*\\.\\(\\)\\[\\]\\{\\}<>\\?\\\\\\/\\'\\\"]$/.test(value);\r\n");
      out.write("}\r\n");
      out.write("/**\r\n");
      out.write(" * 校验表单\r\n");
      out.write(" */\r\n");
      out.write("function checkForm(){\r\n");
      out.write("    \r\n");
      out.write("    if($('#userName').val() == ''){\r\n");
      out.write("          $.MsgBox.newAlert(\"提示\",\"请输入用户名\",function(){\r\n");
      out.write("              $('#userName').focus();\r\n");
      out.write("          });\r\n");
      out.write("          return false;\r\n");
      out.write("     }\r\n");
      out.write("     if (isValidateUserName($('#userName').val())) {\r\n");
      out.write("         $.MsgBox.newAlert(\"提示\",\"您输入的用户名含有特殊字符！\",function(){\r\n");
      out.write("             $('#userName').focus();\r\n");
      out.write("         });         \r\n");
      out.write("         return false;\r\n");
      out.write("     }\r\n");
      out.write("     \r\n");
      out.write("      \r\n");
      out.write("     if($(\"#verifyCode\").val()=='' && loginByCode==\"1\"){\r\n");
      out.write("            $.MsgBox.newAlert(\"提示\",\"请输入验证码\",function(){\r\n");
      out.write("                $(\"#verifyCode\").focus();   \r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("            return false;\r\n");
      out.write("        }\r\n");
      out.write("     return true;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function refreshCode(obj){\r\n");
      out.write("    $(obj).attr(\"src\",contextPath+\"/verifyCode/generate.action?rand=\"+new Date().getTime());\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function reSet(){\r\n");
      out.write("    $('#userName').val('');\r\n");
      out.write("    $('#pwd').val('');\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("$(function () {\r\n");
      out.write("    if (getCookie('userName') && secUserMem == '1'){\r\n");
      out.write("          $('#userName').val(getCookie('userName'));\r\n");
      out.write("          $('#pwd').focus();\r\n");
      out.write("    }else{\r\n");
      out.write("          $(\"#userName\").focus();\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    $('#pwd,#userName,#verifyCode').bind('keypress',function(event){\r\n");
      out.write("          if(event.keyCode == \"13\")    \r\n");
      out.write("          {\r\n");
      out.write("            doLogin();\r\n");
      out.write("          }\r\n");
      out.write("      });\r\n");
      out.write("    \r\n");
      out.write("    if(loginByCode==\"1\"){\r\n");
      out.write("        $(\"#verifyCodeLi\").show();\r\n");
      out.write("    }\r\n");
      out.write("});\r\n");
      out.write("document.onselectstart = function(){\r\n");
      out.write("    return false;\r\n");
      out.write("}\r\n");
      out.write("</script> \r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("   * {\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        padding: 0;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    a {\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    ul {\r\n");
      out.write("        list-style: none;\r\n");
      out.write("    }\r\n");
      out.write("        #myId{\r\n");
      out.write("        padding: 0;\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        height: 100%;\r\n");
      out.write("        overflow: hidden;\r\n");
      out.write("        position: relative;\r\n");
      out.write("        z-index:1000;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("   .container {\r\n");
      out.write("        position: relative;\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        height: 100%;\r\n");
      out.write("    }\r\n");
      out.write("    #carousel{\r\n");
      out.write("    height:100%;\r\n");
      out.write("    width:100%;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .container .bgi{\r\n");
      out.write("        height:100%;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .header{\r\n");
      out.write("       width:100%;\r\n");
      out.write("       z-index:999;\r\n");
      out.write("       height:80px;\r\n");
      out.write("       position: absolute;\r\n");
      out.write("       background: url(\"/common/zt_webframe/imgs/login/header_5.png\");\r\n");
      out.write("       background-size:contain;\r\n");
      out.write("       background-position:center center;\r\n");
      out.write("    }\r\n");
      out.write("    .header i{\r\n");
      out.write("        display:block;\r\n");
      out.write("        float:left;\r\n");
      out.write("        width: 80px;\r\n");
      out.write("        height:100%;\r\n");
      out.write("        margin-left:20px;\r\n");
      out.write("        background: url(\"/logo.png\") no-repeat;\r\n");
      out.write("        background-position:center 12px;\r\n");
      out.write("        background-size:60px 60px;\r\n");
      out.write("    }\r\n");
      out.write("    .header .newp{\r\n");
      out.write("        margin:0 58px;\r\n");
      out.write("        padding: 0;\r\n");
      out.write("        float:left;\r\n");
      out.write("        color:#fff;\r\n");
      out.write("        font-size: 36px;\r\n");
      out.write("        line-height: 80px;\r\n");
      out.write("    }\r\n");
      out.write("    .container .box {\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        width: 386px;\r\n");
      out.write("        height: 411px;\r\n");
      out.write("        border-radius:5px;\r\n");
      out.write("        /* height: 36.3333%; */\r\n");
      out.write("        /*min-width: 318px; */\r\n");
      out.write("        /* min-height: 243px; */\r\n");
      out.write("        /*margin: 0 auto;*/\r\n");
      out.write("        background-color: rgba(255,255,255,0.4);\r\n");
      out.write("        top:20%;\r\n");
      out.write("        right: 10%;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    .input-header{\r\n");
      out.write("         position: relative;\r\n");
      out.write("         height:55px;\r\n");
      out.write("         width:100%;\r\n");
      out.write("         line-height:55px;\r\n");
      out.write("         font-size:16px;\r\n");
      out.write("         text-align:center;\r\n");
      out.write("         font-weight: 700;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .input-split{\r\n");
      out.write("         display:block;\r\n");
      out.write("         width:100%;\r\n");
      out.write("         height:4px;\r\n");
      out.write("         background:url('/common/zt_webframe/imgs/login/input_split.png');\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .container .box input {\r\n");
      out.write("        font-family: \"Microsoft Yahei\";\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .container .box .input1 {\r\n");
      out.write("        border: none;\r\n");
      out.write("        border: 1px solid #e8e8e8;\r\n");
      out.write("        margin: 37px 39px 27px;\r\n");
      out.write("        display:block;\r\n");
      out.write("        height:39px;\r\n");
      out.write("        width:295px;\r\n");
      out.write("        padding: 10px 10px 10px 45px;\r\n");
      out.write("        line-height:27px\\9;\r\n");
      out.write("        background-repeat: no-repeat;\r\n");
      out.write("        background-position: 2.9017% center;\r\n");
      out.write("        -webkit-background-size: 6%;\r\n");
      out.write("        background-size: 6%;\r\n");
      out.write("        outline: none;\r\n");
      out.write("        background-color:#f9faff;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .container .box .input2 {\r\n");
      out.write("        border: none;\r\n");
      out.write("        border: 1px solid #e8e8e8;\r\n");
      out.write("         margin: 0 39px 27px;\r\n");
      out.write("        height: 40px;\r\n");
      out.write("       width:295px;\r\n");
      out.write("        padding: 10px 10px 10px 45px;\r\n");
      out.write("        display:block;\r\n");
      out.write("        line-height:27px\\9;\r\n");
      out.write("        background-repeat: no-repeat;\r\n");
      out.write("        background-position: 2.9017% center;\r\n");
      out.write("        -webkit-background-size: 6%;\r\n");
      out.write("        background-size: 6%;\r\n");
      out.write("        outline: none;\r\n");
      out.write("        font-family: \"Microsoft Yahei\";\r\n");
      out.write("        background-color:#f9faff;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .container .box .input3 {\r\n");
      out.write("        width: 309px;\r\n");
      out.write("        height: 40px;\r\n");
      out.write("        margin: 50px auto 0;\r\n");
      out.write("        border: none;\r\n");
      out.write("        display:block;\r\n");
      out.write("        outline: none;\r\n");
      out.write("        background-color: #3582f8;\r\n");
      out.write("        color: #fff;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("        font-size:18px;\r\n");
      out.write("        font-family: \"Microsoft YaHei\";\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    input::-ms-input-placeholder {\r\n");
      out.write("        font-size: 10%;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    input::-webkit-input-placeholder {\r\n");
      out.write("        font-size: 10%;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .container .box .check {\r\n");
      out.write("        background-color:#f9faff;\r\n");
      out.write("        width: 156px;\r\n");
      out.write("        height:39px;\r\n");
      out.write("        outline: none;\r\n");
      out.write("        border: none;\r\n");
      out.write("        border: 1px solid #e8e8e8;\r\n");
      out.write("        margin-left:38.5px;\r\n");
      out.write("        padding:10px 0px 10px 15px;\r\n");
      out.write("        margin-right: 10px;\r\n");
      out.write("    }\r\n");
      out.write("/* \r\n");
      out.write("    div.container .box .pic {\r\n");
      out.write("        float:right;\r\n");
      out.write("                width: 70px;\r\n");
      out.write("        margin-top:32px;\r\n");
      out.write("        margin-right:97px;\r\n");
      out.write("        border-color: gray;\r\n");
      out.write("    } */\r\n");
      out.write("    #inputArea a{\r\n");
      out.write("    display:inline;\r\n");
      out.write("        margin-left: 10px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .container .box .img {\r\n");
      out.write("        width: 225px;\r\n");
      out.write("        height: 32px;\r\n");
      out.write("        margin: 0 auto;\r\n");
      out.write("        margin-top: 10px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .container .box .img img {\r\n");
      out.write("        width: 17px;\r\n");
      out.write("    }\r\n");
      out.write("    .container .box .img1{\r\n");
      out.write("        margin-left:16px;\r\n");
      out.write("    }\r\n");
      out.write("    .container .box .img .img2 {\r\n");
      out.write("        padding-left: 68px;\r\n");
      out.write("        padding-right: 61px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .container p {\r\n");
      out.write("        width: auto;\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        left: 37px;\r\n");
      out.write("        margin: 5px 0 10px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .forgetpsw {\r\n");
      out.write("        margin-left: 195px;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .footer{\r\n");
      out.write("        position:fixed;\r\n");
      out.write("        bottom:0px;\r\n");
      out.write("        left:0px;\r\n");
      out.write("        color:rgb(0,0,0);\r\n");
      out.write("        text-align:center;\r\n");
      out.write("        line-height:98px;\r\n");
      out.write("        font-size:12px;\r\n");
      out.write("        width:100%;\r\n");
      out.write("        background-color:#fff;\r\n");
      out.write("    }\r\n");
      out.write("    .carousel-inner{overflow:visible;}\r\n");
      out.write("   /*重置默认样式*/\r\n");
      out.write("   .container{padding:0;}\r\n");
      out.write("   .item {\r\n");
      out.write("     height: auto; \r\n");
      out.write("    line-height: normal; \r\n");
      out.write("     margin: 0; \r\n");
      out.write("    }   \r\n");
      out.write("    .item img{display:block;height:800px;}\r\n");
      out.write("    @media screen and (min-width: 768px){\r\n");
      out.write("        .carousel-indicators {\r\n");
      out.write("            bottom: 100px;\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("    }\r\n");
      out.write("    @media screen and (max-width: 1366px) {     \r\n");
      out.write("        .header {\r\n");
      out.write("            height:65px;\r\n");
      out.write("        }\r\n");
      out.write("        .header i{\r\n");
      out.write("            background-size:45px 45px;\r\n");
      out.write("            background-position:center 13px;\r\n");
      out.write("            margin-left:0;\r\n");
      out.write("        }\r\n");
      out.write("        .header .newp{\r\n");
      out.write("            font-size: 26px;\r\n");
      out.write("            line-height: 65px;\r\n");
      out.write("            margin: 0px 40px;\r\n");
      out.write("        }\r\n");
      out.write("        .footer {\r\n");
      out.write("            height: 50px;\r\n");
      out.write("            line-height: 50px;\r\n");
      out.write("        }\r\n");
      out.write("        .container .box {\r\n");
      out.write("            width: 336px;\r\n");
      out.write("            height: 358px;\r\n");
      out.write("        }\r\n");
      out.write("        .input-header{\r\n");
      out.write("            height: 50px;\r\n");
      out.write("        }\r\n");
      out.write("        .container .box .input1 {\r\n");
      out.write("            width:265px;\r\n");
      out.write("            margin: 33px 34px 27px;\r\n");
      out.write("            padding: 5px 0 5px 45px;\r\n");
      out.write("            line-height: 30px;\r\n");
      out.write("        }\r\n");
      out.write("        .container .box .input2 {\r\n");
      out.write("            width:265px;\r\n");
      out.write("            margin: 0 34px 27px;\r\n");
      out.write("            padding: 5px 0 5px 45px;\r\n");
      out.write("            line-height: 30px;\r\n");
      out.write("        }\r\n");
      out.write("        .container .box .input3 {\r\n");
      out.write("            width: 270px;\r\n");
      out.write("            height: 35px;\r\n");
      out.write("            margin: 40px auto 0;\r\n");
      out.write("        }\r\n");
      out.write("        .container .box .check {\r\n");
      out.write("            width: 114px;\r\n");
      out.write("            margin-left: 34.5px;\r\n");
      out.write("            height: 33px;\r\n");
      out.write("            padding: 4px 0px 10px 15px;\r\n");
      out.write("        }\r\n");
      out.write("        .container p {\r\n");
      out.write("            left: 33px;\r\n");
      out.write("        }\r\n");
      out.write("        .forgetpsw {\r\n");
      out.write("            margin-left: 154px;\r\n");
      out.write("        }\r\n");
      out.write("        .input-split {\r\n");
      out.write("            background: url(\"/common/zt_webframe/imgs/login/input_split1.png\");\r\n");
      out.write("        }\r\n");
      out.write("        .carousel-indicators {\r\n");
      out.write("            bottom: 50px;\r\n");
      out.write("        }\r\n");
      out.write("        .box #inputArea .eye_close {\r\n");
      out.write("            top: 75px;\r\n");
      out.write("            right: 45px;\r\n");
      out.write("        }\r\n");
      out.write("        .box #inputArea .login_user {\r\n");
      out.write("            top: 9px;\r\n");
      out.write("            left: 50px;\r\n");
      out.write("        }\r\n");
      out.write("        .box #inputArea .login_psw {\r\n");
      out.write("            top: 75px;\r\n");
      out.write("            left: 50px;\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("    #inputArea{\r\n");
      out.write("        display: block;\r\n");
      out.write("        position: relative;\r\n");
      out.write("    }\r\n");
      out.write("    #inputArea i{\r\n");
      out.write("        position:absolute;\r\n");
      out.write("    }\r\n");
      out.write("    #inputArea i img{\r\n");
      out.write("        width: 18px;\r\n");
      out.write("    }\r\n");
      out.write("    #inputArea .login_user{\r\n");
      out.write("        top: 10px;\r\n");
      out.write("        left: 53px;\r\n");
      out.write("    }\r\n");
      out.write("    #inputArea .login_psw{\r\n");
      out.write("        top: 75px;\r\n");
      out.write("        left: 53px;\r\n");
      out.write("    }\r\n");
      out.write("    #inputArea .eye_close{\r\n");
      out.write("        top: 75px;\r\n");
      out.write("        right: 57px;\r\n");
      out.write("    }\r\n");
      out.write("    #inputArea .eye_close img{\r\n");
      out.write("        width: 20px;\r\n");
      out.write("        height: 13px;\r\n");
      out.write("    }\r\n");
      out.write("     /* @media screen and (max-width: 1366px) {\r\n");
      out.write("        .div.container .box {\r\n");
      out.write("            top:175px;\r\n");
      out.write("            right: 200px;\r\n");
      out.write("        }\r\n");
      out.write("    } */\r\n");
      out.write(" .carousel-indicators li {\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    width: 10px;\r\n");
      out.write("    height: 10px;\r\n");
      out.write("    margin: 1px;\r\n");
      out.write("    text-indent: -999px;\r\n");
      out.write("    border-radius: 10px;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    background-color: #C1BFBE;\r\n");
      out.write("} \r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body id=\"myId\" onload=\"doInit();\" class=\"login-back login\">\r\n");

if("1".equals(TeeSysProps.getString("USB_KEY"))){
    
      out.write("\r\n");
      out.write("    <object id=\"AuthIE\" name=\"AuthIE\" width=\"0px\" height=\"0px\"\r\n");
      out.write("       codebase=\"/system/ukey/DogAuth.CAB\"\r\n");
      out.write("       classid=\"CLSID:05C384B0-F45D-46DB-9055-C72DC76176E3\">\r\n");
      out.write("    </object>\r\n");
      out.write("    ");

}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("    <!-- 头部 -->\r\n");
      out.write("    <div class=\"header\">\r\n");
      out.write("    <i></i>\r\n");
      out.write("    <p class=\"newp\" >行政复议工作平台</p>\r\n");
      out.write("    </div>  \r\n");
      out.write("  <!-- BEGIN LOGIN -->\r\n");
      out.write("    \r\n");
      out.write("  \r\n");
      out.write("    <!-- BEGIN LOGIN FORM -->\r\n");
      out.write("        <form id=\"form1\" >\r\n");
      out.write("         <div class=\"box\">\r\n");
      out.write("            <!-- <img state=\"scan\"  onclick=\"switchScan(this)\" id=\"scanImg\" style=\"cursor:pointer;z-index:9999;width:30px;position:absolute;top:0px;right:0px;\" src=\"/common/zt_webframe/imgs/login/codeMode.png\" />\r\n");
      out.write("             -->\r\n");
      out.write("             <div class=\"input-header\">账号登录</div>\r\n");
      out.write("             <span class=\"input-split\"></span>\r\n");
      out.write("             <span id=\"inputArea\">\r\n");
      out.write("                <input type=\"text\" placeholder=\"用户名\" class=\"input1\" name=\"userName\" id=\"userName\" onmouseover=\"$(this).select()\">\r\n");
      out.write("                <input type=\"password\" placeholder=\"密码\" class=\"input2\" name=\"pwd\" id=\"pwd\" onmouseover=\"$(this).select()\">\r\n");
      out.write("                <i class=\"login_user\"><img src=\"/common/zt_webframe/imgs/login/input1.gif\" /></i>\r\n");
      out.write("                <i class=\"login_psw\"><img src=\"/common/zt_webframe/imgs/login/input2.gif\" /></i>\r\n");
      out.write("                <i class=\"eye_close\" ><img src=\"/common/zt_webframe/imgs/login/eye_close.png\" /></i>\r\n");
      out.write("                <!-- <input type=\"hidden\" id=\"pwdCrypt\" name=\"pwdCrypt\"/> -->\r\n");
      out.write("                <input type=\"text\" id=\"verifyCode\" name=\"verifyCode\" class=\"check\" placeholder=\"验证码\" onmouseover=\"$(this).select()\"autocomplete=\"off\">\r\n");
      out.write("                <img  id=\"vimage\" class=\"pic\" src=\"");
      out.print(contextPath );
      out.write("/verifyCode/generate.action\" title=\"点击图片切换验证码\" alt=\"点击刷新\" onclick=\"refreshCode(this)\">\r\n");
      out.write("                ");
      out.write("\r\n");
      out.write("                <a id=\"codeReplace\" onclick=\"refreshCode()\">换一组</a>\r\n");
      out.write("                <script>\r\n");
      out.write("                    function refreshCode(){\r\n");
      out.write("                        $(\"#vimage\").attr(\"src\",contextPath+\"/verifyCode/generate.action?rand=\"+new Date().getTime());\r\n");
      out.write("                    }\r\n");
      out.write("                </script>\r\n");
      out.write("            \r\n");
      out.write("                <input type=\"button\"  name=\"submit\" id=\"login\" value=\"登&nbsp;&nbsp;&nbsp;录\" class=\"input3\"  onclick=\"doLogin()\" >\r\n");
      out.write("                <p><span>立即注册</span> <span class=\"forgetpsw\">忘记密码</span></p>\r\n");
      out.write("               <div class=\"img\">\r\n");
      out.write("                    <!-- <img src=\"/common/zt_webframe/imgs/login/win.gif\" title=\"PC协同办公程序\" class= 'img1' style=\"cursor:pointer\" onclick=\"window.open('http://www.zatp.com.cn/PC_Setup.exe');\">\r\n");
      out.write("                     --><span>\r\n");
      out.write("                        <!-- <img src=\"/common/zt_webframe/imgs/login/andr_09.gif\"  class=\"img2\" id=\"AndroidImg\" style=\"cursor:pointer\" onclick=\"window.open('http://a.app.qq.com/o/simple.jsp?pkgname=com.zatp.app');\">\r\n");
      out.write("                         --><img id=\"AndroidQrCode\" style=\"display:none;position:absolute;top:103%;left:123px;z-index:99999;width:80px;\" src=\"");
      out.print(contextPath );
      out.write("/systemAction/qrCodeDownload.action?dlType=Android\"/>\r\n");
      out.write("                    </span>\r\n");
      out.write("                    <span>\r\n");
      out.write("                        <!-- <img src=\"/common/zt_webframe/imgs/login/apple_11.gif\"  id=\"iOSImg\"   style=\"cursor:pointer\" onclick=\"window.open('https://itunes.apple.com/us/app/%E7%A7%BB%E5%8A%A8%E5%8A%9E%E5%85%AC2017/id1203190020?mt=8');\">\r\n");
      out.write("                         --><img id=\"iOSQrCode\" style=\"display:none;position:absolute;top:103%;left:204px;z-index:99999;width:80px;\" src=\"");
      out.print(contextPath );
      out.write("/systemAction/qrCodeDownload.action?dlType=iOS\"/>\r\n");
      out.write("                    </span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    \r\n");
      out.write("                    \r\n");
      out.write("                </div>\r\n");
      out.write("            </span>\r\n");
      out.write("            <span id=\"scanArea\" style=\"display:none;\">\r\n");
      out.write("                <center><img onclick=\"refreshScanCode(this)\" title=\"点击重新生成二维码\" id=\"codeImg\" src=\"\" style=\"width:150px;z-index:9999;position:inherit;margin:20px;cursor:pointer\" /><center>\r\n");
      out.write("            </span>\r\n");
      out.write("        </div>      \r\n");
      out.write("        </form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <!-- END LOGIN -->\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("        <form id=\"form13\" > \r\n");
      out.write("        </form>\r\n");
      out.write("    <div class=\"footer\">&copy;2001-2018 &nbsp;&nbsp;&nbsp; 北京北大软件工程股份有限公司 &nbsp;&nbsp;&nbsp; 版权所有 &nbsp;&nbsp;&nbsp; 京ICP备09003427号  </div>\r\n");
      out.write(" <!--  <div style=\"position:fixed;bottom:25px;height:20px;left:-2px;color:#aaa;text-align:center;right:0px;font-size:12px\">\r\n");
      out.write("    \t<label class=\"text-right\" style=\"vertical-align:middle;height:20spx;\">版权所有：司法部行政执法协调监督局</label>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div style=\"position:fixed;bottom:4px;height:20px;left:-2px;color:#aaa;text-align:center;right:0px;font-size:12px\">\r\n");
      out.write("    \t<label class=\"text-right\" style=\"vertical-align:top;height:20px;\">技术支持：司法部信息中心       北京北大软件工程股份有限公司</label>\r\n");
      out.write("<!--        Copyright © 2001-2015 All Rights Reserved. &nbsp;&nbsp; -->\r\n");
      out.write("       <!-- <a href=\"http://zatp.com.cn/oarelations.html\" target=\"_blank\">OA常用工具下载</a> -->\r\n");
      out.write("    </div>-->   \r\n");
      out.write("   \r\n");
      out.write(" \r\n");
      out.write("<script>\r\n");
      out.write("$(\"#inputArea .eye_close\").click(function(){\r\n");
      out.write("    if(($(\"#inputArea .eye_close img\").attr(\"src\")) == \"/common/zt_webframe/imgs/login/eye.png\"){\r\n");
      out.write("      $(\"#inputArea .eye_close img\").attr(\"src\",\"/common/zt_webframe/imgs/login/eye_close.png\");\r\n");
      out.write("      $(\"#pwd\").attr(\"type\",\"password\");\r\n");
      out.write("    }else{\r\n");
      out.write("    $(\"#inputArea .eye_close img\").attr(\"src\",\"/common/zt_webframe/imgs/login/eye.png\");\r\n");
      out.write("     $(\"#pwd\").attr(\"type\",\"text\");\r\n");
      out.write("    }\r\n");
      out.write("});\r\n");
      out.write("$(\"#AndroidImg\").hover(function(){\r\n");
      out.write("    \r\n");
      out.write("    $(\"#AndroidQrCode\").show();\r\n");
      out.write("    $(\"#iOSQrCode\").hide();\r\n");
      out.write("},function(){\r\n");
      out.write("    $(\"#AndroidQrCode\").hide();\r\n");
      out.write("    $(\"#iOSQrCode\").hide(); \r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("$(\"#iOSImg\").hover(function(){\r\n");
      out.write("    $(\"#AndroidQrCode\").hide();\r\n");
      out.write("    $(\"#iOSQrCode\").show();\r\n");
      out.write("},function(){\r\n");
      out.write("    $(\"#AndroidQrCode\").hide();\r\n");
      out.write("    $(\"#iOSQrCode\").hide(); \r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("var newImg;\r\n");
      out.write("var newCode;\r\n");
      out.write("function switchScan(obj){\r\n");
      out.write("    var state = $(obj).attr(\"state\");\r\n");
      out.write("    if(state==\"scan\"){\r\n");
      out.write("        $(obj).attr(\"state\",\"input\");\r\n");
      out.write("        $(\"#inputArea\").hide();\r\n");
      out.write("        $(\"#scanArea\").show();\r\n");
      out.write("        $(obj).attr(\"src\",\"/common/zt_webframe/imgs/login/inputMode.png\");\r\n");
      out.write("        newImg = new GUID();\r\n");
      out.write("        newCode = newImg.newGUID();\r\n");
      out.write("        $(\"#codeImg\").attr(\"src\",\"/systemAction/qrCodeLoginImage.action?guid=\" + newCode);\r\n");
      out.write("    }else{\r\n");
      out.write("        $(obj).attr(\"state\",\"scan\");\r\n");
      out.write("        $(\"#inputArea\").show();\r\n");
      out.write("        $(\"#scanArea\").hide();\r\n");
      out.write("        $(obj).attr(\"src\",\"/common/zt_webframe/imgs/login/codeMode.png\");\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function refreshScanCode(obj){\r\n");
      out.write("    newImg = new GUID();\r\n");
      out.write("    newCode = newImg.newGUID();\r\n");
      out.write("    $(obj).attr(\"src\",\"/systemAction/qrCodeLoginImage.action?guid=\" + newCode)\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function GUID() {\r\n");
      out.write("    this.date = new Date();\r\n");
      out.write("    /* 判断是否初始化过，如果初始化过以下代码，则以下代码将不再执行，实际中只执行一次 */\r\n");
      out.write("    if (typeof this.newGUID != 'function') {   /* 生成GUID码 */\r\n");
      out.write("        GUID.prototype.newGUID = function () {\r\n");
      out.write("            this.date = new Date();\r\n");
      out.write("            var guidStr = '';\r\n");
      out.write("            sexadecimalDate = this.hexadecimal(this.getGUIDDate(), 16);\r\n");
      out.write("            sexadecimalTime = this.hexadecimal(this.getGUIDTime(), 16);\r\n");
      out.write("            for (var i = 0; i < 9; i++) {\r\n");
      out.write("                guidStr += Math.floor(Math.random() * 16).toString(16);\r\n");
      out.write("            }\r\n");
      out.write("            guidStr += sexadecimalDate;\r\n");
      out.write("            guidStr += sexadecimalTime;\r\n");
      out.write("            while (guidStr.length < 32) {\r\n");
      out.write("                guidStr += Math.floor(Math.random() * 16).toString(16);\r\n");
      out.write("            }\r\n");
      out.write("            return this.formatGUID(guidStr);\r\n");
      out.write("        }\r\n");
      out.write("        /* * 功能：获取当前日期的GUID格式，即8位数的日期：19700101 * 返回值：返回GUID日期格式的字条串 */\r\n");
      out.write("        GUID.prototype.getGUIDDate = function () {\r\n");
      out.write("            return this.date.getFullYear() + this.addZero(this.date.getMonth() + 1) + this.addZero(this.date.getDay());\r\n");
      out.write("        }\r\n");
      out.write("        /* * 功能：获取当前时间的GUID格式，即8位数的时间，包括毫秒，毫秒为2位数：12300933 * 返回值：返回GUID日期格式的字条串 */\r\n");
      out.write("        GUID.prototype.getGUIDTime = function () {\r\n");
      out.write("            return this.addZero(this.date.getHours()) + this.addZero(this.date.getMinutes()) + this.addZero(this.date.getSeconds()) + this.addZero(parseInt(this.date.getMilliseconds() / 10));\r\n");
      out.write("        }\r\n");
      out.write("        /* * 功能: 为一位数的正整数前面添加0，如果是可以转成非NaN数字的字符串也可以实现 * 参数: 参数表示准备再前面添加0的数字或可以转换成数字的字符串 * 返回值: 如果符合条件，返回添加0后的字条串类型，否则返回自身的字符串 */\r\n");
      out.write("        GUID.prototype.addZero = function (num) {\r\n");
      out.write("            if (Number(num).toString() != 'NaN' && num >= 0 && num < 10) {\r\n");
      out.write("                return '0' + Math.floor(num);\r\n");
      out.write("            } else {\r\n");
      out.write("                return num.toString();\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        /*  * 功能：将y进制的数值，转换为x进制的数值 * 参数：第1个参数表示欲转换的数值；第2个参数表示欲转换的进制；第3个参数可选，表示当前的进制数，如不写则为10 * 返回值：返回转换后的字符串 */\r\n");
      out.write("        GUID.prototype.hexadecimal = function (num, x, y) {\r\n");
      out.write("            if (y != undefined) {\r\n");
      out.write("                return parseInt(num.toString(), y).toString(x);\r\n");
      out.write("            }\r\n");
      out.write("            else {\r\n");
      out.write("                return parseInt(num.toString()).toString(x);\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        /* * 功能：格式化32位的字符串为GUID模式的字符串 * 参数：第1个参数表示32位的字符串 * 返回值：标准GUID格式的字符串 */\r\n");
      out.write("        GUID.prototype.formatGUID = function (guidStr) {\r\n");
      out.write("            var str1 = guidStr.slice(0, 8) + '-', str2 = guidStr.slice(8, 12) + '-', str3 = guidStr.slice(12, 16) + '-', str4 = guidStr.slice(16, 20) + '-', str5 = guidStr.slice(20);\r\n");
      out.write("            return str1 + str2 + str3 + str4 + str5;\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function loginByImg() {\r\n");
      out.write("    $.ajax({\r\n");
      out.write("        type: \"post\",\r\n");
      out.write("        url: \"/systemAction/qrCodeLoginCheck.action\",\r\n");
      out.write("        data: {\r\n");
      out.write("            guid: newCode\r\n");
      out.write("        },\r\n");
      out.write("        dataType: \"json\",\r\n");
      out.write("        success: function (data) {\r\n");
      out.write("            if (data.rtState) {\r\n");
      out.write("                var id = data.rtData.userId;\r\n");
      out.write("                var pwd = data.rtData.pwdCrypt;\r\n");
      out.write("                $(\"#userName\").val(id);\r\n");
      out.write("                $(\"#pwdCrypt\").val(pwd);\r\n");
      out.write("                doLogin();\r\n");
      out.write("            }\r\n");
      out.write("            setTimeout(\"loginByImg()\",2000);\r\n");
      out.write("        },\r\n");
      out.write("        error: function (err) {\r\n");
      out.write("            setTimeout(\"loginByImg()\",2000);\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("}\r\n");
      out.write("loginByImg();\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else log(t.getMessage(), t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
